// All Business Types by Sector - Complete Data

export interface BusinessTypeData {
  id: string;
  emoji: string;
  labels: { es: string; 'pt-BR': string };
  description: { es: string; 'pt-BR': string };
  gradient: string;
}

export interface SectorBusinessTypes {
  [areaId: string]: BusinessTypeData[];
}

// A1_GASTRO - Gastronomía y Bebidas
const GASTRO_TYPES: BusinessTypeData[] = [
  {
    id: 'restaurant_general',
    emoji: '🍽️',
    labels: { es: 'Restaurant General', 'pt-BR': 'Restaurante Geral' },
    description: { es: 'Cocina variada y menú diverso', 'pt-BR': 'Cozinha variada e cardápio diversificado' },
    gradient: 'from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'alta_cocina',
    emoji: '👨‍🍳',
    labels: { es: 'Alta Cocina - Gourmet', 'pt-BR': 'Alta Gastronomia - Gourmet' },
    description: { es: 'Fine dining y experiencia premium', 'pt-BR': 'Fine dining e experiência premium' },
    gradient: 'from-purple-500/20 to-pink-500/20',
  },
  {
    id: 'bodegon_cantina',
    emoji: '🍲',
    labels: { es: 'Bodegón - Cantina', 'pt-BR': 'Boteco - Cantina' },
    description: { es: 'Comida casera y ambiente tradicional', 'pt-BR': 'Comida caseira e ambiente tradicional' },
    gradient: 'from-yellow-600/20 to-amber-600/20',
  },
  {
    id: 'parrilla_asador',
    emoji: '🥩',
    labels: { es: 'Parrilla / Asador', 'pt-BR': 'Churrascaria / Assador' },
    description: { es: 'Carnes a la parrilla y cortes', 'pt-BR': 'Carnes na brasa e cortes' },
    gradient: 'from-red-500/20 to-orange-600/20',
  },
  {
    id: 'cocina_criolla',
    emoji: '🫕',
    labels: { es: 'Cocina Criolla / Regional', 'pt-BR': 'Cozinha Regional / Típica' },
    description: { es: 'Sabores locales y tradicionales', 'pt-BR': 'Sabores locais e tradicionais' },
    gradient: 'from-green-600/20 to-yellow-600/20',
  },
  {
    id: 'pescados_mariscos',
    emoji: '🦐',
    labels: { es: 'Pescados, Mariscos y Ceviche', 'pt-BR': 'Peixes, Frutos do Mar e Ceviche' },
    description: { es: 'Especialidad en productos del mar', 'pt-BR': 'Especialidade em frutos do mar' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'pizzeria',
    emoji: '🍕',
    labels: { es: 'Pizzería', 'pt-BR': 'Pizzaria' },
    description: { es: 'Pizzas artesanales y al horno', 'pt-BR': 'Pizzas artesanais e de forno' },
    gradient: 'from-red-500/20 to-yellow-500/20',
  },
  {
    id: 'panaderia',
    emoji: '🥖',
    labels: { es: 'Panadería', 'pt-BR': 'Padaria' },
    description: { es: 'Pan artesanal y productos horneados', 'pt-BR': 'Pães artesanais e produtos assados' },
    gradient: 'from-amber-400/20 to-yellow-500/20',
  },
  {
    id: 'pastas_italiana',
    emoji: '🍝',
    labels: { es: 'Pastas - Cocina Italiana', 'pt-BR': 'Massas - Cozinha Italiana' },
    description: { es: 'Pastas frescas y cocina italiana', 'pt-BR': 'Massas frescas e cozinha italiana' },
    gradient: 'from-green-500/20 to-red-500/20',
  },
  {
    id: 'heladeria',
    emoji: '🍦',
    labels: { es: 'Heladería', 'pt-BR': 'Sorveteria' },
    description: { es: 'Helados artesanales y postres fríos', 'pt-BR': 'Sorvetes artesanais e sobremesas geladas' },
    gradient: 'from-pink-400/20 to-blue-400/20',
  },
  {
    id: 'fast_food',
    emoji: '🍔',
    labels: { es: 'Fast Food (Hamburguesas, Panchos)', 'pt-BR': 'Fast Food (Hambúrgueres, Hot Dogs)' },
    description: { es: 'Incluye food trucks y comida rápida', 'pt-BR': 'Inclui food trucks e comida rápida' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'cafeteria_pasteleria',
    emoji: '☕',
    labels: { es: 'Cafetería y Pastelería', 'pt-BR': 'Cafeteria e Confeitaria' },
    description: { es: 'Café de especialidad y dulces', 'pt-BR': 'Café especial e doces' },
    gradient: 'from-amber-600/20 to-pink-400/20',
  },
  {
    id: 'cocina_asiatica',
    emoji: '🍜',
    labels: { es: 'Cocina Asiática (Sushi, Ramen)', 'pt-BR': 'Cozinha Asiática (Sushi, Ramen)' },
    description: { es: 'Sushi, ramen, wok y más', 'pt-BR': 'Sushi, ramen, wok e mais' },
    gradient: 'from-rose-500/20 to-red-600/20',
  },
  {
    id: 'cocina_arabe',
    emoji: '🧆',
    labels: { es: 'Cocina Árabe - Oriental', 'pt-BR': 'Cozinha Árabe - Oriental' },
    description: { es: 'Sabores del medio oriente', 'pt-BR': 'Sabores do oriente médio' },
    gradient: 'from-amber-500/20 to-orange-600/20',
  },
  {
    id: 'cocina_saludable',
    emoji: '🥗',
    labels: { es: 'Cocina Saludable / Veggie', 'pt-BR': 'Cozinha Saudável / Veggie' },
    description: { es: 'Vegetariano, vegano y healthy', 'pt-BR': 'Vegetariano, vegano e saudável' },
    gradient: 'from-green-400/20 to-emerald-500/20',
  },
  {
    id: 'bar_cerveceria',
    emoji: '🍺',
    labels: { es: 'Bar / Cervecería / Coctelería', 'pt-BR': 'Bar / Cervejaria / Coquetelaria' },
    description: { es: 'Bebidas, tragos y ambiente nocturno', 'pt-BR': 'Bebidas, drinks e ambiente noturno' },
    gradient: 'from-amber-500/20 to-yellow-600/20',
  },
  {
    id: 'servicio_comida',
    emoji: '📦',
    labels: { es: 'Servicio de Comida', 'pt-BR': 'Serviço de Comida' },
    description: { es: 'Take away, viandas, catering', 'pt-BR': 'Take away, marmitas, catering' },
    gradient: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    id: 'dark_kitchen',
    emoji: '👻',
    labels: { es: 'Cocina Oculta (Dark/Ghost Kitchen)', 'pt-BR': 'Cozinha Fantasma (Dark/Ghost Kitchen)' },
    description: { es: 'Solo delivery, sin salón', 'pt-BR': 'Apenas delivery, sem salão' },
    gradient: 'from-slate-500/20 to-gray-600/20',
  },
];

// A2_TURISMO - Turismo, hotelería, ocio y eventos
const TURISMO_TYPES: BusinessTypeData[] = [
  {
    id: 'hotel_urbano',
    emoji: '🏨',
    labels: { es: 'Hotel Urbano / Business', 'pt-BR': 'Hotel Urbano / Business' },
    description: { es: 'Alojamiento en ciudad y viajes de trabajo', 'pt-BR': 'Hospedagem na cidade e viagens de negócios' },
    gradient: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    id: 'hotel_boutique',
    emoji: '🏩',
    labels: { es: 'Hotel Boutique', 'pt-BR': 'Hotel Boutique' },
    description: { es: 'Experiencia diferenciada y alta atención', 'pt-BR': 'Experiência diferenciada e alta atenção' },
    gradient: 'from-purple-500/20 to-pink-500/20',
  },
  {
    id: 'resort_all_inclusive',
    emoji: '🏝️',
    labels: { es: 'Resort / All Inclusive', 'pt-BR': 'Resort / All Inclusive' },
    description: { es: 'Ocio completo y estadías largas', 'pt-BR': 'Lazer completo e estadias longas' },
    gradient: 'from-cyan-400/20 to-teal-500/20',
  },
  {
    id: 'hostel',
    emoji: '🛏️',
    labels: { es: 'Hostel / Hostal', 'pt-BR': 'Hostel / Albergue' },
    description: { es: 'Económico, social y turismo joven', 'pt-BR': 'Econômico, social e turismo jovem' },
    gradient: 'from-orange-400/20 to-yellow-500/20',
  },
  {
    id: 'posada_lodge',
    emoji: '🏡',
    labels: { es: 'Posada / Lodge', 'pt-BR': 'Pousada / Lodge' },
    description: { es: 'Naturaleza, descanso y estilo local', 'pt-BR': 'Natureza, descanso e estilo local' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'apart_hotel',
    emoji: '🏢',
    labels: { es: 'Apart Hotel / Suites', 'pt-BR': 'Apart Hotel / Suítes' },
    description: { es: 'Estadías medias con cocina y confort', 'pt-BR': 'Estadias médias com cozinha e conforto' },
    gradient: 'from-slate-500/20 to-gray-500/20',
  },
  {
    id: 'alquiler_temporario',
    emoji: '🔑',
    labels: { es: 'Alquiler Temporario / Short Stay', 'pt-BR': 'Aluguel Temporário / Short Stay' },
    description: { es: 'Propiedades por días o semanas', 'pt-BR': 'Propriedades por dias ou semanas' },
    gradient: 'from-amber-500/20 to-orange-500/20',
  },
  {
    id: 'agencia_viajes',
    emoji: '🧳',
    labels: { es: 'Agencia de Viajes', 'pt-BR': 'Agência de Viagens' },
    description: { es: 'Paquetes, aéreos, hoteles y asistencia', 'pt-BR': 'Pacotes, aéreos, hotéis e assistência' },
    gradient: 'from-blue-400/20 to-cyan-500/20',
  },
  {
    id: 'operador_turistico',
    emoji: '🗺️',
    labels: { es: 'Operador Turístico / Receptivo', 'pt-BR': 'Operador Turístico / Receptivo' },
    description: { es: 'Tours y experiencias en destino', 'pt-BR': 'Tours e experiências no destino' },
    gradient: 'from-teal-500/20 to-green-500/20',
  },
  {
    id: 'tours_guiados',
    emoji: '🚶',
    labels: { es: 'Tours Guiados / Excursiones', 'pt-BR': 'Tours Guiados / Excursões' },
    description: { es: 'Recorridos, city tours y actividades', 'pt-BR': 'Passeios, city tours e atividades' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'turismo_aventura',
    emoji: '🧗',
    labels: { es: 'Turismo Aventura / Outdoor', 'pt-BR': 'Turismo Aventura / Outdoor' },
    description: { es: 'Actividades de naturaleza y adrenalina', 'pt-BR': 'Atividades de natureza e adrenalina' },
    gradient: 'from-green-600/20 to-lime-500/20',
  },
  {
    id: 'atracciones_tickets',
    emoji: '🎟️',
    labels: { es: 'Atracciones / Tickets / Experiencias', 'pt-BR': 'Atrações / Ingressos / Experiências' },
    description: { es: 'Entradas, pases y actividades de ocio', 'pt-BR': 'Entradas, passes e atividades de lazer' },
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'parque_tematico',
    emoji: '🎢',
    labels: { es: 'Parque Temático / Atracción', 'pt-BR': 'Parque Temático / Atração' },
    description: { es: 'Entretenimiento masivo y familiar', 'pt-BR': 'Entretenimento massivo e familiar' },
    gradient: 'from-yellow-500/20 to-orange-500/20',
  },
  {
    id: 'teatro_espectaculos',
    emoji: '🎭',
    labels: { es: 'Teatro / Sala de Espectáculos', 'pt-BR': 'Teatro / Casa de Shows' },
    description: { es: 'Shows, funciones y programación cultural', 'pt-BR': 'Shows, sessões e programação cultural' },
    gradient: 'from-red-500/20 to-purple-500/20',
  },
  {
    id: 'salon_eventos_sociales',
    emoji: '🎉',
    labels: { es: 'Salón de Eventos Sociales', 'pt-BR': 'Salão de Eventos Sociais' },
    description: { es: 'Casamientos, fiestas y celebraciones', 'pt-BR': 'Casamentos, festas e celebrações' },
    gradient: 'from-pink-400/20 to-purple-400/20',
  },
  {
    id: 'eventos_corporativos',
    emoji: '🏢',
    labels: { es: 'Eventos Corporativos (MICE)', 'pt-BR': 'Eventos Corporativos (MICE)' },
    description: { es: 'Congresos, reuniones y convenciones', 'pt-BR': 'Congressos, reuniões e convenções' },
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  {
    id: 'productora_eventos',
    emoji: '🎬',
    labels: { es: 'Productora de Eventos', 'pt-BR': 'Produtora de Eventos' },
    description: { es: 'Producción, técnica y logística integral', 'pt-BR': 'Produção, técnica e logística integral' },
    gradient: 'from-slate-600/20 to-gray-600/20',
  },
  {
    id: 'ocio_nocturno',
    emoji: '🕺',
    labels: { es: 'Ocio Nocturno (Boliche/Club)', 'pt-BR': 'Vida Noturna (Balada/Club)' },
    description: { es: 'Entretenimiento nocturno y música', 'pt-BR': 'Entretenimento noturno e música' },
    gradient: 'from-violet-600/20 to-purple-600/20',
  },
];

// A3_RETAIL - Comercio minorista y e-commerce
const RETAIL_TYPES: BusinessTypeData[] = [
  {
    id: 'almacen_tienda_barrio',
    emoji: '🏪',
    labels: { es: 'Almacén / Tienda de Barrio', 'pt-BR': 'Mercearia / Loja de Bairro' },
    description: { es: 'Venta diaria y cercanía al cliente', 'pt-BR': 'Venda diária e proximidade ao cliente' },
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 'supermercado',
    emoji: '🛒',
    labels: { es: 'Supermercado / Autoservicio', 'pt-BR': 'Supermercado / Autosserviço' },
    description: { es: 'Alto volumen y categorías variadas', 'pt-BR': 'Alto volume e categorias variadas' },
    gradient: 'from-green-500/20 to-teal-500/20',
  },
  {
    id: 'moda_accesorios',
    emoji: '👗',
    labels: { es: 'Moda y Accesorios', 'pt-BR': 'Moda e Acessórios' },
    description: { es: 'Indumentaria, tendencias y temporada', 'pt-BR': 'Vestuário, tendências e temporada' },
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'calzado_marroquineria',
    emoji: '👟',
    labels: { es: 'Calzado y Marroquinería', 'pt-BR': 'Calçados e Couro' },
    description: { es: 'Zapatos, bolsos y complementos', 'pt-BR': 'Sapatos, bolsas e complementos' },
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  {
    id: 'hogar_decoracion',
    emoji: '🏠',
    labels: { es: 'Hogar y Decoración', 'pt-BR': 'Casa e Decoração' },
    description: { es: 'Muebles, deco y artículos del hogar', 'pt-BR': 'Móveis, decoração e artigos para casa' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'electronica_tecnologia',
    emoji: '📱',
    labels: { es: 'Electrónica y Tecnología', 'pt-BR': 'Eletrônicos e Tecnologia' },
    description: { es: 'Gadgets, accesorios y equipos', 'pt-BR': 'Gadgets, acessórios e equipamentos' },
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  {
    id: 'ferreteria',
    emoji: '🧰',
    labels: { es: 'Ferretería / Herramientas', 'pt-BR': 'Ferragem / Ferramentas' },
    description: { es: 'Insumos, reparación y construcción', 'pt-BR': 'Insumos, reparação e construção' },
    gradient: 'from-gray-500/20 to-slate-500/20',
  },
  {
    id: 'libreria_papeleria',
    emoji: '📚',
    labels: { es: 'Librería / Papelería', 'pt-BR': 'Livraria / Papelaria' },
    description: { es: 'Escolar, oficina y regalos', 'pt-BR': 'Escolar, escritório e presentes' },
    gradient: 'from-blue-400/20 to-cyan-400/20',
  },
  {
    id: 'jugueteria',
    emoji: '🧸',
    labels: { es: 'Juguetería y Hobbies', 'pt-BR': 'Brinquedos e Hobbies' },
    description: { es: 'Juegos, colección y entretenimiento', 'pt-BR': 'Jogos, coleção e entretenimento' },
    gradient: 'from-yellow-400/20 to-orange-400/20',
  },
  {
    id: 'deportes_outdoor',
    emoji: '🏋️',
    labels: { es: 'Deportes y Outdoor', 'pt-BR': 'Esportes e Outdoor' },
    description: { es: 'Ropa, accesorios y equipamiento', 'pt-BR': 'Roupas, acessórios e equipamentos' },
    gradient: 'from-green-600/20 to-lime-500/20',
  },
  {
    id: 'belleza_perfumeria',
    emoji: '💄',
    labels: { es: 'Belleza y Perfumería', 'pt-BR': 'Beleza e Perfumaria' },
    description: { es: 'Cosmética, skincare y fragancias', 'pt-BR': 'Cosméticos, skincare e fragrâncias' },
    gradient: 'from-pink-400/20 to-purple-400/20',
  },
  {
    id: 'pet_shop',
    emoji: '🐾',
    labels: { es: 'Pet Shop', 'pt-BR': 'Pet Shop' },
    description: { es: 'Alimentos, accesorios y cuidados', 'pt-BR': 'Alimentos, acessórios e cuidados' },
    gradient: 'from-amber-400/20 to-yellow-400/20',
  },
  {
    id: 'gourmet_delicatessen',
    emoji: '🧀',
    labels: { es: 'Gourmet / Delicatessen', 'pt-BR': 'Gourmet / Delicatessen' },
    description: { es: 'Productos premium y especiales', 'pt-BR': 'Produtos premium e especiais' },
    gradient: 'from-red-500/20 to-orange-500/20',
  },
  {
    id: 'segunda_mano',
    emoji: '♻️',
    labels: { es: 'Segunda Mano / Re-commerce', 'pt-BR': 'Segunda Mão / Re-commerce' },
    description: { es: 'Reventa, consignación y usados', 'pt-BR': 'Revenda, consignação e usados' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'ecommerce_d2c',
    emoji: '🛒',
    labels: { es: 'E-commerce Marca Propia (D2C)', 'pt-BR': 'E-commerce Marca Própria (D2C)' },
    description: { es: 'Venta online directa al consumidor', 'pt-BR': 'Venda online direto ao consumidor' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'seller_marketplace',
    emoji: '🏷️',
    labels: { es: 'Seller en Marketplaces', 'pt-BR': 'Seller em Marketplaces' },
    description: { es: 'Catálogo en plataformas y envíos', 'pt-BR': 'Catálogo em plataformas e envios' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'suscripcion_cajas',
    emoji: '📦',
    labels: { es: 'Suscripción / Cajas Mensuales', 'pt-BR': 'Assinatura / Caixas Mensais' },
    description: { es: 'Productos recurrentes por membresía', 'pt-BR': 'Produtos recorrentes por assinatura' },
    gradient: 'from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'mayorista_distribuidor',
    emoji: '🏭',
    labels: { es: 'Mayorista / Distribuidor', 'pt-BR': 'Atacadista / Distribuidor' },
    description: { es: 'Venta B2B por volumen y reposición', 'pt-BR': 'Venda B2B por volume e reposição' },
    gradient: 'from-slate-600/20 to-gray-600/20',
  },
];

// A4_SALUD - Salud, bienestar y belleza
const SALUD_TYPES: BusinessTypeData[] = [
  {
    id: 'clinica_policonsultorio',
    emoji: '🏥',
    labels: { es: 'Clínica / Policonsultorio', 'pt-BR': 'Clínica / Policlínica' },
    description: { es: 'Atención integral y especialidades', 'pt-BR': 'Atendimento integral e especialidades' },
    gradient: 'from-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'consultorio_medico',
    emoji: '🩺',
    labels: { es: 'Consultorio Médico', 'pt-BR': 'Consultório Médico' },
    description: { es: 'Atención por especialidad y turnos', 'pt-BR': 'Atendimento por especialidade e consultas' },
    gradient: 'from-teal-500/20 to-green-500/20',
  },
  {
    id: 'centro_odontologico',
    emoji: '🦷',
    labels: { es: 'Centro Odontológico', 'pt-BR': 'Centro Odontológico' },
    description: { es: 'Odonto general y tratamientos', 'pt-BR': 'Odonto geral e tratamentos' },
    gradient: 'from-sky-400/20 to-blue-400/20',
  },
  {
    id: 'laboratorio_analisis',
    emoji: '🧪',
    labels: { es: 'Laboratorio de Análisis', 'pt-BR': 'Laboratório de Análises' },
    description: { es: 'Estudios, extracciones y resultados', 'pt-BR': 'Exames, coletas e resultados' },
    gradient: 'from-purple-400/20 to-indigo-400/20',
  },
  {
    id: 'centro_diagnostico',
    emoji: '🩻',
    labels: { es: 'Centro de Diagnóstico por Imágenes', 'pt-BR': 'Centro de Diagnóstico por Imagem' },
    description: { es: 'Rx, eco, tomografía y resonancia', 'pt-BR': 'Rx, eco, tomografia e ressonância' },
    gradient: 'from-slate-500/20 to-gray-500/20',
  },
  {
    id: 'kinesiologia',
    emoji: '🦴',
    labels: { es: 'Kinesiología / Rehabilitación', 'pt-BR': 'Fisioterapia / Reabilitação' },
    description: { es: 'Recuperación, terapia y movimiento', 'pt-BR': 'Recuperação, terapia e movimento' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'psicologia',
    emoji: '🧠',
    labels: { es: 'Psicología / Salud Mental', 'pt-BR': 'Psicologia / Saúde Mental' },
    description: { es: 'Terapias, sesiones y seguimiento', 'pt-BR': 'Terapias, sessões e acompanhamento' },
    gradient: 'from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'nutricion',
    emoji: '🥗',
    labels: { es: 'Nutrición / Dietética Clínica', 'pt-BR': 'Nutrição / Dietética Clínica' },
    description: { es: 'Planes, control y educación alimentaria', 'pt-BR': 'Planos, controle e educação alimentar' },
    gradient: 'from-green-400/20 to-lime-400/20',
  },
  {
    id: 'medicina_estetica',
    emoji: '💉',
    labels: { es: 'Medicina Estética', 'pt-BR': 'Medicina Estética' },
    description: { es: 'Procedimientos médicos estéticos', 'pt-BR': 'Procedimentos médicos estéticos' },
    gradient: 'from-pink-400/20 to-rose-400/20',
  },
  {
    id: 'centro_estetica',
    emoji: '✨',
    labels: { es: 'Centro de Estética', 'pt-BR': 'Centro de Estética' },
    description: { es: 'Facial, corporal y tratamientos', 'pt-BR': 'Facial, corporal e tratamentos' },
    gradient: 'from-purple-400/20 to-pink-400/20',
  },
  {
    id: 'spa_masajes',
    emoji: '🧖',
    labels: { es: 'Spa / Masajes', 'pt-BR': 'Spa / Massagens' },
    description: { es: 'Relax, bienestar y circuitos', 'pt-BR': 'Relaxamento, bem-estar e circuitos' },
    gradient: 'from-cyan-400/20 to-teal-400/20',
  },
  {
    id: 'gimnasio_fitness',
    emoji: '🏋️',
    labels: { es: 'Gimnasio / Fitness', 'pt-BR': 'Academia / Fitness' },
    description: { es: 'Entrenamiento y membresías', 'pt-BR': 'Treinamento e mensalidades' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'yoga_pilates',
    emoji: '🧘',
    labels: { es: 'Yoga / Pilates', 'pt-BR': 'Yoga / Pilates' },
    description: { es: 'Clases, bienestar y postura', 'pt-BR': 'Aulas, bem-estar e postura' },
    gradient: 'from-indigo-400/20 to-purple-400/20',
  },
  {
    id: 'peluqueria_salon',
    emoji: '💇',
    labels: { es: 'Peluquería / Salón', 'pt-BR': 'Salão de Beleza' },
    description: { es: 'Corte, color y styling', 'pt-BR': 'Corte, coloração e styling' },
    gradient: 'from-pink-500/20 to-purple-500/20',
  },
  {
    id: 'barberia',
    emoji: '🧔',
    labels: { es: 'Barbería', 'pt-BR': 'Barbearia' },
    description: { es: 'Corte masculino y cuidado', 'pt-BR': 'Corte masculino e cuidados' },
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  {
    id: 'manicuria',
    emoji: '💅',
    labels: { es: 'Manicuría / Uñas', 'pt-BR': 'Manicure / Unhas' },
    description: { es: 'Uñas, belleza y turnos', 'pt-BR': 'Unhas, beleza e agendamentos' },
    gradient: 'from-rose-400/20 to-pink-400/20',
  },
  {
    id: 'depilacion',
    emoji: '🪒',
    labels: { es: 'Depilación (Cera/Láser)', 'pt-BR': 'Depilação (Cera/Laser)' },
    description: { es: 'Sesiones, packs y mantenimiento', 'pt-BR': 'Sessões, pacotes e manutenção' },
    gradient: 'from-yellow-400/20 to-amber-400/20',
  },
  {
    id: 'optica',
    emoji: '👓',
    labels: { es: 'Óptica / Contactología', 'pt-BR': 'Ótica / Lentes de Contato' },
    description: { es: 'Lentes, controles y adaptación', 'pt-BR': 'Óculos, controles e adaptação' },
    gradient: 'from-blue-400/20 to-indigo-400/20',
  },
];

// A5_EDUCACION - Educación, formación y academias
const EDUCACION_TYPES: BusinessTypeData[] = [
  {
    id: 'jardin_inicial',
    emoji: '🧒',
    labels: { es: 'Jardín / Inicial', 'pt-BR': 'Jardim / Educação Infantil' },
    description: { es: 'Primera infancia y cuidado educativo', 'pt-BR': 'Primeira infância e cuidado educativo' },
    gradient: 'from-yellow-400/20 to-orange-400/20',
  },
  {
    id: 'escuela_primaria_secundaria',
    emoji: '🏫',
    labels: { es: 'Escuela Primaria / Secundaria', 'pt-BR': 'Escola Fundamental / Médio' },
    description: { es: 'Educación formal y comunidad', 'pt-BR': 'Educação formal e comunidade' },
    gradient: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    id: 'terciario_instituto',
    emoji: '🎓',
    labels: { es: 'Terciario / Instituto Técnico', 'pt-BR': 'Técnico / Instituto' },
    description: { es: 'Carreras cortas y salida laboral', 'pt-BR': 'Cursos técnicos e empregabilidade' },
    gradient: 'from-teal-500/20 to-cyan-500/20',
  },
  {
    id: 'universidad_posgrado',
    emoji: '🏛️',
    labels: { es: 'Universidad / Posgrado', 'pt-BR': 'Universidade / Pós-graduação' },
    description: { es: 'Formación superior y especialización', 'pt-BR': 'Formação superior e especialização' },
    gradient: 'from-purple-600/20 to-indigo-600/20',
  },
  {
    id: 'instituto_idiomas',
    emoji: '🌎',
    labels: { es: 'Instituto de Idiomas', 'pt-BR': 'Escola de Idiomas' },
    description: { es: 'Cursos, niveles y certificaciones', 'pt-BR': 'Cursos, níveis e certificações' },
    gradient: 'from-green-500/20 to-teal-500/20',
  },
  {
    id: 'apoyo_escolar',
    emoji: '📚',
    labels: { es: 'Apoyo Escolar', 'pt-BR': 'Reforço Escolar' },
    description: { es: 'Refuerzo, tareas y acompañamiento', 'pt-BR': 'Reforço, tarefas e acompanhamento' },
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 'preparacion_examenes',
    emoji: '📝',
    labels: { es: 'Preparación de Exámenes', 'pt-BR': 'Preparação para Exames' },
    description: { es: 'Ingreso, finales y certificaciones', 'pt-BR': 'Vestibular, provas e certificações' },
    gradient: 'from-red-500/20 to-orange-500/20',
  },
  {
    id: 'programacion_tech',
    emoji: '💻',
    labels: { es: 'Programación / Data / IA', 'pt-BR': 'Programação / Data / IA' },
    description: { es: 'Skills tech y empleabilidad', 'pt-BR': 'Skills tech e empregabilidade' },
    gradient: 'from-blue-600/20 to-cyan-600/20',
  },
  {
    id: 'diseno_creatividad',
    emoji: '🎨',
    labels: { es: 'Diseño / Creatividad', 'pt-BR': 'Design / Criatividade' },
    description: { es: 'Diseño gráfico, UX y contenidos', 'pt-BR': 'Design gráfico, UX e conteúdos' },
    gradient: 'from-pink-500/20 to-purple-500/20',
  },
  {
    id: 'marketing_negocios',
    emoji: '📣',
    labels: { es: 'Marketing Digital / Negocios', 'pt-BR': 'Marketing Digital / Negócios' },
    description: { es: 'Estrategia, anuncios y crecimiento', 'pt-BR': 'Estratégia, anúncios e crescimento' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'cursos_oficios',
    emoji: '🛠️',
    labels: { es: 'Cursos de Oficios', 'pt-BR': 'Cursos de Ofícios' },
    description: { es: 'Técnicos, manuales y prácticos', 'pt-BR': 'Técnicos, manuais e práticos' },
    gradient: 'from-gray-500/20 to-slate-500/20',
  },
  {
    id: 'capacitacion_corporativa',
    emoji: '🏢',
    labels: { es: 'Capacitación Corporativa (B2B)', 'pt-BR': 'Treinamento Corporativo (B2B)' },
    description: { es: 'Entrenamiento para empresas', 'pt-BR': 'Treinamento para empresas' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'elearning_plataforma',
    emoji: '🖥️',
    labels: { es: 'E-learning / Plataforma Online', 'pt-BR': 'E-learning / Plataforma Online' },
    description: { es: 'Cursos digitales y escalabilidad', 'pt-BR': 'Cursos digitais e escalabilidade' },
    gradient: 'from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'clases_particulares',
    emoji: '👩‍🏫',
    labels: { es: 'Clases Particulares / Tutorías 1:1', 'pt-BR': 'Aulas Particulares / Tutorias 1:1' },
    description: { es: 'Personalizado y por objetivo', 'pt-BR': 'Personalizado e por objetivo' },
    gradient: 'from-green-400/20 to-emerald-400/20',
  },
  {
    id: 'artes_escenicas',
    emoji: '🎭',
    labels: { es: 'Artes Escénicas (Teatro/Actuación)', 'pt-BR': 'Artes Cênicas (Teatro/Atuação)' },
    description: { es: 'Formación artística y práctica', 'pt-BR': 'Formação artística e prática' },
    gradient: 'from-red-500/20 to-purple-500/20',
  },
  {
    id: 'academia_musica',
    emoji: '🎵',
    labels: { es: 'Academia de Música', 'pt-BR': 'Escola de Música' },
    description: { es: 'Instrumentos, canto y teoría', 'pt-BR': 'Instrumentos, canto e teoria' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'academia_danza',
    emoji: '💃',
    labels: { es: 'Academia de Danza', 'pt-BR': 'Escola de Dança' },
    description: { es: 'Estilos, niveles y shows', 'pt-BR': 'Estilos, níveis e shows' },
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'academia_deportiva',
    emoji: '🏅',
    labels: { es: 'Academia Deportiva', 'pt-BR': 'Academia Esportiva' },
    description: { es: 'Entrenamiento por disciplina', 'pt-BR': 'Treinamento por modalidade' },
    gradient: 'from-green-600/20 to-lime-500/20',
  },
];

// A6_B2B - Servicios profesionales y B2B
const B2B_TYPES: BusinessTypeData[] = [
  {
    id: 'consultoria_estrategica',
    emoji: '🧠',
    labels: { es: 'Consultoría Estratégica', 'pt-BR': 'Consultoria Estratégica' },
    description: { es: 'Diagnóstico, planificación y dirección', 'pt-BR': 'Diagnóstico, planejamento e direção' },
    gradient: 'from-purple-500/20 to-indigo-500/20',
  },
  {
    id: 'consultoria_comercial',
    emoji: '📈',
    labels: { es: 'Consultoría Comercial / Ventas', 'pt-BR': 'Consultoria Comercial / Vendas' },
    description: { es: 'Procesos, equipos y resultados', 'pt-BR': 'Processos, equipes e resultados' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'agencia_marketing',
    emoji: '📣',
    labels: { es: 'Agencia de Marketing / Performance', 'pt-BR': 'Agência de Marketing / Performance' },
    description: { es: 'Campañas, leads y crecimiento', 'pt-BR': 'Campanhas, leads e crescimento' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'branding_diseno',
    emoji: '🎨',
    labels: { es: 'Branding / Diseño', 'pt-BR': 'Branding / Design' },
    description: { es: 'Identidad, comunicación y marca', 'pt-BR': 'Identidade, comunicação e marca' },
    gradient: 'from-pink-500/20 to-purple-500/20',
  },
  {
    id: 'desarrollo_software',
    emoji: '💻',
    labels: { es: 'Desarrollo de Software / Producto', 'pt-BR': 'Desenvolvimento de Software / Produto' },
    description: { es: 'Apps, sistemas y plataformas', 'pt-BR': 'Apps, sistemas e plataformas' },
    gradient: 'from-blue-600/20 to-cyan-600/20',
  },
  {
    id: 'servicios_it',
    emoji: '🖥️',
    labels: { es: 'Servicios IT / Soporte', 'pt-BR': 'Serviços de TI / Suporte' },
    description: { es: 'Infraestructura, redes y mantenimiento', 'pt-BR': 'Infraestrutura, redes e manutenção' },
    gradient: 'from-slate-500/20 to-gray-500/20',
  },
  {
    id: 'ciberseguridad',
    emoji: '🛡️',
    labels: { es: 'Ciberseguridad', 'pt-BR': 'Cibersegurança' },
    description: { es: 'Protección, auditorías y prevención', 'pt-BR': 'Proteção, auditorias e prevenção' },
    gradient: 'from-red-600/20 to-orange-600/20',
  },
  {
    id: 'estudio_contable',
    emoji: '🧾',
    labels: { es: 'Estudio Contable / Impositivo', 'pt-BR': 'Escritório Contábil / Tributário' },
    description: { es: 'Contabilidad, impuestos y gestión', 'pt-BR': 'Contabilidade, impostos e gestão' },
    gradient: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    id: 'estudio_juridico',
    emoji: '⚖️',
    labels: { es: 'Estudio Jurídico', 'pt-BR': 'Escritório Jurídico' },
    description: { es: 'Asesoría legal y trámites', 'pt-BR': 'Assessoria jurídica e trâmites' },
    gradient: 'from-amber-600/20 to-yellow-600/20',
  },
  {
    id: 'rrhh_reclutamiento',
    emoji: '👥',
    labels: { es: 'RRHH / Reclutamiento', 'pt-BR': 'RH / Recrutamento' },
    description: { es: 'Búsqueda, selección y talento', 'pt-BR': 'Busca, seleção e talento' },
    gradient: 'from-teal-500/20 to-cyan-500/20',
  },
  {
    id: 'capacitacion_empresarial',
    emoji: '🎓',
    labels: { es: 'Capacitación Empresarial', 'pt-BR': 'Treinamento Empresarial' },
    description: { es: 'Formación, talleres y programas', 'pt-BR': 'Formação, workshops e programas' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'asesoria_financiera',
    emoji: '💰',
    labels: { es: 'Asesoría Financiera', 'pt-BR': 'Assessoria Financeira' },
    description: { es: 'Estructura, flujo y planificación', 'pt-BR': 'Estrutura, fluxo e planejamento' },
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  {
    id: 'seguros_broker',
    emoji: '🧯',
    labels: { es: 'Seguros (Broker/Productor)', 'pt-BR': 'Seguros (Corretor/Produtor)' },
    description: { es: 'Coberturas, pólizas y gestión', 'pt-BR': 'Coberturas, apólices e gestão' },
    gradient: 'from-red-500/20 to-orange-500/20',
  },
  {
    id: 'investigacion_mercado',
    emoji: '🔎',
    labels: { es: 'Investigación de Mercado', 'pt-BR': 'Pesquisa de Mercado' },
    description: { es: 'Insights, encuestas y análisis', 'pt-BR': 'Insights, pesquisas e análises' },
    gradient: 'from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'produccion_audiovisual',
    emoji: '🎥',
    labels: { es: 'Producción Audiovisual / Foto', 'pt-BR': 'Produção Audiovisual / Foto' },
    description: { es: 'Contenido, eventos y piezas', 'pt-BR': 'Conteúdo, eventos e peças' },
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'traduccion_localizacion',
    emoji: '🌐',
    labels: { es: 'Traducción / Localización', 'pt-BR': 'Tradução / Localização' },
    description: { es: 'Idiomas, adaptación y calidad', 'pt-BR': 'Idiomas, adaptação e qualidade' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'limpieza_facility',
    emoji: '🧼',
    labels: { es: 'Limpieza / Facility B2B', 'pt-BR': 'Limpeza / Facility B2B' },
    description: { es: 'Servicios para empresas y edificios', 'pt-BR': 'Serviços para empresas e edifícios' },
    gradient: 'from-sky-400/20 to-cyan-400/20',
  },
  {
    id: 'outsourcing_backoffice',
    emoji: '📞',
    labels: { es: 'Outsourcing / Backoffice / Call Center', 'pt-BR': 'Outsourcing / Backoffice / Call Center' },
    description: { es: 'Operación, soporte y procesos', 'pt-BR': 'Operação, suporte e processos' },
    gradient: 'from-gray-500/20 to-slate-500/20',
  },
];

// A7_HOGAR_SERV - Hogar, mantenimiento y servicios técnicos
const HOGAR_TYPES: BusinessTypeData[] = [
  {
    id: 'plomeria',
    emoji: '🚰',
    labels: { es: 'Plomería / Sanitarios', 'pt-BR': 'Encanamento / Hidráulica' },
    description: { es: 'Pérdidas, cañerías e instalaciones', 'pt-BR': 'Vazamentos, canos e instalações' },
    gradient: 'from-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'electricidad',
    emoji: '⚡',
    labels: { es: 'Electricidad', 'pt-BR': 'Eletricidade' },
    description: { es: 'Tableros, cableado y arreglos', 'pt-BR': 'Quadros, fiação e reparos' },
    gradient: 'from-yellow-500/20 to-amber-500/20',
  },
  {
    id: 'gasista',
    emoji: '🔥',
    labels: { es: 'Gasista', 'pt-BR': 'Gasista' },
    description: { es: 'Instalaciones, revisiones y seguridad', 'pt-BR': 'Instalações, revisões e segurança' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'aire_acondicionado',
    emoji: '❄️',
    labels: { es: 'Aire Acondicionado / Climatización', 'pt-BR': 'Ar Condicionado / Climatização' },
    description: { es: 'Instalación, service y reparación', 'pt-BR': 'Instalação, manutenção e reparo' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'reparacion_electrodomesticos',
    emoji: '🧺',
    labels: { es: 'Reparación de Electrodomésticos', 'pt-BR': 'Reparo de Eletrodomésticos' },
    description: { es: 'Arreglos, repuestos y service', 'pt-BR': 'Reparos, peças e manutenção' },
    gradient: 'from-slate-500/20 to-gray-500/20',
  },
  {
    id: 'soporte_tecnico_hogar',
    emoji: '🖥️',
    labels: { es: 'Soporte Técnico Hogar (PC/Redes)', 'pt-BR': 'Suporte Técnico Casa (PC/Redes)' },
    description: { es: 'WiFi, computadoras y configuración', 'pt-BR': 'WiFi, computadores e configuração' },
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  {
    id: 'pintura',
    emoji: '🎨',
    labels: { es: 'Pintura / Revestimientos', 'pt-BR': 'Pintura / Revestimentos' },
    description: { es: 'Interiores, exteriores y terminaciones', 'pt-BR': 'Interiores, exteriores e acabamentos' },
    gradient: 'from-pink-500/20 to-purple-500/20',
  },
  {
    id: 'albanileria',
    emoji: '🧱',
    labels: { es: 'Albañilería / Refacciones Menores', 'pt-BR': 'Pedreiro / Pequenos Reparos' },
    description: { es: 'Arreglos, arreglos y mejoras', 'pt-BR': 'Reparos, consertos e melhorias' },
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  {
    id: 'carpinteria',
    emoji: '🪚',
    labels: { es: 'Carpintería', 'pt-BR': 'Carpintaria' },
    description: { es: 'Muebles, puertas y trabajos a medida', 'pt-BR': 'Móveis, portas e trabalhos sob medida' },
    gradient: 'from-amber-500/20 to-yellow-600/20',
  },
  {
    id: 'herreria',
    emoji: '🔩',
    labels: { es: 'Herrería', 'pt-BR': 'Serralheria' },
    description: { es: 'Rejas, portones y estructuras', 'pt-BR': 'Grades, portões e estruturas' },
    gradient: 'from-gray-600/20 to-slate-600/20',
  },
  {
    id: 'vidrieria',
    emoji: '🪟',
    labels: { es: 'Vidriería', 'pt-BR': 'Vidraçaria' },
    description: { es: 'Cristales, ventanas y reemplazos', 'pt-BR': 'Vidros, janelas e substituições' },
    gradient: 'from-cyan-400/20 to-sky-400/20',
  },
  {
    id: 'cerrajeria',
    emoji: '🔐',
    labels: { es: 'Cerrajería', 'pt-BR': 'Chaveiro' },
    description: { es: 'Llaves, cerraduras y urgencias', 'pt-BR': 'Chaves, fechaduras e urgências' },
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 'jardineria',
    emoji: '🌿',
    labels: { es: 'Jardinería', 'pt-BR': 'Jardinagem' },
    description: { es: 'Mantenimiento, poda y diseño básico', 'pt-BR': 'Manutenção, poda e design básico' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'piscinas',
    emoji: '🏊',
    labels: { es: 'Piscinas', 'pt-BR': 'Piscinas' },
    description: { es: 'Limpieza, químicos y mantenimiento', 'pt-BR': 'Limpeza, químicos e manutenção' },
    gradient: 'from-blue-400/20 to-cyan-400/20',
  },
  {
    id: 'control_plagas',
    emoji: '🐜',
    labels: { es: 'Control de Plagas', 'pt-BR': 'Controle de Pragas' },
    description: { es: 'Fumigación y prevención', 'pt-BR': 'Fumigação e prevenção' },
    gradient: 'from-red-500/20 to-orange-500/20',
  },
  {
    id: 'limpieza_hogar',
    emoji: '🧽',
    labels: { es: 'Limpieza del Hogar', 'pt-BR': 'Limpeza Residencial' },
    description: { es: 'Servicios recurrentes o puntuales', 'pt-BR': 'Serviços recorrentes ou pontuais' },
    gradient: 'from-sky-400/20 to-blue-400/20',
  },
  {
    id: 'mudanzas_traslados',
    emoji: '🚚',
    labels: { es: 'Mudanzas y Traslados', 'pt-BR': 'Mudanças e Transportes' },
    description: { es: 'Fletes, embalaje y logística', 'pt-BR': 'Fretes, embalagem e logística' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'seguridad_hogar',
    emoji: '📷',
    labels: { es: 'Seguridad Hogar (Alarmas/Cámaras)', 'pt-BR': 'Segurança Residencial (Alarmes/Câmeras)' },
    description: { es: 'Instalación y monitoreo', 'pt-BR': 'Instalação e monitoramento' },
    gradient: 'from-slate-600/20 to-gray-600/20',
  },
];

// A8_CONSTRU_INMO - Construcción, inmobiliario y gestión de propiedades
const CONSTRUCCION_TYPES: BusinessTypeData[] = [
  {
    id: 'constructora',
    emoji: '🏢',
    labels: { es: 'Constructora (Obra Nueva)', 'pt-BR': 'Construtora (Obra Nova)' },
    description: { es: 'Ejecución de obras y proyectos', 'pt-BR': 'Execução de obras e projetos' },
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  {
    id: 'desarrolladora_inmobiliaria',
    emoji: '🏙️',
    labels: { es: 'Desarrolladora Inmobiliaria', 'pt-BR': 'Incorporadora Imobiliária' },
    description: { es: 'Proyectos, lotes y emprendimientos', 'pt-BR': 'Projetos, lotes e empreendimentos' },
    gradient: 'from-purple-500/20 to-pink-500/20',
  },
  {
    id: 'estudio_arquitectura',
    emoji: '📐',
    labels: { es: 'Estudio de Arquitectura', 'pt-BR': 'Escritório de Arquitetura' },
    description: { es: 'Diseño, planos y dirección', 'pt-BR': 'Design, plantas e direção' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'ingenieria_estructuras',
    emoji: '🧱',
    labels: { es: 'Ingeniería / Estructuras', 'pt-BR': 'Engenharia / Estruturas' },
    description: { es: 'Cálculo, obra y soporte técnico', 'pt-BR': 'Cálculo, obra e suporte técnico' },
    gradient: 'from-gray-500/20 to-slate-500/20',
  },
  {
    id: 'obras_civiles',
    emoji: '🛣️',
    labels: { es: 'Obras Civiles / Infraestructura', 'pt-BR': 'Obras Civis / Infraestrutura' },
    description: { es: 'Vialidad, redes y gran escala', 'pt-BR': 'Viação, redes e grande escala' },
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  {
    id: 'remodelaciones',
    emoji: '🔨',
    labels: { es: 'Remodelaciones / Refacciones', 'pt-BR': 'Reformas / Renovações' },
    description: { es: 'Renovación y mejora de espacios', 'pt-BR': 'Renovação e melhoria de espaços' },
    gradient: 'from-yellow-500/20 to-amber-500/20',
  },
  {
    id: 'instalaciones_obra',
    emoji: '🚿',
    labels: { es: 'Instalaciones de Obra (Sanitaria/Eléctrica)', 'pt-BR': 'Instalações de Obra (Hidráulica/Elétrica)' },
    description: { es: 'Montaje técnico en construcción', 'pt-BR': 'Montagem técnica em construção' },
    gradient: 'from-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'mantenimiento_edilicio',
    emoji: '🧰',
    labels: { es: 'Mantenimiento Edilicio', 'pt-BR': 'Manutenção Predial' },
    description: { es: 'Reparaciones programadas y correctivas', 'pt-BR': 'Reparos programados e corretivos' },
    gradient: 'from-slate-500/20 to-gray-500/20',
  },
  {
    id: 'inmobiliaria_residencial',
    emoji: '🏠',
    labels: { es: 'Inmobiliaria Residencial', 'pt-BR': 'Imobiliária Residencial' },
    description: { es: 'Compra/venta y asesoramiento', 'pt-BR': 'Compra/venda e assessoria' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'inmobiliaria_comercial',
    emoji: '🏬',
    labels: { es: 'Inmobiliaria Comercial', 'pt-BR': 'Imobiliária Comercial' },
    description: { es: 'Locales, oficinas y contratos', 'pt-BR': 'Lojas, escritórios e contratos' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'administracion_alquileres',
    emoji: '🔑',
    labels: { es: 'Administración de Alquileres', 'pt-BR': 'Administração de Aluguéis' },
    description: { es: 'Cobranza, contratos y gestión', 'pt-BR': 'Cobrança, contratos e gestão' },
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 'gestion_consorcios',
    emoji: '🏘️',
    labels: { es: 'Gestión de Consorcios', 'pt-BR': 'Gestão de Condomínios' },
    description: { es: 'Administración de edificios y expensas', 'pt-BR': 'Administração de prédios e taxas' },
    gradient: 'from-teal-500/20 to-cyan-500/20',
  },
  {
    id: 'property_management',
    emoji: '🏢',
    labels: { es: 'Property Management Corporativo', 'pt-BR': 'Property Management Corporativo' },
    description: { es: 'Gestión integral de propiedades', 'pt-BR': 'Gestão integral de propriedades' },
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  {
    id: 'lotes_terrenos',
    emoji: '🌳',
    labels: { es: 'Lotes / Terrenos / Country', 'pt-BR': 'Lotes / Terrenos / Condomínio' },
    description: { es: 'Venta y desarrollo de tierra', 'pt-BR': 'Venda e desenvolvimento de terra' },
    gradient: 'from-green-600/20 to-lime-500/20',
  },
  {
    id: 'tasacion_peritaje',
    emoji: '📏',
    labels: { es: 'Tasación / Peritaje', 'pt-BR': 'Avaliação / Perícia' },
    description: { es: 'Valuación y reportes técnicos', 'pt-BR': 'Avaliação e laudos técnicos' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'seguridad_higiene_obra',
    emoji: '🦺',
    labels: { es: 'Seguridad e Higiene (Obra)', 'pt-BR': 'Segurança do Trabalho (Obra)' },
    description: { es: 'Normas, inspecciones y cumplimiento', 'pt-BR': 'Normas, inspeções e conformidade' },
    gradient: 'from-yellow-500/20 to-orange-500/20',
  },
  {
    id: 'interiorismo',
    emoji: '🛋️',
    labels: { es: 'Interiorismo / Decoración', 'pt-BR': 'Design de Interiores / Decoração' },
    description: { es: 'Diseño interior y ambientación', 'pt-BR': 'Design de interiores e ambientação' },
    gradient: 'from-pink-500/20 to-purple-500/20',
  },
  {
    id: 'paisajismo',
    emoji: '🌿',
    labels: { es: 'Paisajismo', 'pt-BR': 'Paisagismo' },
    description: { es: 'Espacios verdes y proyectos exteriores', 'pt-BR': 'Espaços verdes e projetos externos' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
];

// A9_LOGISTICA - Transporte, logística y movilidad
const LOGISTICA_TYPES: BusinessTypeData[] = [
  {
    id: 'mensajeria_urbana',
    emoji: '🛵',
    labels: { es: 'Mensajería Urbana', 'pt-BR': 'Motoboy / Entrega Urbana' },
    description: { es: 'Envíos rápidos en ciudad', 'pt-BR': 'Entregas rápidas na cidade' },
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'courier_nacional',
    emoji: '📦',
    labels: { es: 'Courier Nacional', 'pt-BR': 'Transportadora Nacional' },
    description: { es: 'Paquetes a todo el país', 'pt-BR': 'Pacotes para todo o país' },
    gradient: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    id: 'logistica_ecommerce',
    emoji: '🏬',
    labels: { es: 'Logística E-commerce / Fulfillment', 'pt-BR': 'Logística E-commerce / Fulfillment' },
    description: { es: 'Picking, packing y despacho', 'pt-BR': 'Picking, packing e despacho' },
    gradient: 'from-purple-500/20 to-pink-500/20',
  },
  {
    id: 'ultima_milla',
    emoji: '🚚',
    labels: { es: 'Última Milla', 'pt-BR': 'Última Milha' },
    description: { es: 'Distribución final al cliente', 'pt-BR': 'Distribuição final ao cliente' },
    gradient: 'from-green-500/20 to-teal-500/20',
  },
  {
    id: 'transporte_carga',
    emoji: '🚛',
    labels: { es: 'Transporte de Carga General', 'pt-BR': 'Transporte de Carga Geral' },
    description: { es: 'Fletes y rutas nacionales', 'pt-BR': 'Fretes e rotas nacionais' },
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  {
    id: 'transporte_refrigerado',
    emoji: '🧊',
    labels: { es: 'Transporte Refrigerado', 'pt-BR': 'Transporte Refrigerado' },
    description: { es: 'Cadena de frío y alimentos', 'pt-BR': 'Cadeia de frio e alimentos' },
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 'cargas_peligrosas',
    emoji: '☣️',
    labels: { es: 'Cargas Peligrosas / Especiales', 'pt-BR': 'Cargas Perigosas / Especiais' },
    description: { es: 'Normativa y transporte específico', 'pt-BR': 'Normativa e transporte específico' },
    gradient: 'from-red-600/20 to-orange-600/20',
  },
  {
    id: 'fletes_mudanzas',
    emoji: '🏠',
    labels: { es: 'Fletes y Mudanzas', 'pt-BR': 'Fretes e Mudanças' },
    description: { es: 'Traslados residenciales y comerciales', 'pt-BR': 'Transportes residenciais e comerciais' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'deposito_almacenaje',
    emoji: '🏢',
    labels: { es: 'Depósito / Almacenaje', 'pt-BR': 'Depósito / Armazenagem' },
    description: { es: 'Guardado, stock y distribución', 'pt-BR': 'Guarda, estoque e distribuição' },
    gradient: 'from-slate-500/20 to-gray-500/20',
  },
  {
    id: 'freight_forwarder',
    emoji: '🌍',
    labels: { es: 'Freight Forwarder / Internacional', 'pt-BR': 'Freight Forwarder / Internacional' },
    description: { es: 'Import/export y coordinación logística', 'pt-BR': 'Import/export e coordenação logística' },
    gradient: 'from-teal-500/20 to-cyan-500/20',
  },
  {
    id: 'despachante_aduana',
    emoji: '🧾',
    labels: { es: 'Despachante de Aduana', 'pt-BR': 'Despachante Aduaneiro' },
    description: { es: 'Gestión documental y aduanera', 'pt-BR': 'Gestão documental e aduaneira' },
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 'taxi_remis',
    emoji: '🚖',
    labels: { es: 'Taxi / Remis', 'pt-BR': 'Táxi / Transporte Executivo' },
    description: { es: 'Transporte urbano y traslados', 'pt-BR': 'Transporte urbano e translados' },
    gradient: 'from-yellow-500/20 to-amber-500/20',
  },
  {
    id: 'flota_app',
    emoji: '🚘',
    labels: { es: 'Flota por App / Movilidad', 'pt-BR': 'Frota por App / Mobilidade' },
    description: { es: 'Operación de flota y viajes', 'pt-BR': 'Operação de frota e viagens' },
    gradient: 'from-violet-500/20 to-purple-500/20',
  },
  {
    id: 'transporte_turistico',
    emoji: '🚌',
    labels: { es: 'Transporte Turístico', 'pt-BR': 'Transporte Turístico' },
    description: { es: 'Excursiones y traslados grupales', 'pt-BR': 'Excursões e translados em grupo' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'transporte_escolar',
    emoji: '🧒',
    labels: { es: 'Transporte Escolar', 'pt-BR': 'Transporte Escolar' },
    description: { es: 'Rutas, seguridad y horarios', 'pt-BR': 'Rotas, segurança e horários' },
    gradient: 'from-yellow-400/20 to-orange-400/20',
  },
  {
    id: 'transporte_corporativo',
    emoji: '🏭',
    labels: { es: 'Transporte Corporativo (Shuttles)', 'pt-BR': 'Transporte Corporativo (Shuttles)' },
    description: { es: 'Personal, turnos y empresas', 'pt-BR': 'Pessoal, turnos e empresas' },
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  {
    id: 'alquiler_vehiculos',
    emoji: '🚗',
    labels: { es: 'Alquiler de Vehículos (Rent a Car)', 'pt-BR': 'Aluguel de Veículos (Rent a Car)' },
    description: { es: 'Autos por día y servicios', 'pt-BR': 'Carros por dia e serviços' },
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'gestion_flotas',
    emoji: '📡',
    labels: { es: 'Gestión de Flotas', 'pt-BR': 'Gestão de Frotas' },
    description: { es: 'Control, optimización y operación B2B', 'pt-BR': 'Controle, otimização e operação B2B' },
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
];

// A10_AGRO - Agro, ganadería y agroindustria
const AGRO_TYPES: BusinessTypeData[] = [
  {
    id: 'agricultura_extensiva',
    emoji: '🌽',
    labels: { es: 'Agricultura Extensiva (Granos)', 'pt-BR': 'Agricultura Extensiva (Grãos)' },
    description: { es: 'Soja, maíz, trigo y rotación', 'pt-BR': 'Soja, milho, trigo e rotação' },
    gradient: 'from-yellow-500/20 to-amber-500/20',
  },
  {
    id: 'horticultura',
    emoji: '🥬',
    labels: { es: 'Horticultura (Intensiva)', 'pt-BR': 'Horticultura (Intensiva)' },
    description: { es: 'Verduras, invernadero y ciclos cortos', 'pt-BR': 'Verduras, estufa e ciclos curtos' },
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 'fruticultura',
    emoji: '🍎',
    labels: { es: 'Fruticultura', 'pt-BR': 'Fruticultura' },
    description: { es: 'Producción frutal y estacionalidad', 'pt-BR': 'Produção de frutas e sazonalidade' },
    gradient: 'from-red-500/20 to-orange-500/20',
  },
  {
    id: 'vitivinicultura',
    emoji: '🍇',
    labels: { es: 'Vitivinicultura', 'pt-BR': 'Vitivinicultura' },
    description: { es: 'Uva, viñedo y producción asociada', 'pt-BR': 'Uva, vinhedo e produção associada' },
    gradient: 'from-purple-500/20 to-pink-500/20',
  },
  {
    id: 'ganaderia_bovina',
    emoji: '🐄',
    labels: { es: 'Ganadería Bovina (Cría/Recría)', 'pt-BR': 'Pecuária Bovina (Cria/Recria)' },
    description: { es: 'Producción de carne y manejo', 'pt-BR': 'Produção de carne e manejo' },
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  {
    id: 'feedlot_engorde',
    emoji: '🥩',
    labels: { es: 'Feedlot / Engorde', 'pt-BR': 'Confinamento / Engorda' },
    description: { es: 'Engorde intensivo y terminación', 'pt-BR': 'Engorda intensiva e terminação' },
    gradient: 'from-red-600/20 to-rose-600/20',
  },
  {
    id: 'porcicultura',
    emoji: '🐖',
    labels: { es: 'Porcicultura', 'pt-BR': 'Suinocultura' },
    description: { es: 'Producción porcina y ciclos', 'pt-BR': 'Produção suína e ciclos' },
    gradient: 'from-pink-400/20 to-rose-400/20',
  },
  {
    id: 'avicultura',
    emoji: '🐔',
    labels: { es: 'Avicultura', 'pt-BR': 'Avicultura' },
    description: { es: 'Pollos, huevos y granjas', 'pt-BR': 'Frangos, ovos e granjas' },
    gradient: 'from-orange-400/20 to-yellow-400/20',
  },
  {
    id: 'lecheria_tambo',
    emoji: '🥛',
    labels: { es: 'Lechería / Tambo', 'pt-BR': 'Laticínios / Ordenha' },
    description: { es: 'Producción láctea y ordeñe', 'pt-BR': 'Produção leiteira e ordenha' },
    gradient: 'from-sky-400/20 to-blue-400/20',
  },
  {
    id: 'apicultura',
    emoji: '🍯',
    labels: { es: 'Apicultura', 'pt-BR': 'Apicultura' },
    description: { es: 'Miel, colmenas y derivados', 'pt-BR': 'Mel, colmeias e derivados' },
    gradient: 'from-yellow-400/20 to-amber-400/20',
  },
  {
    id: 'acuicultura',
    emoji: '🐟',
    labels: { es: 'Acuicultura / Piscicultura', 'pt-BR': 'Aquicultura / Piscicultura' },
    description: { es: 'Producción de peces y sistemas', 'pt-BR': 'Produção de peixes e sistemas' },
    gradient: 'from-cyan-500/20 to-teal-500/20',
  },
  {
    id: 'vivero_semilleria',
    emoji: '🌱',
    labels: { es: 'Vivero / Semillería', 'pt-BR': 'Viveiro / Sementeira' },
    description: { es: 'Plantines, semillas y genética', 'pt-BR': 'Mudas, sementes e genética' },
    gradient: 'from-green-400/20 to-lime-400/20',
  },
  {
    id: 'agroinsumos',
    emoji: '🧪',
    labels: { es: 'Agroinsumos', 'pt-BR': 'Agroinsumos' },
    description: { es: 'Fertilizantes, fitos y nutrición', 'pt-BR': 'Fertilizantes, defensivos e nutrição' },
    gradient: 'from-indigo-500/20 to-purple-500/20',
  },
  {
    id: 'contratista_rural',
    emoji: '🚜',
    labels: { es: 'Contratista Rural (Maquinaria)', 'pt-BR': 'Prestador Rural (Maquinário)' },
    description: { es: 'Siembra, cosecha y servicios', 'pt-BR': 'Plantio, colheita e serviços' },
    gradient: 'from-green-600/20 to-teal-600/20',
  },
  {
    id: 'acopio_granos',
    emoji: '🏗️',
    labels: { es: 'Acopio y Comercialización de Granos', 'pt-BR': 'Armazenagem e Comercialização de Grãos' },
    description: { es: 'Recepción, silos y venta', 'pt-BR': 'Recepção, silos e venda' },
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 'cooperativa_agropecuaria',
    emoji: '🤝',
    labels: { es: 'Cooperativa Agropecuaria', 'pt-BR': 'Cooperativa Agropecuária' },
    description: { es: 'Servicios, compras y comercialización', 'pt-BR': 'Serviços, compras e comercialização' },
    gradient: 'from-blue-500/20 to-indigo-500/20',
  },
  {
    id: 'agroindustria',
    emoji: '🏭',
    labels: { es: 'Agroindustria (Procesamiento)', 'pt-BR': 'Agroindústria (Processamento)' },
    description: { es: 'Molienda, alimentos y agregado de valor', 'pt-BR': 'Moagem, alimentos e agregação de valor' },
    gradient: 'from-slate-600/20 to-gray-600/20',
  },
  {
    id: 'agtech',
    emoji: '🛰️',
    labels: { es: 'Agtech / Servicios de Datos', 'pt-BR': 'Agtech / Serviços de Dados' },
    description: { es: 'Monitoreo, drones y gestión digital', 'pt-BR': 'Monitoramento, drones e gestão digital' },
    gradient: 'from-violet-500/20 to-purple-500/20',
  },
];

// Export all business types by sector
export const ALL_BUSINESS_TYPES: SectorBusinessTypes = {
  'A1_GASTRO': GASTRO_TYPES,
  'A2_TURISMO': TURISMO_TYPES,
  'A3_RETAIL': RETAIL_TYPES,
  'A4_SALUD': SALUD_TYPES,
  'A5_EDUCACION': EDUCACION_TYPES,
  'A6_B2B': B2B_TYPES,
  'A7_HOGAR_SERV': HOGAR_TYPES,
  'A8_CONSTRU_INMO': CONSTRUCCION_TYPES,
  'A9_LOGISTICA': LOGISTICA_TYPES,
  'A10_AGRO': AGRO_TYPES,
};

// Helper function to get business types for a specific area
export function getBusinessTypesForArea(areaId: string): BusinessTypeData[] {
  return ALL_BUSINESS_TYPES[areaId] || [];
}

// Helper function to get a specific business type by ID across all areas
export function getBusinessTypeById(typeId: string): BusinessTypeData | undefined {
  for (const types of Object.values(ALL_BUSINESS_TYPES)) {
    const found = types.find(t => t.id === typeId);
    if (found) return found;
  }
  return undefined;
}
