// Gimnasio / Fitness Center - Complete Questionnaire
// 36 questions across 9 valid categories
// Categories: identity, operation, sales, menu, finance, team, marketing, reputation, goals

import type { GastroQuestion } from '../../gastroQuestionsEngine';

export const GIMNASIO_QUESTIONS: GastroQuestion[] = [
  // ==================== IDENTITY (5) ====================
  {
    id: 'SA_GYM_001',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de gimnasio operás?', 'pt-BR': 'Que tipo de academia você opera?' },
    type: 'single',
    required: true,
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'full_gym', label: { es: 'Gimnasio completo (musculación + cardio + clases)', 'pt-BR': 'Academia completa (musculação + cardio + aulas)' }, emoji: '🏋️', impactScore: 18 },
      { id: 'boutique', label: { es: 'Boutique fitness (especializado)', 'pt-BR': 'Boutique fitness (especializado)' }, emoji: '💎', impactScore: 20 },
      { id: 'crossfit', label: { es: 'CrossFit / Funcional', 'pt-BR': 'CrossFit / Funcional' }, emoji: '🔥', impactScore: 18 },
      { id: 'low_cost', label: { es: 'Low cost / 24 horas', 'pt-BR': 'Low cost / 24 horas' }, emoji: '⏰', impactScore: 15 },
      { id: 'studio', label: { es: 'Estudio pequeño', 'pt-BR': 'Estúdio pequeno' }, emoji: '🏠', impactScore: 12 },
    ],
  },
  {
    id: 'SA_GYM_002',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Cuántos años tiene el gimnasio?', 'pt-BR': 'Quantos anos tem a academia?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '0-1', label: { es: 'Menos de 1 año', 'pt-BR': 'Menos de 1 ano' }, emoji: '🌱', impactScore: 8 },
      { id: '1-3', label: { es: '1-3 años', 'pt-BR': '1-3 anos' }, emoji: '📈', impactScore: 12 },
      { id: '3-7', label: { es: '3-7 años', 'pt-BR': '3-7 anos' }, emoji: '🏆', impactScore: 15 },
      { id: '7+', label: { es: 'Más de 7 años', 'pt-BR': 'Mais de 7 anos' }, emoji: '👑', impactScore: 18 },
    ],
  },
  {
    id: 'SA_GYM_003',
    category: 'identity',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántos metros cuadrados tiene?', 'pt-BR': 'Quantos metros quadrados tem?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'small', label: { es: 'Menos de 200 m²', 'pt-BR': 'Menos de 200 m²' }, emoji: '🏠', impactScore: 10 },
      { id: 'medium', label: { es: '200-500 m²', 'pt-BR': '200-500 m²' }, emoji: '🏢', impactScore: 15 },
      { id: 'large', label: { es: '500-1000 m²', 'pt-BR': '500-1000 m²' }, emoji: '🏟️', impactScore: 18 },
      { id: 'xlarge', label: { es: 'Más de 1000 m²', 'pt-BR': 'Mais de 1000 m²' }, emoji: '🏰', impactScore: 20 },
    ],
  },
  {
    id: 'SA_GYM_004',
    category: 'identity',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Dónde está ubicado?', 'pt-BR': 'Onde está localizado?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'downtown', label: { es: 'Centro/Zona comercial', 'pt-BR': 'Centro/Zona comercial' }, emoji: '🏢', impactScore: 15 },
      { id: 'residential', label: { es: 'Barrio residencial', 'pt-BR': 'Bairro residencial' }, emoji: '🏘️', impactScore: 15 },
      { id: 'mall', label: { es: 'Centro comercial', 'pt-BR': 'Shopping center' }, emoji: '🏬', impactScore: 18 },
      { id: 'office', label: { es: 'Zona de oficinas', 'pt-BR': 'Zona de escritórios' }, emoji: '💼', impactScore: 15 },
    ],
  },
  {
    id: 'SA_GYM_005',
    category: 'identity',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Cuál es tu diferenciador principal?', 'pt-BR': 'Qual é seu diferencial principal?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'equipment', label: { es: 'Equipamiento de última generación', 'pt-BR': 'Equipamento de última geração' }, emoji: '🏋️', impactScore: 18 },
      { id: 'classes', label: { es: 'Variedad de clases grupales', 'pt-BR': 'Variedade de aulas em grupo' }, emoji: '👥', impactScore: 15 },
      { id: 'trainers', label: { es: 'Entrenadores certificados', 'pt-BR': 'Treinadores certificados' }, emoji: '👨‍🏫', impactScore: 18 },
      { id: 'price', label: { es: 'Mejor precio de la zona', 'pt-BR': 'Melhor preço da região' }, emoji: '💰', impactScore: 12 },
      { id: 'community', label: { es: 'Comunidad / Ambiente', 'pt-BR': 'Comunidade / Ambiente' }, emoji: '❤️', impactScore: 18 },
    ],
  },

  // ==================== MENU/SERVICES (4) ====================
  {
    id: 'SA_GYM_006',
    category: 'menu',
    mode: 'both',
    dimension: 'traffic',
    weight: 9,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'weights', label: { es: 'Musculación / Pesas', 'pt-BR': 'Musculação / Pesos' }, emoji: '🏋️', impactScore: 15 },
      { id: 'cardio', label: { es: 'Zona cardio', 'pt-BR': 'Zona cardio' }, emoji: '🏃', impactScore: 12 },
      { id: 'group_classes', label: { es: 'Clases grupales', 'pt-BR': 'Aulas em grupo' }, emoji: '👥', impactScore: 15 },
      { id: 'personal', label: { es: 'Entrenamiento personal', 'pt-BR': 'Treino personal' }, emoji: '👨‍🏫', impactScore: 18 },
      { id: 'spinning', label: { es: 'Spinning / Cycling', 'pt-BR': 'Spinning / Cycling' }, emoji: '🚴', impactScore: 12 },
      { id: 'functional', label: { es: 'Entrenamiento funcional', 'pt-BR': 'Treino funcional' }, emoji: '🔥', impactScore: 15 },
      { id: 'pool', label: { es: 'Piscina', 'pt-BR': 'Piscina' }, emoji: '🏊', impactScore: 18 },
    ],
  },
  {
    id: 'SA_GYM_007',
    category: 'menu',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Ofrecés nutrición o suplementos?', 'pt-BR': 'Você oferece nutrição ou suplementos?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'yes_both', label: { es: 'Sí, nutricionista + venta de suplementos', 'pt-BR': 'Sim, nutricionista + venda de suplementos' }, emoji: '🥗', impactScore: 20 },
      { id: 'supplements', label: { es: 'Solo venta de suplementos', 'pt-BR': 'Só venda de suplementos' }, emoji: '💊', impactScore: 15 },
      { id: 'nutritionist', label: { es: 'Solo nutricionista', 'pt-BR': 'Só nutricionista' }, emoji: '👨‍⚕️', impactScore: 15 },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌', impactScore: 5 },
    ],
  },

  // ==================== SALES (4) ====================
  {
    id: 'SA_GYM_008',
    category: 'sales',
    mode: 'both',
    dimension: 'traffic',
    weight: 9,
    title: { es: '¿Cuántos socios activos tenés?', 'pt-BR': 'Quantos membros ativos você tem?' },
    type: 'single',
    required: true,
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '0-100', label: { es: 'Menos de 100', 'pt-BR': 'Menos de 100' }, emoji: '👤', impactScore: 8 },
      { id: '100-300', label: { es: '100-300 socios', 'pt-BR': '100-300 membros' }, emoji: '👥', impactScore: 12 },
      { id: '300-600', label: { es: '300-600 socios', 'pt-BR': '300-600 membros' }, emoji: '🏢', impactScore: 15 },
      { id: '600-1000', label: { es: '600-1000 socios', 'pt-BR': '600-1000 membros' }, emoji: '🏟️', impactScore: 18 },
      { id: '1000+', label: { es: 'Más de 1000', 'pt-BR': 'Mais de 1000' }, emoji: '🏰', impactScore: 20 },
    ],
  },
  {
    id: 'SA_GYM_009',
    category: 'sales',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿Cuántos socios nuevos sumás por mes?', 'pt-BR': 'Quantos novos membros você adiciona por mês?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '0-10', label: { es: '0-10 nuevos', 'pt-BR': '0-10 novos' }, emoji: '📉', impactScore: 5 },
      { id: '10-30', label: { es: '10-30 nuevos', 'pt-BR': '10-30 novos' }, emoji: '📈', impactScore: 12 },
      { id: '30-60', label: { es: '30-60 nuevos', 'pt-BR': '30-60 novos' }, emoji: '🚀', impactScore: 18 },
      { id: '60+', label: { es: 'Más de 60', 'pt-BR': 'Mais de 60' }, emoji: '💎', impactScore: 20 },
    ],
  },

  // ==================== OPERATION (5) ====================
  {
    id: 'SA_GYM_010',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Qué sistema usás para gestionar socios?', 'pt-BR': 'Que sistema você usa para gerenciar membros?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'specialized', label: { es: 'Software especializado (Gympass, etc)', 'pt-BR': 'Software especializado (Gympass, etc)' }, emoji: '💻', impactScore: 20 },
      { id: 'generic', label: { es: 'Software genérico (Excel, etc)', 'pt-BR': 'Software genérico (Excel, etc)' }, emoji: '📊', impactScore: 10 },
      { id: 'manual', label: { es: 'Manual / Fichas', 'pt-BR': 'Manual / Fichas' }, emoji: '📝', impactScore: 5 },
    ],
  },
  {
    id: 'SA_GYM_011',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántas horas operás por día?', 'pt-BR': 'Quantas horas você opera por dia?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '8-10', label: { es: '8-10 horas', 'pt-BR': '8-10 horas' }, emoji: '🕐', impactScore: 10 },
      { id: '12-14', label: { es: '12-14 horas', 'pt-BR': '12-14 horas' }, emoji: '🕑', impactScore: 15 },
      { id: '16-18', label: { es: '16-18 horas', 'pt-BR': '16-18 horas' }, emoji: '🕒', impactScore: 18 },
      { id: '24', label: { es: '24 horas', 'pt-BR': '24 horas' }, emoji: '🔄', impactScore: 20 },
    ],
  },
  {
    id: 'SA_GYM_012',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Estado del equipamiento?', 'pt-BR': 'Estado dos equipamentos?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'new', label: { es: 'Nuevo (menos de 2 años)', 'pt-BR': 'Novo (menos de 2 anos)' }, emoji: '✨', impactScore: 20 },
      { id: 'good', label: { es: 'Buen estado (2-5 años)', 'pt-BR': 'Bom estado (2-5 anos)' }, emoji: '👍', impactScore: 15 },
      { id: 'used', label: { es: 'Usado (5-10 años)', 'pt-BR': 'Usado (5-10 anos)' }, emoji: '😐', impactScore: 10 },
      { id: 'old', label: { es: 'Necesita renovación', 'pt-BR': 'Precisa renovação' }, emoji: '⚠️', impactScore: 5 },
    ],
  },

  // ==================== FINANCE (4) ====================
  {
    id: 'SA_GYM_013',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 9,
    title: { es: '¿Cuál es tu cuota mensual promedio?', 'pt-BR': 'Qual é sua mensalidade média?' },
    type: 'number',
    businessTypes: ['gimnasio_fitness'],
  },
  {
    id: 'SA_GYM_014',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 8,
    title: { es: '¿Cuál es tu tasa de deserción mensual?', 'pt-BR': 'Qual é sua taxa de evasão mensal?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'low', label: { es: 'Menos de 5%', 'pt-BR': 'Menos de 5%' }, emoji: '💚', impactScore: 20 },
      { id: 'medium', label: { es: '5-10%', 'pt-BR': '5-10%' }, emoji: '💛', impactScore: 15 },
      { id: 'high', label: { es: '10-15%', 'pt-BR': '10-15%' }, emoji: '🟠', impactScore: 10 },
      { id: 'very_high', label: { es: 'Más de 15%', 'pt-BR': 'Mais de 15%' }, emoji: '🔴', impactScore: 5 },
    ],
  },

  // ==================== TEAM (3) ====================
  {
    id: 'SA_GYM_015',
    category: 'team',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántos entrenadores tenés?', 'pt-BR': 'Quantos treinadores você tem?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '1-3', label: { es: '1-3 entrenadores', 'pt-BR': '1-3 treinadores' }, emoji: '👤', impactScore: 10 },
      { id: '4-8', label: { es: '4-8 entrenadores', 'pt-BR': '4-8 treinadores' }, emoji: '👥', impactScore: 15 },
      { id: '9-15', label: { es: '9-15 entrenadores', 'pt-BR': '9-15 treinadores' }, emoji: '🏢', impactScore: 18 },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '🏟️', impactScore: 20 },
    ],
  },
  {
    id: 'SA_GYM_016',
    category: 'team',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Tus entrenadores tienen certificaciones?', 'pt-BR': 'Seus treinadores têm certificações?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'all', label: { es: 'Todos certificados', 'pt-BR': 'Todos certificados' }, emoji: '🎓', impactScore: 20 },
      { id: 'most', label: { es: 'La mayoría', 'pt-BR': 'A maioria' }, emoji: '📚', impactScore: 15 },
      { id: 'some', label: { es: 'Algunos', 'pt-BR': 'Alguns' }, emoji: '📖', impactScore: 10 },
      { id: 'few', label: { es: 'Pocos', 'pt-BR': 'Poucos' }, emoji: '⚠️', impactScore: 5 },
    ],
  },

  // ==================== MARKETING (3) ====================
  {
    id: 'SA_GYM_017',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cómo atraés nuevos socios?', 'pt-BR': 'Como você atrai novos membros?' },
    type: 'multi',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'referrals', label: { es: 'Referidos / Boca a boca', 'pt-BR': 'Indicações / Boca a boca' }, emoji: '🗣️', impactScore: 18 },
      { id: 'social', label: { es: 'Redes sociales', 'pt-BR': 'Redes sociais' }, emoji: '📱', impactScore: 15 },
      { id: 'google', label: { es: 'Google Ads', 'pt-BR': 'Google Ads' }, emoji: '🔍', impactScore: 15 },
      { id: 'local', label: { es: 'Publicidad local', 'pt-BR': 'Publicidade local' }, emoji: '📍', impactScore: 10 },
      { id: 'partnerships', label: { es: 'Convenios empresariales', 'pt-BR': 'Convênios empresariais' }, emoji: '🤝', impactScore: 18 },
    ],
  },
  {
    id: 'SA_GYM_018',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Tenés programa de referidos?', 'pt-BR': 'Você tem programa de indicação?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'yes_active', label: { es: 'Sí, muy activo', 'pt-BR': 'Sim, muito ativo' }, emoji: '🌟', impactScore: 20 },
      { id: 'yes_basic', label: { es: 'Sí, básico', 'pt-BR': 'Sim, básico' }, emoji: '👍', impactScore: 15 },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌', impactScore: 5 },
    ],
  },

  // ==================== REPUTATION (3) ====================
  {
    id: 'SA_GYM_019',
    category: 'reputation',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuál es tu rating en Google?', 'pt-BR': 'Qual é sua avaliação no Google?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '4.5+', label: { es: '4.5 o más', 'pt-BR': '4.5 ou mais' }, emoji: '⭐', impactScore: 20 },
      { id: '4-4.5', label: { es: '4.0-4.4', 'pt-BR': '4.0-4.4' }, emoji: '⭐', impactScore: 15 },
      { id: '3.5-4', label: { es: '3.5-3.9', 'pt-BR': '3.5-3.9' }, emoji: '⭐', impactScore: 10 },
      { id: 'below_3.5', label: { es: 'Menos de 3.5', 'pt-BR': 'Menos de 3.5' }, emoji: '😔', impactScore: 5 },
      { id: 'no_reviews', label: { es: 'No tengo reseñas', 'pt-BR': 'Não tenho avaliações' }, emoji: '❓', impactScore: 0 },
    ],
  },
  {
    id: 'SA_GYM_020',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Medís satisfacción de socios?', 'pt-BR': 'Você mede satisfação dos membros?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'nps', label: { es: 'Sí, NPS sistemático', 'pt-BR': 'Sim, NPS sistemático' }, emoji: '📊', impactScore: 20 },
      { id: 'surveys', label: { es: 'Encuestas ocasionales', 'pt-BR': 'Pesquisas ocasionais' }, emoji: '📋', impactScore: 12 },
      { id: 'informal', label: { es: 'Solo feedback informal', 'pt-BR': 'Só feedback informal' }, emoji: '💬', impactScore: 8 },
      { id: 'no', label: { es: 'No medimos', 'pt-BR': 'Não medimos' }, emoji: '❌', impactScore: 5 },
    ],
  },

  // ==================== GOALS (3) ====================
  {
    id: 'SA_GYM_021',
    category: 'goals',
    mode: 'both',
    dimension: 'growth',
    weight: 8,
    title: { es: '¿Cuál es tu objetivo principal?', 'pt-BR': 'Qual é seu objetivo principal?' },
    type: 'single',
    required: true,
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'grow_members', label: { es: 'Aumentar socios', 'pt-BR': 'Aumentar membros' }, emoji: '📈', impactScore: 15 },
      { id: 'reduce_churn', label: { es: 'Reducir deserción', 'pt-BR': 'Reduzir evasão' }, emoji: '🔄', impactScore: 18 },
      { id: 'increase_revenue', label: { es: 'Aumentar ingresos por socio', 'pt-BR': 'Aumentar receita por membro' }, emoji: '💰', impactScore: 18 },
      { id: 'expand', label: { es: 'Abrir otra sede', 'pt-BR': 'Abrir outra unidade' }, emoji: '🚀', impactScore: 20 },
      { id: 'optimize', label: { es: 'Optimizar operación', 'pt-BR': 'Otimizar operação' }, emoji: '⚙️', impactScore: 15 },
    ],
  },
  {
    id: 'SA_GYM_022',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿Mayor riesgo actual?', 'pt-BR': 'Maior risco atual?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'competition', label: { es: 'Competencia nueva', 'pt-BR': 'Concorrência nova' }, emoji: '🏋️', impactScore: -15 },
      { id: 'economy', label: { es: 'Situación económica', 'pt-BR': 'Situação econômica' }, emoji: '💸', impactScore: -15 },
      { id: 'seasonality', label: { es: 'Estacionalidad (verano)', 'pt-BR': 'Sazonalidade (verão)' }, emoji: '☀️', impactScore: -10 },
      { id: 'equipment', label: { es: 'Equipamiento obsoleto', 'pt-BR': 'Equipamento obsoleto' }, emoji: '⚠️', impactScore: -12 },
      { id: 'rent', label: { es: 'Alquiler del local', 'pt-BR': 'Aluguel do local' }, emoji: '🏢', impactScore: -12 },
    ],
  },
];

export default GIMNASIO_QUESTIONS;
