// ============================================
// B2B - Cuestionario Ultra-Específico Completo
// Sector: Servicios profesionales y B2B
// 18 tipos de negocio, Quick (10-15) + Complete (68-75 preguntas)
// 7 Dimensiones: Crecimiento, Equipo, Tráfico, Rentabilidad, Finanzas, Eficiencia, Reputación
// ============================================

export interface B2BQuestion {
  id: string;
  category: string;
  mode: 'quick' | 'complete' | 'both';
  dimension: 'reputation' | 'profitability' | 'finances' | 'efficiency' | 'traffic' | 'team' | 'growth';
  weight: number;
  title: { es: string; 'pt-BR': string };
  help?: { es: string; 'pt-BR': string };
  type: 'single' | 'multi' | 'number' | 'slider' | 'text' | 'money';
  options?: Array<{ id: string; label: { es: string; 'pt-BR': string }; emoji?: string }>;
  min?: number;
  max?: number;
  unit?: string;
  required?: boolean;
  businessTypes?: string[];
}

// IDs de tipos de negocio B2B
export const B2B_BUSINESS_TYPES = {
  CONSULTORIA_ESTRATEGICA: 'consultoria_estrategica',
  CONSULTORIA_COMERCIAL: 'consultoria_comercial',
  AGENCIA_MARKETING: 'agencia_marketing',
  BRANDING_DISENO: 'branding_diseno',
  DESARROLLO_SOFTWARE: 'desarrollo_software',
  SERVICIOS_IT: 'servicios_it',
  CIBERSEGURIDAD: 'ciberseguridad',
  ESTUDIO_CONTABLE: 'estudio_contable',
  ESTUDIO_JURIDICO: 'estudio_juridico',
  RRHH_RECLUTAMIENTO: 'rrhh_reclutamiento',
  CAPACITACION: 'capacitacion_empresarial',
  ASESORIA_FINANCIERA: 'asesoria_financiera',
  SEGUROS: 'seguros_broker',
  INVESTIGACION: 'investigacion_mercado',
  PRODUCCION_AUDIOVISUAL: 'produccion_audiovisual',
  TRADUCCION: 'traduccion_localizacion',
  LIMPIEZA_FACILITY: 'limpieza_facility',
  OUTSOURCING: 'outsourcing_backoffice',
};

// Grupos de tipos para preguntas condicionales
const CONSULTORIA = [
  B2B_BUSINESS_TYPES.CONSULTORIA_ESTRATEGICA,
  B2B_BUSINESS_TYPES.CONSULTORIA_COMERCIAL,
  B2B_BUSINESS_TYPES.ASESORIA_FINANCIERA,
];

const AGENCIAS_CREATIVAS = [
  B2B_BUSINESS_TYPES.AGENCIA_MARKETING,
  B2B_BUSINESS_TYPES.BRANDING_DISENO,
  B2B_BUSINESS_TYPES.PRODUCCION_AUDIOVISUAL,
];

const TECH_SERVICES = [
  B2B_BUSINESS_TYPES.DESARROLLO_SOFTWARE,
  B2B_BUSINESS_TYPES.SERVICIOS_IT,
  B2B_BUSINESS_TYPES.CIBERSEGURIDAD,
];

const PROFESSIONAL_SERVICES = [
  B2B_BUSINESS_TYPES.ESTUDIO_CONTABLE,
  B2B_BUSINESS_TYPES.ESTUDIO_JURIDICO,
  B2B_BUSINESS_TYPES.SEGUROS,
];

const OPERATIONAL_SERVICES = [
  B2B_BUSINESS_TYPES.LIMPIEZA_FACILITY,
  B2B_BUSINESS_TYPES.OUTSOURCING,
];

// ============================================
// PREGUNTAS UNIVERSALES B2B (todos los tipos)
// ============================================

export const B2B_COMPLETE_QUESTIONS: B2BQuestion[] = [
  // --- IDENTIDAD (8 preguntas) ---
  {
    id: 'B2B01_YEARS',
    category: 'identity',
    mode: 'both',
    dimension: 'growth',
    weight: 8,
    title: { es: '¿Hace cuánto opera tu empresa/estudio?', 'pt-BR': 'Há quanto tempo sua empresa/escritório opera?' },
    type: 'single',
    options: [
      { id: '<1y', label: { es: 'Menos de 1 año', 'pt-BR': 'Menos de 1 ano' }, emoji: '🆕' },
      { id: '1-3y', label: { es: '1-3 años', 'pt-BR': '1-3 anos' }, emoji: '📅' },
      { id: '3-10y', label: { es: '3-10 años', 'pt-BR': '3-10 anos' }, emoji: '📈' },
      { id: '10+', label: { es: 'Más de 10 años', 'pt-BR': 'Mais de 10 anos' }, emoji: '🏆' },
    ],
  },
  {
    id: 'B2B02_ACTIVE_CLIENTS',
    category: 'identity',
    mode: 'both',
    dimension: 'growth',
    weight: 9,
    title: { es: '¿Cuántos clientes activos tenés actualmente?', 'pt-BR': 'Quantos clientes ativos você tem atualmente?' },
    type: 'single',
    options: [
      { id: '<5', label: { es: 'Menos de 5', 'pt-BR': 'Menos de 5' }, emoji: '👤' },
      { id: '5-15', label: { es: '5-15 clientes', 'pt-BR': '5-15 clientes' }, emoji: '👥' },
      { id: '15-50', label: { es: '15-50 clientes', 'pt-BR': '15-50 clientes' }, emoji: '🏢' },
      { id: '50-200', label: { es: '50-200 clientes', 'pt-BR': '50-200 clientes' }, emoji: '🏛️' },
      { id: '200+', label: { es: 'Más de 200', 'pt-BR': 'Mais de 200' }, emoji: '🌐' },
    ],
  },
  {
    id: 'B2B03_CLIENT_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Qué tipo de clientes atendés principalmente?', 'pt-BR': 'Que tipo de clientes você atende principalmente?' },
    type: 'multi',
    options: [
      { id: 'startups', label: { es: 'Startups', 'pt-BR': 'Startups' }, emoji: '🚀' },
      { id: 'pymes', label: { es: 'PyMEs', 'pt-BR': 'PMEs' }, emoji: '🏪' },
      { id: 'mid_market', label: { es: 'Medianas empresas', 'pt-BR': 'Médias empresas' }, emoji: '🏢' },
      { id: 'enterprise', label: { es: 'Grandes corporaciones', 'pt-BR': 'Grandes corporações' }, emoji: '🏛️' },
      { id: 'government', label: { es: 'Gobierno/Sector público', 'pt-BR': 'Governo/Setor público' }, emoji: '🏦' },
    ],
  },
  {
    id: 'B2B04_INDUSTRY_FOCUS',
    category: 'identity',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Te especializás en alguna industria?', 'pt-BR': 'Você se especializa em algum setor?' },
    type: 'single',
    options: [
      { id: 'generalist', label: { es: 'Generalista (cualquier industria)', 'pt-BR': 'Generalista (qualquer setor)' }, emoji: '🌐' },
      { id: 'few_industries', label: { es: 'Algunas industrias específicas', 'pt-BR': 'Alguns setores específicos' }, emoji: '🎯' },
      { id: 'specialist', label: { es: 'Especialista en una industria', 'pt-BR': 'Especialista em um setor' }, emoji: '🔬' },
      { id: 'niche', label: { es: 'Nicho muy específico', 'pt-BR': 'Nicho muito específico' }, emoji: '💎' },
    ],
  },
  {
    id: 'B2B05_POSITIONING',
    category: 'identity',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cómo definirías tu posicionamiento?', 'pt-BR': 'Como você definiria seu posicionamento?' },
    type: 'single',
    options: [
      { id: 'budget', label: { es: 'Económico/Competitivo en precio', 'pt-BR': 'Econômico/Competitivo em preço' }, emoji: '💰' },
      { id: 'value', label: { es: 'Buena relación precio-valor', 'pt-BR': 'Boa relação preço-valor' }, emoji: '⚖️' },
      { id: 'premium', label: { es: 'Premium', 'pt-BR': 'Premium' }, emoji: '✨' },
      { id: 'boutique', label: { es: 'Boutique/Exclusivo', 'pt-BR': 'Boutique/Exclusivo' }, emoji: '💎' },
    ],
  },
  {
    id: 'B2B06_SERVICE_MODEL',
    category: 'identity',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cómo es tu modelo de servicio?', 'pt-BR': 'Como é seu modelo de serviço?' },
    type: 'multi',
    options: [
      { id: 'project', label: { es: 'Por proyecto', 'pt-BR': 'Por projeto' }, emoji: '📋' },
      { id: 'retainer', label: { es: 'Retainer/Mensualidad', 'pt-BR': 'Retainer/Mensalidade' }, emoji: '📅' },
      { id: 'hourly', label: { es: 'Por hora', 'pt-BR': 'Por hora' }, emoji: '⏰' },
      { id: 'success_fee', label: { es: 'Fee de éxito', 'pt-BR': 'Fee de sucesso' }, emoji: '🎯' },
      { id: 'subscription', label: { es: 'Suscripción', 'pt-BR': 'Assinatura' }, emoji: '♾️' },
    ],
  },
  {
    id: 'B2B07_SERVICES_COUNT',
    category: 'identity',
    mode: 'complete',
    dimension: 'growth',
    weight: 6,
    title: { es: '¿Cuántos servicios/productos diferentes ofrecés?', 'pt-BR': 'Quantos serviços/produtos diferentes você oferece?' },
    type: 'single',
    options: [
      { id: '1', label: { es: 'Un servicio core', 'pt-BR': 'Um serviço core' }, emoji: '1️⃣' },
      { id: '2-5', label: { es: '2-5 servicios', 'pt-BR': '2-5 serviços' }, emoji: '🔢' },
      { id: '6-10', label: { es: '6-10 servicios', 'pt-BR': '6-10 serviços' }, emoji: '📊' },
      { id: '10+', label: { es: 'Más de 10', 'pt-BR': 'Mais de 10' }, emoji: '🗄️' },
    ],
  },
  {
    id: 'B2B08_GEOGRAPHY',
    category: 'identity',
    mode: 'complete',
    dimension: 'growth',
    weight: 6,
    title: { es: '¿Cuál es tu alcance geográfico?', 'pt-BR': 'Qual é seu alcance geográfico?' },
    type: 'single',
    options: [
      { id: 'local', label: { es: 'Local/Ciudad', 'pt-BR': 'Local/Cidade' }, emoji: '📍' },
      { id: 'regional', label: { es: 'Regional/Provincia', 'pt-BR': 'Regional/Estado' }, emoji: '🗺️' },
      { id: 'national', label: { es: 'Nacional', 'pt-BR': 'Nacional' }, emoji: '🇦🇷' },
      { id: 'latam', label: { es: 'LATAM', 'pt-BR': 'LATAM' }, emoji: '🌎' },
      { id: 'global', label: { es: 'Global', 'pt-BR': 'Global' }, emoji: '🌍' },
    ],
  },

  // --- OPERACIÓN (12 preguntas) ---
  {
    id: 'B2B09_DELIVERY_MODEL',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo entregás tus servicios?', 'pt-BR': 'Como você entrega seus serviços?' },
    type: 'multi',
    options: [
      { id: 'onsite', label: { es: 'Presencial en cliente', 'pt-BR': 'Presencial no cliente' }, emoji: '🏢' },
      { id: 'own_office', label: { es: 'En nuestra oficina', 'pt-BR': 'No nosso escritório' }, emoji: '🏠' },
      { id: 'remote', label: { es: '100% remoto', 'pt-BR': '100% remoto' }, emoji: '💻' },
      { id: 'hybrid', label: { es: 'Híbrido', 'pt-BR': 'Híbrido' }, emoji: '🔄' },
    ],
  },
  {
    id: 'B2B10_PROJECT_DURATION',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Cuál es la duración promedio de un proyecto?', 'pt-BR': 'Qual é a duração média de um projeto?' },
    type: 'single',
    options: [
      { id: 'short', label: { es: 'Corto (< 1 mes)', 'pt-BR': 'Curto (< 1 mês)' }, emoji: '⚡' },
      { id: 'medium', label: { es: 'Medio (1-3 meses)', 'pt-BR': 'Médio (1-3 meses)' }, emoji: '📅' },
      { id: 'long', label: { es: 'Largo (3-12 meses)', 'pt-BR': 'Longo (3-12 meses)' }, emoji: '📆' },
      { id: 'ongoing', label: { es: 'Continuo/Sin fin', 'pt-BR': 'Contínuo/Sem fim' }, emoji: '♾️' },
    ],
  },
  {
    id: 'B2B11_CAPACITY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿A qué capacidad estás operando actualmente?', 'pt-BR': 'A que capacidade você está operando atualmente?' },
    type: 'single',
    options: [
      { id: 'under', label: { es: 'Baja (busco más trabajo)', 'pt-BR': 'Baixa (busco mais trabalho)' }, emoji: '📉' },
      { id: 'balanced', label: { es: 'Equilibrada', 'pt-BR': 'Equilibrada' }, emoji: '⚖️' },
      { id: 'full', label: { es: 'Capacidad máxima', 'pt-BR': 'Capacidade máxima' }, emoji: '📊' },
      { id: 'over', label: { es: 'Sobrecargado', 'pt-BR': 'Sobrecarregado' }, emoji: '🔥' },
    ],
  },
  {
    id: 'B2B12_TOOLS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Qué herramientas de gestión usás?', 'pt-BR': 'Quais ferramentas de gestão você usa?' },
    type: 'multi',
    options: [
      { id: 'pm', label: { es: 'Project Management (Asana, Monday, etc)', 'pt-BR': 'Project Management (Asana, Monday, etc)' }, emoji: '📋' },
      { id: 'crm', label: { es: 'CRM (HubSpot, Pipedrive, etc)', 'pt-BR': 'CRM (HubSpot, Pipedrive, etc)' }, emoji: '👥' },
      { id: 'time', label: { es: 'Time tracking', 'pt-BR': 'Time tracking' }, emoji: '⏰' },
      { id: 'communication', label: { es: 'Comunicación (Slack, Teams)', 'pt-BR': 'Comunicação (Slack, Teams)' }, emoji: '💬' },
      { id: 'basic', label: { es: 'Solo email y Excel', 'pt-BR': 'Apenas email e Excel' }, emoji: '📧' },
    ],
  },
  {
    id: 'B2B13_SLA',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Manejás SLAs o compromisos de respuesta?', 'pt-BR': 'Você gerencia SLAs ou compromissos de resposta?' },
    type: 'single',
    options: [
      { id: 'formal', label: { es: 'Sí, formales y medidos', 'pt-BR': 'Sim, formais e medidos' }, emoji: '📋' },
      { id: 'informal', label: { es: 'Compromisos informales', 'pt-BR': 'Compromissos informais' }, emoji: '🤝' },
      { id: 'none', label: { es: 'No manejo SLAs', 'pt-BR': 'Não gerencio SLAs' }, emoji: '❌' },
    ],
    businessTypes: [...TECH_SERVICES, ...OPERATIONAL_SERVICES],
  },
  {
    id: 'B2B14_METHODOLOGY',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Tenés metodología de trabajo estandarizada?', 'pt-BR': 'Você tem metodologia de trabalho padronizada?' },
    type: 'single',
    options: [
      { id: 'documented', label: { es: 'Sí, documentada y replicable', 'pt-BR': 'Sim, documentada e replicável' }, emoji: '📚' },
      { id: 'informal', label: { es: 'Proceso informal', 'pt-BR': 'Processo informal' }, emoji: '💭' },
      { id: 'adhoc', label: { es: 'Caso por caso', 'pt-BR': 'Caso a caso' }, emoji: '🔄' },
    ],
    businessTypes: [...CONSULTORIA, ...AGENCIAS_CREATIVAS],
  },
  {
    id: 'B2B15_SUBCONTRACTING',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Subcontratás o externalizás trabajo?', 'pt-BR': 'Você subcontrata ou terceiriza trabalho?' },
    type: 'single',
    options: [
      { id: 'never', label: { es: 'Nunca', 'pt-BR': 'Nunca' }, emoji: '❌' },
      { id: 'rarely', label: { es: 'Ocasionalmente', 'pt-BR': 'Ocasionalmente' }, emoji: '🔄' },
      { id: 'regular', label: { es: 'Regularmente', 'pt-BR': 'Regularmente' }, emoji: '📅' },
      { id: 'core', label: { es: 'Es parte de mi modelo', 'pt-BR': 'É parte do meu modelo' }, emoji: '🏢' },
    ],
  },
  {
    id: 'B2B16_QUALITY_CONTROL',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Cómo controlás la calidad del trabajo?', 'pt-BR': 'Como você controla a qualidade do trabalho?' },
    type: 'multi',
    options: [
      { id: 'review', label: { es: 'Revisión por pares', 'pt-BR': 'Revisão por pares' }, emoji: '👥' },
      { id: 'checklist', label: { es: 'Checklists de calidad', 'pt-BR': 'Checklists de qualidade' }, emoji: '✅' },
      { id: 'owner', label: { es: 'Yo reviso todo personalmente', 'pt-BR': 'Eu reviso tudo pessoalmente' }, emoji: '👤' },
      { id: 'client_feedback', label: { es: 'Feedback del cliente', 'pt-BR': 'Feedback do cliente' }, emoji: '💬' },
      { id: 'none', label: { es: 'Sin proceso formal', 'pt-BR': 'Sem processo formal' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B17_PROPOSAL_WIN_RATE',
    category: 'operation',
    mode: 'complete',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Qué % de propuestas ganás?', 'pt-BR': 'Qual % de propostas você ganha?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'B2B18_SCOPE_CREEP',
    category: 'operation',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Con qué frecuencia tenés problemas de scope creep?', 'pt-BR': 'Com que frequência você tem problemas de scope creep?' },
    type: 'single',
    options: [
      { id: 'never', label: { es: 'Casi nunca', 'pt-BR': 'Quase nunca' }, emoji: '✅' },
      { id: 'sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🔄' },
      { id: 'often', label: { es: 'Frecuentemente', 'pt-BR': 'Frequentemente' }, emoji: '⚠️' },
      { id: 'always', label: { es: 'En casi todos los proyectos', 'pt-BR': 'Em quase todos os projetos' }, emoji: '🔥' },
    ],
  },
  {
    id: 'B2B19_RECURRING_REVENUE',
    category: 'operation',
    mode: 'complete',
    dimension: 'finances',
    weight: 8,
    title: { es: '¿Qué % de tus ingresos es recurrente?', 'pt-BR': 'Qual % da sua receita é recorrente?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'B2B20_CLIENT_CONCENTRATION',
    category: 'operation',
    mode: 'complete',
    dimension: 'finances',
    weight: 8,
    title: { es: '¿Tu cliente más grande representa qué % de ingresos?', 'pt-BR': 'Seu maior cliente representa qual % da receita?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },

  // --- EQUIPO (10 preguntas) ---
  {
    id: 'B2B21_TEAM_SIZE',
    category: 'team',
    mode: 'both',
    dimension: 'team',
    weight: 8,
    title: { es: '¿Cuántas personas hay en tu equipo?', 'pt-BR': 'Quantas pessoas há na sua equipe?' },
    type: 'single',
    options: [
      { id: '1', label: { es: 'Solo yo', 'pt-BR': 'Só eu' }, emoji: '👤' },
      { id: '2-5', label: { es: '2-5 personas', 'pt-BR': '2-5 pessoas' }, emoji: '👥' },
      { id: '6-15', label: { es: '6-15 personas', 'pt-BR': '6-15 pessoas' }, emoji: '🏢' },
      { id: '16-50', label: { es: '16-50 personas', 'pt-BR': '16-50 pessoas' }, emoji: '🏛️' },
      { id: '50+', label: { es: 'Más de 50', 'pt-BR': 'Mais de 50' }, emoji: '🌐' },
    ],
  },
  {
    id: 'B2B22_TEAM_TYPE',
    category: 'team',
    mode: 'both',
    dimension: 'team',
    weight: 7,
    title: { es: '¿Cómo está compuesto tu equipo?', 'pt-BR': 'Como sua equipe é composta?' },
    type: 'multi',
    options: [
      { id: 'employees', label: { es: 'Empleados fijos', 'pt-BR': 'Funcionários fixos' }, emoji: '📋' },
      { id: 'contractors', label: { es: 'Contratistas/Freelancers', 'pt-BR': 'Contratados/Freelancers' }, emoji: '📝' },
      { id: 'partners', label: { es: 'Socios', 'pt-BR': 'Sócios' }, emoji: '🤝' },
      { id: 'agencies', label: { es: 'Otras agencias/proveedores', 'pt-BR': 'Outras agências/fornecedores' }, emoji: '🏢' },
    ],
  },
  {
    id: 'B2B23_SENIOR_RATIO',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 6,
    title: { es: '¿Qué % de tu equipo es senior/especialista?', 'pt-BR': 'Qual % da sua equipe é sênior/especialista?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'B2B24_BILLABLE_RATE',
    category: 'team',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Qué % del tiempo de tu equipo es facturable?', 'pt-BR': 'Qual % do tempo da sua equipe é faturável?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'B2B25_REMOTE_WORK',
    category: 'team',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Qué modalidad de trabajo tiene tu equipo?', 'pt-BR': 'Qual modalidade de trabalho sua equipe tem?' },
    type: 'single',
    options: [
      { id: 'office', label: { es: '100% oficina', 'pt-BR': '100% escritório' }, emoji: '🏢' },
      { id: 'hybrid', label: { es: 'Híbrido', 'pt-BR': 'Híbrido' }, emoji: '🔄' },
      { id: 'remote', label: { es: '100% remoto', 'pt-BR': '100% remoto' }, emoji: '🏠' },
      { id: 'flexible', label: { es: 'A elección del empleado', 'pt-BR': 'À escolha do funcionário' }, emoji: '🆓' },
    ],
  },
  {
    id: 'B2B26_HIRING_DIFFICULTY',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 6,
    title: { es: '¿Qué tan difícil es conseguir talento?', 'pt-BR': 'Quão difícil é conseguir talento?' },
    type: 'single',
    options: [
      { id: 'easy', label: { es: 'Fácil', 'pt-BR': 'Fácil' }, emoji: '✅' },
      { id: 'moderate', label: { es: 'Moderado', 'pt-BR': 'Moderado' }, emoji: '⚖️' },
      { id: 'hard', label: { es: 'Difícil', 'pt-BR': 'Difícil' }, emoji: '⚠️' },
      { id: 'very_hard', label: { es: 'Muy difícil', 'pt-BR': 'Muito difícil' }, emoji: '🔥' },
    ],
  },
  {
    id: 'B2B27_TURNOVER',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 7,
    title: { es: '¿Cuál es tu rotación anual de personal?', 'pt-BR': 'Qual é sua rotatividade anual de pessoal?' },
    type: 'single',
    options: [
      { id: 'low', label: { es: 'Baja (< 10%)', 'pt-BR': 'Baixa (< 10%)' }, emoji: '✅' },
      { id: 'moderate', label: { es: 'Moderada (10-25%)', 'pt-BR': 'Moderada (10-25%)' }, emoji: '📊' },
      { id: 'high', label: { es: 'Alta (25-50%)', 'pt-BR': 'Alta (25-50%)' }, emoji: '⚠️' },
      { id: 'very_high', label: { es: 'Muy alta (> 50%)', 'pt-BR': 'Muito alta (> 50%)' }, emoji: '🔥' },
    ],
  },
  {
    id: 'B2B28_TRAINING',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 5,
    title: { es: '¿Invertís en capacitación del equipo?', 'pt-BR': 'Você investe em capacitação da equipe?' },
    type: 'single',
    options: [
      { id: 'regular', label: { es: 'Sí, regularmente', 'pt-BR': 'Sim, regularmente' }, emoji: '📚' },
      { id: 'occasional', label: { es: 'Ocasionalmente', 'pt-BR': 'Ocasionalmente' }, emoji: '📅' },
      { id: 'on_demand', label: { es: 'Solo cuando es necesario', 'pt-BR': 'Apenas quando necessário' }, emoji: '🔄' },
      { id: 'never', label: { es: 'No invierto', 'pt-BR': 'Não invisto' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B29_OWNER_ROLE',
    category: 'team',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuál es tu rol principal actualmente?', 'pt-BR': 'Qual é seu papel principal atualmente?' },
    type: 'single',
    options: [
      { id: 'delivery', label: { es: 'Ejecutando proyectos', 'pt-BR': 'Executando projetos' }, emoji: '⚙️' },
      { id: 'sales', label: { es: 'Ventas y desarrollo', 'pt-BR': 'Vendas e desenvolvimento' }, emoji: '📈' },
      { id: 'management', label: { es: 'Gestión del equipo', 'pt-BR': 'Gestão da equipe' }, emoji: '👥' },
      { id: 'strategic', label: { es: 'Estrategia y visión', 'pt-BR': 'Estratégia e visão' }, emoji: '🎯' },
      { id: 'all', label: { es: 'Todo (no puedo delegar)', 'pt-BR': 'Tudo (não consigo delegar)' }, emoji: '🦸' },
    ],
  },
  {
    id: 'B2B30_TEAM_CHALLENGE',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 6,
    title: { es: '¿Cuál es tu mayor desafío con el equipo?', 'pt-BR': 'Qual é seu maior desafio com a equipe?' },
    type: 'single',
    options: [
      { id: 'finding', label: { es: 'Encontrar talento', 'pt-BR': 'Encontrar talento' }, emoji: '🔍' },
      { id: 'retaining', label: { es: 'Retener talento', 'pt-BR': 'Reter talento' }, emoji: '🔄' },
      { id: 'productivity', label: { es: 'Productividad', 'pt-BR': 'Produtividade' }, emoji: '📊' },
      { id: 'quality', label: { es: 'Calidad del trabajo', 'pt-BR': 'Qualidade do trabalho' }, emoji: '⭐' },
      { id: 'culture', label: { es: 'Cultura y motivación', 'pt-BR': 'Cultura e motivação' }, emoji: '❤️' },
      { id: 'none', label: { es: 'Sin desafíos mayores', 'pt-BR': 'Sem desafios maiores' }, emoji: '✅' },
    ],
  },

  // --- FINANZAS (10 preguntas) ---
  {
    id: 'B2B31_REVENUE_MONTHLY',
    category: 'finance',
    mode: 'both',
    dimension: 'finances',
    weight: 9,
    title: { es: '¿Cuál es tu facturación mensual promedio?', 'pt-BR': 'Qual é seu faturamento mensal médio?' },
    type: 'single',
    options: [
      { id: 'micro', label: { es: 'Menos de $2.000 USD', 'pt-BR': 'Menos de R$10.000' }, emoji: '💵' },
      { id: 'small', label: { es: '$2.000-10.000 USD', 'pt-BR': 'R$10.000-50.000' }, emoji: '💰' },
      { id: 'medium', label: { es: '$10.000-50.000 USD', 'pt-BR': 'R$50.000-250.000' }, emoji: '💎' },
      { id: 'large', label: { es: '$50.000-200.000 USD', 'pt-BR': 'R$250.000-1M' }, emoji: '🏆' },
      { id: 'enterprise', label: { es: 'Más de $200.000 USD', 'pt-BR': 'Mais de R$1M' }, emoji: '🏛️' },
    ],
  },
  {
    id: 'B2B32_AVG_PROJECT_VALUE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es el valor promedio de un proyecto?', 'pt-BR': 'Qual é o valor médio de um projeto?' },
    type: 'single',
    options: [
      { id: 'micro', label: { es: 'Menos de $1.000 USD', 'pt-BR': 'Menos de R$5.000' }, emoji: '💵' },
      { id: 'small', label: { es: '$1.000-5.000 USD', 'pt-BR': 'R$5.000-25.000' }, emoji: '💰' },
      { id: 'medium', label: { es: '$5.000-20.000 USD', 'pt-BR': 'R$25.000-100.000' }, emoji: '💎' },
      { id: 'large', label: { es: '$20.000-100.000 USD', 'pt-BR': 'R$100.000-500.000' }, emoji: '🏆' },
      { id: 'enterprise', label: { es: 'Más de $100.000 USD', 'pt-BR': 'Mais de R$500.000' }, emoji: '🏛️' },
    ],
  },
  {
    id: 'B2B33_HOURLY_RATE',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cuál es tu tarifa horaria promedio?', 'pt-BR': 'Qual é sua tarifa horária média?' },
    type: 'single',
    options: [
      { id: 'low', label: { es: 'Menos de $50 USD/h', 'pt-BR': 'Menos de R$200/h' }, emoji: '💵' },
      { id: 'medium', label: { es: '$50-100 USD/h', 'pt-BR': 'R$200-400/h' }, emoji: '💰' },
      { id: 'high', label: { es: '$100-200 USD/h', 'pt-BR': 'R$400-800/h' }, emoji: '💎' },
      { id: 'premium', label: { es: 'Más de $200 USD/h', 'pt-BR': 'Mais de R$800/h' }, emoji: '🏆' },
      { id: 'na', label: { es: 'No cobro por hora', 'pt-BR': 'Não cobro por hora' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B34_GROSS_MARGIN',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 9,
    title: { es: '¿Cuál es tu margen bruto promedio?', 'pt-BR': 'Qual é sua margem bruta média?' },
    type: 'single',
    options: [
      { id: 'low', label: { es: 'Bajo (< 30%)', 'pt-BR': 'Baixo (< 30%)' }, emoji: '📉' },
      { id: 'medium', label: { es: 'Medio (30-50%)', 'pt-BR': 'Médio (30-50%)' }, emoji: '📊' },
      { id: 'good', label: { es: 'Bueno (50-70%)', 'pt-BR': 'Bom (50-70%)' }, emoji: '📈' },
      { id: 'high', label: { es: 'Alto (> 70%)', 'pt-BR': 'Alto (> 70%)' }, emoji: '🏆' },
    ],
  },
  {
    id: 'B2B35_PAYMENT_TERMS',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 6,
    title: { es: '¿Cuáles son tus condiciones de pago típicas?', 'pt-BR': 'Quais são suas condições de pagamento típicas?' },
    type: 'single',
    options: [
      { id: 'advance', label: { es: '100% por adelantado', 'pt-BR': '100% antecipado' }, emoji: '💵' },
      { id: '50_50', label: { es: '50% adelanto / 50% entrega', 'pt-BR': '50% antecipado / 50% entrega' }, emoji: '⚖️' },
      { id: '30_days', label: { es: 'Pago a 30 días', 'pt-BR': 'Pagamento a 30 dias' }, emoji: '📅' },
      { id: '60_days', label: { es: 'Pago a 60+ días', 'pt-BR': 'Pagamento a 60+ dias' }, emoji: '📆' },
      { id: 'mixed', label: { es: 'Depende del cliente', 'pt-BR': 'Depende do cliente' }, emoji: '🔄' },
    ],
  },
  {
    id: 'B2B36_COLLECTIONS',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 7,
    title: { es: '¿Tenés problemas de cobranza?', 'pt-BR': 'Você tem problemas de cobrança?' },
    type: 'single',
    options: [
      { id: 'never', label: { es: 'Casi nunca', 'pt-BR': 'Quase nunca' }, emoji: '✅' },
      { id: 'rarely', label: { es: 'Ocasionalmente', 'pt-BR': 'Ocasionalmente' }, emoji: '📅' },
      { id: 'often', label: { es: 'Frecuentemente', 'pt-BR': 'Frequentemente' }, emoji: '⚠️' },
      { id: 'major', label: { es: 'Es un problema serio', 'pt-BR': 'É um problema sério' }, emoji: '🔥' },
    ],
  },
  {
    id: 'B2B37_CASH_RUNWAY',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 8,
    title: { es: '¿Cuántos meses de gastos tenés en reserva?', 'pt-BR': 'Quantos meses de gastos você tem em reserva?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'Ninguno', 'pt-BR': 'Nenhum' }, emoji: '⚠️' },
      { id: '1-2', label: { es: '1-2 meses', 'pt-BR': '1-2 meses' }, emoji: '📅' },
      { id: '3-6', label: { es: '3-6 meses', 'pt-BR': '3-6 meses' }, emoji: '✅' },
      { id: '6+', label: { es: 'Más de 6 meses', 'pt-BR': 'Mais de 6 meses' }, emoji: '🏆' },
    ],
  },
  {
    id: 'B2B38_PROFITABILITY',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 9,
    title: { es: '¿Cuál es tu rentabilidad neta?', 'pt-BR': 'Qual é sua rentabilidade líquida?' },
    type: 'single',
    options: [
      { id: 'negative', label: { es: 'Negativa', 'pt-BR': 'Negativa' }, emoji: '📉' },
      { id: 'breakeven', label: { es: 'Apenas cubro gastos', 'pt-BR': 'Apenas cubro gastos' }, emoji: '⚖️' },
      { id: 'low', label: { es: 'Baja (< 10%)', 'pt-BR': 'Baixa (< 10%)' }, emoji: '💵' },
      { id: 'medium', label: { es: 'Media (10-20%)', 'pt-BR': 'Média (10-20%)' }, emoji: '💰' },
      { id: 'good', label: { es: 'Buena (20-40%)', 'pt-BR': 'Boa (20-40%)' }, emoji: '📈' },
      { id: 'high', label: { es: 'Alta (> 40%)', 'pt-BR': 'Alta (> 40%)' }, emoji: '🏆' },
    ],
  },
  {
    id: 'B2B39_FINANCIAL_CONTROL',
    category: 'finance',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Cómo llevás el control financiero?', 'pt-BR': 'Como você faz o controle financeiro?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'No llevo control sistemático', 'pt-BR': 'Não tenho controle sistemático' }, emoji: '❌' },
      { id: 'basic', label: { es: 'Excel/Planilla básica', 'pt-BR': 'Excel/Planilha básica' }, emoji: '📊' },
      { id: 'software', label: { es: 'Software contable', 'pt-BR': 'Software contábil' }, emoji: '💻' },
      { id: 'accountant', label: { es: 'Contador externo', 'pt-BR': 'Contador externo' }, emoji: '👨‍💼' },
      { id: 'cfo', label: { es: 'CFO/Director financiero', 'pt-BR': 'CFO/Diretor financeiro' }, emoji: '🏛️' },
    ],
  },
  {
    id: 'B2B40_PRICING_STRATEGY',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cómo definís tus precios?', 'pt-BR': 'Como você define seus preços?' },
    type: 'single',
    options: [
      { id: 'cost_plus', label: { es: 'Costo + margen', 'pt-BR': 'Custo + margem' }, emoji: '📊' },
      { id: 'market', label: { es: 'Precio de mercado', 'pt-BR': 'Preço de mercado' }, emoji: '⚖️' },
      { id: 'value', label: { es: 'Basado en valor', 'pt-BR': 'Baseado em valor' }, emoji: '💎' },
      { id: 'negotiated', label: { es: 'Caso por caso/Negociación', 'pt-BR': 'Caso a caso/Negociação' }, emoji: '🤝' },
    ],
  },

  // --- MARKETING Y VENTAS (10 preguntas) ---
  {
    id: 'B2B41_LEAD_SOURCE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 9,
    title: { es: '¿De dónde vienen la mayoría de tus clientes?', 'pt-BR': 'De onde vem a maioria dos seus clientes?' },
    type: 'multi',
    options: [
      { id: 'referral', label: { es: 'Referidos/Boca a boca', 'pt-BR': 'Indicações/Boca a boca' }, emoji: '🗣️' },
      { id: 'network', label: { es: 'Red de contactos', 'pt-BR': 'Rede de contatos' }, emoji: '🤝' },
      { id: 'linkedin', label: { es: 'LinkedIn', 'pt-BR': 'LinkedIn' }, emoji: '💼' },
      { id: 'inbound', label: { es: 'Inbound/Content', 'pt-BR': 'Inbound/Conteúdo' }, emoji: '📝' },
      { id: 'outbound', label: { es: 'Outbound/Prospección', 'pt-BR': 'Outbound/Prospecção' }, emoji: '📞' },
      { id: 'events', label: { es: 'Eventos/Networking', 'pt-BR': 'Eventos/Networking' }, emoji: '🎪' },
    ],
  },
  {
    id: 'B2B42_SALES_PROCESS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Tenés proceso de ventas definido?', 'pt-BR': 'Você tem processo de vendas definido?' },
    type: 'single',
    options: [
      { id: 'formal', label: { es: 'Sí, formal y medido', 'pt-BR': 'Sim, formal e medido' }, emoji: '📋' },
      { id: 'informal', label: { es: 'Informal pero consistente', 'pt-BR': 'Informal mas consistente' }, emoji: '💭' },
      { id: 'adhoc', label: { es: 'Ad hoc', 'pt-BR': 'Ad hoc' }, emoji: '🔄' },
      { id: 'reactive', label: { es: 'Reactivo (espero que me contacten)', 'pt-BR': 'Reativo (espero que me contatem)' }, emoji: '⏳' },
    ],
  },
  {
    id: 'B2B43_WEBSITE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 6,
    title: { es: '¿Tenés sitio web profesional?', 'pt-BR': 'Você tem site profissional?' },
    type: 'single',
    options: [
      { id: 'pro', label: { es: 'Sí, optimizado para leads', 'pt-BR': 'Sim, otimizado para leads' }, emoji: '⚡' },
      { id: 'basic', label: { es: 'Sí, básico/institucional', 'pt-BR': 'Sim, básico/institucional' }, emoji: '🌐' },
      { id: 'outdated', label: { es: 'Sí, pero desactualizado', 'pt-BR': 'Sim, mas desatualizado' }, emoji: '📅' },
      { id: 'none', label: { es: 'No tengo', 'pt-BR': 'Não tenho' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B44_CONTENT_MARKETING',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 6,
    title: { es: '¿Creás contenido para posicionarte?', 'pt-BR': 'Você cria conteúdo para se posicionar?' },
    type: 'multi',
    options: [
      { id: 'blog', label: { es: 'Blog/Artículos', 'pt-BR': 'Blog/Artigos' }, emoji: '📝' },
      { id: 'linkedin', label: { es: 'Posts LinkedIn', 'pt-BR': 'Posts LinkedIn' }, emoji: '💼' },
      { id: 'video', label: { es: 'Videos/YouTube', 'pt-BR': 'Vídeos/YouTube' }, emoji: '🎬' },
      { id: 'podcast', label: { es: 'Podcast', 'pt-BR': 'Podcast' }, emoji: '🎙️' },
      { id: 'webinars', label: { es: 'Webinars', 'pt-BR': 'Webinars' }, emoji: '📹' },
      { id: 'none', label: { es: 'No creo contenido', 'pt-BR': 'Não crio conteúdo' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B45_CASE_STUDIES',
    category: 'marketing',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Tenés casos de éxito documentados?', 'pt-BR': 'Você tem cases de sucesso documentados?' },
    type: 'single',
    options: [
      { id: 'many', label: { es: 'Sí, varios con métricas', 'pt-BR': 'Sim, vários com métricas' }, emoji: '📊' },
      { id: 'some', label: { es: 'Algunos básicos', 'pt-BR': 'Alguns básicos' }, emoji: '📝' },
      { id: 'testimonials', label: { es: 'Solo testimonios', 'pt-BR': 'Apenas depoimentos' }, emoji: '💬' },
      { id: 'none', label: { es: 'No tengo', 'pt-BR': 'Não tenho' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B46_SALES_CYCLE',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 6,
    title: { es: '¿Cuál es tu ciclo de venta promedio?', 'pt-BR': 'Qual é seu ciclo de venda médio?' },
    type: 'single',
    options: [
      { id: 'short', label: { es: 'Corto (< 2 semanas)', 'pt-BR': 'Curto (< 2 semanas)' }, emoji: '⚡' },
      { id: 'medium', label: { es: 'Medio (2-8 semanas)', 'pt-BR': 'Médio (2-8 semanas)' }, emoji: '📅' },
      { id: 'long', label: { es: 'Largo (2-6 meses)', 'pt-BR': 'Longo (2-6 meses)' }, emoji: '📆' },
      { id: 'very_long', label: { es: 'Muy largo (6+ meses)', 'pt-BR': 'Muito longo (6+ meses)' }, emoji: '⏳' },
    ],
  },
  {
    id: 'B2B47_MARKETING_SPEND',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 5,
    title: { es: '¿Cuánto invertís en marketing mensualmente?', 'pt-BR': 'Quanto você investe em marketing mensalmente?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'Nada', 'pt-BR': 'Nada' }, emoji: '💵' },
      { id: 'low', label: { es: 'Poco (< $500 USD)', 'pt-BR': 'Pouco (< R$2.500)' }, emoji: '💰' },
      { id: 'medium', label: { es: 'Moderado ($500-2.000 USD)', 'pt-BR': 'Moderado (R$2.500-10.000)' }, emoji: '📊' },
      { id: 'high', label: { es: 'Alto (> $2.000 USD)', 'pt-BR': 'Alto (> R$10.000)' }, emoji: '🚀' },
    ],
  },
  {
    id: 'B2B48_PROPOSAL_PROCESS',
    category: 'marketing',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Cómo preparás propuestas?', 'pt-BR': 'Como você prepara propostas?' },
    type: 'single',
    options: [
      { id: 'custom', label: { es: '100% a medida cada vez', 'pt-BR': '100% sob medida cada vez' }, emoji: '✍️' },
      { id: 'template', label: { es: 'Templates que adapto', 'pt-BR': 'Templates que adapto' }, emoji: '📋' },
      { id: 'productized', label: { es: 'Servicios productizados', 'pt-BR': 'Serviços produtizados' }, emoji: '📦' },
      { id: 'mixed', label: { es: 'Depende del caso', 'pt-BR': 'Depende do caso' }, emoji: '🔄' },
    ],
  },
  {
    id: 'B2B49_COMPETITION',
    category: 'marketing',
    mode: 'complete',
    dimension: 'growth',
    weight: 6,
    title: { es: '¿Cómo percibís tu competencia?', 'pt-BR': 'Como você percebe sua concorrência?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'Casi sin competencia directa', 'pt-BR': 'Quase sem concorrência direta' }, emoji: '🏆' },
      { id: 'few', label: { es: 'Pocos competidores', 'pt-BR': 'Poucos concorrentes' }, emoji: '👀' },
      { id: 'many', label: { es: 'Muchos competidores', 'pt-BR': 'Muitos concorrentes' }, emoji: '🏃' },
      { id: 'saturated', label: { es: 'Mercado saturado', 'pt-BR': 'Mercado saturado' }, emoji: '🔥' },
    ],
  },
  {
    id: 'B2B50_PARTNER_NETWORK',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 5,
    title: { es: '¿Tenés alianzas o partners para referidos?', 'pt-BR': 'Você tem alianças ou parceiros para indicações?' },
    type: 'single',
    options: [
      { id: 'formal', label: { es: 'Sí, formales', 'pt-BR': 'Sim, formais' }, emoji: '📋' },
      { id: 'informal', label: { es: 'Informales', 'pt-BR': 'Informais' }, emoji: '🤝' },
      { id: 'building', label: { es: 'Estoy desarrollando', 'pt-BR': 'Estou desenvolvendo' }, emoji: '🔨' },
      { id: 'none', label: { es: 'No tengo', 'pt-BR': 'Não tenho' }, emoji: '❌' },
    ],
  },

  // --- REPUTACIÓN (8 preguntas) ---
  {
    id: 'B2B51_CLIENT_SATISFACTION',
    category: 'reputation',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Medís la satisfacción de clientes?', 'pt-BR': 'Você mede a satisfação dos clientes?' },
    type: 'single',
    options: [
      { id: 'systematic', label: { es: 'Sí, sistemáticamente', 'pt-BR': 'Sim, sistematicamente' }, emoji: '📊' },
      { id: 'project_end', label: { es: 'Al final de proyectos', 'pt-BR': 'No final de projetos' }, emoji: '📝' },
      { id: 'informal', label: { es: 'Informalmente', 'pt-BR': 'Informalmente' }, emoji: '💬' },
      { id: 'never', label: { es: 'No la mido', 'pt-BR': 'Não meço' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B52_NPS',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Cuál es tu NPS o score de satisfacción?', 'pt-BR': 'Qual é seu NPS ou score de satisfação?' },
    type: 'single',
    options: [
      { id: 'dont_measure', label: { es: 'No lo mido', 'pt-BR': 'Não meço' }, emoji: '❓' },
      { id: 'low', label: { es: 'Bajo (< 30)', 'pt-BR': 'Baixo (< 30)' }, emoji: '📉' },
      { id: 'medium', label: { es: 'Medio (30-50)', 'pt-BR': 'Médio (30-50)' }, emoji: '📊' },
      { id: 'good', label: { es: 'Bueno (50-70)', 'pt-BR': 'Bom (50-70)' }, emoji: '📈' },
      { id: 'excellent', label: { es: 'Excelente (+70)', 'pt-BR': 'Excelente (+70)' }, emoji: '🏆' },
    ],
  },
  {
    id: 'B2B53_RETENTION_RATE',
    category: 'reputation',
    mode: 'complete',
    dimension: 'growth',
    weight: 8,
    title: { es: '¿Qué % de clientes vuelve a contratarte?', 'pt-BR': 'Qual % de clientes volta a te contratar?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'B2B54_TESTIMONIALS',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿Tenés testimonios de clientes?', 'pt-BR': 'Você tem depoimentos de clientes?' },
    type: 'single',
    options: [
      { id: 'many', label: { es: 'Muchos y los uso activamente', 'pt-BR': 'Muitos e uso ativamente' }, emoji: '⭐' },
      { id: 'some', label: { es: 'Algunos', 'pt-BR': 'Alguns' }, emoji: '📝' },
      { id: 'few', label: { es: 'Pocos', 'pt-BR': 'Poucos' }, emoji: '🔄' },
      { id: 'none', label: { es: 'No tengo', 'pt-BR': 'Não tenho' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B55_AWARDS',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 4,
    title: { es: '¿Tenés premios o reconocimientos?', 'pt-BR': 'Você tem prêmios ou reconhecimentos?' },
    type: 'single',
    options: [
      { id: 'several', label: { es: 'Varios reconocimientos', 'pt-BR': 'Vários reconhecimentos' }, emoji: '🏆' },
      { id: 'some', label: { es: 'Algunos', 'pt-BR': 'Alguns' }, emoji: '🏅' },
      { id: 'none', label: { es: 'No tengo', 'pt-BR': 'Não tenho' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B56_LINKEDIN_PRESENCE',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿Cómo es tu presencia en LinkedIn?', 'pt-BR': 'Como é sua presença no LinkedIn?' },
    type: 'single',
    options: [
      { id: 'strong', label: { es: 'Fuerte (publico regularmente)', 'pt-BR': 'Forte (publico regularmente)' }, emoji: '🔥' },
      { id: 'moderate', label: { es: 'Moderada', 'pt-BR': 'Moderada' }, emoji: '📊' },
      { id: 'basic', label: { es: 'Básica (solo perfil)', 'pt-BR': 'Básica (apenas perfil)' }, emoji: '👤' },
      { id: 'none', label: { es: 'Sin presencia activa', 'pt-BR': 'Sem presença ativa' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B57_THOUGHT_LEADERSHIP',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 5,
    title: { es: '¿Te perciben como referente en tu área?', 'pt-BR': 'Te percebem como referência na sua área?' },
    type: 'single',
    options: [
      { id: 'yes', label: { es: 'Sí, soy reconocido', 'pt-BR': 'Sim, sou reconhecido' }, emoji: '🏆' },
      { id: 'growing', label: { es: 'Lo estoy construyendo', 'pt-BR': 'Estou construindo' }, emoji: '📈' },
      { id: 'no', label: { es: 'No todavía', 'pt-BR': 'Ainda não' }, emoji: '🔄' },
      { id: 'not_interested', label: { es: 'No me interesa', 'pt-BR': 'Não me interessa' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B58_COMPLAINT_HANDLING',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿Cómo manejás quejas o problemas?', 'pt-BR': 'Como você lida com reclamações ou problemas?' },
    type: 'single',
    options: [
      { id: 'process', label: { es: 'Proceso formal', 'pt-BR': 'Processo formal' }, emoji: '📋' },
      { id: 'personal', label: { es: 'Contacto personal inmediato', 'pt-BR': 'Contato pessoal imediato' }, emoji: '📞' },
      { id: 'reactive', label: { es: 'Las resuelvo cuando surgen', 'pt-BR': 'Resolvo quando surgem' }, emoji: '🔄' },
      { id: 'rare', label: { es: 'Casi nunca tengo quejas', 'pt-BR': 'Quase nunca tenho reclamações' }, emoji: '✅' },
    ],
  },

  // --- OBJETIVOS Y CRECIMIENTO (10 preguntas) ---
  {
    id: 'B2B59_MAIN_GOAL',
    category: 'goals',
    mode: 'both',
    dimension: 'growth',
    weight: 9,
    title: { es: '¿Cuál es tu principal objetivo ahora?', 'pt-BR': 'Qual é seu principal objetivo agora?' },
    type: 'single',
    options: [
      { id: 'more_revenue', label: { es: 'Aumentar ingresos', 'pt-BR': 'Aumentar receita' }, emoji: '📈' },
      { id: 'better_margins', label: { es: 'Mejorar rentabilidad', 'pt-BR': 'Melhorar rentabilidade' }, emoji: '💰' },
      { id: 'scale', label: { es: 'Escalar el negocio', 'pt-BR': 'Escalar o negócio' }, emoji: '🚀' },
      { id: 'new_services', label: { es: 'Nuevos servicios/mercados', 'pt-BR': 'Novos serviços/mercados' }, emoji: '🆕' },
      { id: 'team', label: { es: 'Construir equipo', 'pt-BR': 'Construir equipe' }, emoji: '👥' },
      { id: 'stability', label: { es: 'Estabilidad', 'pt-BR': 'Estabilidade' }, emoji: '⚖️' },
    ],
  },
  {
    id: 'B2B60_BIGGEST_CHALLENGE',
    category: 'goals',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu mayor desafío actual?', 'pt-BR': 'Qual é seu maior desafio atual?' },
    type: 'single',
    options: [
      { id: 'sales', label: { es: 'Conseguir más clientes', 'pt-BR': 'Conseguir mais clientes' }, emoji: '📣' },
      { id: 'delivery', label: { es: 'Capacidad de entrega', 'pt-BR': 'Capacidade de entrega' }, emoji: '⚙️' },
      { id: 'team', label: { es: 'Gestión del equipo', 'pt-BR': 'Gestão da equipe' }, emoji: '👥' },
      { id: 'finances', label: { es: 'Finanzas/Flujo de caja', 'pt-BR': 'Finanças/Fluxo de caixa' }, emoji: '💸' },
      { id: 'differentiation', label: { es: 'Diferenciación', 'pt-BR': 'Diferenciação' }, emoji: '💎' },
      { id: 'time', label: { es: 'Falta de tiempo personal', 'pt-BR': 'Falta de tempo pessoal' }, emoji: '⏰' },
    ],
  },
  {
    id: 'B2B61_GROWTH_PLAN',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿Tenés plan de crecimiento definido?', 'pt-BR': 'Você tem plano de crescimento definido?' },
    type: 'single',
    options: [
      { id: 'formal', label: { es: 'Sí, formal y documentado', 'pt-BR': 'Sim, formal e documentado' }, emoji: '📋' },
      { id: 'informal', label: { es: 'Sí, pero informal', 'pt-BR': 'Sim, mas informal' }, emoji: '💭' },
      { id: 'thinking', label: { es: 'Lo estoy pensando', 'pt-BR': 'Estou pensando' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No tengo plan claro', 'pt-BR': 'Não tenho plano claro' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B62_PRODUCTIZATION',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Te interesa productizar tus servicios?', 'pt-BR': 'Você tem interesse em produtizar seus serviços?' },
    type: 'single',
    options: [
      { id: 'done', label: { es: 'Ya tengo servicios productizados', 'pt-BR': 'Já tenho serviços produtizados' }, emoji: '📦' },
      { id: 'working', label: { es: 'Estoy trabajando en ello', 'pt-BR': 'Estou trabalhando nisso' }, emoji: '🔨' },
      { id: 'interested', label: { es: 'Me interesa', 'pt-BR': 'Me interessa' }, emoji: '🤔' },
      { id: 'no', label: { es: 'Prefiero personalizado', 'pt-BR': 'Prefiro personalizado' }, emoji: '✍️' },
    ],
  },
  {
    id: 'B2B63_AUTOMATION',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Qué tan automatizado está tu negocio?', 'pt-BR': 'Quão automatizado está seu negócio?' },
    type: 'single',
    options: [
      { id: 'high', label: { es: 'Muy automatizado', 'pt-BR': 'Muito automatizado' }, emoji: '🤖' },
      { id: 'medium', label: { es: 'Parcialmente', 'pt-BR': 'Parcialmente' }, emoji: '⚙️' },
      { id: 'low', label: { es: 'Poco automatizado', 'pt-BR': 'Pouco automatizado' }, emoji: '🔧' },
      { id: 'manual', label: { es: 'Todo manual', 'pt-BR': 'Tudo manual' }, emoji: '✍️' },
    ],
  },
  {
    id: 'B2B64_AI_ADOPTION',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Usás IA en tus procesos?', 'pt-BR': 'Você usa IA nos seus processos?' },
    type: 'single',
    options: [
      { id: 'advanced', label: { es: 'Sí, extensivamente', 'pt-BR': 'Sim, extensivamente' }, emoji: '🤖' },
      { id: 'exploring', label: { es: 'Experimentando', 'pt-BR': 'Experimentando' }, emoji: '🔬' },
      { id: 'interested', label: { es: 'Me interesa', 'pt-BR': 'Me interessa' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No la uso', 'pt-BR': 'Não uso' }, emoji: '❌' },
    ],
  },
  {
    id: 'B2B65_EXIT_STRATEGY',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 4,
    title: { es: '¿Tenés estrategia de salida en mente?', 'pt-BR': 'Você tem estratégia de saída em mente?' },
    type: 'single',
    options: [
      { id: 'sale', label: { es: 'Vender el negocio', 'pt-BR': 'Vender o negócio' }, emoji: '💰' },
      { id: 'scale', label: { es: 'Escalar y mantener', 'pt-BR': 'Escalar e manter' }, emoji: '📈' },
      { id: 'lifestyle', label: { es: 'Negocio de estilo de vida', 'pt-BR': 'Negócio de estilo de vida' }, emoji: '🏝️' },
      { id: 'succession', label: { es: 'Sucesión familiar', 'pt-BR': 'Sucessão familiar' }, emoji: '👨‍👩‍👦' },
      { id: 'none', label: { es: 'No he pensado', 'pt-BR': 'Não pensei' }, emoji: '🤔' },
    ],
  },
  {
    id: 'B2B66_TIME_DEDICATION',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Cuántas horas semanales le dedicás?', 'pt-BR': 'Quantas horas semanais você dedica?' },
    type: 'single',
    options: [
      { id: 'part_time', label: { es: 'Part-time (< 30h)', 'pt-BR': 'Part-time (< 30h)' }, emoji: '⏰' },
      { id: 'full_time', label: { es: 'Full-time (40-50h)', 'pt-BR': 'Full-time (40-50h)' }, emoji: '💼' },
      { id: 'intensive', label: { es: 'Intensivo (50-70h)', 'pt-BR': 'Intensivo (50-70h)' }, emoji: '🔥' },
      { id: 'all_in', label: { es: 'Todo mi tiempo (+70h)', 'pt-BR': 'Todo meu tempo (+70h)' }, emoji: '💯' },
    ],
  },
  {
    id: 'B2B67_SUPPORT_NEEDED',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿En qué área necesitás más apoyo?', 'pt-BR': 'Em qual área você precisa de mais apoio?' },
    type: 'multi',
    options: [
      { id: 'sales', label: { es: 'Ventas/Desarrollo de negocio', 'pt-BR': 'Vendas/Desenvolvimento de negócio' }, emoji: '📈' },
      { id: 'marketing', label: { es: 'Marketing/Posicionamiento', 'pt-BR': 'Marketing/Posicionamento' }, emoji: '📣' },
      { id: 'operations', label: { es: 'Operaciones/Procesos', 'pt-BR': 'Operações/Processos' }, emoji: '⚙️' },
      { id: 'finance', label: { es: 'Finanzas/Pricing', 'pt-BR': 'Finanças/Pricing' }, emoji: '💰' },
      { id: 'people', label: { es: 'Gestión de personas', 'pt-BR': 'Gestão de pessoas' }, emoji: '👥' },
      { id: 'strategy', label: { es: 'Estrategia', 'pt-BR': 'Estratégia' }, emoji: '🎯' },
    ],
  },
  {
    id: 'B2B68_DIFFERENTIATOR',
    category: 'goals',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Cuál es tu principal diferenciador?', 'pt-BR': 'Qual é seu principal diferenciador?' },
    type: 'multi',
    options: [
      { id: 'expertise', label: { es: 'Expertise/Especialización', 'pt-BR': 'Expertise/Especialização' }, emoji: '🎯' },
      { id: 'results', label: { es: 'Resultados comprobados', 'pt-BR': 'Resultados comprovados' }, emoji: '📊' },
      { id: 'methodology', label: { es: 'Metodología única', 'pt-BR': 'Metodologia única' }, emoji: '📚' },
      { id: 'service', label: { es: 'Calidad de servicio', 'pt-BR': 'Qualidade de serviço' }, emoji: '⭐' },
      { id: 'price', label: { es: 'Precio competitivo', 'pt-BR': 'Preço competitivo' }, emoji: '💰' },
      { id: 'speed', label: { es: 'Velocidad de entrega', 'pt-BR': 'Velocidade de entrega' }, emoji: '⚡' },
    ],
  },
];

// ============= EXPORTS =============
export function getB2BQuestions(): B2BQuestion[] {
  return B2B_COMPLETE_QUESTIONS;
}
