// ============================================
// EDUCACIÓN - Cuestionario Ultra-Específico Completo
// Sector: Educación, formación y academias
// 18 tipos de negocio, Quick (10-15) + Complete (68-75 preguntas)
// 7 Dimensiones: Crecimiento, Equipo, Tráfico, Rentabilidad, Finanzas, Eficiencia, Reputación
// ============================================

export interface EducacionQuestion {
  id: string;
  category: string;
  mode: 'quick' | 'complete' | 'both';
  dimension: 'reputation' | 'profitability' | 'finances' | 'efficiency' | 'traffic' | 'team' | 'growth';
  weight: number;
  title: { es: string; 'pt-BR': string };
  help?: { es: string; 'pt-BR': string };
  type: 'single' | 'multi' | 'number' | 'slider' | 'text' | 'money';
  options?: Array<{ id: string; label: { es: string; 'pt-BR': string }; emoji?: string }>;
  min?: number;
  max?: number;
  unit?: string;
  required?: boolean;
  businessTypes?: string[];
}

// IDs de tipos de negocio educación
export const EDUCACION_BUSINESS_TYPES = {
  JARDIN_INICIAL: 'jardin_inicial',
  ESCUELA_PRIMARIA: 'escuela_primaria_secundaria',
  TERCIARIO: 'terciario_instituto',
  UNIVERSIDAD: 'universidad_posgrado',
  IDIOMAS: 'instituto_idiomas',
  APOYO_ESCOLAR: 'apoyo_escolar',
  PREPARACION_EXAMENES: 'preparacion_examenes',
  PROGRAMACION: 'programacion_tech',
  DISENO: 'diseno_creatividad',
  MARKETING: 'marketing_negocios',
  OFICIOS: 'cursos_oficios',
  CAPACITACION_CORP: 'capacitacion_corporativa',
  ELEARNING: 'elearning_plataforma',
  CLASES_PART: 'clases_particulares',
  ARTES_ESCENICAS: 'artes_escenicas',
  MUSICA: 'academia_musica',
  DANZA: 'academia_danza',
  DEPORTIVA: 'academia_deportiva',
};

// Grupos de tipos para preguntas condicionales
const EDUCACION_FORMAL = [
  EDUCACION_BUSINESS_TYPES.JARDIN_INICIAL,
  EDUCACION_BUSINESS_TYPES.ESCUELA_PRIMARIA,
  EDUCACION_BUSINESS_TYPES.TERCIARIO,
  EDUCACION_BUSINESS_TYPES.UNIVERSIDAD,
];

const CURSOS_TECH = [
  EDUCACION_BUSINESS_TYPES.PROGRAMACION,
  EDUCACION_BUSINESS_TYPES.DISENO,
  EDUCACION_BUSINESS_TYPES.MARKETING,
  EDUCACION_BUSINESS_TYPES.ELEARNING,
];

const ARTES_RECREACION = [
  EDUCACION_BUSINESS_TYPES.ARTES_ESCENICAS,
  EDUCACION_BUSINESS_TYPES.MUSICA,
  EDUCACION_BUSINESS_TYPES.DANZA,
  EDUCACION_BUSINESS_TYPES.DEPORTIVA,
];

const TUTORIA_INDIVIDUAL = [
  EDUCACION_BUSINESS_TYPES.APOYO_ESCOLAR,
  EDUCACION_BUSINESS_TYPES.CLASES_PART,
  EDUCACION_BUSINESS_TYPES.PREPARACION_EXAMENES,
];

// ============================================
// PREGUNTAS UNIVERSALES EDUCACIÓN (todos los tipos)
// ============================================

export const EDUCACION_COMPLETE_QUESTIONS: EducacionQuestion[] = [
  // --- IDENTIDAD (8 preguntas) ---
  {
    id: 'EDU01_YEARS',
    category: 'identity',
    mode: 'both',
    dimension: 'growth',
    weight: 8,
    title: { es: '¿Hace cuánto opera tu institución/academia?', 'pt-BR': 'Há quanto tempo sua instituição/academia opera?' },
    type: 'single',
    options: [
      { id: '<1y', label: { es: 'Menos de 1 año', 'pt-BR': 'Menos de 1 ano' }, emoji: '🆕' },
      { id: '1-3y', label: { es: '1-3 años', 'pt-BR': '1-3 anos' }, emoji: '📅' },
      { id: '3-10y', label: { es: '3-10 años', 'pt-BR': '3-10 anos' }, emoji: '📈' },
      { id: '10+', label: { es: 'Más de 10 años', 'pt-BR': 'Mais de 10 anos' }, emoji: '🏆' },
    ],
  },
  {
    id: 'EDU02_STUDENTS_ACTIVE',
    category: 'identity',
    mode: 'both',
    dimension: 'growth',
    weight: 9,
    title: { es: '¿Cuántos alumnos activos tenés actualmente?', 'pt-BR': 'Quantos alunos ativos você tem atualmente?' },
    type: 'single',
    options: [
      { id: '<20', label: { es: 'Menos de 20', 'pt-BR': 'Menos de 20' }, emoji: '👤' },
      { id: '20-50', label: { es: '20-50 alumnos', 'pt-BR': '20-50 alunos' }, emoji: '👥' },
      { id: '50-150', label: { es: '50-150 alumnos', 'pt-BR': '50-150 alunos' }, emoji: '🏫' },
      { id: '150-500', label: { es: '150-500 alumnos', 'pt-BR': '150-500 alunos' }, emoji: '🎓' },
      { id: '500+', label: { es: 'Más de 500', 'pt-BR': 'Mais de 500' }, emoji: '🏛️' },
    ],
  },
  {
    id: 'EDU03_MODALITY',
    category: 'identity',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Qué modalidad de enseñanza ofrecés?', 'pt-BR': 'Que modalidade de ensino você oferece?' },
    type: 'multi',
    options: [
      { id: 'presencial', label: { es: 'Presencial', 'pt-BR': 'Presencial' }, emoji: '🏫' },
      { id: 'online_sync', label: { es: 'Online en vivo', 'pt-BR': 'Online ao vivo' }, emoji: '📹' },
      { id: 'online_async', label: { es: 'Online grabado', 'pt-BR': 'Online gravado' }, emoji: '🎬' },
      { id: 'hybrid', label: { es: 'Híbrido', 'pt-BR': 'Híbrido' }, emoji: '🔄' },
    ],
  },
  {
    id: 'EDU04_TARGET_AGE',
    category: 'identity',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿A qué rango etario te dirigís principalmente?', 'pt-BR': 'Para qual faixa etária você se dirige principalmente?' },
    type: 'multi',
    options: [
      { id: 'children', label: { es: 'Niños (0-12)', 'pt-BR': 'Crianças (0-12)' }, emoji: '🧒' },
      { id: 'teens', label: { es: 'Adolescentes (13-17)', 'pt-BR': 'Adolescentes (13-17)' }, emoji: '🎒' },
      { id: 'young_adults', label: { es: 'Jóvenes (18-25)', 'pt-BR': 'Jovens (18-25)' }, emoji: '🎓' },
      { id: 'adults', label: { es: 'Adultos (26-50)', 'pt-BR': 'Adultos (26-50)' }, emoji: '👨‍💼' },
      { id: 'seniors', label: { es: 'Mayores (+50)', 'pt-BR': 'Maiores (+50)' }, emoji: '👴' },
    ],
    businessTypes: [...EDUCACION_FORMAL, ...ARTES_RECREACION, EDUCACION_BUSINESS_TYPES.IDIOMAS],
  },
  {
    id: 'EDU05_POSITIONING',
    category: 'identity',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cómo definirías tu posicionamiento de precio?', 'pt-BR': 'Como você definiria seu posicionamento de preço?' },
    type: 'single',
    options: [
      { id: 'budget', label: { es: 'Económico/Accesible', 'pt-BR': 'Econômico/Acessível' }, emoji: '💰' },
      { id: 'value', label: { es: 'Buena relación precio-calidad', 'pt-BR': 'Boa relação custo-benefício' }, emoji: '⚖️' },
      { id: 'premium', label: { es: 'Premium', 'pt-BR': 'Premium' }, emoji: '✨' },
      { id: 'elite', label: { es: 'Elite/Exclusivo', 'pt-BR': 'Elite/Exclusivo' }, emoji: '💎' },
    ],
  },
  {
    id: 'EDU06_CERTIFICATION',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Otorgás certificación o título oficial?', 'pt-BR': 'Você oferece certificação ou diploma oficial?' },
    type: 'single',
    options: [
      { id: 'official', label: { es: 'Sí, título oficial', 'pt-BR': 'Sim, diploma oficial' }, emoji: '🏛️' },
      { id: 'private_cert', label: { es: 'Certificado propio', 'pt-BR': 'Certificado próprio' }, emoji: '📜' },
      { id: 'partner_cert', label: { es: 'Certificación de partner', 'pt-BR': 'Certificação de parceiro' }, emoji: '🤝' },
      { id: 'none', label: { es: 'Sin certificación formal', 'pt-BR': 'Sem certificação formal' }, emoji: '📝' },
    ],
  },
  {
    id: 'EDU07_MAIN_COURSES',
    category: 'identity',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿Cuántos cursos/programas diferentes ofrecés?', 'pt-BR': 'Quantos cursos/programas diferentes você oferece?' },
    type: 'single',
    options: [
      { id: '1', label: { es: 'Solo 1 programa principal', 'pt-BR': 'Apenas 1 programa principal' }, emoji: '1️⃣' },
      { id: '2-5', label: { es: '2-5 programas', 'pt-BR': '2-5 programas' }, emoji: '🔢' },
      { id: '6-15', label: { es: '6-15 programas', 'pt-BR': '6-15 programas' }, emoji: '📚' },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '🗄️' },
    ],
  },
  {
    id: 'EDU08_COURSE_DURATION',
    category: 'identity',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Cuál es la duración típica de tus cursos?', 'pt-BR': 'Qual é a duração típica dos seus cursos?' },
    type: 'single',
    options: [
      { id: 'workshop', label: { es: 'Talleres (1 día - 1 semana)', 'pt-BR': 'Workshops (1 dia - 1 semana)' }, emoji: '⚡' },
      { id: 'short', label: { es: 'Cursos cortos (1-3 meses)', 'pt-BR': 'Cursos curtos (1-3 meses)' }, emoji: '📅' },
      { id: 'medium', label: { es: 'Medios (4-12 meses)', 'pt-BR': 'Médios (4-12 meses)' }, emoji: '📆' },
      { id: 'long', label: { es: 'Carreras (+1 año)', 'pt-BR': 'Carreiras (+1 ano)' }, emoji: '🎓' },
      { id: 'continuous', label: { es: 'Continuo/Sin fin definido', 'pt-BR': 'Contínuo/Sem fim definido' }, emoji: '🔄' },
    ],
  },

  // --- OPERACIÓN (12 preguntas) ---
  {
    id: 'EDU09_CLASS_SIZE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es el tamaño promedio de tus clases/grupos?', 'pt-BR': 'Qual é o tamanho médio das suas turmas/grupos?' },
    type: 'single',
    options: [
      { id: 'individual', label: { es: 'Individual (1:1)', 'pt-BR': 'Individual (1:1)' }, emoji: '👤' },
      { id: 'small', label: { es: 'Pequeño (2-8)', 'pt-BR': 'Pequeno (2-8)' }, emoji: '👥' },
      { id: 'medium', label: { es: 'Medio (9-20)', 'pt-BR': 'Médio (9-20)' }, emoji: '🏫' },
      { id: 'large', label: { es: 'Grande (21-40)', 'pt-BR': 'Grande (21-40)' }, emoji: '🎓' },
      { id: 'massive', label: { es: 'Masivo (+40)', 'pt-BR': 'Massivo (+40)' }, emoji: '🏟️' },
    ],
  },
  {
    id: 'EDU10_SCHEDULE',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿En qué horarios dictás clases?', 'pt-BR': 'Em que horários você dá aulas?' },
    type: 'multi',
    options: [
      { id: 'morning', label: { es: 'Mañana (8-12h)', 'pt-BR': 'Manhã (8-12h)' }, emoji: '🌅' },
      { id: 'afternoon', label: { es: 'Tarde (12-18h)', 'pt-BR': 'Tarde (12-18h)' }, emoji: '☀️' },
      { id: 'evening', label: { es: 'Noche (18-22h)', 'pt-BR': 'Noite (18-22h)' }, emoji: '🌙' },
      { id: 'weekend', label: { es: 'Fines de semana', 'pt-BR': 'Fins de semana' }, emoji: '📅' },
      { id: 'flexible', label: { es: 'Bajo demanda/Flexible', 'pt-BR': 'Sob demanda/Flexível' }, emoji: '🔄' },
    ],
  },
  {
    id: 'EDU11_PLATFORM_LMS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Usás alguna plataforma LMS/educativa?', 'pt-BR': 'Você usa alguma plataforma LMS/educativa?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'No uso ninguna', 'pt-BR': 'Não uso nenhuma' }, emoji: '❌' },
      { id: 'basic', label: { es: 'Básica (Classroom, Moodle gratuito)', 'pt-BR': 'Básica (Classroom, Moodle grátis)' }, emoji: '📝' },
      { id: 'pro', label: { es: 'Profesional (Teachable, Hotmart, etc)', 'pt-BR': 'Profissional (Teachable, Hotmart, etc)' }, emoji: '⚡' },
      { id: 'custom', label: { es: 'Plataforma propia', 'pt-BR': 'Plataforma própria' }, emoji: '🛠️' },
    ],
    businessTypes: [...CURSOS_TECH, EDUCACION_BUSINESS_TYPES.ELEARNING, EDUCACION_BUSINESS_TYPES.IDIOMAS],
  },
  {
    id: 'EDU12_MATERIALS',
    category: 'operation',
    mode: 'both',
    dimension: 'profitability',
    weight: 6,
    title: { es: '¿Cómo manejas los materiales didácticos?', 'pt-BR': 'Como você gerencia os materiais didáticos?' },
    type: 'single',
    options: [
      { id: 'included', label: { es: 'Incluidos en el precio', 'pt-BR': 'Incluídos no preço' }, emoji: '📦' },
      { id: 'separate', label: { es: 'Se cobran aparte', 'pt-BR': 'Cobrados separadamente' }, emoji: '💰' },
      { id: 'digital_only', label: { es: 'Solo material digital', 'pt-BR': 'Apenas material digital' }, emoji: '💻' },
      { id: 'third_party', label: { es: 'Libros de terceros', 'pt-BR': 'Livros de terceiros' }, emoji: '📚' },
    ],
  },
  {
    id: 'EDU13_FACILITY_TYPE',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Dónde dictás tus clases presenciales?', 'pt-BR': 'Onde você dá suas aulas presenciais?' },
    type: 'multi',
    options: [
      { id: 'own_space', label: { es: 'Espacio propio', 'pt-BR': 'Espaço próprio' }, emoji: '🏢' },
      { id: 'rented', label: { es: 'Espacio alquilado', 'pt-BR': 'Espaço alugado' }, emoji: '🔑' },
      { id: 'cowork', label: { es: 'Coworking/Compartido', 'pt-BR': 'Coworking/Compartilhado' }, emoji: '🏪' },
      { id: 'client_site', label: { es: 'En casa del cliente', 'pt-BR': 'Na casa do cliente' }, emoji: '🏠' },
      { id: 'company_site', label: { es: 'In-company', 'pt-BR': 'In-company' }, emoji: '🏭' },
      { id: 'online_only', label: { es: 'Solo online', 'pt-BR': 'Apenas online' }, emoji: '💻' },
    ],
  },
  {
    id: 'EDU14_CLASSROOMS',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Cuántas aulas/salas tenés disponibles?', 'pt-BR': 'Quantas salas você tem disponíveis?' },
    type: 'single',
    options: [
      { id: '1', label: { es: '1 aula', 'pt-BR': '1 sala' }, emoji: '1️⃣' },
      { id: '2-3', label: { es: '2-3 aulas', 'pt-BR': '2-3 salas' }, emoji: '🔢' },
      { id: '4-8', label: { es: '4-8 aulas', 'pt-BR': '4-8 salas' }, emoji: '🏫' },
      { id: '8+', label: { es: 'Más de 8', 'pt-BR': 'Mais de 8' }, emoji: '🏛️' },
      { id: 'na', label: { es: 'No aplica (online)', 'pt-BR': 'Não aplica (online)' }, emoji: '💻' },
    ],
    businessTypes: [...EDUCACION_FORMAL, ...ARTES_RECREACION],
  },
  {
    id: 'EDU15_EQUIPMENT',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Qué equipamiento especial tenés?', 'pt-BR': 'Que equipamento especial você tem?' },
    type: 'multi',
    options: [
      { id: 'projector', label: { es: 'Proyector/Pantallas', 'pt-BR': 'Projetor/Telas' }, emoji: '📽️' },
      { id: 'computers', label: { es: 'Computadoras para alumnos', 'pt-BR': 'Computadores para alunos' }, emoji: '💻' },
      { id: 'instruments', label: { es: 'Instrumentos musicales', 'pt-BR': 'Instrumentos musicais' }, emoji: '🎸' },
      { id: 'sports', label: { es: 'Equipamiento deportivo', 'pt-BR': 'Equipamento esportivo' }, emoji: '⚽' },
      { id: 'lab', label: { es: 'Laboratorio', 'pt-BR': 'Laboratório' }, emoji: '🔬' },
      { id: 'basic', label: { es: 'Solo mobiliario básico', 'pt-BR': 'Apenas mobiliário básico' }, emoji: '🪑' },
    ],
  },
  {
    id: 'EDU16_ATTENDANCE',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Cómo controlás la asistencia?', 'pt-BR': 'Como você controla a presença?' },
    type: 'single',
    options: [
      { id: 'manual', label: { es: 'Manual/Planilla', 'pt-BR': 'Manual/Planilha' }, emoji: '📋' },
      { id: 'digital', label: { es: 'App/Sistema digital', 'pt-BR': 'App/Sistema digital' }, emoji: '📱' },
      { id: 'auto', label: { es: 'Automático (LMS/Zoom)', 'pt-BR': 'Automático (LMS/Zoom)' }, emoji: '🤖' },
      { id: 'none', label: { es: 'No controlo', 'pt-BR': 'Não controlo' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU17_EVALUATIONS',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Cómo evaluás a tus alumnos?', 'pt-BR': 'Como você avalia seus alunos?' },
    type: 'multi',
    options: [
      { id: 'exams', label: { es: 'Exámenes escritos', 'pt-BR': 'Provas escritas' }, emoji: '📝' },
      { id: 'projects', label: { es: 'Proyectos prácticos', 'pt-BR': 'Projetos práticos' }, emoji: '🎯' },
      { id: 'continuous', label: { es: 'Evaluación continua', 'pt-BR': 'Avaliação contínua' }, emoji: '📊' },
      { id: 'oral', label: { es: 'Exámenes orales', 'pt-BR': 'Provas orais' }, emoji: '🗣️' },
      { id: 'portfolio', label: { es: 'Portafolio', 'pt-BR': 'Portfólio' }, emoji: '📁' },
      { id: 'none', label: { es: 'Sin evaluación formal', 'pt-BR': 'Sem avaliação formal' }, emoji: '🆓' },
    ],
  },
  {
    id: 'EDU18_COMPLETION_RATE',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué % de alumnos completa el programa?', 'pt-BR': 'Qual % de alunos completa o programa?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'EDU19_REENROLLMENT',
    category: 'operation',
    mode: 'complete',
    dimension: 'growth',
    weight: 8,
    title: { es: '¿Qué % de alumnos se reinscribe o toma otro curso?', 'pt-BR': 'Qual % de alunos se rematriculam ou fazem outro curso?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'EDU20_DROPOUT',
    category: 'operation',
    mode: 'complete',
    dimension: 'finances',
    weight: 7,
    title: { es: '¿Cuál es tu tasa de deserción mensual?', 'pt-BR': 'Qual é sua taxa de evasão mensal?' },
    type: 'slider',
    min: 0,
    max: 30,
    unit: '%',
  },

  // --- EQUIPO (8 preguntas) ---
  {
    id: 'EDU21_TEACHERS_COUNT',
    category: 'team',
    mode: 'both',
    dimension: 'team',
    weight: 8,
    title: { es: '¿Cuántos docentes/instructores tenés?', 'pt-BR': 'Quantos professores/instrutores você tem?' },
    type: 'single',
    options: [
      { id: '1', label: { es: 'Solo yo', 'pt-BR': 'Só eu' }, emoji: '👤' },
      { id: '2-5', label: { es: '2-5 docentes', 'pt-BR': '2-5 professores' }, emoji: '👥' },
      { id: '6-15', label: { es: '6-15 docentes', 'pt-BR': '6-15 professores' }, emoji: '👨‍🏫' },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '🏫' },
    ],
  },
  {
    id: 'EDU22_TEACHER_CONTRACT',
    category: 'team',
    mode: 'both',
    dimension: 'team',
    weight: 7,
    title: { es: '¿Cómo es la relación laboral con tus docentes?', 'pt-BR': 'Como é a relação de trabalho com seus professores?' },
    type: 'multi',
    options: [
      { id: 'employee', label: { es: 'Empleados fijos', 'pt-BR': 'Funcionários fixos' }, emoji: '📋' },
      { id: 'contractor', label: { es: 'Contratados/Freelance', 'pt-BR': 'Contratados/Freelance' }, emoji: '📝' },
      { id: 'hourly', label: { es: 'Por hora dictada', 'pt-BR': 'Por hora dada' }, emoji: '⏰' },
      { id: 'revenue_share', label: { es: 'Participación de ingresos', 'pt-BR': 'Participação nos lucros' }, emoji: '💰' },
    ],
  },
  {
    id: 'EDU23_TEACHER_QUALIFICATION',
    category: 'team',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué nivel de formación tienen tus docentes?', 'pt-BR': 'Qual nível de formação têm seus professores?' },
    type: 'single',
    options: [
      { id: 'practitioners', label: { es: 'Profesionales con experiencia', 'pt-BR': 'Profissionais com experiência' }, emoji: '💼' },
      { id: 'degree', label: { es: 'Título universitario', 'pt-BR': 'Diploma universitário' }, emoji: '🎓' },
      { id: 'postgrad', label: { es: 'Posgrado/Especialización', 'pt-BR': 'Pós-graduação/Especialização' }, emoji: '📚' },
      { id: 'phd', label: { es: 'Doctorado/PhD', 'pt-BR': 'Doutorado/PhD' }, emoji: '🏅' },
      { id: 'mixed', label: { es: 'Variado', 'pt-BR': 'Variado' }, emoji: '🔄' },
    ],
    businessTypes: [...EDUCACION_FORMAL, EDUCACION_BUSINESS_TYPES.UNIVERSIDAD],
  },
  {
    id: 'EDU24_ADMIN_STAFF',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 5,
    title: { es: '¿Cuántas personas en administración/secretaría?', 'pt-BR': 'Quantas pessoas na administração/secretaria?' },
    type: 'single',
    options: [
      { id: '0', label: { es: 'Ninguna (yo hago todo)', 'pt-BR': 'Nenhuma (eu faço tudo)' }, emoji: '🦸' },
      { id: '1', label: { es: '1 persona', 'pt-BR': '1 pessoa' }, emoji: '👤' },
      { id: '2-5', label: { es: '2-5 personas', 'pt-BR': '2-5 pessoas' }, emoji: '👥' },
      { id: '5+', label: { es: 'Más de 5', 'pt-BR': 'Mais de 5' }, emoji: '🏢' },
    ],
  },
  {
    id: 'EDU25_TEACHER_TRAINING',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 6,
    title: { es: '¿Ofrecés capacitación a tus docentes?', 'pt-BR': 'Você oferece treinamento aos seus professores?' },
    type: 'single',
    options: [
      { id: 'regular', label: { es: 'Sí, regularmente', 'pt-BR': 'Sim, regularmente' }, emoji: '✅' },
      { id: 'occasional', label: { es: 'Ocasionalmente', 'pt-BR': 'Ocasionalmente' }, emoji: '📅' },
      { id: 'onboarding', label: { es: 'Solo al ingresar', 'pt-BR': 'Apenas ao entrar' }, emoji: '👋' },
      { id: 'none', label: { es: 'No ofrezco', 'pt-BR': 'Não ofereço' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU26_TEACHER_RETENTION',
    category: 'team',
    mode: 'complete',
    dimension: 'team',
    weight: 7,
    title: { es: '¿Cuánto tiempo permanecen los docentes en promedio?', 'pt-BR': 'Quanto tempo os professores permanecem em média?' },
    type: 'single',
    options: [
      { id: '<1y', label: { es: 'Menos de 1 año', 'pt-BR': 'Menos de 1 ano' }, emoji: '📅' },
      { id: '1-2y', label: { es: '1-2 años', 'pt-BR': '1-2 anos' }, emoji: '📆' },
      { id: '3-5y', label: { es: '3-5 años', 'pt-BR': '3-5 anos' }, emoji: '📈' },
      { id: '5+', label: { es: 'Más de 5 años', 'pt-BR': 'Mais de 5 anos' }, emoji: '🏆' },
    ],
  },
  {
    id: 'EDU27_PAYROLL_CHALLENGE',
    category: 'team',
    mode: 'complete',
    dimension: 'finances',
    weight: 6,
    title: { es: '¿Cuál es tu mayor desafío con el equipo?', 'pt-BR': 'Qual é seu maior desafio com a equipe?' },
    type: 'single',
    options: [
      { id: 'find_talent', label: { es: 'Encontrar buenos docentes', 'pt-BR': 'Encontrar bons professores' }, emoji: '🔍' },
      { id: 'cost', label: { es: 'Costo de nómina', 'pt-BR': 'Custo da folha' }, emoji: '💸' },
      { id: 'quality', label: { es: 'Mantener calidad uniforme', 'pt-BR': 'Manter qualidade uniforme' }, emoji: '⭐' },
      { id: 'turnover', label: { es: 'Alta rotación', 'pt-BR': 'Alta rotatividade' }, emoji: '🔄' },
      { id: 'none', label: { es: 'Sin problemas mayores', 'pt-BR': 'Sem problemas maiores' }, emoji: '✅' },
    ],
  },
  {
    id: 'EDU28_OWNER_TEACHES',
    category: 'team',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Vos también das clases?', 'pt-BR': 'Você também dá aulas?' },
    type: 'single',
    options: [
      { id: 'all', label: { es: 'Soy el único docente', 'pt-BR': 'Sou o único professor' }, emoji: '👤' },
      { id: 'most', label: { es: 'La mayoría de las clases', 'pt-BR': 'A maioria das aulas' }, emoji: '👨‍🏫' },
      { id: 'some', label: { es: 'Algunas clases', 'pt-BR': 'Algumas aulas' }, emoji: '📊' },
      { id: 'none', label: { es: 'No, solo gestiono', 'pt-BR': 'Não, apenas gerencio' }, emoji: '💼' },
    ],
  },

  // --- FINANZAS (12 preguntas) ---
  {
    id: 'EDU29_REVENUE_MONTHLY',
    category: 'finance',
    mode: 'both',
    dimension: 'finances',
    weight: 9,
    title: { es: '¿Cuál es tu facturación mensual promedio?', 'pt-BR': 'Qual é seu faturamento mensal médio?' },
    type: 'single',
    options: [
      { id: 'micro', label: { es: 'Menos de $500 USD', 'pt-BR': 'Menos de R$2.500' }, emoji: '💵' },
      { id: 'small', label: { es: '$500-2.000 USD', 'pt-BR': 'R$2.500-10.000' }, emoji: '💰' },
      { id: 'medium', label: { es: '$2.000-10.000 USD', 'pt-BR': 'R$10.000-50.000' }, emoji: '💎' },
      { id: 'large', label: { es: '$10.000-50.000 USD', 'pt-BR': 'R$50.000-250.000' }, emoji: '🏆' },
      { id: 'enterprise', label: { es: 'Más de $50.000 USD', 'pt-BR': 'Mais de R$250.000' }, emoji: '🏛️' },
    ],
  },
  {
    id: 'EDU30_PRICING_MODEL',
    category: 'finance',
    mode: 'both',
    dimension: 'finances',
    weight: 8,
    title: { es: '¿Cómo estructuras tus precios?', 'pt-BR': 'Como você estrutura seus preços?' },
    type: 'multi',
    options: [
      { id: 'monthly', label: { es: 'Cuota mensual', 'pt-BR': 'Mensalidade' }, emoji: '📅' },
      { id: 'per_course', label: { es: 'Por curso completo', 'pt-BR': 'Por curso completo' }, emoji: '📦' },
      { id: 'per_class', label: { es: 'Por clase individual', 'pt-BR': 'Por aula individual' }, emoji: '1️⃣' },
      { id: 'package', label: { es: 'Packs de clases', 'pt-BR': 'Pacotes de aulas' }, emoji: '🎁' },
      { id: 'subscription', label: { es: 'Suscripción/Membresía', 'pt-BR': 'Assinatura/Membros' }, emoji: '♾️' },
    ],
  },
  {
    id: 'EDU31_AVG_TICKET',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es el precio promedio de tu servicio principal?', 'pt-BR': 'Qual é o preço médio do seu serviço principal?' },
    type: 'single',
    options: [
      { id: 'low', label: { es: 'Bajo (menos que la competencia)', 'pt-BR': 'Baixo (menos que a concorrência)' }, emoji: '💵' },
      { id: 'market', label: { es: 'Precio de mercado', 'pt-BR': 'Preço de mercado' }, emoji: '⚖️' },
      { id: 'above', label: { es: 'Sobre el promedio', 'pt-BR': 'Acima da média' }, emoji: '📈' },
      { id: 'premium', label: { es: 'Premium/Alto', 'pt-BR': 'Premium/Alto' }, emoji: '💎' },
    ],
  },
  {
    id: 'EDU32_PAYMENT_METHODS',
    category: 'finance',
    mode: 'both',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Qué medios de pago aceptás?', 'pt-BR': 'Quais meios de pagamento você aceita?' },
    type: 'multi',
    options: [
      { id: 'cash', label: { es: 'Efectivo', 'pt-BR': 'Dinheiro' }, emoji: '💵' },
      { id: 'transfer', label: { es: 'Transferencia', 'pt-BR': 'Transferência' }, emoji: '🏦' },
      { id: 'card', label: { es: 'Tarjeta de crédito/débito', 'pt-BR': 'Cartão de crédito/débito' }, emoji: '💳' },
      { id: 'mp', label: { es: 'MercadoPago/Billetera digital', 'pt-BR': 'MercadoPago/Carteira digital' }, emoji: '📱' },
      { id: 'financing', label: { es: 'Financiación propia', 'pt-BR': 'Financiamento próprio' }, emoji: '📊' },
    ],
  },
  {
    id: 'EDU33_DELINQUENCY',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 8,
    title: { es: '¿Qué % de alumnos tiene pagos atrasados?', 'pt-BR': 'Qual % de alunos tem pagamentos atrasados?' },
    type: 'slider',
    min: 0,
    max: 50,
    unit: '%',
  },
  {
    id: 'EDU34_TEACHER_COST_PCT',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué % de tus ingresos va a pago de docentes?', 'pt-BR': 'Qual % da sua receita vai para pagamento de professores?' },
    type: 'slider',
    min: 0,
    max: 80,
    unit: '%',
  },
  {
    id: 'EDU35_FIXED_COSTS',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 7,
    title: { es: '¿Cuál es tu principal costo fijo después de docentes?', 'pt-BR': 'Qual é seu principal custo fixo depois de professores?' },
    type: 'single',
    options: [
      { id: 'rent', label: { es: 'Alquiler/Local', 'pt-BR': 'Aluguel/Local' }, emoji: '🏢' },
      { id: 'marketing', label: { es: 'Marketing/Publicidad', 'pt-BR': 'Marketing/Publicidade' }, emoji: '📣' },
      { id: 'tech', label: { es: 'Tecnología/Plataformas', 'pt-BR': 'Tecnologia/Plataformas' }, emoji: '💻' },
      { id: 'admin', label: { es: 'Administración', 'pt-BR': 'Administração' }, emoji: '📋' },
      { id: 'materials', label: { es: 'Materiales', 'pt-BR': 'Materiais' }, emoji: '📚' },
    ],
  },
  {
    id: 'EDU36_PROFIT_MARGIN',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 9,
    title: { es: '¿Cuál es tu margen de ganancia estimado?', 'pt-BR': 'Qual é sua margem de lucro estimada?' },
    type: 'single',
    options: [
      { id: 'negative', label: { es: 'Negativo (pierdo dinero)', 'pt-BR': 'Negativo (perco dinheiro)' }, emoji: '📉' },
      { id: 'low', label: { es: 'Bajo (0-15%)', 'pt-BR': 'Baixo (0-15%)' }, emoji: '💵' },
      { id: 'medium', label: { es: 'Medio (15-30%)', 'pt-BR': 'Médio (15-30%)' }, emoji: '💰' },
      { id: 'good', label: { es: 'Bueno (30-50%)', 'pt-BR': 'Bom (30-50%)' }, emoji: '📈' },
      { id: 'high', label: { es: 'Alto (+50%)', 'pt-BR': 'Alto (+50%)' }, emoji: '🏆' },
    ],
  },
  {
    id: 'EDU37_BILLING_SYSTEM',
    category: 'finance',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Cómo manejás la facturación?', 'pt-BR': 'Como você gerencia o faturamento?' },
    type: 'single',
    options: [
      { id: 'manual', label: { es: 'Manual/Excel', 'pt-BR': 'Manual/Excel' }, emoji: '📝' },
      { id: 'basic_sw', label: { es: 'Software básico', 'pt-BR': 'Software básico' }, emoji: '💻' },
      { id: 'integrated', label: { es: 'Sistema integrado', 'pt-BR': 'Sistema integrado' }, emoji: '⚡' },
      { id: 'accountant', label: { es: 'Lo hace mi contador', 'pt-BR': 'O contador faz' }, emoji: '👨‍💼' },
    ],
  },
  {
    id: 'EDU38_SEASONALITY',
    category: 'finance',
    mode: 'complete',
    dimension: 'finances',
    weight: 7,
    title: { es: '¿Tu negocio tiene estacionalidad marcada?', 'pt-BR': 'Seu negócio tem sazonalidade marcada?' },
    type: 'single',
    options: [
      { id: 'very', label: { es: 'Muy estacional (verano baja mucho)', 'pt-BR': 'Muito sazonal (verão cai muito)' }, emoji: '📊' },
      { id: 'some', label: { es: 'Algo estacional', 'pt-BR': 'Algo sazonal' }, emoji: '📈' },
      { id: 'stable', label: { es: 'Bastante estable', 'pt-BR': 'Bastante estável' }, emoji: '➖' },
      { id: 'inverse', label: { es: 'Inversa (verano sube)', 'pt-BR': 'Inversa (verão sobe)' }, emoji: '🔄' },
    ],
  },
  {
    id: 'EDU39_SCHOLARSHIPS',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 5,
    title: { es: '¿Ofrecés becas o descuentos especiales?', 'pt-BR': 'Você oferece bolsas ou descontos especiais?' },
    type: 'multi',
    options: [
      { id: 'scholarships', label: { es: 'Becas por mérito', 'pt-BR': 'Bolsas por mérito' }, emoji: '🏆' },
      { id: 'need_based', label: { es: 'Ayuda económica', 'pt-BR': 'Ajuda financeira' }, emoji: '🤝' },
      { id: 'early_bird', label: { es: 'Descuento pronto pago', 'pt-BR': 'Desconto pagamento antecipado' }, emoji: '⚡' },
      { id: 'referral', label: { es: 'Descuento por referido', 'pt-BR': 'Desconto por indicação' }, emoji: '👥' },
      { id: 'none', label: { es: 'No ofrezco', 'pt-BR': 'Não ofereço' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU40_B2B_REVENUE',
    category: 'finance',
    mode: 'complete',
    dimension: 'growth',
    weight: 6,
    title: { es: '¿Qué % de tus ingresos viene de empresas (B2B)?', 'pt-BR': 'Qual % da sua receita vem de empresas (B2B)?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
    businessTypes: [EDUCACION_BUSINESS_TYPES.CAPACITACION_CORP, ...CURSOS_TECH, EDUCACION_BUSINESS_TYPES.IDIOMAS],
  },

  // --- MARKETING Y TRÁFICO (12 preguntas) ---
  {
    id: 'EDU41_LEAD_SOURCE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿De dónde vienen la mayoría de tus alumnos nuevos?', 'pt-BR': 'De onde vem a maioria dos seus novos alunos?' },
    type: 'multi',
    options: [
      { id: 'referral', label: { es: 'Recomendación/Boca a boca', 'pt-BR': 'Recomendação/Boca a boca' }, emoji: '🗣️' },
      { id: 'social', label: { es: 'Redes sociales', 'pt-BR': 'Redes sociais' }, emoji: '📱' },
      { id: 'google', label: { es: 'Google/Búsqueda', 'pt-BR': 'Google/Busca' }, emoji: '🔍' },
      { id: 'ads', label: { es: 'Publicidad paga', 'pt-BR': 'Publicidade paga' }, emoji: '📣' },
      { id: 'website', label: { es: 'Web propia', 'pt-BR': 'Site próprio' }, emoji: '🌐' },
      { id: 'marketplace', label: { es: 'Plataformas (Udemy, Domestika)', 'pt-BR': 'Plataformas (Udemy, Domestika)' }, emoji: '🏪' },
    ],
  },
  {
    id: 'EDU42_SOCIAL_PRESENCE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿En qué redes sociales estás activo?', 'pt-BR': 'Em quais redes sociais você está ativo?' },
    type: 'multi',
    options: [
      { id: 'instagram', label: { es: 'Instagram', 'pt-BR': 'Instagram' }, emoji: '📸' },
      { id: 'facebook', label: { es: 'Facebook', 'pt-BR': 'Facebook' }, emoji: '📘' },
      { id: 'linkedin', label: { es: 'LinkedIn', 'pt-BR': 'LinkedIn' }, emoji: '💼' },
      { id: 'youtube', label: { es: 'YouTube', 'pt-BR': 'YouTube' }, emoji: '▶️' },
      { id: 'tiktok', label: { es: 'TikTok', 'pt-BR': 'TikTok' }, emoji: '🎵' },
      { id: 'none', label: { es: 'Ninguna', 'pt-BR': 'Nenhuma' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU43_WEBSITE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Tenés sitio web?', 'pt-BR': 'Você tem site?' },
    type: 'single',
    options: [
      { id: 'pro', label: { es: 'Sí, profesional con inscripción online', 'pt-BR': 'Sim, profissional com inscrição online' }, emoji: '⚡' },
      { id: 'basic', label: { es: 'Sí, básico/informativo', 'pt-BR': 'Sim, básico/informativo' }, emoji: '🌐' },
      { id: 'landing', label: { es: 'Solo landing page', 'pt-BR': 'Apenas landing page' }, emoji: '📄' },
      { id: 'none', label: { es: 'No tengo', 'pt-BR': 'Não tenho' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU44_GOOGLE_RATING',
    category: 'marketing',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Cuál es tu calificación en Google?', 'pt-BR': 'Qual é sua nota no Google?' },
    type: 'single',
    options: [
      { id: 'no_profile', label: { es: 'No tengo perfil', 'pt-BR': 'Não tenho perfil' }, emoji: '❌' },
      { id: '<4', label: { es: 'Menos de 4 estrellas', 'pt-BR': 'Menos de 4 estrelas' }, emoji: '⭐' },
      { id: '4-4.5', label: { es: '4 - 4.5 estrellas', 'pt-BR': '4 - 4.5 estrelas' }, emoji: '⭐⭐' },
      { id: '4.5-5', label: { es: '4.5 - 5 estrellas', 'pt-BR': '4.5 - 5 estrelas' }, emoji: '⭐⭐⭐' },
    ],
  },
  {
    id: 'EDU45_REVIEWS_COUNT',
    category: 'marketing',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿Cuántas reseñas tenés en Google?', 'pt-BR': 'Quantas avaliações você tem no Google?' },
    type: 'single',
    options: [
      { id: '<10', label: { es: 'Menos de 10', 'pt-BR': 'Menos de 10' }, emoji: '📝' },
      { id: '10-50', label: { es: '10-50 reseñas', 'pt-BR': '10-50 avaliações' }, emoji: '📊' },
      { id: '50-200', label: { es: '50-200 reseñas', 'pt-BR': '50-200 avaliações' }, emoji: '📈' },
      { id: '200+', label: { es: 'Más de 200', 'pt-BR': 'Mais de 200' }, emoji: '🏆' },
    ],
  },
  {
    id: 'EDU46_MARKETING_SPEND',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuánto invertís en marketing mensualmente?', 'pt-BR': 'Quanto você investe em marketing mensalmente?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'Nada', 'pt-BR': 'Nada' }, emoji: '💵' },
      { id: 'low', label: { es: 'Poco (< $200 USD)', 'pt-BR': 'Pouco (< R$1.000)' }, emoji: '💰' },
      { id: 'medium', label: { es: 'Moderado ($200-1.000 USD)', 'pt-BR': 'Moderado (R$1.000-5.000)' }, emoji: '📊' },
      { id: 'high', label: { es: 'Alto (> $1.000 USD)', 'pt-BR': 'Alto (> R$5.000)' }, emoji: '🚀' },
    ],
  },
  {
    id: 'EDU47_CONTENT_STRATEGY',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 6,
    title: { es: '¿Creás contenido educativo gratuito?', 'pt-BR': 'Você cria conteúdo educativo gratuito?' },
    type: 'multi',
    options: [
      { id: 'blog', label: { es: 'Blog/Artículos', 'pt-BR': 'Blog/Artigos' }, emoji: '📝' },
      { id: 'videos', label: { es: 'Videos YouTube/Reels', 'pt-BR': 'Vídeos YouTube/Reels' }, emoji: '🎬' },
      { id: 'podcast', label: { es: 'Podcast', 'pt-BR': 'Podcast' }, emoji: '🎙️' },
      { id: 'webinar', label: { es: 'Webinars/Lives', 'pt-BR': 'Webinars/Lives' }, emoji: '📹' },
      { id: 'ebook', label: { es: 'Ebooks/Guías', 'pt-BR': 'Ebooks/Guias' }, emoji: '📚' },
      { id: 'none', label: { es: 'No creo contenido', 'pt-BR': 'Não crio conteúdo' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU48_ENROLLMENT_PROCESS',
    category: 'marketing',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo es tu proceso de inscripción?', 'pt-BR': 'Como é seu processo de inscrição?' },
    type: 'single',
    options: [
      { id: 'online_auto', label: { es: 'Online automático', 'pt-BR': 'Online automático' }, emoji: '⚡' },
      { id: 'online_manual', label: { es: 'Online con confirmación manual', 'pt-BR': 'Online com confirmação manual' }, emoji: '📧' },
      { id: 'presencial', label: { es: 'Presencial', 'pt-BR': 'Presencial' }, emoji: '🏢' },
      { id: 'whatsapp', label: { es: 'Por WhatsApp', 'pt-BR': 'Por WhatsApp' }, emoji: '📱' },
      { id: 'mixed', label: { es: 'Mixto', 'pt-BR': 'Misto' }, emoji: '🔄' },
    ],
  },
  {
    id: 'EDU49_OPEN_HOUSE',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 5,
    title: { es: '¿Hacés clases de prueba o jornadas abiertas?', 'pt-BR': 'Você faz aulas experimentais ou dias abertos?' },
    type: 'single',
    options: [
      { id: 'regular', label: { es: 'Sí, regularmente', 'pt-BR': 'Sim, regularmente' }, emoji: '📅' },
      { id: 'on_demand', label: { es: 'A pedido', 'pt-BR': 'Sob demanda' }, emoji: '📞' },
      { id: 'rarely', label: { es: 'Ocasionalmente', 'pt-BR': 'Ocasionalmente' }, emoji: '🔄' },
      { id: 'never', label: { es: 'Nunca', 'pt-BR': 'Nunca' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU50_CRM_LEADS',
    category: 'marketing',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Cómo gestionás los interesados/leads?', 'pt-BR': 'Como você gerencia os interessados/leads?' },
    type: 'single',
    options: [
      { id: 'none', label: { es: 'No hago seguimiento sistemático', 'pt-BR': 'Não faço acompanhamento sistemático' }, emoji: '❌' },
      { id: 'excel', label: { es: 'Excel/Planilla', 'pt-BR': 'Excel/Planilha' }, emoji: '📊' },
      { id: 'whatsapp', label: { es: 'WhatsApp/Chat', 'pt-BR': 'WhatsApp/Chat' }, emoji: '📱' },
      { id: 'crm', label: { es: 'CRM dedicado', 'pt-BR': 'CRM dedicado' }, emoji: '⚡' },
    ],
  },
  {
    id: 'EDU51_CONVERSION_RATE',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Qué % de interesados se inscribe?', 'pt-BR': 'Qual % de interessados se inscrevem?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'EDU52_TESTIMONIALS',
    category: 'marketing',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿Usás testimonios de alumnos en tu marketing?', 'pt-BR': 'Você usa depoimentos de alunos no seu marketing?' },
    type: 'single',
    options: [
      { id: 'active', label: { es: 'Sí, los pido activamente', 'pt-BR': 'Sim, peço ativamente' }, emoji: '⭐' },
      { id: 'passive', label: { es: 'Solo los que llegan solos', 'pt-BR': 'Apenas os que chegam sozinhos' }, emoji: '📝' },
      { id: 'rarely', label: { es: 'Casi no los uso', 'pt-BR': 'Quase não uso' }, emoji: '🔄' },
      { id: 'never', label: { es: 'No los uso', 'pt-BR': 'Não uso' }, emoji: '❌' },
    ],
  },

  // --- REPUTACIÓN Y CALIDAD (8 preguntas) ---
  {
    id: 'EDU53_SATISFACTION',
    category: 'reputation',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Medís la satisfacción de tus alumnos?', 'pt-BR': 'Você mede a satisfação dos seus alunos?' },
    type: 'single',
    options: [
      { id: 'systematic', label: { es: 'Sí, con encuestas regulares', 'pt-BR': 'Sim, com pesquisas regulares' }, emoji: '📊' },
      { id: 'end_course', label: { es: 'Al final de cada curso', 'pt-BR': 'No final de cada curso' }, emoji: '📝' },
      { id: 'informal', label: { es: 'Informalmente', 'pt-BR': 'Informalmente' }, emoji: '💬' },
      { id: 'never', label: { es: 'No la mido', 'pt-BR': 'Não meço' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU54_NPS_SCORE',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Cuál es tu NPS o score de satisfacción?', 'pt-BR': 'Qual é seu NPS ou score de satisfação?' },
    type: 'single',
    options: [
      { id: 'dont_measure', label: { es: 'No lo mido', 'pt-BR': 'Não meço' }, emoji: '❓' },
      { id: 'low', label: { es: 'Bajo (< 30)', 'pt-BR': 'Baixo (< 30)' }, emoji: '📉' },
      { id: 'medium', label: { es: 'Medio (30-50)', 'pt-BR': 'Médio (30-50)' }, emoji: '📊' },
      { id: 'good', label: { es: 'Bueno (50-70)', 'pt-BR': 'Bom (50-70)' }, emoji: '📈' },
      { id: 'excellent', label: { es: 'Excelente (+70)', 'pt-BR': 'Excelente (+70)' }, emoji: '🏆' },
    ],
  },
  {
    id: 'EDU55_ALUMNI_SUCCESS',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Hacés seguimiento del éxito de egresados?', 'pt-BR': 'Você acompanha o sucesso dos formados?' },
    type: 'single',
    options: [
      { id: 'systematic', label: { es: 'Sí, sistemáticamente', 'pt-BR': 'Sim, sistematicamente' }, emoji: '📊' },
      { id: 'casual', label: { es: 'Casualmente', 'pt-BR': 'Casualmente' }, emoji: '💬' },
      { id: 'linkedin', label: { es: 'Solo por LinkedIn', 'pt-BR': 'Apenas pelo LinkedIn' }, emoji: '💼' },
      { id: 'no', label: { es: 'No hago seguimiento', 'pt-BR': 'Não acompanho' }, emoji: '❌' },
    ],
    businessTypes: [...CURSOS_TECH, EDUCACION_BUSINESS_TYPES.UNIVERSIDAD, EDUCACION_BUSINESS_TYPES.TERCIARIO],
  },
  {
    id: 'EDU56_EMPLOYMENT_RATE',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué % de egresados consigue empleo en el área?', 'pt-BR': 'Qual % de formados consegue emprego na área?' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
    businessTypes: [...CURSOS_TECH, EDUCACION_BUSINESS_TYPES.OFICIOS, EDUCACION_BUSINESS_TYPES.TERCIARIO],
  },
  {
    id: 'EDU57_ACCREDITATIONS',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Tenés acreditaciones o certificaciones institucionales?', 'pt-BR': 'Você tem credenciamentos ou certificações institucionais?' },
    type: 'multi',
    options: [
      { id: 'ministry', label: { es: 'Ministerio de Educación', 'pt-BR': 'Ministério da Educação' }, emoji: '🏛️' },
      { id: 'international', label: { es: 'Certificación internacional', 'pt-BR': 'Certificação internacional' }, emoji: '🌍' },
      { id: 'industry', label: { es: 'Certificación de industria', 'pt-BR': 'Certificação da indústria' }, emoji: '🏭' },
      { id: 'partner', label: { es: 'Partner oficial (Google, Microsoft, etc)', 'pt-BR': 'Parceiro oficial (Google, Microsoft, etc)' }, emoji: '🤝' },
      { id: 'none', label: { es: 'Ninguna', 'pt-BR': 'Nenhuma' }, emoji: '❌' },
    ],
    businessTypes: [...EDUCACION_FORMAL, ...CURSOS_TECH, EDUCACION_BUSINESS_TYPES.IDIOMAS],
  },
  {
    id: 'EDU58_COMPLAINTS_HANDLING',
    category: 'reputation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿Cómo manejás las quejas de alumnos?', 'pt-BR': 'Como você lida com reclamações de alunos?' },
    type: 'single',
    options: [
      { id: 'process', label: { es: 'Proceso formal de reclamos', 'pt-BR': 'Processo formal de reclamações' }, emoji: '📋' },
      { id: 'direct', label: { es: 'Contacto directo conmigo', 'pt-BR': 'Contato direto comigo' }, emoji: '📞' },
      { id: 'coordinator', label: { es: 'Coordinador/Tutor', 'pt-BR': 'Coordenador/Tutor' }, emoji: '👨‍💼' },
      { id: 'reactive', label: { es: 'Las atiendo cuando surgen', 'pt-BR': 'Atendo quando surgem' }, emoji: '🔄' },
    ],
  },
  {
    id: 'EDU59_CURRICULUM_UPDATE',
    category: 'reputation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cada cuánto actualizás tu contenido/curriculum?', 'pt-BR': 'Com que frequência você atualiza seu conteúdo/currículo?' },
    type: 'single',
    options: [
      { id: 'continuous', label: { es: 'Continuamente', 'pt-BR': 'Continuamente' }, emoji: '🔄' },
      { id: 'yearly', label: { es: 'Anualmente', 'pt-BR': 'Anualmente' }, emoji: '📅' },
      { id: 'occasionally', label: { es: 'Cada 2-3 años', 'pt-BR': 'A cada 2-3 anos' }, emoji: '📆' },
      { id: 'rarely', label: { es: 'Raramente', 'pt-BR': 'Raramente' }, emoji: '⏳' },
    ],
  },
  {
    id: 'EDU60_COMPETITIVE_ADVANTAGE',
    category: 'reputation',
    mode: 'complete',
    dimension: 'growth',
    weight: 8,
    title: { es: '¿Cuál es tu principal diferenciador?', 'pt-BR': 'Qual é seu principal diferencial?' },
    type: 'multi',
    options: [
      { id: 'methodology', label: { es: 'Metodología única', 'pt-BR': 'Metodologia única' }, emoji: '📚' },
      { id: 'teachers', label: { es: 'Calidad de docentes', 'pt-BR': 'Qualidade dos professores' }, emoji: '👨‍🏫' },
      { id: 'results', label: { es: 'Resultados/Empleabilidad', 'pt-BR': 'Resultados/Empregabilidade' }, emoji: '🏆' },
      { id: 'price', label: { es: 'Precio accesible', 'pt-BR': 'Preço acessível' }, emoji: '💰' },
      { id: 'flexibility', label: { es: 'Flexibilidad horaria', 'pt-BR': 'Flexibilidade de horários' }, emoji: '🕐' },
      { id: 'technology', label: { es: 'Tecnología/Plataforma', 'pt-BR': 'Tecnologia/Plataforma' }, emoji: '💻' },
    ],
  },

  // --- OBJETIVOS Y CRECIMIENTO (8 preguntas) ---
  {
    id: 'EDU61_MAIN_GOAL',
    category: 'goals',
    mode: 'both',
    dimension: 'growth',
    weight: 9,
    title: { es: '¿Cuál es tu principal objetivo ahora?', 'pt-BR': 'Qual é seu principal objetivo agora?' },
    type: 'single',
    options: [
      { id: 'more_students', label: { es: 'Más alumnos', 'pt-BR': 'Mais alunos' }, emoji: '📈' },
      { id: 'better_margins', label: { es: 'Mejorar rentabilidad', 'pt-BR': 'Melhorar rentabilidade' }, emoji: '💰' },
      { id: 'new_programs', label: { es: 'Lanzar nuevos cursos', 'pt-BR': 'Lançar novos cursos' }, emoji: '🆕' },
      { id: 'go_online', label: { es: 'Crecer online', 'pt-BR': 'Crescer online' }, emoji: '💻' },
      { id: 'quality', label: { es: 'Mejorar calidad', 'pt-BR': 'Melhorar qualidade' }, emoji: '⭐' },
      { id: 'stability', label: { es: 'Estabilizar operación', 'pt-BR': 'Estabilizar operação' }, emoji: '⚖️' },
    ],
  },
  {
    id: 'EDU62_GROWTH_PLAN',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿Tenés plan de crecimiento definido?', 'pt-BR': 'Você tem plano de crescimento definido?' },
    type: 'single',
    options: [
      { id: 'formal', label: { es: 'Sí, formal y documentado', 'pt-BR': 'Sim, formal e documentado' }, emoji: '📋' },
      { id: 'informal', label: { es: 'Sí, pero informal', 'pt-BR': 'Sim, mas informal' }, emoji: '💭' },
      { id: 'thinking', label: { es: 'Lo estoy pensando', 'pt-BR': 'Estou pensando' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No tengo plan claro', 'pt-BR': 'Não tenho plano claro' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU63_BIGGEST_CHALLENGE',
    category: 'goals',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu mayor desafío actual?', 'pt-BR': 'Qual é seu maior desafio atual?' },
    type: 'single',
    options: [
      { id: 'attract', label: { es: 'Atraer más alumnos', 'pt-BR': 'Atrair mais alunos' }, emoji: '📣' },
      { id: 'retain', label: { es: 'Retener alumnos', 'pt-BR': 'Reter alunos' }, emoji: '🔄' },
      { id: 'teachers', label: { es: 'Encontrar buenos docentes', 'pt-BR': 'Encontrar bons professores' }, emoji: '👨‍🏫' },
      { id: 'operations', label: { es: 'Gestionar operaciones', 'pt-BR': 'Gerenciar operações' }, emoji: '⚙️' },
      { id: 'finances', label: { es: 'Finanzas/Flujo de caja', 'pt-BR': 'Finanças/Fluxo de caixa' }, emoji: '💸' },
      { id: 'competition', label: { es: 'Competencia', 'pt-BR': 'Concorrência' }, emoji: '🏃' },
    ],
  },
  {
    id: 'EDU64_EXPANSION_INTEREST',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 6,
    title: { es: '¿Te interesa expandir a otras ubicaciones?', 'pt-BR': 'Você tem interesse em expandir para outros locais?' },
    type: 'single',
    options: [
      { id: 'yes_planning', label: { es: 'Sí, lo estoy planificando', 'pt-BR': 'Sim, estou planejando' }, emoji: '📋' },
      { id: 'maybe', label: { es: 'Quizás en el futuro', 'pt-BR': 'Talvez no futuro' }, emoji: '🤔' },
      { id: 'online_focus', label: { es: 'No, prefiero crecer online', 'pt-BR': 'Não, prefiro crescer online' }, emoji: '💻' },
      { id: 'no', label: { es: 'No me interesa', 'pt-BR': 'Não me interessa' }, emoji: '❌' },
    ],
  },
  {
    id: 'EDU65_TECH_ADOPTION',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Qué tan abierto estás a nuevas tecnologías?', 'pt-BR': 'Quão aberto você está a novas tecnologias?' },
    type: 'single',
    options: [
      { id: 'early', label: { es: 'Muy abierto, adopto rápido', 'pt-BR': 'Muito aberto, adoto rápido' }, emoji: '🚀' },
      { id: 'open', label: { es: 'Abierto si tiene sentido', 'pt-BR': 'Aberto se fizer sentido' }, emoji: '✅' },
      { id: 'cautious', label: { es: 'Cauteloso, espero que se pruebe', 'pt-BR': 'Cauteloso, espero que se prove' }, emoji: '⏳' },
      { id: 'resistant', label: { es: 'Prefiero métodos tradicionales', 'pt-BR': 'Prefiro métodos tradicionais' }, emoji: '📚' },
    ],
  },
  {
    id: 'EDU66_AI_INTEREST',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Usás o te interesa IA en educación?', 'pt-BR': 'Você usa ou tem interesse em IA na educação?' },
    type: 'single',
    options: [
      { id: 'using', label: { es: 'Ya la uso activamente', 'pt-BR': 'Já uso ativamente' }, emoji: '🤖' },
      { id: 'experimenting', label: { es: 'Experimentando', 'pt-BR': 'Experimentando' }, emoji: '🔬' },
      { id: 'interested', label: { es: 'Me interesa aprender', 'pt-BR': 'Tenho interesse em aprender' }, emoji: '📚' },
      { id: 'skeptical', label: { es: 'No me convence', 'pt-BR': 'Não me convence' }, emoji: '🤔' },
    ],
  },
  {
    id: 'EDU67_TIME_DEDICATION',
    category: 'goals',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 5,
    title: { es: '¿Cuántas horas semanales le dedicás al negocio?', 'pt-BR': 'Quantas horas semanais você dedica ao negócio?' },
    type: 'single',
    options: [
      { id: 'part_time', label: { es: 'Part-time (< 20h)', 'pt-BR': 'Part-time (< 20h)' }, emoji: '⏰' },
      { id: 'full_time', label: { es: 'Full-time (40-50h)', 'pt-BR': 'Full-time (40-50h)' }, emoji: '💼' },
      { id: 'intensive', label: { es: 'Intensivo (50-70h)', 'pt-BR': 'Intensivo (50-70h)' }, emoji: '🔥' },
      { id: 'all_in', label: { es: 'Todo mi tiempo (+70h)', 'pt-BR': 'Todo meu tempo (+70h)' }, emoji: '💯' },
    ],
  },
  {
    id: 'EDU68_SUPPORT_NEEDED',
    category: 'goals',
    mode: 'complete',
    dimension: 'growth',
    weight: 7,
    title: { es: '¿En qué área necesitás más apoyo?', 'pt-BR': 'Em qual área você precisa de mais apoio?' },
    type: 'multi',
    options: [
      { id: 'marketing', label: { es: 'Marketing/Captación', 'pt-BR': 'Marketing/Captação' }, emoji: '📣' },
      { id: 'sales', label: { es: 'Ventas/Cierre', 'pt-BR': 'Vendas/Fechamento' }, emoji: '💰' },
      { id: 'operations', label: { es: 'Operaciones/Gestión', 'pt-BR': 'Operações/Gestão' }, emoji: '⚙️' },
      { id: 'content', label: { es: 'Contenido/Curriculum', 'pt-BR': 'Conteúdo/Currículo' }, emoji: '📚' },
      { id: 'technology', label: { es: 'Tecnología', 'pt-BR': 'Tecnologia' }, emoji: '💻' },
      { id: 'finance', label: { es: 'Finanzas', 'pt-BR': 'Finanças' }, emoji: '📊' },
    ],
  },
];

// ============= EXPORTS =============
export function getEducacionQuestions(): EducacionQuestion[] {
  return EDUCACION_COMPLETE_QUESTIONS;
}
