// ============================================
// GASTRONOMÍA - Cuestionario Ultra-Específico Completo
// Sector: Gastronomía y Bebidas
// 18 tipos de negocio, Quick (10-15) + Complete (68-75 preguntas)
// 7 Dimensiones: Crecimiento, Equipo, Tráfico, Rentabilidad, Finanzas, Eficiencia, Reputación
// ============================================

export interface GastroCompleteQuestion {
  id: string;
  category: string;
  categoryLabel: { es: string; 'pt-BR': string };
  mode: 'quick' | 'complete' | 'both';
  score_area: 'Reputación' | 'Rentabilidad' | 'Finanzas' | 'Eficiencia' | 'Tráfico' | 'Equipo' | 'Crecimiento';
  title: { es: string; 'pt-BR': string };
  help?: { es: string; 'pt-BR': string };
  type: 'single' | 'multi' | 'number' | 'slider' | 'text' | 'money';
  options?: Array<{ id: string; label: { es: string; 'pt-BR': string }; emoji?: string }>;
  min?: number;
  max?: number;
  unit?: string;
  required?: boolean;
  businessTypes?: string[];
}

// IDs de tipos de negocio gastronomía
export const GASTRO_BUSINESS_TYPES = {
  RESTAURANT_GENERAL: 'restaurant_general',
  ALTA_COCINA: 'alta_cocina',
  BODEGON: 'bodegon_cantina',
  PARRILLA: 'parrilla_asador',
  COCINA_CRIOLLA: 'cocina_criolla',
  PESCADOS: 'pescados_mariscos',
  PIZZERIA: 'pizzeria',
  PANADERIA: 'panaderia',
  PASTAS: 'pastas_italiana',
  HELADERIA: 'heladeria',
  FAST_FOOD: 'fast_food',
  CAFETERIA: 'cafeteria_pasteleria',
  ASIATICA: 'cocina_asiatica',
  ARABE: 'cocina_arabe',
  SALUDABLE: 'cocina_saludable',
  BAR: 'bar_cerveceria',
  SERVICIO_COMIDA: 'servicio_comida',
  DARK_KITCHEN: 'dark_kitchen',
};

// Grupos de tipos para preguntas condicionales
const TIENE_SALON = [
  GASTRO_BUSINESS_TYPES.RESTAURANT_GENERAL,
  GASTRO_BUSINESS_TYPES.ALTA_COCINA,
  GASTRO_BUSINESS_TYPES.BODEGON,
  GASTRO_BUSINESS_TYPES.PARRILLA,
  GASTRO_BUSINESS_TYPES.COCINA_CRIOLLA,
  GASTRO_BUSINESS_TYPES.PESCADOS,
  GASTRO_BUSINESS_TYPES.PIZZERIA,
  GASTRO_BUSINESS_TYPES.PASTAS,
  GASTRO_BUSINESS_TYPES.CAFETERIA,
  GASTRO_BUSINESS_TYPES.ASIATICA,
  GASTRO_BUSINESS_TYPES.ARABE,
  GASTRO_BUSINESS_TYPES.SALUDABLE,
  GASTRO_BUSINESS_TYPES.BAR,
];

const TIENE_PRODUCCION = [
  GASTRO_BUSINESS_TYPES.PANADERIA,
  GASTRO_BUSINESS_TYPES.HELADERIA,
  GASTRO_BUSINESS_TYPES.PASTAS,
  GASTRO_BUSINESS_TYPES.PIZZERIA,
];

const SOLO_DELIVERY = [
  GASTRO_BUSINESS_TYPES.DARK_KITCHEN,
  GASTRO_BUSINESS_TYPES.SERVICIO_COMIDA,
];

const ALTA_GAMA = [
  GASTRO_BUSINESS_TYPES.ALTA_COCINA,
  GASTRO_BUSINESS_TYPES.PESCADOS,
];

const BAR_BEBIDAS = [
  GASTRO_BUSINESS_TYPES.BAR,
];

// ============================================
// PREGUNTAS UNIVERSALES GASTRONOMÍA (todos los tipos)
// ============================================

const GASTRO_UNIVERSAL_QUESTIONS: GastroCompleteQuestion[] = [
  // --- IDENTIDAD (5 preguntas) ---
  {
    id: 'G01_YEARS_OPERATING',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿Hace cuánto opera tu negocio?', 'pt-BR': 'Há quanto tempo seu negócio opera?' },
    type: 'single',
    options: [
      { id: '<1y', label: { es: 'Menos de 1 año', 'pt-BR': 'Menos de 1 ano' }, emoji: '🆕' },
      { id: '1-3y', label: { es: '1-3 años', 'pt-BR': '1-3 anos' }, emoji: '📅' },
      { id: '3-10y', label: { es: '3-10 años', 'pt-BR': '3-10 anos' }, emoji: '📈' },
      { id: '10+', label: { es: 'Más de 10 años', 'pt-BR': 'Mais de 10 anos' }, emoji: '🏆' },
    ],
  },
  {
    id: 'G02_BRAND_POSITIONING',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Cómo definirías tu posicionamiento?', 'pt-BR': 'Como você definiria seu posicionamento?' },
    type: 'single',
    options: [
      { id: 'budget', label: { es: 'Económico', 'pt-BR': 'Econômico' }, emoji: '💰' },
      { id: 'value', label: { es: 'Buena relación precio-calidad', 'pt-BR': 'Boa relação custo-benefício' }, emoji: '⚖️' },
      { id: 'premium', label: { es: 'Premium', 'pt-BR': 'Premium' }, emoji: '✨' },
      { id: 'luxury', label: { es: 'Lujo', 'pt-BR': 'Luxo' }, emoji: '💎' },
    ],
  },
  {
    id: 'G03_UNIQUE_SELLING',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Qué te diferencia de la competencia?', 'pt-BR': 'O que te diferencia da concorrência?' },
    type: 'multi',
    options: [
      { id: 'quality', label: { es: 'Calidad de ingredientes', 'pt-BR': 'Qualidade dos ingredientes' }, emoji: '🥇' },
      { id: 'price', label: { es: 'Precio competitivo', 'pt-BR': 'Preço competitivo' }, emoji: '💵' },
      { id: 'location', label: { es: 'Ubicación', 'pt-BR': 'Localização' }, emoji: '📍' },
      { id: 'ambiance', label: { es: 'Ambiente/Decoración', 'pt-BR': 'Ambiente/Decoração' }, emoji: '🎨' },
      { id: 'service', label: { es: 'Servicio excepcional', 'pt-BR': 'Serviço excepcional' }, emoji: '⭐' },
      { id: 'unique_product', label: { es: 'Producto único', 'pt-BR': 'Produto único' }, emoji: '🍽️' },
    ],
  },
  {
    id: 'G04_OWNER_ROLE',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Cuál es tu rol principal en el negocio?', 'pt-BR': 'Qual é seu papel principal no negócio?' },
    type: 'single',
    options: [
      { id: 'all_roles', label: { es: 'Hago de todo', 'pt-BR': 'Faço de tudo' }, emoji: '🦸' },
      { id: 'operations', label: { es: 'Operaciones/Cocina', 'pt-BR': 'Operações/Cozinha' }, emoji: '👨‍🍳' },
      { id: 'admin', label: { es: 'Administración', 'pt-BR': 'Administração' }, emoji: '📊' },
      { id: 'strategic', label: { es: 'Estratégico (no operativo)', 'pt-BR': 'Estratégico (não operacional)' }, emoji: '🎯' },
    ],
  },
  {
    id: 'G05_LOCATIONS',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿Cuántas ubicaciones tenés?', 'pt-BR': 'Quantas unidades você tem?' },
    type: 'single',
    options: [
      { id: '1', label: { es: '1 local', 'pt-BR': '1 unidade' } },
      { id: '2-3', label: { es: '2-3 locales', 'pt-BR': '2-3 unidades' } },
      { id: '4-10', label: { es: '4-10 locales', 'pt-BR': '4-10 unidades' } },
      { id: '10+', label: { es: 'Más de 10', 'pt-BR': 'Mais de 10' } },
    ],
  },

  // --- OPERACIÓN (15 preguntas) ---
  {
    id: 'G06_SALES_CHANNELS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'both',
    score_area: 'Tráfico',
    title: { es: '¿Cómo vendés hoy?', 'pt-BR': 'Como você vende hoje?' },
    help: { es: 'Elegí todo lo que aplique', 'pt-BR': 'Escolha tudo que se aplica' },
    type: 'multi',
    required: true,
    options: [
      { id: 'dine_in', label: { es: 'Salón', 'pt-BR': 'Salão' }, emoji: '🍽️' },
      { id: 'delivery_apps', label: { es: 'Apps de delivery', 'pt-BR': 'Apps de delivery' }, emoji: '📱' },
      { id: 'delivery_own', label: { es: 'Delivery propio', 'pt-BR': 'Delivery próprio' }, emoji: '🛵' },
      { id: 'pickup', label: { es: 'Take away', 'pt-BR': 'Take away' }, emoji: '🥡' },
      { id: 'catering', label: { es: 'Catering/Eventos', 'pt-BR': 'Catering/Eventos' }, emoji: '🎉' },
    ],
  },
  {
    id: 'G07_PEAK_HOURS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'both',
    score_area: 'Tráfico',
    title: { es: '¿Cuándo se te llena más?', 'pt-BR': 'Quando enche mais?' },
    type: 'multi',
    options: [
      { id: 'morning', label: { es: 'Mañana (8-12h)', 'pt-BR': 'Manhã (8-12h)' }, emoji: '☀️' },
      { id: 'noon', label: { es: 'Mediodía (12-15h)', 'pt-BR': 'Almoço (12-15h)' }, emoji: '🌞' },
      { id: 'afternoon', label: { es: 'Tarde (15-19h)', 'pt-BR': 'Tarde (15-19h)' }, emoji: '🌤️' },
      { id: 'night', label: { es: 'Noche (19-24h)', 'pt-BR': 'Noite (19-24h)' }, emoji: '🌙' },
      { id: 'late_night', label: { es: 'Madrugada (+24h)', 'pt-BR': 'Madrugada (+24h)' }, emoji: '🌃' },
    ],
  },
  {
    id: 'G08_PEAK_DAYS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: '¿Cuáles son tus días más fuertes?', 'pt-BR': 'Quais são seus dias mais fortes?' },
    type: 'multi',
    options: [
      { id: 'mon_thu', label: { es: 'Lunes a Jueves', 'pt-BR': 'Segunda a Quinta' }, emoji: '📅' },
      { id: 'friday', label: { es: 'Viernes', 'pt-BR': 'Sexta' }, emoji: '🎉' },
      { id: 'saturday', label: { es: 'Sábado', 'pt-BR': 'Sábado' }, emoji: '🥳' },
      { id: 'sunday', label: { es: 'Domingo', 'pt-BR': 'Domingo' }, emoji: '☀️' },
    ],
  },
  {
    id: 'G09_OPENING_HOURS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Días de operación por semana', 'pt-BR': 'Dias de operação por semana' },
    type: 'single',
    options: [
      { id: '5', label: { es: '5 días', 'pt-BR': '5 dias' } },
      { id: '6', label: { es: '6 días', 'pt-BR': '6 dias' } },
      { id: '7', label: { es: '7 días', 'pt-BR': '7 dias' } },
    ],
  },
  {
    id: 'G10_CAPACITY',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'both',
    score_area: 'Eficiencia',
    title: { es: 'Capacidad del local (asientos)', 'pt-BR': 'Capacidade do local (lugares)' },
    help: { es: 'Aproximado está bien', 'pt-BR': 'Aproximado está bom' },
    type: 'slider',
    min: 0,
    max: 300,
    unit: 'asientos',
    businessTypes: TIENE_SALON,
  },
  {
    id: 'G11_RESERVATIONS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Trabajás con reservas?', 'pt-BR': 'Você trabalha com reservas?' },
    type: 'single',
    businessTypes: TIENE_SALON,
    options: [
      { id: 'yes_system', label: { es: 'Sí, con sistema', 'pt-BR': 'Sim, com sistema' }, emoji: '📲' },
      { id: 'yes_manual', label: { es: 'Sí, manual', 'pt-BR': 'Sim, manual' }, emoji: '📓' },
      { id: 'sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🤷' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G12_TABLE_TURNOVER',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Rotación de mesas por turno', 'pt-BR': 'Giro de mesas por turno' },
    type: 'single',
    businessTypes: TIENE_SALON,
    options: [
      { id: '1', label: { es: '1 vez', 'pt-BR': '1 vez' } },
      { id: '2', label: { es: '2 veces', 'pt-BR': '2 vezes' } },
      { id: '3+', label: { es: '3+ veces', 'pt-BR': '3+ vezes' } },
      { id: 'unknown', label: { es: 'No sé', 'pt-BR': 'Não sei' } },
    ],
  },
  {
    id: 'G13_SERVICE_TIME',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Tiempo promedio de servicio (sentarse → pagar)', 'pt-BR': 'Tempo médio de serviço (sentar → pagar)' },
    type: 'single',
    businessTypes: TIENE_SALON,
    options: [
      { id: '30min', label: { es: 'Menos de 30 min', 'pt-BR': 'Menos de 30 min' } },
      { id: '30-60', label: { es: '30-60 min', 'pt-BR': '30-60 min' } },
      { id: '60-90', label: { es: '60-90 min', 'pt-BR': '60-90 min' } },
      { id: '90+', label: { es: 'Más de 90 min', 'pt-BR': 'Mais de 90 min' } },
    ],
  },
  {
    id: 'G14_DELIVERY_APPS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿En qué apps de delivery estás?', 'pt-BR': 'Em quais apps de delivery você está?' },
    type: 'multi',
    options: [
      { id: 'rappi', label: { es: 'Rappi', 'pt-BR': 'Rappi' }, emoji: '🧡' },
      { id: 'pedidosya', label: { es: 'PedidosYa', 'pt-BR': 'iFood' }, emoji: '🔴' },
      { id: 'ubereats', label: { es: 'Uber Eats', 'pt-BR': 'Uber Eats' }, emoji: '🟢' },
      { id: 'mercadolibre', label: { es: 'Mercado Libre', 'pt-BR': 'Mercado Livre' }, emoji: '🟡' },
      { id: 'none', label: { es: 'Ninguna', 'pt-BR': 'Nenhuma' }, emoji: '❌' },
    ],
  },
  {
    id: 'G15_DELIVERY_PCT',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '% de ventas por delivery', 'pt-BR': '% de vendas por delivery' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'G16_KITCHEN_TYPE',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Tipo de cocina', 'pt-BR': 'Tipo de cozinha' },
    type: 'single',
    options: [
      { id: 'scratch', label: { es: 'Todo desde cero', 'pt-BR': 'Tudo do zero' }, emoji: '👨‍🍳' },
      { id: 'mixed', label: { es: 'Mixto (productos + elaboración)', 'pt-BR': 'Misto (produtos + elaboração)' }, emoji: '🔄' },
      { id: 'assembly', label: { es: 'Ensamble/Montaje', 'pt-BR': 'Montagem' }, emoji: '📦' },
    ],
  },
  {
    id: 'G17_POS_SYSTEM',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'both',
    score_area: 'Eficiencia',
    title: { es: '¿Usás sistema de punto de venta (POS)?', 'pt-BR': 'Você usa sistema de ponto de venda (PDV)?' },
    type: 'single',
    options: [
      { id: 'yes_full', label: { es: 'Sí, completo', 'pt-BR': 'Sim, completo' }, emoji: '✅' },
      { id: 'yes_basic', label: { es: 'Sí, básico', 'pt-BR': 'Sim, básico' }, emoji: '📊' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G18_INVENTORY_CONTROL',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Cómo controlás el inventario?', 'pt-BR': 'Como você controla o estoque?' },
    type: 'single',
    options: [
      { id: 'software', label: { es: 'Software/Sistema', 'pt-BR': 'Software/Sistema' }, emoji: '💻' },
      { id: 'excel', label: { es: 'Excel/Planilla', 'pt-BR': 'Excel/Planilha' }, emoji: '📊' },
      { id: 'manual', label: { es: 'Manual/Cuaderno', 'pt-BR': 'Manual/Caderno' }, emoji: '📓' },
      { id: 'none', label: { es: 'No llevo control', 'pt-BR': 'Não controlo' }, emoji: '🤷' },
    ],
  },
  {
    id: 'G19_WASTE_LEVEL',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: 'Nivel de desperdicio/merma', 'pt-BR': 'Nível de desperdício/perda' },
    type: 'single',
    options: [
      { id: 'low', label: { es: 'Bajo (<3%)', 'pt-BR': 'Baixo (<3%)' }, emoji: '✅' },
      { id: 'medium', label: { es: 'Medio (3-7%)', 'pt-BR': 'Médio (3-7%)' }, emoji: '⚠️' },
      { id: 'high', label: { es: 'Alto (>7%)', 'pt-BR': 'Alto (>7%)' }, emoji: '🔴' },
      { id: 'unknown', label: { es: 'No sé', 'pt-BR': 'Não sei' }, emoji: '🤷' },
    ],
  },
  {
    id: 'G20_SUPPLIERS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Cuántos proveedores principales tenés?', 'pt-BR': 'Quantos fornecedores principais você tem?' },
    type: 'single',
    options: [
      { id: '1-3', label: { es: '1-3', 'pt-BR': '1-3' } },
      { id: '4-8', label: { es: '4-8', 'pt-BR': '4-8' } },
      { id: '9-15', label: { es: '9-15', 'pt-BR': '9-15' } },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' } },
    ],
  },

  // --- VENTAS/TICKET (10 preguntas) ---
  {
    id: 'G21_AVG_TICKET',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'both',
    score_area: 'Rentabilidad',
    title: { es: 'Ticket promedio por mesa/pedido', 'pt-BR': 'Ticket médio por mesa/pedido' },
    type: 'money',
    required: true,
  },
  {
    id: 'G22_DAILY_COVERS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'both',
    score_area: 'Tráfico',
    title: { es: 'Clientes/cubiertos promedio por día', 'pt-BR': 'Clientes/couverts médios por dia' },
    type: 'single',
    options: [
      { id: '1-30', label: { es: '1-30', 'pt-BR': '1-30' } },
      { id: '31-80', label: { es: '31-80', 'pt-BR': '31-80' } },
      { id: '81-150', label: { es: '81-150', 'pt-BR': '81-150' } },
      { id: '151-300', label: { es: '151-300', 'pt-BR': '151-300' } },
      { id: '300+', label: { es: 'Más de 300', 'pt-BR': 'Mais de 300' } },
    ],
  },
  {
    id: 'G23_PAYMENT_METHODS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: 'Métodos de pago aceptados', 'pt-BR': 'Métodos de pagamento aceitos' },
    type: 'multi',
    options: [
      { id: 'cash', label: { es: 'Efectivo', 'pt-BR': 'Dinheiro' }, emoji: '💵' },
      { id: 'debit', label: { es: 'Débito', 'pt-BR': 'Débito' }, emoji: '💳' },
      { id: 'credit', label: { es: 'Crédito', 'pt-BR': 'Crédito' }, emoji: '💳' },
      { id: 'qr', label: { es: 'QR/Billetera virtual', 'pt-BR': 'QR/Carteira virtual' }, emoji: '📱' },
      { id: 'transfer', label: { es: 'Transferencia', 'pt-BR': 'Transferência' }, emoji: '🏦' },
    ],
  },
  {
    id: 'G24_CASH_PCT',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '% de ventas en efectivo', 'pt-BR': '% de vendas em dinheiro' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'G25_UPSELLING',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Hacés upselling activo (postres, bebidas)?', 'pt-BR': 'Você faz upselling ativo (sobremesas, bebidas)?' },
    type: 'single',
    options: [
      { id: 'always', label: { es: 'Siempre', 'pt-BR': 'Sempre' }, emoji: '✅' },
      { id: 'sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🔄' },
      { id: 'rarely', label: { es: 'Pocas veces', 'pt-BR': 'Raramente' }, emoji: '😐' },
      { id: 'never', label: { es: 'Nunca', 'pt-BR': 'Nunca' }, emoji: '❌' },
    ],
  },
  {
    id: 'G26_PROMOTIONS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Hacés promociones regularmente?', 'pt-BR': 'Você faz promoções regularmente?' },
    type: 'single',
    options: [
      { id: 'weekly', label: { es: 'Semanales', 'pt-BR': 'Semanais' }, emoji: '📅' },
      { id: 'monthly', label: { es: 'Mensuales', 'pt-BR': 'Mensais' }, emoji: '📆' },
      { id: 'occasional', label: { es: 'Ocasionales', 'pt-BR': 'Ocasionais' }, emoji: '🎯' },
      { id: 'never', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G27_LOYALTY_PROGRAM',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Tenés programa de fidelización?', 'pt-BR': 'Você tem programa de fidelização?' },
    type: 'single',
    options: [
      { id: 'yes_digital', label: { es: 'Sí, digital', 'pt-BR': 'Sim, digital' }, emoji: '📱' },
      { id: 'yes_physical', label: { es: 'Sí, tarjeta física', 'pt-BR': 'Sim, cartão físico' }, emoji: '💳' },
      { id: 'planning', label: { es: 'Lo estoy planeando', 'pt-BR': 'Estou planejando' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G28_REPEAT_CUSTOMERS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '% aproximado de clientes recurrentes', 'pt-BR': '% aproximado de clientes recorrentes' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },
  {
    id: 'G29_SALES_TREND',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: 'Tendencia de ventas vs año anterior', 'pt-BR': 'Tendência de vendas vs ano anterior' },
    type: 'single',
    options: [
      { id: 'up_lot', label: { es: 'Subiendo mucho (+20%)', 'pt-BR': 'Subindo muito (+20%)' }, emoji: '🚀' },
      { id: 'up', label: { es: 'Subiendo (5-20%)', 'pt-BR': 'Subindo (5-20%)' }, emoji: '📈' },
      { id: 'stable', label: { es: 'Estable', 'pt-BR': 'Estável' }, emoji: '➖' },
      { id: 'down', label: { es: 'Bajando', 'pt-BR': 'Caindo' }, emoji: '📉' },
      { id: 'first_year', label: { es: 'Primer año', 'pt-BR': 'Primeiro ano' }, emoji: '🆕' },
    ],
  },
  {
    id: 'G30_SEASONALITY',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: '¿Tu negocio es estacional?', 'pt-BR': 'Seu negócio é sazonal?' },
    type: 'single',
    options: [
      { id: 'very', label: { es: 'Muy estacional', 'pt-BR': 'Muito sazonal' }, emoji: '🌊' },
      { id: 'some', label: { es: 'Algo estacional', 'pt-BR': 'Um pouco sazonal' }, emoji: '🔄' },
      { id: 'stable', label: { es: 'Bastante estable', 'pt-BR': 'Bastante estável' }, emoji: '➖' },
    ],
  },

  // --- MENÚ / PRODUCTO (10 preguntas) ---
  {
    id: 'G31_MENU_SIZE',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'both',
    score_area: 'Eficiencia',
    title: { es: 'Cantidad de ítems en tu menú/carta', 'pt-BR': 'Quantidade de itens no seu cardápio' },
    type: 'single',
    options: [
      { id: '1-15', label: { es: '1-15 (enfocado)', 'pt-BR': '1-15 (focado)' } },
      { id: '16-40', label: { es: '16-40 (moderado)', 'pt-BR': '16-40 (moderado)' } },
      { id: '41-80', label: { es: '41-80 (amplio)', 'pt-BR': '41-80 (amplo)' } },
      { id: '80+', label: { es: 'Más de 80', 'pt-BR': 'Mais de 80' } },
    ],
  },
  {
    id: 'G32_MENU_UPDATE',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Cada cuánto actualizás el menú?', 'pt-BR': 'Com que frequência atualiza o cardápio?' },
    type: 'single',
    options: [
      { id: 'weekly', label: { es: 'Semanal', 'pt-BR': 'Semanal' } },
      { id: 'monthly', label: { es: 'Mensual', 'pt-BR': 'Mensal' } },
      { id: 'seasonal', label: { es: 'Por temporada', 'pt-BR': 'Por temporada' } },
      { id: 'yearly', label: { es: 'Anual o menos', 'pt-BR': 'Anual ou menos' } },
    ],
  },
  {
    id: 'G33_STAR_ITEMS',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Sabés cuáles son tus platos estrella (más rentables)?', 'pt-BR': 'Você sabe quais são seus pratos estrela (mais rentáveis)?' },
    type: 'single',
    options: [
      { id: 'yes_data', label: { es: 'Sí, con datos', 'pt-BR': 'Sim, com dados' }, emoji: '📊' },
      { id: 'yes_intuition', label: { es: 'Sí, por intuición', 'pt-BR': 'Sim, por intuição' }, emoji: '💡' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G34_MENU_ENGINEERING',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Hacés ingeniería de menú (análisis de rentabilidad)?', 'pt-BR': 'Você faz engenharia de cardápio (análise de rentabilidade)?' },
    type: 'single',
    options: [
      { id: 'yes_regular', label: { es: 'Sí, regularmente', 'pt-BR': 'Sim, regularmente' }, emoji: '📈' },
      { id: 'sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🔄' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G35_DIETARY_OPTIONS',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Ofrecés opciones dietéticas especiales?', 'pt-BR': 'Você oferece opções dietéticas especiais?' },
    type: 'multi',
    options: [
      { id: 'vegetarian', label: { es: 'Vegetariano', 'pt-BR': 'Vegetariano' }, emoji: '🥗' },
      { id: 'vegan', label: { es: 'Vegano', 'pt-BR': 'Vegano' }, emoji: '🌱' },
      { id: 'gluten_free', label: { es: 'Sin gluten', 'pt-BR': 'Sem glúten' }, emoji: '🌾' },
      { id: 'keto', label: { es: 'Keto/Low carb', 'pt-BR': 'Keto/Low carb' }, emoji: '🥩' },
      { id: 'none', label: { es: 'No especialmente', 'pt-BR': 'Não especialmente' }, emoji: '➖' },
    ],
  },
  {
    id: 'G36_PORTION_SIZE',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Cómo son tus porciones vs competencia?', 'pt-BR': 'Como são suas porções vs concorrência?' },
    type: 'single',
    options: [
      { id: 'bigger', label: { es: 'Más grandes', 'pt-BR': 'Maiores' }, emoji: '📈' },
      { id: 'similar', label: { es: 'Similares', 'pt-BR': 'Similares' }, emoji: '➖' },
      { id: 'smaller', label: { es: 'Más chicas', 'pt-BR': 'Menores' }, emoji: '📉' },
    ],
  },
  {
    id: 'G37_SIGNATURE_DISHES',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés platos "signature" únicos?', 'pt-BR': 'Você tem pratos "signature" únicos?' },
    type: 'single',
    options: [
      { id: 'yes_famous', label: { es: 'Sí, son famosos', 'pt-BR': 'Sim, são famosos' }, emoji: '⭐' },
      { id: 'yes_some', label: { es: 'Sí, algunos', 'pt-BR': 'Sim, alguns' }, emoji: '🍽️' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G38_BEVERAGE_SALES',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '% de ventas en bebidas', 'pt-BR': '% de vendas em bebidas' },
    type: 'slider',
    min: 0,
    max: 80,
    unit: '%',
  },
  {
    id: 'G39_ALCOHOL_SALES',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Vendés alcohol?', 'pt-BR': 'Você vende álcool?' },
    type: 'single',
    options: [
      { id: 'yes_main', label: { es: 'Sí, es fuerte', 'pt-BR': 'Sim, é forte' }, emoji: '🍷' },
      { id: 'yes_some', label: { es: 'Sí, algo', 'pt-BR': 'Sim, um pouco' }, emoji: '🍺' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G40_DESSERTS',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '% de mesas que piden postre', 'pt-BR': '% de mesas que pedem sobremesa' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
    businessTypes: TIENE_SALON,
  },

  // --- FINANZAS (12 preguntas) ---
  {
    id: 'G41_MONTHLY_REVENUE',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: 'Facturación mensual promedio', 'pt-BR': 'Faturamento mensal médio' },
    type: 'single',
    options: [
      { id: 'tier1', label: { es: 'Menos de $2M', 'pt-BR': 'Menos de R$50k' } },
      { id: 'tier2', label: { es: '$2M - $5M', 'pt-BR': 'R$50k - R$150k' } },
      { id: 'tier3', label: { es: '$5M - $15M', 'pt-BR': 'R$150k - R$500k' } },
      { id: 'tier4', label: { es: 'Más de $15M', 'pt-BR': 'Mais de R$500k' } },
    ],
  },
  {
    id: 'G42_FOOD_COST',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'both',
    score_area: 'Rentabilidad',
    title: { es: 'Food cost promedio (%)', 'pt-BR': 'CMV médio (%)' },
    help: { es: 'Costo de materia prima / Ventas', 'pt-BR': 'Custo de matéria-prima / Vendas' },
    type: 'slider',
    min: 15,
    max: 50,
    unit: '%',
  },
  {
    id: 'G43_LABOR_COST',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: 'Costo de personal (% sobre ventas)', 'pt-BR': 'Custo de pessoal (% sobre vendas)' },
    type: 'slider',
    min: 10,
    max: 50,
    unit: '%',
  },
  {
    id: 'G44_RENT_COST',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: 'Alquiler (% sobre ventas)', 'pt-BR': 'Aluguel (% sobre vendas)' },
    type: 'slider',
    min: 3,
    max: 25,
    unit: '%',
  },
  {
    id: 'G45_FIXED_COSTS',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: 'Costos fijos mensuales totales', 'pt-BR': 'Custos fixos mensais totais' },
    type: 'money',
  },
  {
    id: 'G46_PROFIT_MARGIN',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'both',
    score_area: 'Rentabilidad',
    title: { es: 'Margen de ganancia neto estimado', 'pt-BR': 'Margem de lucro líquido estimado' },
    type: 'single',
    options: [
      { id: 'negative', label: { es: 'Negativo/Pérdida', 'pt-BR': 'Negativo/Prejuízo' }, emoji: '📉' },
      { id: '0-5', label: { es: '0-5%', 'pt-BR': '0-5%' }, emoji: '😐' },
      { id: '5-10', label: { es: '5-10%', 'pt-BR': '5-10%' }, emoji: '📊' },
      { id: '10-15', label: { es: '10-15%', 'pt-BR': '10-15%' }, emoji: '📈' },
      { id: '15+', label: { es: 'Más del 15%', 'pt-BR': 'Mais de 15%' }, emoji: '🚀' },
    ],
  },
  {
    id: 'G47_CASH_FLOW',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '¿Cómo está tu flujo de caja?', 'pt-BR': 'Como está seu fluxo de caixa?' },
    type: 'single',
    options: [
      { id: 'tight', label: { es: 'Ajustado/Mes a mes', 'pt-BR': 'Apertado/Mês a mês' }, emoji: '😰' },
      { id: 'ok', label: { es: 'Estable pero sin holgura', 'pt-BR': 'Estável mas sem folga' }, emoji: '😐' },
      { id: 'healthy', label: { es: 'Saludable, con reservas', 'pt-BR': 'Saudável, com reservas' }, emoji: '😊' },
      { id: 'strong', label: { es: 'Muy bueno, para invertir', 'pt-BR': 'Muito bom, para investir' }, emoji: '💪' },
    ],
  },
  {
    id: 'G48_BREAKEVEN',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '¿Conocés tu punto de equilibrio?', 'pt-BR': 'Você conhece seu ponto de equilíbrio?' },
    type: 'single',
    options: [
      { id: 'yes_exact', label: { es: 'Sí, exacto', 'pt-BR': 'Sim, exato' }, emoji: '✅' },
      { id: 'yes_approx', label: { es: 'Sí, aproximado', 'pt-BR': 'Sim, aproximado' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G49_ACCOUNTING',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '¿Cómo llevás la contabilidad?', 'pt-BR': 'Como você faz a contabilidade?' },
    type: 'single',
    options: [
      { id: 'external', label: { es: 'Contador externo', 'pt-BR': 'Contador externo' }, emoji: '👔' },
      { id: 'internal', label: { es: 'Interno/Propio', 'pt-BR': 'Interno/Próprio' }, emoji: '💼' },
      { id: 'mixed', label: { es: 'Mixto', 'pt-BR': 'Misto' }, emoji: '🔄' },
      { id: 'basic', label: { es: 'Muy básico', 'pt-BR': 'Muito básico' }, emoji: '📝' },
    ],
  },
  {
    id: 'G50_FINANCIAL_REPORTS',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '¿Revisás reportes financieros regularmente?', 'pt-BR': 'Você revisa relatórios financeiros regularmente?' },
    type: 'single',
    options: [
      { id: 'weekly', label: { es: 'Semanalmente', 'pt-BR': 'Semanalmente' }, emoji: '📅' },
      { id: 'monthly', label: { es: 'Mensualmente', 'pt-BR': 'Mensalmente' }, emoji: '📆' },
      { id: 'quarterly', label: { es: 'Trimestralmente', 'pt-BR': 'Trimestralmente' }, emoji: '📊' },
      { id: 'rarely', label: { es: 'Pocas veces', 'pt-BR': 'Raramente' }, emoji: '😐' },
    ],
  },
  {
    id: 'G51_DEBT',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '¿Tenés deuda significativa?', 'pt-BR': 'Você tem dívida significativa?' },
    type: 'single',
    options: [
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '✅' },
      { id: 'manageable', label: { es: 'Sí, manejable', 'pt-BR': 'Sim, gerenciável' }, emoji: '📊' },
      { id: 'significant', label: { es: 'Sí, significativa', 'pt-BR': 'Sim, significativa' }, emoji: '⚠️' },
      { id: 'critical', label: { es: 'Sí, crítica', 'pt-BR': 'Sim, crítica' }, emoji: '🆘' },
    ],
  },
  {
    id: 'G52_PRICING_STRATEGY',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Cómo fijás los precios?', 'pt-BR': 'Como você define os preços?' },
    type: 'single',
    options: [
      { id: 'cost_plus', label: { es: 'Costo + margen', 'pt-BR': 'Custo + margem' }, emoji: '📊' },
      { id: 'competition', label: { es: 'Basado en competencia', 'pt-BR': 'Baseado na concorrência' }, emoji: '👀' },
      { id: 'value', label: { es: 'Valor percibido', 'pt-BR': 'Valor percebido' }, emoji: '💎' },
      { id: 'intuition', label: { es: 'Intuición', 'pt-BR': 'Intuição' }, emoji: '🧠' },
    ],
  },

  // --- EQUIPO (10 preguntas) ---
  {
    id: 'G53_TEAM_SIZE',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'both',
    score_area: 'Equipo',
    title: { es: 'Tamaño del equipo (total empleados)', 'pt-BR': 'Tamanho da equipe (total de funcionários)' },
    type: 'single',
    options: [
      { id: 'solo', label: { es: 'Solo yo', 'pt-BR': 'Só eu' }, emoji: '👤' },
      { id: '2-5', label: { es: '2-5 personas', 'pt-BR': '2-5 pessoas' }, emoji: '👥' },
      { id: '6-15', label: { es: '6-15 personas', 'pt-BR': '6-15 pessoas' }, emoji: '👨‍👩‍👧‍👦' },
      { id: '16-30', label: { es: '16-30 personas', 'pt-BR': '16-30 pessoas' }, emoji: '🏢' },
      { id: '30+', label: { es: 'Más de 30', 'pt-BR': 'Mais de 30' }, emoji: '🏭' },
    ],
  },
  {
    id: 'G54_KITCHEN_STAFF',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: 'Personal de cocina', 'pt-BR': 'Pessoal de cozinha' },
    type: 'single',
    options: [
      { id: '1-2', label: { es: '1-2', 'pt-BR': '1-2' } },
      { id: '3-5', label: { es: '3-5', 'pt-BR': '3-5' } },
      { id: '6-10', label: { es: '6-10', 'pt-BR': '6-10' } },
      { id: '10+', label: { es: 'Más de 10', 'pt-BR': 'Mais de 10' } },
    ],
  },
  {
    id: 'G55_SERVICE_STAFF',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: 'Personal de salón/servicio', 'pt-BR': 'Pessoal de salão/serviço' },
    type: 'single',
    businessTypes: TIENE_SALON,
    options: [
      { id: '1-2', label: { es: '1-2', 'pt-BR': '1-2' } },
      { id: '3-5', label: { es: '3-5', 'pt-BR': '3-5' } },
      { id: '6-10', label: { es: '6-10', 'pt-BR': '6-10' } },
      { id: '10+', label: { es: 'Más de 10', 'pt-BR': 'Mais de 10' } },
    ],
  },
  {
    id: 'G56_TURNOVER',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'both',
    score_area: 'Equipo',
    title: { es: 'Rotación de personal', 'pt-BR': 'Rotatividade de funcionários' },
    type: 'single',
    options: [
      { id: 'low', label: { es: 'Baja (equipo estable)', 'pt-BR': 'Baixa (equipe estável)' }, emoji: '💚' },
      { id: 'medium', label: { es: 'Media (algunos cambios)', 'pt-BR': 'Média (algumas mudanças)' }, emoji: '💛' },
      { id: 'high', label: { es: 'Alta (mucho recambio)', 'pt-BR': 'Alta (muita troca)' }, emoji: '🔴' },
    ],
  },
  {
    id: 'G57_HIRING_DIFFICULTY',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: '¿Te cuesta conseguir personal?', 'pt-BR': 'É difícil encontrar funcionários?' },
    type: 'single',
    options: [
      { id: 'no', label: { es: 'No, fácil', 'pt-BR': 'Não, fácil' }, emoji: '✅' },
      { id: 'some', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '😐' },
      { id: 'yes', label: { es: 'Sí, bastante', 'pt-BR': 'Sim, bastante' }, emoji: '😰' },
      { id: 'critical', label: { es: 'Es crítico', 'pt-BR': 'É crítico' }, emoji: '🆘' },
    ],
  },
  {
    id: 'G58_TRAINING',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Capacitás a tu equipo regularmente?', 'pt-BR': 'Você treina sua equipe regularmente?' },
    type: 'single',
    options: [
      { id: 'yes_formal', label: { es: 'Sí, programa formal', 'pt-BR': 'Sim, programa formal' }, emoji: '📚' },
      { id: 'sometimes', label: { es: 'A veces, informal', 'pt-BR': 'Às vezes, informal' }, emoji: '💬' },
      { id: 'no', label: { es: 'No, aprenden trabajando', 'pt-BR': 'Não, aprendem trabalhando' }, emoji: '🔧' },
    ],
  },
  {
    id: 'G59_TEAM_SATISFACTION',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: 'Satisfacción del equipo (tu percepción)', 'pt-BR': 'Satisfação da equipe (sua percepção)' },
    type: 'single',
    options: [
      { id: 'high', label: { es: 'Alta', 'pt-BR': 'Alta' }, emoji: '😊' },
      { id: 'medium', label: { es: 'Media', 'pt-BR': 'Média' }, emoji: '😐' },
      { id: 'low', label: { es: 'Baja', 'pt-BR': 'Baixa' }, emoji: '😞' },
      { id: 'unknown', label: { es: 'No sé', 'pt-BR': 'Não sei' }, emoji: '🤷' },
    ],
  },
  {
    id: 'G60_MANAGER',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Tenés encargado/gerente?', 'pt-BR': 'Você tem gerente?' },
    type: 'single',
    options: [
      { id: 'yes_full', label: { es: 'Sí, de confianza', 'pt-BR': 'Sim, de confiança' }, emoji: '✅' },
      { id: 'yes_partial', label: { es: 'Sí, pero superviso mucho', 'pt-BR': 'Sim, mas supervisiono muito' }, emoji: '👀' },
      { id: 'no', label: { es: 'No, yo hago todo', 'pt-BR': 'Não, eu faço tudo' }, emoji: '🦸' },
    ],
  },
  {
    id: 'G61_WORK_CULTURE',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: '¿Cómo describirías la cultura de trabajo?', 'pt-BR': 'Como você descreveria a cultura de trabalho?' },
    type: 'single',
    options: [
      { id: 'family', label: { es: 'Familiar', 'pt-BR': 'Familiar' }, emoji: '👨‍👩‍👧' },
      { id: 'professional', label: { es: 'Profesional', 'pt-BR': 'Profissional' }, emoji: '👔' },
      { id: 'dynamic', label: { es: 'Dinámica', 'pt-BR': 'Dinâmica' }, emoji: '⚡' },
      { id: 'challenging', label: { es: 'Desafiante', 'pt-BR': 'Desafiadora' }, emoji: '💪' },
    ],
  },
  {
    id: 'G62_TIPS_SYSTEM',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: '¿Cómo manejás las propinas?', 'pt-BR': 'Como você gerencia as gorjetas?' },
    type: 'single',
    businessTypes: TIENE_SALON,
    options: [
      { id: 'individual', label: { es: 'Individuales', 'pt-BR': 'Individuais' }, emoji: '👤' },
      { id: 'pool', label: { es: 'Se reparten', 'pt-BR': 'Divididas' }, emoji: '🔄' },
      { id: 'none', label: { es: 'No hay propinas', 'pt-BR': 'Não há gorjetas' }, emoji: '❌' },
    ],
  },

  // --- MARKETING (8 preguntas) ---
  {
    id: 'G63_MARKETING_CHANNELS',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿Dónde hacés marketing?', 'pt-BR': 'Onde você faz marketing?' },
    type: 'multi',
    options: [
      { id: 'instagram', label: { es: 'Instagram', 'pt-BR': 'Instagram' }, emoji: '📸' },
      { id: 'facebook', label: { es: 'Facebook', 'pt-BR': 'Facebook' }, emoji: '📘' },
      { id: 'google_ads', label: { es: 'Google Ads', 'pt-BR': 'Google Ads' }, emoji: '🔍' },
      { id: 'tiktok', label: { es: 'TikTok', 'pt-BR': 'TikTok' }, emoji: '🎵' },
      { id: 'email', label: { es: 'Email marketing', 'pt-BR': 'Email marketing' }, emoji: '📧' },
      { id: 'none', label: { es: 'No hago marketing', 'pt-BR': 'Não faço marketing' }, emoji: '🤷' },
    ],
  },
  {
    id: 'G64_MARKETING_BUDGET',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Presupuesto mensual de marketing', 'pt-BR': 'Orçamento mensal de marketing' },
    type: 'single',
    options: [
      { id: 'zero', label: { es: '$0', 'pt-BR': 'R$0' } },
      { id: 'low', label: { es: 'Bajo (<$50k)', 'pt-BR': 'Baixo (<R$1k)' } },
      { id: 'medium', label: { es: 'Medio ($50k-200k)', 'pt-BR': 'Médio (R$1-5k)' } },
      { id: 'high', label: { es: 'Alto (>$200k)', 'pt-BR': 'Alto (>R$5k)' } },
    ],
  },
  {
    id: 'G65_SOCIAL_FOLLOWERS',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Seguidores en redes (total aprox)', 'pt-BR': 'Seguidores nas redes (total aprox)' },
    type: 'single',
    options: [
      { id: '0-500', label: { es: '0-500', 'pt-BR': '0-500' } },
      { id: '500-2k', label: { es: '500-2.000', 'pt-BR': '500-2.000' } },
      { id: '2k-10k', label: { es: '2.000-10.000', 'pt-BR': '2.000-10.000' } },
      { id: '10k+', label: { es: 'Más de 10.000', 'pt-BR': 'Mais de 10.000' } },
    ],
  },
  {
    id: 'G66_CONTENT_CREATION',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Quién hace el contenido de redes?', 'pt-BR': 'Quem faz o conteúdo das redes?' },
    type: 'single',
    options: [
      { id: 'myself', label: { es: 'Yo mismo', 'pt-BR': 'Eu mesmo' }, emoji: '🤳' },
      { id: 'employee', label: { es: 'Un empleado', 'pt-BR': 'Um funcionário' }, emoji: '👤' },
      { id: 'agency', label: { es: 'Agencia', 'pt-BR': 'Agência' }, emoji: '🏢' },
      { id: 'none', label: { es: 'No publicamos', 'pt-BR': 'Não publicamos' }, emoji: '❌' },
    ],
  },
  {
    id: 'G67_WEBSITE',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Tenés sitio web?', 'pt-BR': 'Você tem site?' },
    type: 'single',
    options: [
      { id: 'yes_updated', label: { es: 'Sí, actualizado', 'pt-BR': 'Sim, atualizado' }, emoji: '✅' },
      { id: 'yes_old', label: { es: 'Sí, pero desactualizado', 'pt-BR': 'Sim, mas desatualizado' }, emoji: '😐' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G68_GOOGLE_BUSINESS',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'both',
    score_area: 'Reputación',
    title: { es: '¿Tenés Google Business actualizado?', 'pt-BR': 'Você tem Google Business atualizado?' },
    type: 'single',
    options: [
      { id: 'yes_active', label: { es: 'Sí, activo', 'pt-BR': 'Sim, ativo' }, emoji: '✅' },
      { id: 'yes_basic', label: { es: 'Sí, básico', 'pt-BR': 'Sim, básico' }, emoji: '📋' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G69_INFLUENCERS',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Trabajás con influencers?', 'pt-BR': 'Você trabalha com influencers?' },
    type: 'single',
    options: [
      { id: 'yes_paid', label: { es: 'Sí, pagos', 'pt-BR': 'Sim, pagos' }, emoji: '💰' },
      { id: 'yes_exchange', label: { es: 'Sí, canje', 'pt-BR': 'Sim, permuta' }, emoji: '🤝' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G70_PR_PRESS',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Saliste en prensa/medios?', 'pt-BR': 'Você saiu na imprensa/mídia?' },
    type: 'single',
    options: [
      { id: 'yes_often', label: { es: 'Sí, frecuentemente', 'pt-BR': 'Sim, frequentemente' }, emoji: '📰' },
      { id: 'yes_some', label: { es: 'Sí, algunas veces', 'pt-BR': 'Sim, algumas vezes' }, emoji: '📰' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },

  // --- REPUTACIÓN (8 preguntas) ---
  {
    id: 'G71_REVIEW_PLATFORMS',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'both',
    score_area: 'Reputación',
    title: { es: '¿Dónde te dejan reseñas?', 'pt-BR': 'Onde deixam avaliações?' },
    type: 'multi',
    options: [
      { id: 'google', label: { es: 'Google', 'pt-BR': 'Google' }, emoji: '🔍' },
      { id: 'tripadvisor', label: { es: 'TripAdvisor', 'pt-BR': 'TripAdvisor' }, emoji: '🦉' },
      { id: 'instagram', label: { es: 'Instagram', 'pt-BR': 'Instagram' }, emoji: '📸' },
      { id: 'delivery_apps', label: { es: 'Apps delivery', 'pt-BR': 'Apps delivery' }, emoji: '📱' },
      { id: 'facebook', label: { es: 'Facebook', 'pt-BR': 'Facebook' }, emoji: '📘' },
    ],
  },
  {
    id: 'G72_CURRENT_RATING',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'both',
    score_area: 'Reputación',
    title: { es: 'Tu rating promedio en Google', 'pt-BR': 'Sua nota média no Google' },
    type: 'slider',
    min: 1,
    max: 5,
    unit: '⭐',
  },
  {
    id: 'G73_REVIEW_COUNT',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: 'Cantidad de reseñas en Google', 'pt-BR': 'Quantidade de avaliações no Google' },
    type: 'single',
    options: [
      { id: '0-20', label: { es: '0-20', 'pt-BR': '0-20' } },
      { id: '21-100', label: { es: '21-100', 'pt-BR': '21-100' } },
      { id: '101-500', label: { es: '101-500', 'pt-BR': '101-500' } },
      { id: '500+', label: { es: 'Más de 500', 'pt-BR': 'Mais de 500' } },
    ],
  },
  {
    id: 'G74_REVIEW_REPLY',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'both',
    score_area: 'Reputación',
    title: { es: '¿Respondés las reseñas?', 'pt-BR': 'Você responde as avaliações?' },
    type: 'single',
    options: [
      { id: 'always', label: { es: 'Siempre', 'pt-BR': 'Sempre' }, emoji: '✅' },
      { id: 'sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🔄' },
      { id: 'negative_only', label: { es: 'Solo negativas', 'pt-BR': 'Só negativas' }, emoji: '⚠️' },
      { id: 'never', label: { es: 'Nunca', 'pt-BR': 'Nunca' }, emoji: '❌' },
    ],
  },
  {
    id: 'G75_TOP_COMPLAINT',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Principal queja de clientes', 'pt-BR': 'Principal reclamação dos clientes' },
    type: 'single',
    options: [
      { id: 'price', label: { es: 'Precio', 'pt-BR': 'Preço' }, emoji: '💰' },
      { id: 'wait_time', label: { es: 'Tiempo de espera', 'pt-BR': 'Tempo de espera' }, emoji: '⏱️' },
      { id: 'service', label: { es: 'Atención/Servicio', 'pt-BR': 'Atendimento/Serviço' }, emoji: '👥' },
      { id: 'portions', label: { es: 'Porciones', 'pt-BR': 'Porções' }, emoji: '📏' },
      { id: 'quality', label: { es: 'Calidad', 'pt-BR': 'Qualidade' }, emoji: '⭐' },
      { id: 'none', label: { es: 'Sin quejas frecuentes', 'pt-BR': 'Sem reclamações frequentes' }, emoji: '🎉' },
    ],
  },
  {
    id: 'G76_TOP_PRAISE',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Por qué te elogian más?', 'pt-BR': 'Pelo que mais te elogiam?' },
    type: 'single',
    options: [
      { id: 'food', label: { es: 'Comida', 'pt-BR': 'Comida' }, emoji: '🍽️' },
      { id: 'service', label: { es: 'Servicio', 'pt-BR': 'Serviço' }, emoji: '⭐' },
      { id: 'ambiance', label: { es: 'Ambiente', 'pt-BR': 'Ambiente' }, emoji: '🎨' },
      { id: 'price', label: { es: 'Precio', 'pt-BR': 'Preço' }, emoji: '💰' },
      { id: 'location', label: { es: 'Ubicación', 'pt-BR': 'Localização' }, emoji: '📍' },
    ],
  },
  {
    id: 'G77_NPS',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Medís satisfacción del cliente (NPS, encuestas)?', 'pt-BR': 'Você mede satisfação do cliente (NPS, pesquisas)?' },
    type: 'single',
    options: [
      { id: 'yes_formal', label: { es: 'Sí, formalmente', 'pt-BR': 'Sim, formalmente' }, emoji: '📊' },
      { id: 'yes_informal', label: { es: 'Sí, informalmente', 'pt-BR': 'Sim, informalmente' }, emoji: '💬' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'G78_WORD_OF_MOUTH',
    category: 'reputacion',
    categoryLabel: { es: 'Reputación', 'pt-BR': 'Reputação' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '% estimado de clientes por recomendación', 'pt-BR': '% estimado de clientes por recomendação' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
  },

  // --- OBJETIVOS (5 preguntas) ---
  {
    id: 'G79_MAIN_GOAL_30D',
    category: 'objetivos',
    categoryLabel: { es: 'Objetivos', 'pt-BR': 'Objetivos' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿Qué querés mejorar en los próximos 30 días?', 'pt-BR': 'O que você quer melhorar nos próximos 30 dias?' },
    type: 'single',
    required: true,
    options: [
      { id: 'more_sales', label: { es: 'Más ventas', 'pt-BR': 'Mais vendas' }, emoji: '💰' },
      { id: 'better_margin', label: { es: 'Mejor margen', 'pt-BR': 'Melhor margem' }, emoji: '📈' },
      { id: 'reputation', label: { es: 'Mejorar reputación', 'pt-BR': 'Melhorar reputação' }, emoji: '⭐' },
      { id: 'efficiency', label: { es: 'Más eficiencia', 'pt-BR': 'Mais eficiência' }, emoji: '⚡' },
      { id: 'team', label: { es: 'Mejorar equipo', 'pt-BR': 'Melhorar equipe' }, emoji: '👥' },
    ],
  },
  {
    id: 'G80_BIGGEST_CHALLENGE',
    category: 'objetivos',
    categoryLabel: { es: 'Objetivos', 'pt-BR': 'Objetivos' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿Cuál es tu mayor desafío ahora?', 'pt-BR': 'Qual é seu maior desafio agora?' },
    type: 'single',
    options: [
      { id: 'sales', label: { es: 'Ventas/Tráfico', 'pt-BR': 'Vendas/Tráfego' }, emoji: '📉' },
      { id: 'costs', label: { es: 'Costos altos', 'pt-BR': 'Custos altos' }, emoji: '💸' },
      { id: 'staff', label: { es: 'Personal', 'pt-BR': 'Pessoal' }, emoji: '👥' },
      { id: 'competition', label: { es: 'Competencia', 'pt-BR': 'Concorrência' }, emoji: '🏃' },
      { id: 'time', label: { es: 'Falta de tiempo', 'pt-BR': 'Falta de tempo' }, emoji: '⏰' },
      { id: 'growth', label: { es: 'Cómo crecer', 'pt-BR': 'Como crescer' }, emoji: '🚀' },
    ],
  },
  {
    id: 'G81_GOAL_90D',
    category: 'objetivos',
    categoryLabel: { es: 'Objetivos', 'pt-BR': 'Objetivos' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Meta a 90 días (una frase)', 'pt-BR': 'Meta a 90 dias (uma frase)' },
    help: { es: 'Ej: "+15% ventas" o "Abrir 2do local"', 'pt-BR': 'Ex: "+15% vendas" ou "Abrir 2ª unidade"' },
    type: 'text',
  },
  {
    id: 'G82_EXPANSION_PLANS',
    category: 'objetivos',
    categoryLabel: { es: 'Objetivos', 'pt-BR': 'Objetivos' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Tenés planes de expansión?', 'pt-BR': 'Você tem planos de expansão?' },
    type: 'single',
    options: [
      { id: 'yes_soon', label: { es: 'Sí, pronto', 'pt-BR': 'Sim, em breve' }, emoji: '🚀' },
      { id: 'yes_someday', label: { es: 'Sí, algún día', 'pt-BR': 'Sim, um dia' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No, estoy bien así', 'pt-BR': 'Não, estou bem assim' }, emoji: '✅' },
      { id: 'consolidate', label: { es: 'Quiero consolidar primero', 'pt-BR': 'Quero consolidar primeiro' }, emoji: '🎯' },
    ],
  },
  {
    id: 'G83_TIME_DEDICATION',
    category: 'objetivos',
    categoryLabel: { es: 'Objetivos', 'pt-BR': 'Objetivos' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Tiempo semanal que dedicás al negocio', 'pt-BR': 'Tempo semanal que dedica ao negócio' },
    type: 'single',
    options: [
      { id: '20-', label: { es: 'Menos de 20 horas', 'pt-BR': 'Menos de 20 horas' } },
      { id: '20-40', label: { es: '20-40 horas', 'pt-BR': '20-40 horas' } },
      { id: '40-60', label: { es: '40-60 horas', 'pt-BR': '40-60 horas' } },
      { id: '60+', label: { es: 'Más de 60 horas', 'pt-BR': 'Mais de 60 horas' } },
    ],
  },
];

// ============================================
// PREGUNTAS ESPECÍFICAS POR TIPO
// ============================================

// Preguntas específicas para Alta Cocina
const ALTA_COCINA_QUESTIONS: GastroCompleteQuestion[] = [
  {
    id: 'GA01_TASTING_MENU',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Ofrecés menú degustación?', 'pt-BR': 'Você oferece menu degustação?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.ALTA_COCINA],
    options: [
      { id: 'yes_main', label: { es: 'Sí, es el principal', 'pt-BR': 'Sim, é o principal' }, emoji: '⭐' },
      { id: 'yes_option', label: { es: 'Sí, como opción', 'pt-BR': 'Sim, como opção' }, emoji: '🍽️' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'GA02_WINE_PAIRING',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Ofrecés maridaje de vinos?', 'pt-BR': 'Você oferece harmonização de vinhos?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.ALTA_COCINA],
    options: [
      { id: 'yes', label: { es: 'Sí', 'pt-BR': 'Sim' }, emoji: '🍷' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'GA03_SOMMELIER',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: '¿Tenés sommelier?', 'pt-BR': 'Você tem sommelier?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.ALTA_COCINA],
    options: [
      { id: 'yes_full', label: { es: 'Sí, tiempo completo', 'pt-BR': 'Sim, tempo integral' }, emoji: '✅' },
      { id: 'yes_part', label: { es: 'Sí, part-time', 'pt-BR': 'Sim, meio período' }, emoji: '🔄' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
];

// Preguntas específicas para Parrilla/Asador
const PARRILLA_QUESTIONS: GastroCompleteQuestion[] = [
  {
    id: 'GP01_MEAT_SOURCE',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿De dónde traés la carne?', 'pt-BR': 'De onde você traz a carne?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.PARRILLA],
    options: [
      { id: 'butcher', label: { es: 'Carnicería de confianza', 'pt-BR': 'Açougue de confiança' }, emoji: '🥩' },
      { id: 'direct', label: { es: 'Directo del campo', 'pt-BR': 'Direto do campo' }, emoji: '🐄' },
      { id: 'distributor', label: { es: 'Distribuidor', 'pt-BR': 'Distribuidor' }, emoji: '🚚' },
      { id: 'mixed', label: { es: 'Varios', 'pt-BR': 'Vários' }, emoji: '🔄' },
    ],
  },
  {
    id: 'GP02_PARRILLA_TYPE',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Tipo de parrilla/asador', 'pt-BR': 'Tipo de churrasqueira' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.PARRILLA],
    options: [
      { id: 'wood', label: { es: 'Leña', 'pt-BR': 'Lenha' }, emoji: '🪵' },
      { id: 'charcoal', label: { es: 'Carbón', 'pt-BR': 'Carvão' }, emoji: '🔥' },
      { id: 'gas', label: { es: 'Gas', 'pt-BR': 'Gás' }, emoji: '🔵' },
      { id: 'mixed', label: { es: 'Mixto', 'pt-BR': 'Misto' }, emoji: '🔄' },
    ],
  },
];

// Preguntas específicas para Dark Kitchen
const DARK_KITCHEN_QUESTIONS: GastroCompleteQuestion[] = [
  {
    id: 'GD01_VIRTUAL_BRANDS',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'both',
    score_area: 'Crecimiento',
    title: { es: '¿Cuántas marcas virtuales operás?', 'pt-BR': 'Quantas marcas virtuais você opera?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.DARK_KITCHEN],
    options: [
      { id: '1', label: { es: '1', 'pt-BR': '1' } },
      { id: '2-3', label: { es: '2-3', 'pt-BR': '2-3' } },
      { id: '4-6', label: { es: '4-6', 'pt-BR': '4-6' } },
      { id: '6+', label: { es: 'Más de 6', 'pt-BR': 'Mais de 6' } },
    ],
  },
  {
    id: 'GD02_DELIVERY_TIME',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'both',
    score_area: 'Eficiencia',
    title: { es: 'Tiempo promedio de preparación', 'pt-BR': 'Tempo médio de preparo' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.DARK_KITCHEN],
    options: [
      { id: '10-', label: { es: 'Menos de 10 min', 'pt-BR': 'Menos de 10 min' } },
      { id: '10-15', label: { es: '10-15 min', 'pt-BR': '10-15 min' } },
      { id: '15-25', label: { es: '15-25 min', 'pt-BR': '15-25 min' } },
      { id: '25+', label: { es: 'Más de 25 min', 'pt-BR': 'Mais de 25 min' } },
    ],
  },
  {
    id: 'GD03_PACKAGING',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Cómo es tu packaging?', 'pt-BR': 'Como é sua embalagem?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.DARK_KITCHEN],
    options: [
      { id: 'premium', label: { es: 'Premium/Branded', 'pt-BR': 'Premium/Com marca' }, emoji: '✨' },
      { id: 'standard', label: { es: 'Estándar bueno', 'pt-BR': 'Padrão bom' }, emoji: '📦' },
      { id: 'basic', label: { es: 'Básico', 'pt-BR': 'Básico' }, emoji: '📋' },
    ],
  },
];

// Preguntas específicas para Cafetería
const CAFETERIA_QUESTIONS: GastroCompleteQuestion[] = [
  {
    id: 'GC01_COFFEE_TYPE',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'both',
    score_area: 'Reputación',
    title: { es: '¿Qué tipo de café ofrecés?', 'pt-BR': 'Que tipo de café você oferece?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.CAFETERIA],
    options: [
      { id: 'specialty', label: { es: 'De especialidad', 'pt-BR': 'De especialidade' }, emoji: '☕' },
      { id: 'commercial', label: { es: 'Comercial de calidad', 'pt-BR': 'Comercial de qualidade' }, emoji: '🏪' },
      { id: 'basic', label: { es: 'Estándar', 'pt-BR': 'Padrão' }, emoji: '📋' },
    ],
  },
  {
    id: 'GC02_PASTRIES_MADE',
    category: 'menu',
    categoryLabel: { es: 'Menú', 'pt-BR': 'Cardápio' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿La pastelería es producción propia?', 'pt-BR': 'A confeitaria é produção própria?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.CAFETERIA],
    options: [
      { id: 'yes_all', label: { es: 'Sí, todo', 'pt-BR': 'Sim, tudo' }, emoji: '👨‍🍳' },
      { id: 'yes_some', label: { es: 'Sí, parte', 'pt-BR': 'Sim, parte' }, emoji: '🔄' },
      { id: 'no', label: { es: 'No, comprado', 'pt-BR': 'Não, comprado' }, emoji: '📦' },
    ],
  },
  {
    id: 'GC03_WORK_FRIENDLY',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: '¿Es un lugar "work-friendly" (gente trabaja ahí)?', 'pt-BR': 'É um lugar "work-friendly" (pessoas trabalham lá)?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.CAFETERIA],
    options: [
      { id: 'yes_main', label: { es: 'Sí, es nuestro fuerte', 'pt-BR': 'Sim, é nosso forte' }, emoji: '💻' },
      { id: 'yes_some', label: { es: 'Sí, algunos', 'pt-BR': 'Sim, alguns' }, emoji: '🔄' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
];

// Preguntas específicas para Bar
const BAR_QUESTIONS: GastroCompleteQuestion[] = [
  {
    id: 'GB01_BAR_STYLE',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'both',
    score_area: 'Reputación',
    title: { es: 'Estilo del bar', 'pt-BR': 'Estilo do bar' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.BAR],
    options: [
      { id: 'cocktail', label: { es: 'Coctelería', 'pt-BR': 'Coquetelaria' }, emoji: '🍸' },
      { id: 'beer', label: { es: 'Cervecería', 'pt-BR': 'Cervejaria' }, emoji: '🍺' },
      { id: 'wine', label: { es: 'Bar de vinos', 'pt-BR': 'Bar de vinhos' }, emoji: '🍷' },
      { id: 'pub', label: { es: 'Pub/Bar casual', 'pt-BR': 'Pub/Bar casual' }, emoji: '🍻' },
      { id: 'speakeasy', label: { es: 'Speakeasy', 'pt-BR': 'Speakeasy' }, emoji: '🎩' },
    ],
  },
  {
    id: 'GB02_BARTENDERS',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: '¿Tenés bartenders profesionales?', 'pt-BR': 'Você tem bartenders profissionais?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.BAR],
    options: [
      { id: 'yes_certified', label: { es: 'Sí, certificados', 'pt-BR': 'Sim, certificados' }, emoji: '🏆' },
      { id: 'yes_experienced', label: { es: 'Sí, con experiencia', 'pt-BR': 'Sim, com experiência' }, emoji: '✅' },
      { id: 'learning', label: { es: 'Están aprendiendo', 'pt-BR': 'Estão aprendendo' }, emoji: '📚' },
    ],
  },
  {
    id: 'GB03_LIVE_MUSIC',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: '¿Tenés música en vivo o DJ?', 'pt-BR': 'Você tem música ao vivo ou DJ?' },
    type: 'single',
    businessTypes: [GASTRO_BUSINESS_TYPES.BAR],
    options: [
      { id: 'yes_regular', label: { es: 'Sí, regularmente', 'pt-BR': 'Sim, regularmente' }, emoji: '🎵' },
      { id: 'yes_sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🎤' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
];

// ============================================
// COMBINAR TODAS LAS PREGUNTAS
// ============================================

export const GASTRO_COMPLETE_QUESTIONS: GastroCompleteQuestion[] = [
  ...GASTRO_UNIVERSAL_QUESTIONS,
  ...ALTA_COCINA_QUESTIONS,
  ...PARRILLA_QUESTIONS,
  ...DARK_KITCHEN_QUESTIONS,
  ...CAFETERIA_QUESTIONS,
  ...BAR_QUESTIONS,
];

// Helper para obtener preguntas por tipo de negocio y modo
export const getGastroQuestionsForBusiness = (
  businessTypeId: string,
  mode: 'quick' | 'complete'
): GastroCompleteQuestion[] => {
  return GASTRO_COMPLETE_QUESTIONS.filter(q => {
    // Filtrar por modo
    if (q.mode !== 'both' && q.mode !== mode) return false;
    
    // Si no tiene businessTypes, aplica a todos
    if (!q.businessTypes) return true;
    
    // Verificar si el tipo está incluido
    return q.businessTypes.includes(businessTypeId);
  });
};

// Contar preguntas por modo y tipo
export const countGastroQuestions = (businessTypeId: string) => {
  const quick = getGastroQuestionsForBusiness(businessTypeId, 'quick').length;
  const complete = getGastroQuestionsForBusiness(businessTypeId, 'complete').length;
  return { quick, complete };
};
