// Retail & E-commerce - Complete 18 Business Types
// Sector A3_RETAIL - Ultra-specific questionnaires

import type { GastroQuestion } from '../gastroQuestionsEngine';

// ============= ALMACEN / TIENDA DE BARRIO =============
export const ALMACEN_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_ALMACEN_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de productos vendés principalmente?', 'pt-BR': 'Que tipo de produtos você vende principalmente?' },
    type: 'multi',
    required: true,
    businessTypes: ['almacen_tienda'],
    options: [
      { id: 'grocery', label: { es: 'Comestibles/Almacén', 'pt-BR': 'Comestíveis/Mercearia' }, emoji: '🛒', impactScore: 15 },
      { id: 'fresh', label: { es: 'Frescos (verdura, fruta)', 'pt-BR': 'Frescos (verdura, fruta)' }, emoji: '🥬', impactScore: 12 },
      { id: 'drinks', label: { es: 'Bebidas', 'pt-BR': 'Bebidas' }, emoji: '🍺', impactScore: 10 },
      { id: 'cleaning', label: { es: 'Limpieza/Hogar', 'pt-BR': 'Limpeza/Casa' }, emoji: '🧹', impactScore: 8 },
      { id: 'tobacco', label: { es: 'Cigarrillos/Tabaco', 'pt-BR': 'Cigarros/Tabaco' }, emoji: '🚬', impactScore: 8 },
      { id: 'lottery', label: { es: 'Lotería/Recargas', 'pt-BR': 'Loteria/Recargas' }, emoji: '🎰', impactScore: 8 },
    ],
  },
  {
    id: 'Q_ALMACEN_LOCATION',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Dónde está ubicado tu local?', 'pt-BR': 'Onde seu local está localizado?' },
    type: 'single',
    businessTypes: ['almacen_tienda'],
    options: [
      { id: 'residential', label: { es: 'Barrio residencial', 'pt-BR': 'Bairro residencial' }, emoji: '🏘️', impactScore: 15 },
      { id: 'commercial', label: { es: 'Zona comercial', 'pt-BR': 'Zona comercial' }, emoji: '🏢', impactScore: 12 },
      { id: 'transit', label: { es: 'Alta circulación/Tránsito', 'pt-BR': 'Alta circulação/Trânsito' }, emoji: '🚶', impactScore: 18 },
      { id: 'rural', label: { es: 'Rural/Pueblo', 'pt-BR': 'Rural/Cidade pequena' }, emoji: '🌾', impactScore: 10 },
    ],
  },
  {
    id: 'Q_ALMACEN_CLIENTS',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántos clientes atendés por día aprox?', 'pt-BR': 'Quantos clientes você atende por dia aprox?' },
    type: 'single',
    businessTypes: ['almacen_tienda'],
    options: [
      { id: '1-30', label: { es: '1-30 clientes', 'pt-BR': '1-30 clientes' }, emoji: '👤', impactScore: 8 },
      { id: '31-80', label: { es: '31-80 clientes', 'pt-BR': '31-80 clientes' }, emoji: '👥', impactScore: 12 },
      { id: '81-150', label: { es: '81-150 clientes', 'pt-BR': '81-150 clientes' }, emoji: '🏢', impactScore: 18 },
      { id: '150+', label: { es: 'Más de 150', 'pt-BR': 'Mais de 150' }, emoji: '🔥', impactScore: 22 },
    ],
  },
  {
    id: 'Q_ALMACEN_FIADO',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Vendés fiado/a cuenta?', 'pt-BR': 'Você vende fiado/na conta?' },
    type: 'single',
    businessTypes: ['almacen_tienda'],
    options: [
      { id: 'never', label: { es: 'Nunca', 'pt-BR': 'Nunca' }, emoji: '❌', impactScore: 15 },
      { id: 'rarely', label: { es: 'Rara vez', 'pt-BR': 'Raramente' }, emoji: '🤏', impactScore: 12 },
      { id: 'regular', label: { es: 'Clientes conocidos', 'pt-BR': 'Clientes conhecidos' }, emoji: '📝', impactScore: 8 },
      { id: 'frequent', label: { es: 'Es común en mi zona', 'pt-BR': 'É comum na minha área' }, emoji: '📒', impactScore: 5 },
    ],
  },
  {
    id: 'Q_ALMACEN_DELIVERY',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 6,
    title: { es: '¿Hacés delivery/envíos?', 'pt-BR': 'Você faz delivery/entregas?' },
    type: 'single',
    businessTypes: ['almacen_tienda'],
    options: [
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌', impactScore: 5 },
      { id: 'whatsapp', label: { es: 'Sí, por WhatsApp', 'pt-BR': 'Sim, por WhatsApp' }, emoji: '📱', impactScore: 12 },
      { id: 'apps', label: { es: 'Sí, apps (Rappi, PedidosYa)', 'pt-BR': 'Sim, apps (Rappi, iFood)' }, emoji: '🛵', impactScore: 15 },
      { id: 'both', label: { es: 'Ambos', 'pt-BR': 'Ambos' }, emoji: '✅', impactScore: 18 },
    ],
  },
];

// ============= SUPERMERCADO / AUTOSERVICIO =============
export const SUPERMERCADO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_SUPER_FORMAT',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué formato de supermercado sos?', 'pt-BR': 'Qual formato de supermercado você é?' },
    type: 'single',
    required: true,
    businessTypes: ['supermercado'],
    options: [
      { id: 'mini', label: { es: 'Minimarket/Express', 'pt-BR': 'Minimarket/Express' }, emoji: '🏪', impactScore: 10 },
      { id: 'super', label: { es: 'Supermercado tradicional', 'pt-BR': 'Supermercado tradicional' }, emoji: '🛒', impactScore: 15 },
      { id: 'hyper', label: { es: 'Hipermercado', 'pt-BR': 'Hipermercado' }, emoji: '🏬', impactScore: 20 },
      { id: 'discount', label: { es: 'Hard discount', 'pt-BR': 'Hard discount' }, emoji: '💰', impactScore: 12 },
      { id: 'organic', label: { es: 'Orgánico/Natural', 'pt-BR': 'Orgânico/Natural' }, emoji: '🌿', impactScore: 18 },
    ],
  },
  {
    id: 'Q_SUPER_SIZE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es el tamaño de tu local?', 'pt-BR': 'Qual é o tamanho do seu local?' },
    type: 'single',
    businessTypes: ['supermercado'],
    options: [
      { id: 'small_200', label: { es: 'Hasta 200m²', 'pt-BR': 'Até 200m²' }, emoji: '📐', impactScore: 8 },
      { id: 'medium_500', label: { es: '200-500m²', 'pt-BR': '200-500m²' }, emoji: '🏪', impactScore: 12 },
      { id: 'large_1500', label: { es: '500-1500m²', 'pt-BR': '500-1500m²' }, emoji: '🏢', impactScore: 18 },
      { id: 'hyper', label: { es: 'Más de 1500m²', 'pt-BR': 'Mais de 1500m²' }, emoji: '🏬', impactScore: 22 },
    ],
  },
  {
    id: 'Q_SUPER_CHECKOUTS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántas cajas/checkouts tenés?', 'pt-BR': 'Quantos caixas/checkouts você tem?' },
    type: 'single',
    businessTypes: ['supermercado'],
    options: [
      { id: '1-3', label: { es: '1-3 cajas', 'pt-BR': '1-3 caixas' }, emoji: '💳', impactScore: 8 },
      { id: '4-8', label: { es: '4-8 cajas', 'pt-BR': '4-8 caixas' }, emoji: '🛒', impactScore: 12 },
      { id: '9-15', label: { es: '9-15 cajas', 'pt-BR': '9-15 caixas' }, emoji: '🏢', impactScore: 18 },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '🏬', impactScore: 22 },
    ],
  },
  {
    id: 'Q_SUPER_FRESH',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué secciones de frescos tenés?', 'pt-BR': 'Quais seções de frescos você tem?' },
    type: 'multi',
    businessTypes: ['supermercado'],
    options: [
      { id: 'meat', label: { es: 'Carnicería', 'pt-BR': 'Açougue' }, emoji: '🥩', impactScore: 15 },
      { id: 'fish', label: { es: 'Pescadería', 'pt-BR': 'Peixaria' }, emoji: '🐟', impactScore: 12 },
      { id: 'deli', label: { es: 'Fiambrería/Deli', 'pt-BR': 'Frios/Deli' }, emoji: '🧀', impactScore: 12 },
      { id: 'bakery', label: { es: 'Panadería', 'pt-BR': 'Padaria' }, emoji: '🥖', impactScore: 12 },
      { id: 'produce', label: { es: 'Verdulería/Frutas', 'pt-BR': 'Hortifruti' }, emoji: '🥬', impactScore: 12 },
      { id: 'prepared', label: { es: 'Comida preparada', 'pt-BR': 'Comida preparada' }, emoji: '🍱', impactScore: 15 },
    ],
  },
  {
    id: 'Q_SUPER_ECOMMERCE',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Tenés venta online?', 'pt-BR': 'Você tem venda online?' },
    type: 'single',
    businessTypes: ['supermercado'],
    options: [
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌', impactScore: 5 },
      { id: 'whatsapp', label: { es: 'Solo WhatsApp', 'pt-BR': 'Só WhatsApp' }, emoji: '📱', impactScore: 10 },
      { id: 'apps', label: { es: 'Apps de delivery', 'pt-BR': 'Apps de delivery' }, emoji: '🛵', impactScore: 12 },
      { id: 'own', label: { es: 'Tienda online propia', 'pt-BR': 'Loja online própria' }, emoji: '🌐', impactScore: 18 },
      { id: 'full', label: { es: 'Omnicanal completo', 'pt-BR': 'Omnicanal completo' }, emoji: '✅', impactScore: 22 },
    ],
  },
];

// ============= MODA Y ACCESORIOS =============
export const MODA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_MODA_SEGMENT',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué segmento de moda vendés?', 'pt-BR': 'Qual segmento de moda você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['moda_accesorios'],
    options: [
      { id: 'women', label: { es: 'Mujer', 'pt-BR': 'Feminino' }, emoji: '👗', impactScore: 15 },
      { id: 'men', label: { es: 'Hombre', 'pt-BR': 'Masculino' }, emoji: '👔', impactScore: 12 },
      { id: 'kids', label: { es: 'Niños/Bebés', 'pt-BR': 'Infantil/Bebê' }, emoji: '👶', impactScore: 12 },
      { id: 'urban', label: { es: 'Urbano/Streetwear', 'pt-BR': 'Urbano/Streetwear' }, emoji: '🧢', impactScore: 15 },
      { id: 'formal', label: { es: 'Formal/Ejecutivo', 'pt-BR': 'Formal/Executivo' }, emoji: '👨‍💼', impactScore: 12 },
      { id: 'sport', label: { es: 'Deportivo/Fitness', 'pt-BR': 'Esportivo/Fitness' }, emoji: '🏃', impactScore: 12 },
    ],
  },
  {
    id: 'Q_MODA_PRICE_POINT',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu rango de precios?', 'pt-BR': 'Qual é sua faixa de preço?' },
    type: 'single',
    businessTypes: ['moda_accesorios'],
    options: [
      { id: 'budget', label: { es: 'Económico/Popular', 'pt-BR': 'Econômico/Popular' }, emoji: '💰', impactScore: 10 },
      { id: 'mid', label: { es: 'Precio medio', 'pt-BR': 'Preço médio' }, emoji: '💵', impactScore: 12 },
      { id: 'premium', label: { es: 'Premium', 'pt-BR': 'Premium' }, emoji: '✨', impactScore: 18 },
      { id: 'luxury', label: { es: 'Lujo', 'pt-BR': 'Luxo' }, emoji: '💎', impactScore: 22 },
    ],
  },
  {
    id: 'Q_MODA_SOURCE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿De dónde proviene tu mercadería?', 'pt-BR': 'De onde vem sua mercadoria?' },
    type: 'multi',
    businessTypes: ['moda_accesorios'],
    options: [
      { id: 'local_brands', label: { es: 'Marcas locales', 'pt-BR': 'Marcas locais' }, emoji: '🏠', impactScore: 12 },
      { id: 'own_brand', label: { es: 'Marca propia', 'pt-BR': 'Marca própria' }, emoji: '🏷️', impactScore: 18 },
      { id: 'import', label: { es: 'Importación', 'pt-BR': 'Importação' }, emoji: '🌍', impactScore: 12 },
      { id: 'franchise', label: { es: 'Franquicia', 'pt-BR': 'Franquia' }, emoji: '🤝', impactScore: 10 },
      { id: 'multi_brand', label: { es: 'Multimarca', 'pt-BR': 'Multimarca' }, emoji: '🛍️', impactScore: 15 },
    ],
  },
  {
    id: 'Q_MODA_CHANNELS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Dónde vendés?', 'pt-BR': 'Onde você vende?' },
    type: 'multi',
    businessTypes: ['moda_accesorios'],
    options: [
      { id: 'store', label: { es: 'Tienda física', 'pt-BR': 'Loja física' }, emoji: '🏪', impactScore: 12 },
      { id: 'mall', label: { es: 'Shopping/Mall', 'pt-BR': 'Shopping/Mall' }, emoji: '🏬', impactScore: 15 },
      { id: 'ecommerce', label: { es: 'E-commerce propio', 'pt-BR': 'E-commerce próprio' }, emoji: '🌐', impactScore: 18 },
      { id: 'marketplaces', label: { es: 'Marketplaces', 'pt-BR': 'Marketplaces' }, emoji: '📦', impactScore: 12 },
      { id: 'social', label: { es: 'Redes sociales', 'pt-BR': 'Redes sociais' }, emoji: '📱', impactScore: 12 },
      { id: 'showroom', label: { es: 'Showroom', 'pt-BR': 'Showroom' }, emoji: '🪟', impactScore: 10 },
    ],
  },
  {
    id: 'Q_MODA_SEASONS',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo manejás las temporadas?', 'pt-BR': 'Como você gerencia as temporadas?' },
    type: 'single',
    businessTypes: ['moda_accesorios'],
    options: [
      { id: 'two_seasons', label: { es: '2 temporadas (P/V, O/I)', 'pt-BR': '2 temporadas (P/V, O/I)' }, emoji: '📅', impactScore: 15 },
      { id: 'four_seasons', label: { es: '4 temporadas o más', 'pt-BR': '4 temporadas ou mais' }, emoji: '🗓️', impactScore: 18 },
      { id: 'continuous', label: { es: 'Colección continua', 'pt-BR': 'Coleção contínua' }, emoji: '🔄', impactScore: 12 },
      { id: 'basic', label: { es: 'Básicos atemporales', 'pt-BR': 'Básicos atemporais' }, emoji: '👕', impactScore: 10 },
    ],
  },
];

// ============= CALZADO Y MARROQUINERIA =============
export const CALZADO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_CALZADO_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de calzado/productos vendés?', 'pt-BR': 'Que tipo de calçado/produtos você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['calzado_marroquineria'],
    options: [
      { id: 'casual', label: { es: 'Calzado casual', 'pt-BR': 'Calçado casual' }, emoji: '👟', impactScore: 12 },
      { id: 'formal', label: { es: 'Calzado formal', 'pt-BR': 'Calçado formal' }, emoji: '👞', impactScore: 12 },
      { id: 'sports', label: { es: 'Deportivo/Sneakers', 'pt-BR': 'Esportivo/Sneakers' }, emoji: '🏃', impactScore: 15 },
      { id: 'bags', label: { es: 'Bolsos/Carteras', 'pt-BR': 'Bolsas/Carteiras' }, emoji: '👜', impactScore: 12 },
      { id: 'leather', label: { es: 'Marroquinería fina', 'pt-BR': 'Couro fino' }, emoji: '🧳', impactScore: 15 },
      { id: 'accessories', label: { es: 'Accesorios (cintos, etc)', 'pt-BR': 'Acessórios (cintos, etc)' }, emoji: '🎀', impactScore: 10 },
    ],
  },
  {
    id: 'Q_CALZADO_SEGMENT',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Para quién son tus productos?', 'pt-BR': 'Para quem são seus produtos?' },
    type: 'multi',
    businessTypes: ['calzado_marroquineria'],
    options: [
      { id: 'women', label: { es: 'Mujer', 'pt-BR': 'Feminino' }, emoji: '👠', impactScore: 15 },
      { id: 'men', label: { es: 'Hombre', 'pt-BR': 'Masculino' }, emoji: '👞', impactScore: 12 },
      { id: 'kids', label: { es: 'Niños', 'pt-BR': 'Infantil' }, emoji: '👶', impactScore: 12 },
      { id: 'unisex', label: { es: 'Unisex', 'pt-BR': 'Unissex' }, emoji: '👟', impactScore: 12 },
    ],
  },
  {
    id: 'Q_CALZADO_ORIGIN',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuál es el origen de tus productos?', 'pt-BR': 'Qual é a origem dos seus produtos?' },
    type: 'single',
    businessTypes: ['calzado_marroquineria'],
    options: [
      { id: 'own', label: { es: 'Producción propia', 'pt-BR': 'Produção própria' }, emoji: '🏭', impactScore: 20 },
      { id: 'national', label: { es: 'Marcas nacionales', 'pt-BR': 'Marcas nacionais' }, emoji: '🏠', impactScore: 12 },
      { id: 'import', label: { es: 'Importación', 'pt-BR': 'Importação' }, emoji: '🌍', impactScore: 15 },
      { id: 'mix', label: { es: 'Mix de orígenes', 'pt-BR': 'Mix de origens' }, emoji: '🔄', impactScore: 12 },
    ],
  },
  {
    id: 'Q_CALZADO_PRICE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu rango de precios principal?', 'pt-BR': 'Qual é sua faixa de preço principal?' },
    type: 'single',
    businessTypes: ['calzado_marroquineria'],
    options: [
      { id: 'economic', label: { es: 'Económico', 'pt-BR': 'Econômico' }, emoji: '💰', impactScore: 10 },
      { id: 'mid', label: { es: 'Precio medio', 'pt-BR': 'Preço médio' }, emoji: '💵', impactScore: 12 },
      { id: 'premium', label: { es: 'Premium', 'pt-BR': 'Premium' }, emoji: '✨', impactScore: 18 },
      { id: 'luxury', label: { es: 'Lujo/Diseñador', 'pt-BR': 'Luxo/Designer' }, emoji: '💎', impactScore: 22 },
    ],
  },
  {
    id: 'Q_CALZADO_INVENTORY',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo manejás el stock de talles?', 'pt-BR': 'Como você gerencia o estoque de tamanhos?' },
    type: 'single',
    businessTypes: ['calzado_marroquineria'],
    options: [
      { id: 'full_range', label: { es: 'Rango completo siempre', 'pt-BR': 'Faixa completa sempre' }, emoji: '✅', impactScore: 18 },
      { id: 'common', label: { es: 'Solo talles comunes', 'pt-BR': 'Só tamanhos comuns' }, emoji: '📊', impactScore: 12 },
      { id: 'on_demand', label: { es: 'Pedido sobre demanda', 'pt-BR': 'Pedido sob demanda' }, emoji: '📦', impactScore: 10 },
      { id: 'limited', label: { es: 'Stock limitado', 'pt-BR': 'Estoque limitado' }, emoji: '⚡', impactScore: 8 },
    ],
  },
];

// ============= HOGAR Y DECORACION =============
export const HOGAR_DECO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_HOGAR_CATEGORY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué categorías vendés?', 'pt-BR': 'Quais categorias você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['hogar_decoracion'],
    options: [
      { id: 'furniture', label: { es: 'Muebles', 'pt-BR': 'Móveis' }, emoji: '🛋️', impactScore: 18 },
      { id: 'decoration', label: { es: 'Decoración', 'pt-BR': 'Decoração' }, emoji: '🖼️', impactScore: 15 },
      { id: 'textiles', label: { es: 'Textiles/Blancos', 'pt-BR': 'Têxteis/Cama e mesa' }, emoji: '🛏️', impactScore: 12 },
      { id: 'kitchen', label: { es: 'Cocina/Mesa', 'pt-BR': 'Cozinha/Mesa' }, emoji: '🍽️', impactScore: 12 },
      { id: 'lighting', label: { es: 'Iluminación', 'pt-BR': 'Iluminação' }, emoji: '💡', impactScore: 12 },
      { id: 'outdoor', label: { es: 'Exterior/Jardín', 'pt-BR': 'Exterior/Jardim' }, emoji: '🌿', impactScore: 10 },
    ],
  },
  {
    id: 'Q_HOGAR_STYLE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué estilo predomina?', 'pt-BR': 'Qual estilo predomina?' },
    type: 'single',
    businessTypes: ['hogar_decoracion'],
    options: [
      { id: 'modern', label: { es: 'Moderno/Minimalista', 'pt-BR': 'Moderno/Minimalista' }, emoji: '🏢', impactScore: 15 },
      { id: 'classic', label: { es: 'Clásico/Tradicional', 'pt-BR': 'Clássico/Tradicional' }, emoji: '🏛️', impactScore: 12 },
      { id: 'nordic', label: { es: 'Nórdico/Escandinavo', 'pt-BR': 'Nórdico/Escandinavo' }, emoji: '🌲', impactScore: 18 },
      { id: 'industrial', label: { es: 'Industrial/Loft', 'pt-BR': 'Industrial/Loft' }, emoji: '🏭', impactScore: 12 },
      { id: 'bohemian', label: { es: 'Bohemio/Étnico', 'pt-BR': 'Boêmio/Étnico' }, emoji: '🎨', impactScore: 12 },
      { id: 'eclectic', label: { es: 'Ecléctico/Variado', 'pt-BR': 'Eclético/Variado' }, emoji: '🔀', impactScore: 10 },
    ],
  },
  {
    id: 'Q_HOGAR_PRICE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu posicionamiento de precio?', 'pt-BR': 'Qual é seu posicionamento de preço?' },
    type: 'single',
    businessTypes: ['hogar_decoracion'],
    options: [
      { id: 'economic', label: { es: 'Económico/Popular', 'pt-BR': 'Econômico/Popular' }, emoji: '💰', impactScore: 10 },
      { id: 'mid', label: { es: 'Precio medio', 'pt-BR': 'Preço médio' }, emoji: '💵', impactScore: 12 },
      { id: 'design', label: { es: 'Diseño accesible', 'pt-BR': 'Design acessível' }, emoji: '✨', impactScore: 18 },
      { id: 'premium', label: { es: 'Premium/Lujo', 'pt-BR': 'Premium/Luxo' }, emoji: '💎', impactScore: 20 },
    ],
  },
  {
    id: 'Q_HOGAR_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué servicios adicionales ofrecés?', 'pt-BR': 'Quais serviços adicionais você oferece?' },
    type: 'multi',
    businessTypes: ['hogar_decoracion'],
    options: [
      { id: 'delivery', label: { es: 'Entrega a domicilio', 'pt-BR': 'Entrega a domicílio' }, emoji: '🚚', impactScore: 12 },
      { id: 'assembly', label: { es: 'Armado/Instalación', 'pt-BR': 'Montagem/Instalação' }, emoji: '🔧', impactScore: 15 },
      { id: 'design', label: { es: 'Asesoramiento de diseño', 'pt-BR': 'Assessoria de design' }, emoji: '🎨', impactScore: 18 },
      { id: 'custom', label: { es: 'Productos a medida', 'pt-BR': 'Produtos sob medida' }, emoji: '📐', impactScore: 18 },
      { id: 'financing', label: { es: 'Financiación', 'pt-BR': 'Financiamento' }, emoji: '💳', impactScore: 12 },
    ],
  },
];

// ============= ELECTRONICA Y TECNOLOGIA =============
export const ELECTRONICA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_ELEC_CATEGORIES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué categorías vendés?', 'pt-BR': 'Quais categorias você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['electronica_tech'],
    options: [
      { id: 'phones', label: { es: 'Celulares/Smartphones', 'pt-BR': 'Celulares/Smartphones' }, emoji: '📱', impactScore: 18 },
      { id: 'computers', label: { es: 'Computadoras/Laptops', 'pt-BR': 'Computadores/Laptops' }, emoji: '💻', impactScore: 15 },
      { id: 'tv', label: { es: 'TV/Audio', 'pt-BR': 'TV/Áudio' }, emoji: '📺', impactScore: 12 },
      { id: 'gaming', label: { es: 'Gaming/Consolas', 'pt-BR': 'Gaming/Consoles' }, emoji: '🎮', impactScore: 15 },
      { id: 'accessories', label: { es: 'Accesorios', 'pt-BR': 'Acessórios' }, emoji: '🎧', impactScore: 12 },
      { id: 'appliances', label: { es: 'Electrodomésticos', 'pt-BR': 'Eletrodomésticos' }, emoji: '🏠', impactScore: 12 },
    ],
  },
  {
    id: 'Q_ELEC_NEW_USED',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Vendés productos nuevos o usados?', 'pt-BR': 'Você vende produtos novos ou usados?' },
    type: 'single',
    businessTypes: ['electronica_tech'],
    options: [
      { id: 'new', label: { es: 'Solo nuevos', 'pt-BR': 'Só novos' }, emoji: '✨', impactScore: 15 },
      { id: 'refurbished', label: { es: 'Reacondicionados', 'pt-BR': 'Recondicionados' }, emoji: '🔄', impactScore: 12 },
      { id: 'used', label: { es: 'Usados', 'pt-BR': 'Usados' }, emoji: '📦', impactScore: 10 },
      { id: 'mix', label: { es: 'Mix de todo', 'pt-BR': 'Mix de tudo' }, emoji: '🔀', impactScore: 12 },
    ],
  },
  {
    id: 'Q_ELEC_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['electronica_tech'],
    options: [
      { id: 'repair', label: { es: 'Reparación', 'pt-BR': 'Reparo' }, emoji: '🔧', impactScore: 15 },
      { id: 'unlock', label: { es: 'Liberación/Unlock', 'pt-BR': 'Desbloqueio' }, emoji: '🔓', impactScore: 10 },
      { id: 'setup', label: { es: 'Configuración', 'pt-BR': 'Configuração' }, emoji: '⚙️', impactScore: 10 },
      { id: 'warranty', label: { es: 'Garantía extendida', 'pt-BR': 'Garantia estendida' }, emoji: '🛡️', impactScore: 12 },
      { id: 'trade_in', label: { es: 'Trade-in/Canje', 'pt-BR': 'Trade-in/Troca' }, emoji: '🔄', impactScore: 15 },
    ],
  },
  {
    id: 'Q_ELEC_CHANNELS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Dónde vendés?', 'pt-BR': 'Onde você vende?' },
    type: 'multi',
    businessTypes: ['electronica_tech'],
    options: [
      { id: 'store', label: { es: 'Tienda física', 'pt-BR': 'Loja física' }, emoji: '🏪', impactScore: 12 },
      { id: 'ecommerce', label: { es: 'E-commerce propio', 'pt-BR': 'E-commerce próprio' }, emoji: '🌐', impactScore: 18 },
      { id: 'ml', label: { es: 'MercadoLibre', 'pt-BR': 'Mercado Livre' }, emoji: '🛒', impactScore: 15 },
      { id: 'amazon', label: { es: 'Amazon', 'pt-BR': 'Amazon' }, emoji: '📦', impactScore: 12 },
      { id: 'social', label: { es: 'Redes sociales', 'pt-BR': 'Redes sociais' }, emoji: '📱', impactScore: 10 },
    ],
  },
];

// ============= FERRETERIA / HERRAMIENTAS =============
export const FERRETERIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_FERR_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de ferretería sos?', 'pt-BR': 'Que tipo de ferragem você é?' },
    type: 'single',
    required: true,
    businessTypes: ['ferreteria'],
    options: [
      { id: 'neighborhood', label: { es: 'Ferretería de barrio', 'pt-BR': 'Ferragem de bairro' }, emoji: '🏪', impactScore: 12 },
      { id: 'industrial', label: { es: 'Ferretería industrial', 'pt-BR': 'Ferragem industrial' }, emoji: '🏭', impactScore: 18 },
      { id: 'construction', label: { es: 'Materiales de construcción', 'pt-BR': 'Materiais de construção' }, emoji: '🧱', impactScore: 15 },
      { id: 'electrical', label: { es: 'Especializada en eléctrica', 'pt-BR': 'Especializada em elétrica' }, emoji: '⚡', impactScore: 15 },
      { id: 'plumbing', label: { es: 'Especializada en plomería', 'pt-BR': 'Especializada em hidráulica' }, emoji: '🚰', impactScore: 15 },
      { id: 'general', label: { es: 'General/Multirrubro', 'pt-BR': 'Geral/Multirramo' }, emoji: '🔧', impactScore: 12 },
    ],
  },
  {
    id: 'Q_FERR_CLIENTS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Quiénes son tus clientes principales?', 'pt-BR': 'Quem são seus principais clientes?' },
    type: 'multi',
    businessTypes: ['ferreteria'],
    options: [
      { id: 'diy', label: { es: 'Particulares/DIY', 'pt-BR': 'Particulares/DIY' }, emoji: '🏠', impactScore: 12 },
      { id: 'professionals', label: { es: 'Profesionales (plomeros, etc)', 'pt-BR': 'Profissionais (encanadores, etc)' }, emoji: '👷', impactScore: 15 },
      { id: 'contractors', label: { es: 'Contratistas/Constructoras', 'pt-BR': 'Empreiteiros/Construtoras' }, emoji: '🏗️', impactScore: 18 },
      { id: 'industry', label: { es: 'Industria', 'pt-BR': 'Indústria' }, emoji: '🏭', impactScore: 15 },
    ],
  },
  {
    id: 'Q_FERR_PRODUCTS',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué categorías de productos vendés?', 'pt-BR': 'Quais categorias de produtos você vende?' },
    type: 'multi',
    businessTypes: ['ferreteria'],
    options: [
      { id: 'tools', label: { es: 'Herramientas manuales', 'pt-BR': 'Ferramentas manuais' }, emoji: '🔧', impactScore: 12 },
      { id: 'power_tools', label: { es: 'Herramientas eléctricas', 'pt-BR': 'Ferramentas elétricas' }, emoji: '🔌', impactScore: 15 },
      { id: 'electrical', label: { es: 'Material eléctrico', 'pt-BR': 'Material elétrico' }, emoji: '💡', impactScore: 12 },
      { id: 'plumbing', label: { es: 'Plomería/Sanitarios', 'pt-BR': 'Hidráulica/Sanitários' }, emoji: '🚿', impactScore: 12 },
      { id: 'paint', label: { es: 'Pinturas/Químicos', 'pt-BR': 'Tintas/Químicos' }, emoji: '🎨', impactScore: 12 },
      { id: 'security', label: { es: 'Cerrajería/Seguridad', 'pt-BR': 'Fechaduras/Segurança' }, emoji: '🔐', impactScore: 12 },
    ],
  },
  {
    id: 'Q_FERR_CREDIT',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Ofrecés cuenta corriente/crédito?', 'pt-BR': 'Você oferece conta corrente/crédito?' },
    type: 'single',
    businessTypes: ['ferreteria'],
    options: [
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌', impactScore: 10 },
      { id: 'selected', label: { es: 'Solo a clientes seleccionados', 'pt-BR': 'Só para clientes selecionados' }, emoji: '⭐', impactScore: 15 },
      { id: 'regular', label: { es: 'Sí, es común', 'pt-BR': 'Sim, é comum' }, emoji: '📝', impactScore: 12 },
      { id: 'cards', label: { es: 'Solo con tarjetas', 'pt-BR': 'Só com cartões' }, emoji: '💳', impactScore: 12 },
    ],
  },
];

// Continue with remaining 11 retail types...
// ============= LIBRERIA / PAPELERIA =============
export const LIBRERIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_LIB_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de librería sos?', 'pt-BR': 'Que tipo de papelaria você é?' },
    type: 'single',
    required: true,
    businessTypes: ['libreria_papeleria'],
    options: [
      { id: 'school', label: { es: 'Escolar/Papelería', 'pt-BR': 'Escolar/Papelaria' }, emoji: '📚', impactScore: 15 },
      { id: 'office', label: { es: 'Oficina/Corporativo', 'pt-BR': 'Escritório/Corporativo' }, emoji: '🏢', impactScore: 15 },
      { id: 'art', label: { es: 'Artística/Manualidades', 'pt-BR': 'Artística/Artesanato' }, emoji: '🎨', impactScore: 18 },
      { id: 'books', label: { es: 'Librería con libros', 'pt-BR': 'Livraria com livros' }, emoji: '📖', impactScore: 15 },
      { id: 'gifts', label: { es: 'Regalería/Fantasía', 'pt-BR': 'Presentes/Fantasia' }, emoji: '🎁', impactScore: 12 },
      { id: 'general', label: { es: 'General/Mixto', 'pt-BR': 'Geral/Misto' }, emoji: '📝', impactScore: 10 },
    ],
  },
  {
    id: 'Q_LIB_SEASONALITY',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuánto peso tiene la temporada escolar?', 'pt-BR': 'Quanto peso tem a temporada escolar?' },
    type: 'single',
    businessTypes: ['libreria_papeleria'],
    options: [
      { id: 'high_60', label: { es: '+60% de ventas anuales', 'pt-BR': '+60% das vendas anuais' }, emoji: '📊', impactScore: 18 },
      { id: 'mid_40', label: { es: '40-60% de ventas', 'pt-BR': '40-60% das vendas' }, emoji: '📈', impactScore: 15 },
      { id: 'low_20', label: { es: '20-40% de ventas', 'pt-BR': '20-40% das vendas' }, emoji: '📉', impactScore: 12 },
      { id: 'minimal', label: { es: 'Menos del 20%', 'pt-BR': 'Menos de 20%' }, emoji: '➖', impactScore: 8 },
    ],
  },
  {
    id: 'Q_LIB_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué servicios adicionales ofrecés?', 'pt-BR': 'Quais serviços adicionais você oferece?' },
    type: 'multi',
    businessTypes: ['libreria_papeleria'],
    options: [
      { id: 'copies', label: { es: 'Fotocopias/Impresiones', 'pt-BR': 'Fotocópias/Impressões' }, emoji: '🖨️', impactScore: 12 },
      { id: 'binding', label: { es: 'Encuadernado/Anillado', 'pt-BR': 'Encadernação' }, emoji: '📒', impactScore: 10 },
      { id: 'stamps', label: { es: 'Sellos/Timbres', 'pt-BR': 'Carimbos' }, emoji: '📬', impactScore: 8 },
      { id: 'laminating', label: { es: 'Plastificado', 'pt-BR': 'Plastificação' }, emoji: '📄', impactScore: 8 },
      { id: 'custom', label: { es: 'Personalización/Grabado', 'pt-BR': 'Personalização/Gravação' }, emoji: '✨', impactScore: 12 },
    ],
  },
];

// ============= JUGUETERIA Y HOBBIES =============
export const JUGUETERIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_TOY_FOCUS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿En qué te especializás?', 'pt-BR': 'Em que você se especializa?' },
    type: 'multi',
    required: true,
    businessTypes: ['jugueteria_hobbies'],
    options: [
      { id: 'traditional', label: { es: 'Juguetes tradicionales', 'pt-BR': 'Brinquedos tradicionais' }, emoji: '🧸', impactScore: 12 },
      { id: 'educational', label: { es: 'Didácticos/Educativos', 'pt-BR': 'Didáticos/Educativos' }, emoji: '🎓', impactScore: 15 },
      { id: 'collectibles', label: { es: 'Coleccionables/Figuras', 'pt-BR': 'Colecionáveis/Figuras' }, emoji: '🎭', impactScore: 18 },
      { id: 'board_games', label: { es: 'Juegos de mesa', 'pt-BR': 'Jogos de tabuleiro' }, emoji: '🎲', impactScore: 15 },
      { id: 'video_games', label: { es: 'Videojuegos', 'pt-BR': 'Videogames' }, emoji: '🎮', impactScore: 15 },
      { id: 'models', label: { es: 'Modelismo/Maquetas', 'pt-BR': 'Modelismo/Maquetes' }, emoji: '✈️', impactScore: 12 },
    ],
  },
  {
    id: 'Q_TOY_AGE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Qué rango de edad es tu fuerte?', 'pt-BR': 'Qual faixa etária é seu forte?' },
    type: 'multi',
    businessTypes: ['jugueteria_hobbies'],
    options: [
      { id: 'baby', label: { es: 'Bebés (0-2)', 'pt-BR': 'Bebês (0-2)' }, emoji: '👶', impactScore: 12 },
      { id: 'preschool', label: { es: 'Preescolar (3-5)', 'pt-BR': 'Pré-escolar (3-5)' }, emoji: '🧒', impactScore: 12 },
      { id: 'kids', label: { es: 'Niños (6-12)', 'pt-BR': 'Crianças (6-12)' }, emoji: '👦', impactScore: 15 },
      { id: 'teens', label: { es: 'Adolescentes', 'pt-BR': 'Adolescentes' }, emoji: '🧑', impactScore: 12 },
      { id: 'adults', label: { es: 'Adultos/Coleccionistas', 'pt-BR': 'Adultos/Colecionadores' }, emoji: '👨', impactScore: 18 },
    ],
  },
  {
    id: 'Q_TOY_BRANDS',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Trabajás con marcas oficiales?', 'pt-BR': 'Você trabalha com marcas oficiais?' },
    type: 'single',
    businessTypes: ['jugueteria_hobbies'],
    options: [
      { id: 'official', label: { es: 'Solo marcas oficiales', 'pt-BR': 'Só marcas oficiais' }, emoji: '✅', impactScore: 18 },
      { id: 'mix', label: { es: 'Mix oficial + genérico', 'pt-BR': 'Mix oficial + genérico' }, emoji: '🔀', impactScore: 12 },
      { id: 'generic', label: { es: 'Mayormente genérico', 'pt-BR': 'Maiormente genérico' }, emoji: '📦', impactScore: 8 },
      { id: 'exclusive', label: { es: 'Exclusividades/Importados', 'pt-BR': 'Exclusivos/Importados' }, emoji: '💎', impactScore: 20 },
    ],
  },
];

// ============= DEPORTES Y OUTDOOR =============
export const DEPORTES_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_SPORT_FOCUS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿En qué deportes te especializás?', 'pt-BR': 'Em quais esportes você se especializa?' },
    type: 'multi',
    required: true,
    businessTypes: ['deportes_outdoor'],
    options: [
      { id: 'running', label: { es: 'Running/Atletismo', 'pt-BR': 'Running/Atletismo' }, emoji: '🏃', impactScore: 15 },
      { id: 'football', label: { es: 'Fútbol', 'pt-BR': 'Futebol' }, emoji: '⚽', impactScore: 15 },
      { id: 'gym', label: { es: 'Fitness/Gym', 'pt-BR': 'Fitness/Academia' }, emoji: '🏋️', impactScore: 15 },
      { id: 'outdoor', label: { es: 'Outdoor/Camping', 'pt-BR': 'Outdoor/Camping' }, emoji: '🏕️', impactScore: 18 },
      { id: 'cycling', label: { es: 'Ciclismo', 'pt-BR': 'Ciclismo' }, emoji: '🚴', impactScore: 15 },
      { id: 'water', label: { es: 'Acuáticos', 'pt-BR': 'Aquáticos' }, emoji: '🏊', impactScore: 12 },
      { id: 'winter', label: { es: 'Invierno/Nieve', 'pt-BR': 'Inverno/Neve' }, emoji: '⛷️', impactScore: 15 },
    ],
  },
  {
    id: 'Q_SPORT_PRODUCTS',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué tipo de productos vendés?', 'pt-BR': 'Que tipo de produtos você vende?' },
    type: 'multi',
    businessTypes: ['deportes_outdoor'],
    options: [
      { id: 'apparel', label: { es: 'Indumentaria', 'pt-BR': 'Vestuário' }, emoji: '👕', impactScore: 15 },
      { id: 'footwear', label: { es: 'Calzado', 'pt-BR': 'Calçados' }, emoji: '👟', impactScore: 15 },
      { id: 'equipment', label: { es: 'Equipamiento', 'pt-BR': 'Equipamentos' }, emoji: '🎾', impactScore: 15 },
      { id: 'accessories', label: { es: 'Accesorios', 'pt-BR': 'Acessórios' }, emoji: '🧢', impactScore: 10 },
      { id: 'nutrition', label: { es: 'Suplementos/Nutrición', 'pt-BR': 'Suplementos/Nutrição' }, emoji: '💪', impactScore: 12 },
    ],
  },
  {
    id: 'Q_SPORT_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué servicios adicionales ofrecés?', 'pt-BR': 'Quais serviços adicionais você oferece?' },
    type: 'multi',
    businessTypes: ['deportes_outdoor'],
    options: [
      { id: 'rental', label: { es: 'Alquiler de equipos', 'pt-BR': 'Aluguel de equipamentos' }, emoji: '🔄', impactScore: 15 },
      { id: 'repair', label: { es: 'Reparación/Service', 'pt-BR': 'Reparo/Service' }, emoji: '🔧', impactScore: 12 },
      { id: 'custom', label: { es: 'Personalización', 'pt-BR': 'Personalização' }, emoji: '✨', impactScore: 12 },
      { id: 'events', label: { es: 'Organización de eventos', 'pt-BR': 'Organização de eventos' }, emoji: '🎪', impactScore: 15 },
    ],
  },
];

// ============= BELLEZA Y PERFUMERIA =============
export const BELLEZA_PERFUMERIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_BEAUTY_FOCUS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿En qué te especializás?', 'pt-BR': 'Em que você se especializa?' },
    type: 'multi',
    required: true,
    businessTypes: ['belleza_perfumeria'],
    options: [
      { id: 'makeup', label: { es: 'Maquillaje', 'pt-BR': 'Maquiagem' }, emoji: '💄', impactScore: 15 },
      { id: 'skincare', label: { es: 'Skincare', 'pt-BR': 'Skincare' }, emoji: '🧴', impactScore: 18 },
      { id: 'perfume', label: { es: 'Perfumería', 'pt-BR': 'Perfumaria' }, emoji: '🌸', impactScore: 15 },
      { id: 'hair', label: { es: 'Cabello', 'pt-BR': 'Cabelo' }, emoji: '💇', impactScore: 12 },
      { id: 'nails', label: { es: 'Uñas', 'pt-BR': 'Unhas' }, emoji: '💅', impactScore: 12 },
      { id: 'professional', label: { es: 'Productos profesionales', 'pt-BR': 'Produtos profissionais' }, emoji: '🏆', impactScore: 18 },
    ],
  },
  {
    id: 'Q_BEAUTY_SEGMENT',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu segmento de precio?', 'pt-BR': 'Qual é seu segmento de preço?' },
    type: 'single',
    businessTypes: ['belleza_perfumeria'],
    options: [
      { id: 'mass', label: { es: 'Masivo/Drugstore', 'pt-BR': 'Massivo/Farmácia' }, emoji: '💰', impactScore: 10 },
      { id: 'mid', label: { es: 'Gama media', 'pt-BR': 'Gama média' }, emoji: '💵', impactScore: 12 },
      { id: 'prestige', label: { es: 'Prestige/Premium', 'pt-BR': 'Prestige/Premium' }, emoji: '✨', impactScore: 18 },
      { id: 'luxury', label: { es: 'Lujo', 'pt-BR': 'Luxo' }, emoji: '💎', impactScore: 22 },
      { id: 'organic', label: { es: 'Natural/Orgánico', 'pt-BR': 'Natural/Orgânico' }, emoji: '🌿', impactScore: 18 },
    ],
  },
  {
    id: 'Q_BEAUTY_BRANDS',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué tipo de marcas trabajás?', 'pt-BR': 'Que tipo de marcas você trabalha?' },
    type: 'single',
    businessTypes: ['belleza_perfumeria'],
    options: [
      { id: 'exclusive', label: { es: 'Marcas exclusivas/Distribución', 'pt-BR': 'Marcas exclusivas/Distribuição' }, emoji: '⭐', impactScore: 20 },
      { id: 'authorized', label: { es: 'Retail autorizado', 'pt-BR': 'Varejo autorizado' }, emoji: '✅', impactScore: 15 },
      { id: 'indie', label: { es: 'Marcas indie/locales', 'pt-BR': 'Marcas indie/locais' }, emoji: '🏠', impactScore: 15 },
      { id: 'multi', label: { es: 'Multimarca general', 'pt-BR': 'Multimarca geral' }, emoji: '🔀', impactScore: 12 },
    ],
  },
];

// ============= PET SHOP =============
export const PETSHOP_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_PET_PRODUCTS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué productos vendés?', 'pt-BR': 'Quais produtos você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['petshop'],
    options: [
      { id: 'food', label: { es: 'Alimentos', 'pt-BR': 'Alimentos' }, emoji: '🦴', impactScore: 18 },
      { id: 'accessories', label: { es: 'Accesorios/Juguetes', 'pt-BR': 'Acessórios/Brinquedos' }, emoji: '🎾', impactScore: 12 },
      { id: 'health', label: { es: 'Salud/Medicamentos', 'pt-BR': 'Saúde/Medicamentos' }, emoji: '💊', impactScore: 15 },
      { id: 'grooming', label: { es: 'Higiene/Belleza', 'pt-BR': 'Higiene/Beleza' }, emoji: '🧴', impactScore: 12 },
      { id: 'live_animals', label: { es: 'Animales vivos', 'pt-BR': 'Animais vivos' }, emoji: '🐠', impactScore: 15 },
    ],
  },
  {
    id: 'Q_PET_ANIMALS',
    category: 'identity',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Para qué animales vendés?', 'pt-BR': 'Para quais animais você vende?' },
    type: 'multi',
    businessTypes: ['petshop'],
    options: [
      { id: 'dogs', label: { es: 'Perros', 'pt-BR': 'Cães' }, emoji: '🐕', impactScore: 18 },
      { id: 'cats', label: { es: 'Gatos', 'pt-BR': 'Gatos' }, emoji: '🐈', impactScore: 15 },
      { id: 'fish', label: { es: 'Peces', 'pt-BR': 'Peixes' }, emoji: '🐠', impactScore: 10 },
      { id: 'birds', label: { es: 'Aves', 'pt-BR': 'Aves' }, emoji: '🐦', impactScore: 10 },
      { id: 'rodents', label: { es: 'Roedores', 'pt-BR': 'Roedores' }, emoji: '🐹', impactScore: 8 },
      { id: 'exotic', label: { es: 'Exóticos', 'pt-BR': 'Exóticos' }, emoji: '🦎', impactScore: 12 },
    ],
  },
  {
    id: 'Q_PET_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['petshop'],
    options: [
      { id: 'grooming', label: { es: 'Peluquería/Grooming', 'pt-BR': 'Banho e tosa' }, emoji: '✂️', impactScore: 18 },
      { id: 'vet', label: { es: 'Veterinaria', 'pt-BR': 'Veterinária' }, emoji: '🩺', impactScore: 18 },
      { id: 'hotel', label: { es: 'Guardería/Hotel', 'pt-BR': 'Hospedagem/Hotel' }, emoji: '🏠', impactScore: 15 },
      { id: 'training', label: { es: 'Adiestramiento', 'pt-BR': 'Adestramento' }, emoji: '🎓', impactScore: 12 },
      { id: 'delivery', label: { es: 'Delivery', 'pt-BR': 'Delivery' }, emoji: '🚚', impactScore: 12 },
    ],
  },
];

// ============= GOURMET / DELICATESSEN =============
export const GOURMET_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_GOURMET_SPECIALTY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿En qué te especializás?', 'pt-BR': 'Em que você se especializa?' },
    type: 'multi',
    required: true,
    businessTypes: ['gourmet_deli'],
    options: [
      { id: 'cheese', label: { es: 'Quesos', 'pt-BR': 'Queijos' }, emoji: '🧀', impactScore: 15 },
      { id: 'wine', label: { es: 'Vinos', 'pt-BR': 'Vinhos' }, emoji: '🍷', impactScore: 18 },
      { id: 'charcuterie', label: { es: 'Embutidos/Fiambres', 'pt-BR': 'Embutidos/Frios' }, emoji: '🥓', impactScore: 12 },
      { id: 'chocolate', label: { es: 'Chocolates/Dulces', 'pt-BR': 'Chocolates/Doces' }, emoji: '🍫', impactScore: 12 },
      { id: 'coffee_tea', label: { es: 'Café/Té', 'pt-BR': 'Café/Chá' }, emoji: '☕', impactScore: 12 },
      { id: 'olive_oil', label: { es: 'Aceites/Vinagres', 'pt-BR': 'Azeites/Vinagres' }, emoji: '🫒', impactScore: 12 },
      { id: 'spices', label: { es: 'Especias/Condimentos', 'pt-BR': 'Especiarias/Condimentos' }, emoji: '🌶️', impactScore: 10 },
    ],
  },
  {
    id: 'Q_GOURMET_ORIGIN',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿De dónde vienen tus productos?', 'pt-BR': 'De onde vêm seus produtos?' },
    type: 'multi',
    businessTypes: ['gourmet_deli'],
    options: [
      { id: 'local', label: { es: 'Productores locales', 'pt-BR': 'Produtores locais' }, emoji: '🏠', impactScore: 18 },
      { id: 'national', label: { es: 'Nacionales premium', 'pt-BR': 'Nacionais premium' }, emoji: '🇦🇷', impactScore: 15 },
      { id: 'import', label: { es: 'Importados', 'pt-BR': 'Importados' }, emoji: '🌍', impactScore: 18 },
      { id: 'exclusive', label: { es: 'Exclusivos/Distribución', 'pt-BR': 'Exclusivos/Distribuição' }, emoji: '⭐', impactScore: 20 },
    ],
  },
  {
    id: 'Q_GOURMET_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Qué servicios adicionales ofrecés?', 'pt-BR': 'Quais serviços adicionais você oferece?' },
    type: 'multi',
    businessTypes: ['gourmet_deli'],
    options: [
      { id: 'tasting', label: { es: 'Degustaciones', 'pt-BR': 'Degustações' }, emoji: '🍷', impactScore: 15 },
      { id: 'gift_boxes', label: { es: 'Cajas regalo', 'pt-BR': 'Cestas presente' }, emoji: '🎁', impactScore: 15 },
      { id: 'corporate', label: { es: 'Regalos corporativos', 'pt-BR': 'Presentes corporativos' }, emoji: '💼', impactScore: 15 },
      { id: 'events', label: { es: 'Catering/Eventos', 'pt-BR': 'Catering/Eventos' }, emoji: '🎉', impactScore: 15 },
      { id: 'subscription', label: { es: 'Club/Suscripción', 'pt-BR': 'Clube/Assinatura' }, emoji: '📦', impactScore: 18 },
    ],
  },
];

// ============= SEGUNDA MANO / RE-COMMERCE =============
export const SEGUNDA_MANO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_RESALE_PRODUCTS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué productos vendés?', 'pt-BR': 'Quais produtos você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['segunda_mano'],
    options: [
      { id: 'fashion', label: { es: 'Moda/Ropa', 'pt-BR': 'Moda/Roupas' }, emoji: '👗', impactScore: 18 },
      { id: 'luxury', label: { es: 'Lujo/Diseñador', 'pt-BR': 'Luxo/Designer' }, emoji: '💎', impactScore: 20 },
      { id: 'electronics', label: { es: 'Electrónica', 'pt-BR': 'Eletrônicos' }, emoji: '📱', impactScore: 15 },
      { id: 'furniture', label: { es: 'Muebles', 'pt-BR': 'Móveis' }, emoji: '🛋️', impactScore: 12 },
      { id: 'vintage', label: { es: 'Vintage/Antigüedades', 'pt-BR': 'Vintage/Antiguidades' }, emoji: '🕰️', impactScore: 15 },
      { id: 'kids', label: { es: 'Artículos de bebé/niños', 'pt-BR': 'Artigos de bebê/crianças' }, emoji: '👶', impactScore: 12 },
    ],
  },
  {
    id: 'Q_RESALE_MODEL',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu modelo de negocio?', 'pt-BR': 'Qual é seu modelo de negócio?' },
    type: 'single',
    businessTypes: ['segunda_mano'],
    options: [
      { id: 'buy_sell', label: { es: 'Compro y vendo', 'pt-BR': 'Compro e vendo' }, emoji: '💰', impactScore: 15 },
      { id: 'consignment', label: { es: 'Consignación', 'pt-BR': 'Consignação' }, emoji: '🤝', impactScore: 15 },
      { id: 'marketplace', label: { es: 'Marketplace (solo conexión)', 'pt-BR': 'Marketplace (só conexão)' }, emoji: '🔗', impactScore: 12 },
      { id: 'mix', label: { es: 'Mix de modelos', 'pt-BR': 'Mix de modelos' }, emoji: '🔀', impactScore: 12 },
    ],
  },
  {
    id: 'Q_RESALE_QUALITY',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Cómo garantizás la calidad?', 'pt-BR': 'Como você garante a qualidade?' },
    type: 'multi',
    businessTypes: ['segunda_mano'],
    options: [
      { id: 'authentication', label: { es: 'Autenticación', 'pt-BR': 'Autenticação' }, emoji: '✅', impactScore: 20 },
      { id: 'quality_check', label: { es: 'Control de calidad', 'pt-BR': 'Controle de qualidade' }, emoji: '🔍', impactScore: 15 },
      { id: 'guarantee', label: { es: 'Garantía de devolución', 'pt-BR': 'Garantia de devolução' }, emoji: '🛡️', impactScore: 15 },
      { id: 'grading', label: { es: 'Sistema de grades (A, B, C)', 'pt-BR': 'Sistema de notas (A, B, C)' }, emoji: '📊', impactScore: 12 },
    ],
  },
];

// ============= E-COMMERCE D2C =============
export const ECOMMERCE_D2C_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_D2C_CATEGORY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué categoría vendés?', 'pt-BR': 'Qual categoria você vende?' },
    type: 'single',
    required: true,
    businessTypes: ['ecommerce_d2c'],
    options: [
      { id: 'fashion', label: { es: 'Moda/Ropa', 'pt-BR': 'Moda/Roupas' }, emoji: '👗', impactScore: 15 },
      { id: 'beauty', label: { es: 'Belleza/Cosméticos', 'pt-BR': 'Beleza/Cosméticos' }, emoji: '💄', impactScore: 18 },
      { id: 'food', label: { es: 'Alimentos/Bebidas', 'pt-BR': 'Alimentos/Bebidas' }, emoji: '🍫', impactScore: 15 },
      { id: 'home', label: { es: 'Hogar/Decoración', 'pt-BR': 'Casa/Decoração' }, emoji: '🏠', impactScore: 12 },
      { id: 'wellness', label: { es: 'Wellness/Suplementos', 'pt-BR': 'Wellness/Suplementos' }, emoji: '💪', impactScore: 18 },
      { id: 'tech', label: { es: 'Tech/Gadgets', 'pt-BR': 'Tech/Gadgets' }, emoji: '📱', impactScore: 15 },
      { id: 'pets', label: { es: 'Mascotas', 'pt-BR': 'Pets' }, emoji: '🐕', impactScore: 12 },
    ],
  },
  {
    id: 'Q_D2C_ORDERS',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántos pedidos hacés por mes?', 'pt-BR': 'Quantos pedidos você faz por mês?' },
    type: 'single',
    businessTypes: ['ecommerce_d2c'],
    options: [
      { id: '1-100', label: { es: '1-100 pedidos', 'pt-BR': '1-100 pedidos' }, emoji: '📦', impactScore: 8 },
      { id: '101-500', label: { es: '101-500 pedidos', 'pt-BR': '101-500 pedidos' }, emoji: '📈', impactScore: 15 },
      { id: '501-2000', label: { es: '501-2000 pedidos', 'pt-BR': '501-2000 pedidos' }, emoji: '🚀', impactScore: 20 },
      { id: '2000+', label: { es: 'Más de 2000', 'pt-BR': 'Mais de 2000' }, emoji: '🔥', impactScore: 25 },
    ],
  },
  {
    id: 'Q_D2C_CHANNELS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿De dónde viene tu tráfico?', 'pt-BR': 'De onde vem seu tráfego?' },
    type: 'multi',
    businessTypes: ['ecommerce_d2c'],
    options: [
      { id: 'meta', label: { es: 'Meta Ads (FB/IG)', 'pt-BR': 'Meta Ads (FB/IG)' }, emoji: '📱', impactScore: 18 },
      { id: 'google', label: { es: 'Google Ads', 'pt-BR': 'Google Ads' }, emoji: '🔍', impactScore: 15 },
      { id: 'organic', label: { es: 'Orgánico/SEO', 'pt-BR': 'Orgânico/SEO' }, emoji: '🌱', impactScore: 15 },
      { id: 'influencers', label: { es: 'Influencers', 'pt-BR': 'Influencers' }, emoji: '⭐', impactScore: 15 },
      { id: 'email', label: { es: 'Email marketing', 'pt-BR': 'Email marketing' }, emoji: '📧', impactScore: 12 },
      { id: 'referral', label: { es: 'Referidos', 'pt-BR': 'Indicações' }, emoji: '👥', impactScore: 12 },
    ],
  },
  {
    id: 'Q_D2C_FULFILLMENT',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo hacés el fulfillment?', 'pt-BR': 'Como você faz o fulfillment?' },
    type: 'single',
    businessTypes: ['ecommerce_d2c'],
    options: [
      { id: 'inhouse', label: { es: 'In-house', 'pt-BR': 'In-house' }, emoji: '🏠', impactScore: 12 },
      { id: '3pl', label: { es: '3PL (operador logístico)', 'pt-BR': '3PL (operador logístico)' }, emoji: '🚚', impactScore: 18 },
      { id: 'dropship', label: { es: 'Dropshipping', 'pt-BR': 'Dropshipping' }, emoji: '📦', impactScore: 10 },
      { id: 'hybrid', label: { es: 'Híbrido', 'pt-BR': 'Híbrido' }, emoji: '🔀', impactScore: 15 },
    ],
  },
];

// ============= SELLER EN MARKETPLACES =============
export const MARKETPLACE_SELLER_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_MKT_PLATFORMS',
    category: 'identity',
    mode: 'both',
    dimension: 'traffic',
    weight: 9,
    title: { es: '¿En qué plataformas vendés?', 'pt-BR': 'Em quais plataformas você vende?' },
    type: 'multi',
    required: true,
    businessTypes: ['marketplace_seller'],
    options: [
      { id: 'ml', label: { es: 'MercadoLibre', 'pt-BR': 'Mercado Livre' }, emoji: '🛒', impactScore: 18 },
      { id: 'amazon', label: { es: 'Amazon', 'pt-BR': 'Amazon' }, emoji: '📦', impactScore: 18 },
      { id: 'shopee', label: { es: 'Shopee', 'pt-BR': 'Shopee' }, emoji: '🧡', impactScore: 12 },
      { id: 'falabella', label: { es: 'Falabella', 'pt-BR': 'Falabella' }, emoji: '🏬', impactScore: 10, countries: ['AR', 'CL', 'CO'] },
      { id: 'walmart', label: { es: 'Walmart', 'pt-BR': 'Walmart' }, emoji: '🏪', impactScore: 12, countries: ['MX', 'US'] },
      { id: 'magalu', label: { es: 'Magalu', 'pt-BR': 'Magalu' }, emoji: '💙', impactScore: 12, countries: ['BR'] },
    ],
  },
  {
    id: 'Q_MKT_CATEGORY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué categoría vendés?', 'pt-BR': 'Qual categoria você vende?' },
    type: 'multi',
    businessTypes: ['marketplace_seller'],
    options: [
      { id: 'electronics', label: { es: 'Electrónica', 'pt-BR': 'Eletrônicos' }, emoji: '📱', impactScore: 15 },
      { id: 'fashion', label: { es: 'Moda', 'pt-BR': 'Moda' }, emoji: '👗', impactScore: 12 },
      { id: 'home', label: { es: 'Hogar', 'pt-BR': 'Casa' }, emoji: '🏠', impactScore: 12 },
      { id: 'auto', label: { es: 'Automotor', 'pt-BR': 'Automotivo' }, emoji: '🚗', impactScore: 12 },
      { id: 'sports', label: { es: 'Deportes', 'pt-BR': 'Esportes' }, emoji: '⚽', impactScore: 10 },
      { id: 'other', label: { es: 'Otras', 'pt-BR': 'Outras' }, emoji: '📦', impactScore: 8 },
    ],
  },
  {
    id: 'Q_MKT_VOLUME',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántas ventas hacés por mes?', 'pt-BR': 'Quantas vendas você faz por mês?' },
    type: 'single',
    businessTypes: ['marketplace_seller'],
    options: [
      { id: '1-50', label: { es: '1-50 ventas', 'pt-BR': '1-50 vendas' }, emoji: '📊', impactScore: 8 },
      { id: '51-200', label: { es: '51-200 ventas', 'pt-BR': '51-200 vendas' }, emoji: '📈', impactScore: 12 },
      { id: '201-500', label: { es: '201-500 ventas', 'pt-BR': '201-500 vendas' }, emoji: '🚀', impactScore: 18 },
      { id: '500+', label: { es: 'Más de 500', 'pt-BR': 'Mais de 500' }, emoji: '🔥', impactScore: 22 },
    ],
  },
  {
    id: 'Q_MKT_REPUTATION',
    category: 'marketing',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Cuál es tu reputación actual?', 'pt-BR': 'Qual é sua reputação atual?' },
    type: 'single',
    businessTypes: ['marketplace_seller'],
    options: [
      { id: 'platinum', label: { es: 'Platinum/MercadoLíder', 'pt-BR': 'Platinum/MercadoLíder' }, emoji: '💎', impactScore: 25 },
      { id: 'gold', label: { es: 'Oro/Gold', 'pt-BR': 'Ouro/Gold' }, emoji: '🥇', impactScore: 18 },
      { id: 'green', label: { es: 'Verde/Good', 'pt-BR': 'Verde/Good' }, emoji: '🟢', impactScore: 12 },
      { id: 'building', label: { es: 'En construcción', 'pt-BR': 'Em construção' }, emoji: '🏗️', impactScore: 8 },
    ],
  },
];

// ============= SUSCRIPCION / CAJAS MENSUALES =============
export const SUSCRIPCION_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_SUB_CATEGORY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué categoría es tu caja?', 'pt-BR': 'Qual categoria é sua caixa?' },
    type: 'single',
    required: true,
    businessTypes: ['suscripcion_cajas'],
    options: [
      { id: 'beauty', label: { es: 'Belleza/Cosmética', 'pt-BR': 'Beleza/Cosmética' }, emoji: '💄', impactScore: 18 },
      { id: 'food', label: { es: 'Alimentos/Gourmet', 'pt-BR': 'Alimentos/Gourmet' }, emoji: '🍫', impactScore: 15 },
      { id: 'pets', label: { es: 'Mascotas', 'pt-BR': 'Pets' }, emoji: '🐕', impactScore: 12 },
      { id: 'books', label: { es: 'Libros', 'pt-BR': 'Livros' }, emoji: '📚', impactScore: 12 },
      { id: 'kids', label: { es: 'Niños/Juguetes', 'pt-BR': 'Crianças/Brinquedos' }, emoji: '🧸', impactScore: 12 },
      { id: 'fitness', label: { es: 'Fitness/Wellness', 'pt-BR': 'Fitness/Wellness' }, emoji: '💪', impactScore: 15 },
      { id: 'hobby', label: { es: 'Hobbies/Colección', 'pt-BR': 'Hobbies/Coleção' }, emoji: '🎨', impactScore: 12 },
    ],
  },
  {
    id: 'Q_SUB_SUBSCRIBERS',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 9,
    title: { es: '¿Cuántos suscriptores activos tenés?', 'pt-BR': 'Quantos assinantes ativos você tem?' },
    type: 'single',
    businessTypes: ['suscripcion_cajas'],
    options: [
      { id: '1-100', label: { es: '1-100 suscriptores', 'pt-BR': '1-100 assinantes' }, emoji: '📦', impactScore: 8 },
      { id: '101-500', label: { es: '101-500 suscriptores', 'pt-BR': '101-500 assinantes' }, emoji: '📈', impactScore: 15 },
      { id: '501-2000', label: { es: '501-2000 suscriptores', 'pt-BR': '501-2000 assinantes' }, emoji: '🚀', impactScore: 20 },
      { id: '2000+', label: { es: 'Más de 2000', 'pt-BR': 'Mais de 2000' }, emoji: '🔥', impactScore: 25 },
    ],
  },
  {
    id: 'Q_SUB_FREQUENCY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Con qué frecuencia enviás?', 'pt-BR': 'Com que frequência você envia?' },
    type: 'single',
    businessTypes: ['suscripcion_cajas'],
    options: [
      { id: 'weekly', label: { es: 'Semanal', 'pt-BR': 'Semanal' }, emoji: '📅', impactScore: 15 },
      { id: 'monthly', label: { es: 'Mensual', 'pt-BR': 'Mensal' }, emoji: '📆', impactScore: 18 },
      { id: 'bimonthly', label: { es: 'Bimestral', 'pt-BR': 'Bimestral' }, emoji: '🗓️', impactScore: 12 },
      { id: 'quarterly', label: { es: 'Trimestral', 'pt-BR': 'Trimestral' }, emoji: '📊', impactScore: 10 },
    ],
  },
  {
    id: 'Q_SUB_CHURN',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu churn mensual?', 'pt-BR': 'Qual é seu churn mensal?' },
    type: 'single',
    businessTypes: ['suscripcion_cajas'],
    options: [
      { id: 'low_5', label: { es: 'Menos del 5%', 'pt-BR': 'Menos de 5%' }, emoji: '💎', impactScore: 25 },
      { id: 'mid_10', label: { es: '5-10%', 'pt-BR': '5-10%' }, emoji: '👍', impactScore: 18 },
      { id: 'high_20', label: { es: '10-20%', 'pt-BR': '10-20%' }, emoji: '⚠️', impactScore: 10 },
      { id: 'very_high', label: { es: 'Más del 20%', 'pt-BR': 'Mais de 20%' }, emoji: '🚨', impactScore: 5 },
    ],
  },
];

// ============= MAYORISTA / DISTRIBUIDOR =============
export const MAYORISTA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_MAY_CATEGORY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué categoría distribuís?', 'pt-BR': 'Qual categoria você distribui?' },
    type: 'multi',
    required: true,
    businessTypes: ['mayorista_distribuidor'],
    options: [
      { id: 'food', label: { es: 'Alimentos', 'pt-BR': 'Alimentos' }, emoji: '🍎', impactScore: 15 },
      { id: 'beverages', label: { es: 'Bebidas', 'pt-BR': 'Bebidas' }, emoji: '🍺', impactScore: 15 },
      { id: 'cleaning', label: { es: 'Limpieza/Hogar', 'pt-BR': 'Limpeza/Casa' }, emoji: '🧹', impactScore: 12 },
      { id: 'pharma', label: { es: 'Farmacia/Perfumería', 'pt-BR': 'Farmácia/Perfumaria' }, emoji: '💊', impactScore: 15 },
      { id: 'electronics', label: { es: 'Electrónica', 'pt-BR': 'Eletrônicos' }, emoji: '📱', impactScore: 12 },
      { id: 'industrial', label: { es: 'Insumos industriales', 'pt-BR': 'Insumos industriais' }, emoji: '🏭', impactScore: 15 },
    ],
  },
  {
    id: 'Q_MAY_CLIENTS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Quiénes son tus clientes?', 'pt-BR': 'Quem são seus clientes?' },
    type: 'multi',
    businessTypes: ['mayorista_distribuidor'],
    options: [
      { id: 'retail', label: { es: 'Minoristas', 'pt-BR': 'Varejistas' }, emoji: '🏪', impactScore: 15 },
      { id: 'horeca', label: { es: 'HORECA (hoteles, restaurantes)', 'pt-BR': 'HORECA (hotéis, restaurantes)' }, emoji: '🍽️', impactScore: 15 },
      { id: 'industry', label: { es: 'Industria', 'pt-BR': 'Indústria' }, emoji: '🏭', impactScore: 15 },
      { id: 'chains', label: { es: 'Cadenas/Franquicias', 'pt-BR': 'Redes/Franquias' }, emoji: '🔗', impactScore: 18 },
      { id: 'government', label: { es: 'Gobierno/Institucional', 'pt-BR': 'Governo/Institucional' }, emoji: '🏛️', impactScore: 12 },
    ],
  },
  {
    id: 'Q_MAY_COVERAGE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu cobertura geográfica?', 'pt-BR': 'Qual é sua cobertura geográfica?' },
    type: 'single',
    businessTypes: ['mayorista_distribuidor'],
    options: [
      { id: 'local', label: { es: 'Local/Ciudad', 'pt-BR': 'Local/Cidade' }, emoji: '🏘️', impactScore: 10 },
      { id: 'regional', label: { es: 'Regional', 'pt-BR': 'Regional' }, emoji: '🗺️', impactScore: 15 },
      { id: 'national', label: { es: 'Nacional', 'pt-BR': 'Nacional' }, emoji: '🇦🇷', impactScore: 20 },
      { id: 'international', label: { es: 'Internacional', 'pt-BR': 'Internacional' }, emoji: '🌍', impactScore: 22 },
    ],
  },
  {
    id: 'Q_MAY_LOGISTICS',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo manejás la logística?', 'pt-BR': 'Como você gerencia a logística?' },
    type: 'single',
    businessTypes: ['mayorista_distribuidor'],
    options: [
      { id: 'own', label: { es: 'Flota propia', 'pt-BR': 'Frota própria' }, emoji: '🚚', impactScore: 18 },
      { id: '3pl', label: { es: 'Operador logístico', 'pt-BR': 'Operador logístico' }, emoji: '📦', impactScore: 15 },
      { id: 'pickup', label: { es: 'Retiro en depósito', 'pt-BR': 'Retirada no depósito' }, emoji: '🏢', impactScore: 10 },
      { id: 'hybrid', label: { es: 'Híbrido', 'pt-BR': 'Híbrido' }, emoji: '🔀', impactScore: 15 },
    ],
  },
];

// Export all retail questions
export const ALL_RETAIL_QUESTIONS: GastroQuestion[] = [
  ...ALMACEN_QUESTIONS,
  ...SUPERMERCADO_QUESTIONS,
  ...MODA_QUESTIONS,
  ...CALZADO_QUESTIONS,
  ...HOGAR_DECO_QUESTIONS,
  ...ELECTRONICA_QUESTIONS,
  ...FERRETERIA_QUESTIONS,
  ...LIBRERIA_QUESTIONS,
  ...JUGUETERIA_QUESTIONS,
  ...DEPORTES_QUESTIONS,
  ...BELLEZA_PERFUMERIA_QUESTIONS,
  ...PETSHOP_QUESTIONS,
  ...GOURMET_QUESTIONS,
  ...SEGUNDA_MANO_QUESTIONS,
  ...ECOMMERCE_D2C_QUESTIONS,
  ...MARKETPLACE_SELLER_QUESTIONS,
  ...SUSCRIPCION_QUESTIONS,
  ...MAYORISTA_QUESTIONS,
];

// Export function to get retail questions for a specific business type
export function getRetailQuestions(businessTypeId: string): GastroQuestion[] {
  return ALL_RETAIL_QUESTIONS.filter(q => 
    q.businessTypes?.includes(businessTypeId)
  );
}
