// Salud, Bienestar y Belleza - Complete 18 Business Types
// Sector A4_SALUD - Ultra-specific questionnaires

import type { GastroQuestion } from '../gastroQuestionsEngine';

// ============= CLINICA / POLICONSULTORIO =============
export const CLINICA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_CLINICA_SPECIALTIES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué especialidades ofrecés?', 'pt-BR': 'Quais especialidades você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['clinica_policonsultorio'],
    options: [
      { id: 'general', label: { es: 'Medicina general', 'pt-BR': 'Clínica geral' }, emoji: '🩺', impactScore: 15 },
      { id: 'pediatrics', label: { es: 'Pediatría', 'pt-BR': 'Pediatria' }, emoji: '👶', impactScore: 15 },
      { id: 'gynecology', label: { es: 'Ginecología', 'pt-BR': 'Ginecologia' }, emoji: '👩', impactScore: 15 },
      { id: 'cardiology', label: { es: 'Cardiología', 'pt-BR': 'Cardiologia' }, emoji: '❤️', impactScore: 18 },
      { id: 'dermatology', label: { es: 'Dermatología', 'pt-BR': 'Dermatologia' }, emoji: '🧴', impactScore: 15 },
      { id: 'traumatology', label: { es: 'Traumatología', 'pt-BR': 'Traumatologia' }, emoji: '🦴', impactScore: 15 },
    ],
  },
  {
    id: 'Q_CLINICA_PROFESSIONALS',
    category: 'team',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántos profesionales trabajan en la clínica?', 'pt-BR': 'Quantos profissionais trabalham na clínica?' },
    type: 'single',
    businessTypes: ['clinica_policonsultorio'],
    options: [
      { id: '1-5', label: { es: '1-5 profesionales', 'pt-BR': '1-5 profissionais' }, emoji: '👨‍⚕️', impactScore: 10 },
      { id: '6-15', label: { es: '6-15 profesionales', 'pt-BR': '6-15 profissionais' }, emoji: '👥', impactScore: 15 },
      { id: '16-30', label: { es: '16-30 profesionales', 'pt-BR': '16-30 profissionais' }, emoji: '🏥', impactScore: 18 },
      { id: '30+', label: { es: 'Más de 30', 'pt-BR': 'Mais de 30' }, emoji: '🏢', impactScore: 20 },
    ],
  },
  {
    id: 'Q_CLINICA_APPOINTMENTS',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cómo gestionás los turnos?', 'pt-BR': 'Como você gerencia as consultas?' },
    type: 'single',
    businessTypes: ['clinica_policonsultorio'],
    options: [
      { id: 'system', label: { es: 'Sistema de turnos online', 'pt-BR': 'Sistema de agendamento online' }, emoji: '📱', impactScore: 20 },
      { id: 'whatsapp', label: { es: 'WhatsApp/Teléfono', 'pt-BR': 'WhatsApp/Telefone' }, emoji: '📞', impactScore: 12 },
      { id: 'reception', label: { es: 'Solo recepción', 'pt-BR': 'Só recepção' }, emoji: '🏢', impactScore: 8 },
      { id: 'mixed', label: { es: 'Mixto', 'pt-BR': 'Misto' }, emoji: '🔄', impactScore: 15 },
    ],
  },
  {
    id: 'Q_CLINICA_INSURANCE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Trabajás con obras sociales/seguros?', 'pt-BR': 'Você trabalha com convênios?' },
    type: 'single',
    businessTypes: ['clinica_policonsultorio'],
    options: [
      { id: 'all', label: { es: 'Sí, varias obras sociales', 'pt-BR': 'Sim, vários convênios' }, emoji: '🏥', impactScore: 15 },
      { id: 'some', label: { es: 'Algunas seleccionadas', 'pt-BR': 'Alguns selecionados' }, emoji: '✅', impactScore: 18 },
      { id: 'private', label: { es: 'Solo particular', 'pt-BR': 'Só particular' }, emoji: '💰', impactScore: 20 },
      { id: 'mixed', label: { es: 'Mixto 50/50', 'pt-BR': 'Misto 50/50' }, emoji: '⚖️', impactScore: 15 },
    ],
  },
  {
    id: 'Q_CLINICA_PATIENTS_DAY',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántos pacientes atendés por día en promedio?', 'pt-BR': 'Quantos pacientes você atende por dia em média?' },
    type: 'single',
    businessTypes: ['clinica_policonsultorio'],
    options: [
      { id: '1-20', label: { es: '1-20 pacientes', 'pt-BR': '1-20 pacientes' }, emoji: '👤', impactScore: 10 },
      { id: '21-50', label: { es: '21-50 pacientes', 'pt-BR': '21-50 pacientes' }, emoji: '👥', impactScore: 15 },
      { id: '51-100', label: { es: '51-100 pacientes', 'pt-BR': '51-100 pacientes' }, emoji: '🏢', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🏥', impactScore: 20 },
    ],
  },
];

// ============= CONSULTORIO MEDICO =============
export const CONSULTORIO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_CONSULT_SPECIALTY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuál es tu especialidad principal?', 'pt-BR': 'Qual é sua especialidade principal?' },
    type: 'single',
    required: true,
    businessTypes: ['consultorio_medico'],
    options: [
      { id: 'general', label: { es: 'Medicina general', 'pt-BR': 'Clínica geral' }, emoji: '🩺', impactScore: 12 },
      { id: 'pediatrics', label: { es: 'Pediatría', 'pt-BR': 'Pediatria' }, emoji: '👶', impactScore: 15 },
      { id: 'dermatology', label: { es: 'Dermatología', 'pt-BR': 'Dermatologia' }, emoji: '🧴', impactScore: 15 },
      { id: 'psychiatry', label: { es: 'Psiquiatría', 'pt-BR': 'Psiquiatria' }, emoji: '🧠', impactScore: 18 },
      { id: 'neurology', label: { es: 'Neurología', 'pt-BR': 'Neurologia' }, emoji: '🧠', impactScore: 18 },
      { id: 'other', label: { es: 'Otra especialidad', 'pt-BR': 'Outra especialidade' }, emoji: '📋', impactScore: 12 },
    ],
  },
  {
    id: 'Q_CONSULT_PATIENTS_WEEK',
    category: 'finance',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cuántos pacientes atendés por semana?', 'pt-BR': 'Quantos pacientes você atende por semana?' },
    type: 'single',
    businessTypes: ['consultorio_medico'],
    options: [
      { id: '1-20', label: { es: '1-20 pacientes', 'pt-BR': '1-20 pacientes' }, emoji: '👤', impactScore: 10 },
      { id: '21-40', label: { es: '21-40 pacientes', 'pt-BR': '21-40 pacientes' }, emoji: '👥', impactScore: 15 },
      { id: '41-60', label: { es: '41-60 pacientes', 'pt-BR': '41-60 pacientes' }, emoji: '📈', impactScore: 18 },
      { id: '60+', label: { es: 'Más de 60', 'pt-BR': 'Mais de 60' }, emoji: '🔥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_CONSULT_DURATION',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuánto dura una consulta promedio?', 'pt-BR': 'Quanto dura uma consulta em média?' },
    type: 'single',
    businessTypes: ['consultorio_medico'],
    options: [
      { id: '15min', label: { es: '15-20 minutos', 'pt-BR': '15-20 minutos' }, emoji: '⚡', impactScore: 15 },
      { id: '30min', label: { es: '30 minutos', 'pt-BR': '30 minutos' }, emoji: '⏱️', impactScore: 18 },
      { id: '45min', label: { es: '45 minutos', 'pt-BR': '45 minutos' }, emoji: '⏰', impactScore: 15 },
      { id: '60min', label: { es: '60+ minutos', 'pt-BR': '60+ minutos' }, emoji: '🕐', impactScore: 12 },
    ],
  },
  {
    id: 'Q_CONSULT_LOCATION',
    category: 'operation',
    mode: 'complete',
    dimension: 'traffic',
    weight: 6,
    title: { es: '¿Dónde atendés?', 'pt-BR': 'Onde você atende?' },
    type: 'multi',
    businessTypes: ['consultorio_medico'],
    options: [
      { id: 'own', label: { es: 'Consultorio propio', 'pt-BR': 'Consultório próprio' }, emoji: '🏠', impactScore: 18 },
      { id: 'clinic', label: { es: 'En clínica/sanatorio', 'pt-BR': 'Em clínica/hospital' }, emoji: '🏥', impactScore: 15 },
      { id: 'online', label: { es: 'Telemedicina', 'pt-BR': 'Telemedicina' }, emoji: '💻', impactScore: 15 },
      { id: 'home', label: { es: 'A domicilio', 'pt-BR': 'Domiciliar' }, emoji: '🏡', impactScore: 12 },
    ],
  },
];

// ============= CENTRO ODONTOLOGICO =============
export const ODONTOLOGIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_ODONTO_SERVICES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['centro_odontologico'],
    options: [
      { id: 'general', label: { es: 'Odontología general', 'pt-BR': 'Odontologia geral' }, emoji: '🦷', impactScore: 12 },
      { id: 'ortho', label: { es: 'Ortodoncia', 'pt-BR': 'Ortodontia' }, emoji: '😁', impactScore: 18 },
      { id: 'implants', label: { es: 'Implantes', 'pt-BR': 'Implantes' }, emoji: '🔩', impactScore: 20 },
      { id: 'aesthetic', label: { es: 'Estética dental', 'pt-BR': 'Estética dental' }, emoji: '✨', impactScore: 18 },
      { id: 'endodontics', label: { es: 'Endodoncia', 'pt-BR': 'Endodontia' }, emoji: '🔬', impactScore: 15 },
      { id: 'pediatric', label: { es: 'Odontopediatría', 'pt-BR': 'Odontopediatria' }, emoji: '👶', impactScore: 15 },
    ],
  },
  {
    id: 'Q_ODONTO_CHAIRS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántos sillones/unidades tenés?', 'pt-BR': 'Quantas cadeiras/unidades você tem?' },
    type: 'single',
    businessTypes: ['centro_odontologico'],
    options: [
      { id: '1', label: { es: '1 sillón', 'pt-BR': '1 cadeira' }, emoji: '🪑', impactScore: 10 },
      { id: '2-3', label: { es: '2-3 sillones', 'pt-BR': '2-3 cadeiras' }, emoji: '🏠', impactScore: 15 },
      { id: '4-6', label: { es: '4-6 sillones', 'pt-BR': '4-6 cadeiras' }, emoji: '🏢', impactScore: 18 },
      { id: '6+', label: { es: 'Más de 6', 'pt-BR': 'Mais de 6' }, emoji: '🏥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_ODONTO_TECHNOLOGY',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué tecnología usás?', 'pt-BR': 'Que tecnologia você usa?' },
    type: 'multi',
    businessTypes: ['centro_odontologico'],
    options: [
      { id: 'digital_xray', label: { es: 'Rx digital', 'pt-BR': 'Rx digital' }, emoji: '📷', impactScore: 15 },
      { id: 'panoramic', label: { es: 'Panorámico', 'pt-BR': 'Panorâmico' }, emoji: '🔍', impactScore: 15 },
      { id: 'scanner', label: { es: 'Scanner 3D', 'pt-BR': 'Scanner 3D' }, emoji: '🖥️', impactScore: 20 },
      { id: 'laser', label: { es: 'Láser', 'pt-BR': 'Laser' }, emoji: '⚡', impactScore: 18 },
      { id: 'cad_cam', label: { es: 'CAD/CAM', 'pt-BR': 'CAD/CAM' }, emoji: '🦿', impactScore: 20 },
    ],
  },
];

// ============= LABORATORIO DE ANALISIS =============
export const LABORATORIO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_LAB_TESTS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipos de análisis realizás?', 'pt-BR': 'Que tipos de análises você realiza?' },
    type: 'multi',
    required: true,
    businessTypes: ['laboratorio_analisis'],
    options: [
      { id: 'blood', label: { es: 'Sangre/Hemograma', 'pt-BR': 'Sangue/Hemograma' }, emoji: '🩸', impactScore: 15 },
      { id: 'urine', label: { es: 'Orina', 'pt-BR': 'Urina' }, emoji: '🧪', impactScore: 12 },
      { id: 'hormones', label: { es: 'Hormonas', 'pt-BR': 'Hormônios' }, emoji: '🔬', impactScore: 18 },
      { id: 'genetics', label: { es: 'Genética', 'pt-BR': 'Genética' }, emoji: '🧬', impactScore: 22 },
      { id: 'microbiology', label: { es: 'Microbiología', 'pt-BR': 'Microbiologia' }, emoji: '🦠', impactScore: 18 },
      { id: 'toxicology', label: { es: 'Toxicología', 'pt-BR': 'Toxicologia' }, emoji: '☣️', impactScore: 18 },
    ],
  },
  {
    id: 'Q_LAB_DAILY_SAMPLES',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cuántas muestras procesás por día?', 'pt-BR': 'Quantas amostras você processa por dia?' },
    type: 'single',
    businessTypes: ['laboratorio_analisis'],
    options: [
      { id: '1-20', label: { es: '1-20 muestras', 'pt-BR': '1-20 amostras' }, emoji: '🧪', impactScore: 10 },
      { id: '21-50', label: { es: '21-50 muestras', 'pt-BR': '21-50 amostras' }, emoji: '📊', impactScore: 15 },
      { id: '51-100', label: { es: '51-100 muestras', 'pt-BR': '51-100 amostras' }, emoji: '📈', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🔥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_LAB_TURNAROUND',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuánto tardan los resultados en promedio?', 'pt-BR': 'Quanto tempo demora os resultados em média?' },
    type: 'single',
    businessTypes: ['laboratorio_analisis'],
    options: [
      { id: 'same_day', label: { es: 'Mismo día', 'pt-BR': 'Mesmo dia' }, emoji: '⚡', impactScore: 20 },
      { id: '24h', label: { es: '24 horas', 'pt-BR': '24 horas' }, emoji: '⏰', impactScore: 18 },
      { id: '48h', label: { es: '48-72 horas', 'pt-BR': '48-72 horas' }, emoji: '📅', impactScore: 12 },
      { id: 'week', label: { es: 'Más de 3 días', 'pt-BR': 'Mais de 3 dias' }, emoji: '📆', impactScore: 8 },
    ],
  },
];

// ============= CENTRO DE DIAGNOSTICO POR IMAGENES =============
export const DIAGNOSTICO_IMAGENES_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_DIAG_EQUIPMENT',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué equipamiento tenés?', 'pt-BR': 'Que equipamentos você tem?' },
    type: 'multi',
    required: true,
    businessTypes: ['centro_diagnostico'],
    options: [
      { id: 'xray', label: { es: 'Rayos X', 'pt-BR': 'Raios X' }, emoji: '📷', impactScore: 12 },
      { id: 'ultrasound', label: { es: 'Ecografía', 'pt-BR': 'Ultrassom' }, emoji: '🔊', impactScore: 15 },
      { id: 'ct', label: { es: 'Tomografía', 'pt-BR': 'Tomografia' }, emoji: '🔄', impactScore: 20 },
      { id: 'mri', label: { es: 'Resonancia magnética', 'pt-BR': 'Ressonância magnética' }, emoji: '🧲', impactScore: 22 },
      { id: 'mammo', label: { es: 'Mamografía', 'pt-BR': 'Mamografia' }, emoji: '💗', impactScore: 18 },
      { id: 'densitometry', label: { es: 'Densitometría', 'pt-BR': 'Densitometria' }, emoji: '🦴', impactScore: 15 },
    ],
  },
  {
    id: 'Q_DIAG_STUDIES_DAY',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cuántos estudios realizás por día?', 'pt-BR': 'Quantos estudos você realiza por dia?' },
    type: 'single',
    businessTypes: ['centro_diagnostico'],
    options: [
      { id: '1-15', label: { es: '1-15 estudios', 'pt-BR': '1-15 estudos' }, emoji: '📊', impactScore: 10 },
      { id: '16-30', label: { es: '16-30 estudios', 'pt-BR': '16-30 estudos' }, emoji: '📈', impactScore: 15 },
      { id: '31-50', label: { es: '31-50 estudios', 'pt-BR': '31-50 estudos' }, emoji: '🚀', impactScore: 18 },
      { id: '50+', label: { es: 'Más de 50', 'pt-BR': 'Mais de 50' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= KINESIOLOGIA / REHABILITACION =============
export const KINESIOLOGIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_KINE_SPECIALTY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿En qué te especializás?', 'pt-BR': 'Em que você se especializa?' },
    type: 'multi',
    required: true,
    businessTypes: ['kinesiologia_rehabilitacion'],
    options: [
      { id: 'trauma', label: { es: 'Traumatología/Deportiva', 'pt-BR': 'Traumatologia/Esportiva' }, emoji: '🏃', impactScore: 18 },
      { id: 'neuro', label: { es: 'Neurológica', 'pt-BR': 'Neurológica' }, emoji: '🧠', impactScore: 18 },
      { id: 'respiratory', label: { es: 'Respiratoria', 'pt-BR': 'Respiratória' }, emoji: '🌬️', impactScore: 15 },
      { id: 'pediatric', label: { es: 'Pediátrica', 'pt-BR': 'Pediátrica' }, emoji: '👶', impactScore: 15 },
      { id: 'geriatric', label: { es: 'Geriátrica', 'pt-BR': 'Geriátrica' }, emoji: '👴', impactScore: 15 },
      { id: 'pelvic', label: { es: 'Piso pélvico', 'pt-BR': 'Assoalho pélvico' }, emoji: '🩺', impactScore: 18 },
    ],
  },
  {
    id: 'Q_KINE_SESSION_TYPE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo trabajás?', 'pt-BR': 'Como você trabalha?' },
    type: 'single',
    businessTypes: ['kinesiologia_rehabilitacion'],
    options: [
      { id: 'individual', label: { es: 'Sesiones individuales', 'pt-BR': 'Sessões individuais' }, emoji: '👤', impactScore: 15 },
      { id: 'group', label: { es: 'Grupos pequeños', 'pt-BR': 'Grupos pequenos' }, emoji: '👥', impactScore: 12 },
      { id: 'home', label: { es: 'A domicilio', 'pt-BR': 'Domiciliar' }, emoji: '🏠', impactScore: 12 },
      { id: 'mixed', label: { es: 'Mixto', 'pt-BR': 'Misto' }, emoji: '🔄', impactScore: 18 },
    ],
  },
  {
    id: 'Q_KINE_PATIENTS_WEEK',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántos pacientes atendés por semana?', 'pt-BR': 'Quantos pacientes você atende por semana?' },
    type: 'single',
    businessTypes: ['kinesiologia_rehabilitacion'],
    options: [
      { id: '1-15', label: { es: '1-15 pacientes', 'pt-BR': '1-15 pacientes' }, emoji: '👤', impactScore: 10 },
      { id: '16-30', label: { es: '16-30 pacientes', 'pt-BR': '16-30 pacientes' }, emoji: '👥', impactScore: 15 },
      { id: '31-50', label: { es: '31-50 pacientes', 'pt-BR': '31-50 pacientes' }, emoji: '📈', impactScore: 18 },
      { id: '50+', label: { es: 'Más de 50', 'pt-BR': 'Mais de 50' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= PSICOLOGIA / SALUD MENTAL =============
export const PSICOLOGIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_PSI_APPROACH',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuál es tu enfoque terapéutico principal?', 'pt-BR': 'Qual é sua abordagem terapêutica principal?' },
    type: 'single',
    required: true,
    businessTypes: ['psicologia_salud_mental'],
    options: [
      { id: 'cbt', label: { es: 'Cognitivo-conductual', 'pt-BR': 'Cognitivo-comportamental' }, emoji: '🧠', impactScore: 15 },
      { id: 'psychoanalysis', label: { es: 'Psicoanálisis', 'pt-BR': 'Psicanálise' }, emoji: '🛋️', impactScore: 15 },
      { id: 'systemic', label: { es: 'Sistémico/Familiar', 'pt-BR': 'Sistêmico/Familiar' }, emoji: '👨‍👩‍👧', impactScore: 15 },
      { id: 'humanistic', label: { es: 'Humanista/Gestalt', 'pt-BR': 'Humanista/Gestalt' }, emoji: '🌱', impactScore: 15 },
      { id: 'integrative', label: { es: 'Integrativo', 'pt-BR': 'Integrativo' }, emoji: '🔄', impactScore: 18 },
    ],
  },
  {
    id: 'Q_PSI_POPULATION',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Con qué población trabajás principalmente?', 'pt-BR': 'Com que população você trabalha principalmente?' },
    type: 'multi',
    businessTypes: ['psicologia_salud_mental'],
    options: [
      { id: 'adults', label: { es: 'Adultos', 'pt-BR': 'Adultos' }, emoji: '👤', impactScore: 12 },
      { id: 'teens', label: { es: 'Adolescentes', 'pt-BR': 'Adolescentes' }, emoji: '🧑', impactScore: 15 },
      { id: 'children', label: { es: 'Niños', 'pt-BR': 'Crianças' }, emoji: '👶', impactScore: 15 },
      { id: 'couples', label: { es: 'Parejas', 'pt-BR': 'Casais' }, emoji: '💑', impactScore: 15 },
      { id: 'families', label: { es: 'Familias', 'pt-BR': 'Famílias' }, emoji: '👨‍👩‍👧', impactScore: 15 },
    ],
  },
  {
    id: 'Q_PSI_SESSIONS_WEEK',
    category: 'finance',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántas sesiones das por semana?', 'pt-BR': 'Quantas sessões você dá por semana?' },
    type: 'single',
    businessTypes: ['psicologia_salud_mental'],
    options: [
      { id: '1-10', label: { es: '1-10 sesiones', 'pt-BR': '1-10 sessões' }, emoji: '📊', impactScore: 10 },
      { id: '11-20', label: { es: '11-20 sesiones', 'pt-BR': '11-20 sessões' }, emoji: '📈', impactScore: 15 },
      { id: '21-30', label: { es: '21-30 sesiones', 'pt-BR': '21-30 sessões' }, emoji: '🚀', impactScore: 18 },
      { id: '30+', label: { es: 'Más de 30', 'pt-BR': 'Mais de 30' }, emoji: '🔥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_PSI_MODALITY',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Cómo das las sesiones?', 'pt-BR': 'Como você dá as sessões?' },
    type: 'single',
    businessTypes: ['psicologia_salud_mental'],
    options: [
      { id: 'in_person', label: { es: 'Solo presencial', 'pt-BR': 'Só presencial' }, emoji: '🏢', impactScore: 12 },
      { id: 'online', label: { es: 'Solo online', 'pt-BR': 'Só online' }, emoji: '💻', impactScore: 15 },
      { id: 'hybrid', label: { es: 'Híbrido', 'pt-BR': 'Híbrido' }, emoji: '🔄', impactScore: 20 },
    ],
  },
];

// ============= NUTRICION / DIETETICA CLINICA =============
export const NUTRICION_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_NUTRI_SPECIALTY',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿En qué te especializás?', 'pt-BR': 'Em que você se especializa?' },
    type: 'multi',
    required: true,
    businessTypes: ['nutricion_dietetica'],
    options: [
      { id: 'weight', label: { es: 'Control de peso', 'pt-BR': 'Controle de peso' }, emoji: '⚖️', impactScore: 15 },
      { id: 'sports', label: { es: 'Nutrición deportiva', 'pt-BR': 'Nutrição esportiva' }, emoji: '🏋️', impactScore: 18 },
      { id: 'clinical', label: { es: 'Nutrición clínica', 'pt-BR': 'Nutrição clínica' }, emoji: '🏥', impactScore: 18 },
      { id: 'pediatric', label: { es: 'Nutrición pediátrica', 'pt-BR': 'Nutrição pediátrica' }, emoji: '👶', impactScore: 15 },
      { id: 'vegan', label: { es: 'Alimentación vegana/vegetariana', 'pt-BR': 'Alimentação vegana/vegetariana' }, emoji: '🥗', impactScore: 15 },
      { id: 'eating_disorders', label: { es: 'Trastornos alimentarios', 'pt-BR': 'Transtornos alimentares' }, emoji: '💚', impactScore: 18 },
    ],
  },
  {
    id: 'Q_NUTRI_CONSULTATIONS',
    category: 'finance',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cuántas consultas das por semana?', 'pt-BR': 'Quantas consultas você dá por semana?' },
    type: 'single',
    businessTypes: ['nutricion_dietetica'],
    options: [
      { id: '1-10', label: { es: '1-10 consultas', 'pt-BR': '1-10 consultas' }, emoji: '📊', impactScore: 10 },
      { id: '11-25', label: { es: '11-25 consultas', 'pt-BR': '11-25 consultas' }, emoji: '📈', impactScore: 15 },
      { id: '26-40', label: { es: '26-40 consultas', 'pt-BR': '26-40 consultas' }, emoji: '🚀', impactScore: 18 },
      { id: '40+', label: { es: 'Más de 40', 'pt-BR': 'Mais de 40' }, emoji: '🔥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_NUTRI_TOOLS',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Qué herramientas usás?', 'pt-BR': 'Quais ferramentas você usa?' },
    type: 'multi',
    businessTypes: ['nutricion_dietetica'],
    options: [
      { id: 'software', label: { es: 'Software de nutrición', 'pt-BR': 'Software de nutrição' }, emoji: '💻', impactScore: 18 },
      { id: 'bioimpedance', label: { es: 'Bioimpedancia', 'pt-BR': 'Bioimpedância' }, emoji: '📊', impactScore: 15 },
      { id: 'app', label: { es: 'App para pacientes', 'pt-BR': 'App para pacientes' }, emoji: '📱', impactScore: 18 },
      { id: 'meal_plans', label: { es: 'Planes personalizados', 'pt-BR': 'Planos personalizados' }, emoji: '📋', impactScore: 15 },
    ],
  },
];

// ============= MEDICINA ESTETICA =============
export const MEDICINA_ESTETICA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_MED_EST_TREATMENTS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tratamientos ofrecés?', 'pt-BR': 'Quais tratamentos você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['medicina_estetica'],
    options: [
      { id: 'botox', label: { es: 'Toxina botulínica', 'pt-BR': 'Toxina botulínica' }, emoji: '💉', impactScore: 20 },
      { id: 'fillers', label: { es: 'Rellenos/Ácido hialurónico', 'pt-BR': 'Preenchimentos/Ácido hialurônico' }, emoji: '✨', impactScore: 20 },
      { id: 'mesotherapy', label: { es: 'Mesoterapia', 'pt-BR': 'Mesoterapia' }, emoji: '💧', impactScore: 15 },
      { id: 'threads', label: { es: 'Hilos tensores', 'pt-BR': 'Fios tensores' }, emoji: '🧵', impactScore: 20 },
      { id: 'plasma', label: { es: 'Plasma rico en plaquetas', 'pt-BR': 'Plasma rico em plaquetas' }, emoji: '🩸', impactScore: 18 },
      { id: 'laser', label: { es: 'Láser/IPL', 'pt-BR': 'Laser/IPL' }, emoji: '⚡', impactScore: 18 },
    ],
  },
  {
    id: 'Q_MED_EST_PATIENTS_MONTH',
    category: 'finance',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cuántos pacientes atendés por mes?', 'pt-BR': 'Quantos pacientes você atende por mês?' },
    type: 'single',
    businessTypes: ['medicina_estetica'],
    options: [
      { id: '1-20', label: { es: '1-20 pacientes', 'pt-BR': '1-20 pacientes' }, emoji: '👤', impactScore: 10 },
      { id: '21-50', label: { es: '21-50 pacientes', 'pt-BR': '21-50 pacientes' }, emoji: '👥', impactScore: 15 },
      { id: '51-100', label: { es: '51-100 pacientes', 'pt-BR': '51-100 pacientes' }, emoji: '📈', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🔥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_MED_EST_AVG_TICKET',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cuál es tu ticket promedio?', 'pt-BR': 'Qual é seu ticket médio?' },
    type: 'single',
    businessTypes: ['medicina_estetica'],
    options: [
      { id: 'low', label: { es: 'Bajo (tratamientos básicos)', 'pt-BR': 'Baixo (tratamentos básicos)' }, emoji: '💵', impactScore: 10 },
      { id: 'medium', label: { es: 'Medio', 'pt-BR': 'Médio' }, emoji: '💰', impactScore: 15 },
      { id: 'high', label: { es: 'Alto (procedimientos premium)', 'pt-BR': 'Alto (procedimentos premium)' }, emoji: '💎', impactScore: 20 },
    ],
  },
];

// ============= CENTRO DE ESTETICA =============
export const CENTRO_ESTETICA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_EST_SERVICES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['centro_estetica'],
    options: [
      { id: 'facial', label: { es: 'Tratamientos faciales', 'pt-BR': 'Tratamentos faciais' }, emoji: '✨', impactScore: 15 },
      { id: 'body', label: { es: 'Tratamientos corporales', 'pt-BR': 'Tratamentos corporais' }, emoji: '💪', impactScore: 15 },
      { id: 'equipment', label: { es: 'Aparatología', 'pt-BR': 'Aparelhos' }, emoji: '🔬', impactScore: 18 },
      { id: 'massage', label: { es: 'Masajes', 'pt-BR': 'Massagens' }, emoji: '🧖', impactScore: 12 },
      { id: 'nails', label: { es: 'Manicura/Pedicura', 'pt-BR': 'Manicure/Pedicure' }, emoji: '💅', impactScore: 12 },
      { id: 'depilation', label: { es: 'Depilación', 'pt-BR': 'Depilação' }, emoji: '✨', impactScore: 12 },
    ],
  },
  {
    id: 'Q_EST_CABINS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántas cabinas/espacios de atención tenés?', 'pt-BR': 'Quantas cabines/espaços de atendimento você tem?' },
    type: 'single',
    businessTypes: ['centro_estetica'],
    options: [
      { id: '1', label: { es: '1 cabina', 'pt-BR': '1 cabine' }, emoji: '🚪', impactScore: 10 },
      { id: '2-3', label: { es: '2-3 cabinas', 'pt-BR': '2-3 cabines' }, emoji: '🏠', impactScore: 15 },
      { id: '4-6', label: { es: '4-6 cabinas', 'pt-BR': '4-6 cabines' }, emoji: '🏢', impactScore: 18 },
      { id: '6+', label: { es: 'Más de 6', 'pt-BR': 'Mais de 6' }, emoji: '🏪', impactScore: 20 },
    ],
  },
  {
    id: 'Q_EST_CLIENTS_WEEK',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántas clientas atendés por semana?', 'pt-BR': 'Quantas clientes você atende por semana?' },
    type: 'single',
    businessTypes: ['centro_estetica'],
    options: [
      { id: '1-20', label: { es: '1-20 clientas', 'pt-BR': '1-20 clientes' }, emoji: '👤', impactScore: 10 },
      { id: '21-50', label: { es: '21-50 clientas', 'pt-BR': '21-50 clientes' }, emoji: '👥', impactScore: 15 },
      { id: '51-80', label: { es: '51-80 clientas', 'pt-BR': '51-80 clientes' }, emoji: '📈', impactScore: 18 },
      { id: '80+', label: { es: 'Más de 80', 'pt-BR': 'Mais de 80' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= SPA / MASAJES =============
export const SPA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_SPA_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de spa sos?', 'pt-BR': 'Que tipo de spa você é?' },
    type: 'single',
    required: true,
    businessTypes: ['spa_masajes'],
    options: [
      { id: 'day_spa', label: { es: 'Day Spa', 'pt-BR': 'Day Spa' }, emoji: '🌸', impactScore: 15 },
      { id: 'hotel_spa', label: { es: 'Spa de hotel', 'pt-BR': 'Spa de hotel' }, emoji: '🏨', impactScore: 18 },
      { id: 'medical_spa', label: { es: 'Spa médico', 'pt-BR': 'Spa médico' }, emoji: '🏥', impactScore: 20 },
      { id: 'thermal', label: { es: 'Termas/Aguas', 'pt-BR': 'Termas/Águas' }, emoji: '♨️', impactScore: 20 },
      { id: 'wellness', label: { es: 'Centro de bienestar', 'pt-BR': 'Centro de bem-estar' }, emoji: '🧘', impactScore: 15 },
    ],
  },
  {
    id: 'Q_SPA_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['spa_masajes'],
    options: [
      { id: 'massage', label: { es: 'Masajes', 'pt-BR': 'Massagens' }, emoji: '🧖', impactScore: 15 },
      { id: 'facial', label: { es: 'Tratamientos faciales', 'pt-BR': 'Tratamentos faciais' }, emoji: '✨', impactScore: 15 },
      { id: 'body', label: { es: 'Tratamientos corporales', 'pt-BR': 'Tratamentos corporais' }, emoji: '💆', impactScore: 15 },
      { id: 'hydrotherapy', label: { es: 'Hidroterapia', 'pt-BR': 'Hidroterapia' }, emoji: '🌊', impactScore: 18 },
      { id: 'sauna', label: { es: 'Sauna/Vapor', 'pt-BR': 'Sauna/Vapor' }, emoji: '🔥', impactScore: 15 },
      { id: 'yoga', label: { es: 'Yoga/Meditación', 'pt-BR': 'Yoga/Meditação' }, emoji: '🧘', impactScore: 12 },
    ],
  },
  {
    id: 'Q_SPA_CAPACITY',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántos clientes podés atender simultáneamente?', 'pt-BR': 'Quantos clientes você pode atender simultaneamente?' },
    type: 'single',
    businessTypes: ['spa_masajes'],
    options: [
      { id: '1-3', label: { es: '1-3 clientes', 'pt-BR': '1-3 clientes' }, emoji: '👤', impactScore: 10 },
      { id: '4-8', label: { es: '4-8 clientes', 'pt-BR': '4-8 clientes' }, emoji: '👥', impactScore: 15 },
      { id: '9-15', label: { es: '9-15 clientes', 'pt-BR': '9-15 clientes' }, emoji: '🏢', impactScore: 18 },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '🏨', impactScore: 20 },
    ],
  },
];

// ============= GIMNASIO / FITNESS =============
export const GIMNASIO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_GYM_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de gimnasio sos?', 'pt-BR': 'Que tipo de academia você é?' },
    type: 'single',
    required: true,
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'full', label: { es: 'Gimnasio completo', 'pt-BR': 'Academia completa' }, emoji: '🏋️', impactScore: 15 },
      { id: 'boutique', label: { es: 'Boutique/Especializado', 'pt-BR': 'Boutique/Especializado' }, emoji: '✨', impactScore: 18 },
      { id: 'crossfit', label: { es: 'CrossFit/Funcional', 'pt-BR': 'CrossFit/Funcional' }, emoji: '🔥', impactScore: 18 },
      { id: 'low_cost', label: { es: 'Low cost/24h', 'pt-BR': 'Low cost/24h' }, emoji: '💰', impactScore: 12 },
      { id: 'women_only', label: { es: 'Solo mujeres', 'pt-BR': 'Só mulheres' }, emoji: '👩', impactScore: 15 },
    ],
  },
  {
    id: 'Q_GYM_MEMBERS',
    category: 'finance',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cuántos socios activos tenés?', 'pt-BR': 'Quantos membros ativos você tem?' },
    type: 'single',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: '1-100', label: { es: '1-100 socios', 'pt-BR': '1-100 membros' }, emoji: '👤', impactScore: 10 },
      { id: '101-300', label: { es: '101-300 socios', 'pt-BR': '101-300 membros' }, emoji: '👥', impactScore: 15 },
      { id: '301-600', label: { es: '301-600 socios', 'pt-BR': '301-600 membros' }, emoji: '📈', impactScore: 18 },
      { id: '600+', label: { es: 'Más de 600', 'pt-BR': 'Mais de 600' }, emoji: '🔥', impactScore: 20 },
    ],
  },
  {
    id: 'Q_GYM_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['gimnasio_fitness'],
    options: [
      { id: 'weights', label: { es: 'Sala de pesas', 'pt-BR': 'Sala de musculação' }, emoji: '🏋️', impactScore: 12 },
      { id: 'cardio', label: { es: 'Zona cardio', 'pt-BR': 'Zona cardio' }, emoji: '🏃', impactScore: 12 },
      { id: 'classes', label: { es: 'Clases grupales', 'pt-BR': 'Aulas em grupo' }, emoji: '👥', impactScore: 15 },
      { id: 'personal', label: { es: 'Entrenamiento personal', 'pt-BR': 'Personal trainer' }, emoji: '💪', impactScore: 18 },
      { id: 'pool', label: { es: 'Piscina', 'pt-BR': 'Piscina' }, emoji: '🏊', impactScore: 18 },
      { id: 'spa', label: { es: 'Spa/Sauna', 'pt-BR': 'Spa/Sauna' }, emoji: '🧖', impactScore: 15 },
    ],
  },
];

// ============= YOGA / PILATES =============
export const YOGA_PILATES_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_YOGA_STYLE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué disciplinas ofrecés?', 'pt-BR': 'Quais disciplinas você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['yoga_pilates'],
    options: [
      { id: 'hatha', label: { es: 'Hatha Yoga', 'pt-BR': 'Hatha Yoga' }, emoji: '🧘', impactScore: 12 },
      { id: 'vinyasa', label: { es: 'Vinyasa/Flow', 'pt-BR': 'Vinyasa/Flow' }, emoji: '💨', impactScore: 15 },
      { id: 'mat_pilates', label: { es: 'Pilates Mat', 'pt-BR': 'Pilates Mat' }, emoji: '🤸', impactScore: 15 },
      { id: 'reformer', label: { es: 'Pilates Reformer', 'pt-BR': 'Pilates Reformer' }, emoji: '🔧', impactScore: 20 },
      { id: 'hot_yoga', label: { es: 'Hot Yoga', 'pt-BR': 'Hot Yoga' }, emoji: '🔥', impactScore: 18 },
      { id: 'aero', label: { es: 'Yoga aéreo/Suspensión', 'pt-BR': 'Yoga aéreo/Suspensão' }, emoji: '🎪', impactScore: 18 },
    ],
  },
  {
    id: 'Q_YOGA_CLASS_SIZE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántos alumnos por clase en promedio?', 'pt-BR': 'Quantos alunos por aula em média?' },
    type: 'single',
    businessTypes: ['yoga_pilates'],
    options: [
      { id: '1-3', label: { es: '1-3 (individual/dúo)', 'pt-BR': '1-3 (individual/dupla)' }, emoji: '👤', impactScore: 20 },
      { id: '4-8', label: { es: '4-8 alumnos', 'pt-BR': '4-8 alunos' }, emoji: '👥', impactScore: 18 },
      { id: '9-15', label: { es: '9-15 alumnos', 'pt-BR': '9-15 alunos' }, emoji: '🧘', impactScore: 15 },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '📈', impactScore: 12 },
    ],
  },
  {
    id: 'Q_YOGA_STUDENTS',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántos alumnos activos tenés?', 'pt-BR': 'Quantos alunos ativos você tem?' },
    type: 'single',
    businessTypes: ['yoga_pilates'],
    options: [
      { id: '1-30', label: { es: '1-30 alumnos', 'pt-BR': '1-30 alunos' }, emoji: '👤', impactScore: 10 },
      { id: '31-80', label: { es: '31-80 alumnos', 'pt-BR': '31-80 alunos' }, emoji: '👥', impactScore: 15 },
      { id: '81-150', label: { es: '81-150 alumnos', 'pt-BR': '81-150 alunos' }, emoji: '📈', impactScore: 18 },
      { id: '150+', label: { es: 'Más de 150', 'pt-BR': 'Mais de 150' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= PELUQUERIA / SALON =============
export const PELUQUERIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_PELO_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de salón sos?', 'pt-BR': 'Que tipo de salão você é?' },
    type: 'single',
    required: true,
    businessTypes: ['peluqueria_salon'],
    options: [
      { id: 'unisex', label: { es: 'Unisex', 'pt-BR': 'Unissex' }, emoji: '💇', impactScore: 12 },
      { id: 'women', label: { es: 'Femenino', 'pt-BR': 'Feminino' }, emoji: '💇‍♀️', impactScore: 15 },
      { id: 'premium', label: { es: 'Premium/Boutique', 'pt-BR': 'Premium/Boutique' }, emoji: '✨', impactScore: 20 },
      { id: 'color', label: { es: 'Especialista en color', 'pt-BR': 'Especialista em cor' }, emoji: '🎨', impactScore: 18 },
    ],
  },
  {
    id: 'Q_PELO_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['peluqueria_salon'],
    options: [
      { id: 'cut', label: { es: 'Corte', 'pt-BR': 'Corte' }, emoji: '✂️', impactScore: 12 },
      { id: 'color', label: { es: 'Color/Tintura', 'pt-BR': 'Cor/Tintura' }, emoji: '🎨', impactScore: 15 },
      { id: 'treatments', label: { es: 'Tratamientos capilares', 'pt-BR': 'Tratamentos capilares' }, emoji: '💆', impactScore: 15 },
      { id: 'styling', label: { es: 'Peinados/Eventos', 'pt-BR': 'Penteados/Eventos' }, emoji: '👰', impactScore: 15 },
      { id: 'extensions', label: { es: 'Extensiones', 'pt-BR': 'Extensões' }, emoji: '💇', impactScore: 18 },
      { id: 'nails', label: { es: 'Manicura/Pedicura', 'pt-BR': 'Manicure/Pedicure' }, emoji: '💅', impactScore: 12 },
    ],
  },
  {
    id: 'Q_PELO_STATIONS',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántos puestos de trabajo tenés?', 'pt-BR': 'Quantos postos de trabalho você tem?' },
    type: 'single',
    businessTypes: ['peluqueria_salon'],
    options: [
      { id: '1', label: { es: '1 puesto', 'pt-BR': '1 posto' }, emoji: '💇', impactScore: 10 },
      { id: '2-4', label: { es: '2-4 puestos', 'pt-BR': '2-4 postos' }, emoji: '🏠', impactScore: 15 },
      { id: '5-8', label: { es: '5-8 puestos', 'pt-BR': '5-8 postos' }, emoji: '🏢', impactScore: 18 },
      { id: '8+', label: { es: 'Más de 8', 'pt-BR': 'Mais de 8' }, emoji: '🏪', impactScore: 20 },
    ],
  },
];

// ============= BARBERIA =============
export const BARBERIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_BARBER_STYLE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué estilo de barbería sos?', 'pt-BR': 'Que estilo de barbearia você é?' },
    type: 'single',
    required: true,
    businessTypes: ['barberia'],
    options: [
      { id: 'classic', label: { es: 'Clásica/Tradicional', 'pt-BR': 'Clássica/Tradicional' }, emoji: '💈', impactScore: 12 },
      { id: 'modern', label: { es: 'Moderna/Urbana', 'pt-BR': 'Moderna/Urbana' }, emoji: '🔥', impactScore: 18 },
      { id: 'premium', label: { es: 'Premium/Lounge', 'pt-BR': 'Premium/Lounge' }, emoji: '✨', impactScore: 20 },
      { id: 'neighborhood', label: { es: 'De barrio', 'pt-BR': 'De bairro' }, emoji: '🏘️', impactScore: 10 },
    ],
  },
  {
    id: 'Q_BARBER_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['barberia'],
    options: [
      { id: 'cut', label: { es: 'Corte', 'pt-BR': 'Corte' }, emoji: '✂️', impactScore: 12 },
      { id: 'beard', label: { es: 'Barba', 'pt-BR': 'Barba' }, emoji: '🧔', impactScore: 15 },
      { id: 'shave', label: { es: 'Afeitado clásico', 'pt-BR': 'Barbear clássico' }, emoji: '🪒', impactScore: 15 },
      { id: 'treatments', label: { es: 'Tratamientos faciales', 'pt-BR': 'Tratamentos faciais' }, emoji: '🧖‍♂️', impactScore: 18 },
      { id: 'color', label: { es: 'Color/Decoloración', 'pt-BR': 'Cor/Descoloração' }, emoji: '🎨', impactScore: 15 },
    ],
  },
  {
    id: 'Q_BARBER_CLIENTS_WEEK',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántos clientes atendés por semana?', 'pt-BR': 'Quantos clientes você atende por semana?' },
    type: 'single',
    businessTypes: ['barberia'],
    options: [
      { id: '1-30', label: { es: '1-30 clientes', 'pt-BR': '1-30 clientes' }, emoji: '👤', impactScore: 10 },
      { id: '31-60', label: { es: '31-60 clientes', 'pt-BR': '31-60 clientes' }, emoji: '👥', impactScore: 15 },
      { id: '61-100', label: { es: '61-100 clientes', 'pt-BR': '61-100 clientes' }, emoji: '📈', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= MANICURIA / UÑAS =============
export const MANICURIA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_NAILS_SERVICES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['manicuria_unas'],
    options: [
      { id: 'manicure', label: { es: 'Manicura tradicional', 'pt-BR': 'Manicure tradicional' }, emoji: '💅', impactScore: 12 },
      { id: 'pedicure', label: { es: 'Pedicura', 'pt-BR': 'Pedicure' }, emoji: '🦶', impactScore: 12 },
      { id: 'gel', label: { es: 'Semipermanente/Gel', 'pt-BR': 'Gel/Semipermanente' }, emoji: '✨', impactScore: 18 },
      { id: 'acrylic', label: { es: 'Acrílicas/Esculpidas', 'pt-BR': 'Acrílicas/Esculpidas' }, emoji: '💎', impactScore: 18 },
      { id: 'nail_art', label: { es: 'Nail art/Diseños', 'pt-BR': 'Nail art/Designs' }, emoji: '🎨', impactScore: 15 },
    ],
  },
  {
    id: 'Q_NAILS_STATIONS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántos puestos de atención tenés?', 'pt-BR': 'Quantos postos de atendimento você tem?' },
    type: 'single',
    businessTypes: ['manicuria_unas'],
    options: [
      { id: '1', label: { es: '1 puesto (solo yo)', 'pt-BR': '1 posto (só eu)' }, emoji: '💅', impactScore: 10 },
      { id: '2-3', label: { es: '2-3 puestos', 'pt-BR': '2-3 postos' }, emoji: '🏠', impactScore: 15 },
      { id: '4-6', label: { es: '4-6 puestos', 'pt-BR': '4-6 postos' }, emoji: '🏢', impactScore: 18 },
      { id: '6+', label: { es: 'Más de 6', 'pt-BR': 'Mais de 6' }, emoji: '🏪', impactScore: 20 },
    ],
  },
  {
    id: 'Q_NAILS_CLIENTS_WEEK',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántas clientas atendés por semana?', 'pt-BR': 'Quantas clientes você atende por semana?' },
    type: 'single',
    businessTypes: ['manicuria_unas'],
    options: [
      { id: '1-15', label: { es: '1-15 clientas', 'pt-BR': '1-15 clientes' }, emoji: '👤', impactScore: 10 },
      { id: '16-35', label: { es: '16-35 clientas', 'pt-BR': '16-35 clientes' }, emoji: '👥', impactScore: 15 },
      { id: '36-60', label: { es: '36-60 clientas', 'pt-BR': '36-60 clientes' }, emoji: '📈', impactScore: 18 },
      { id: '60+', label: { es: 'Más de 60', 'pt-BR': 'Mais de 60' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= DEPILACION =============
export const DEPILACION_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_DEPI_METHODS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué métodos de depilación ofrecés?', 'pt-BR': 'Quais métodos de depilação você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['depilacion'],
    options: [
      { id: 'wax', label: { es: 'Cera tradicional', 'pt-BR': 'Cera tradicional' }, emoji: '🍯', impactScore: 12 },
      { id: 'laser', label: { es: 'Láser', 'pt-BR': 'Laser' }, emoji: '⚡', impactScore: 22 },
      { id: 'ipl', label: { es: 'Luz pulsada (IPL)', 'pt-BR': 'Luz pulsada (IPL)' }, emoji: '💡', impactScore: 18 },
      { id: 'diode', label: { es: 'Diodo', 'pt-BR': 'Diodo' }, emoji: '🔬', impactScore: 20 },
      { id: 'electrolysis', label: { es: 'Electrólisis', 'pt-BR': 'Eletrólise' }, emoji: '⚡', impactScore: 15 },
    ],
  },
  {
    id: 'Q_DEPI_CABINS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántas cabinas tenés?', 'pt-BR': 'Quantas cabines você tem?' },
    type: 'single',
    businessTypes: ['depilacion'],
    options: [
      { id: '1', label: { es: '1 cabina', 'pt-BR': '1 cabine' }, emoji: '🚪', impactScore: 10 },
      { id: '2-3', label: { es: '2-3 cabinas', 'pt-BR': '2-3 cabines' }, emoji: '🏠', impactScore: 15 },
      { id: '4-6', label: { es: '4-6 cabinas', 'pt-BR': '4-6 cabines' }, emoji: '🏢', impactScore: 18 },
      { id: '6+', label: { es: 'Más de 6', 'pt-BR': 'Mais de 6' }, emoji: '🏪', impactScore: 20 },
    ],
  },
  {
    id: 'Q_DEPI_SESSIONS_WEEK',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántas sesiones realizás por semana?', 'pt-BR': 'Quantas sessões você realiza por semana?' },
    type: 'single',
    businessTypes: ['depilacion'],
    options: [
      { id: '1-20', label: { es: '1-20 sesiones', 'pt-BR': '1-20 sessões' }, emoji: '📊', impactScore: 10 },
      { id: '21-50', label: { es: '21-50 sesiones', 'pt-BR': '21-50 sessões' }, emoji: '📈', impactScore: 15 },
      { id: '51-100', label: { es: '51-100 sesiones', 'pt-BR': '51-100 sessões' }, emoji: '🚀', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// ============= OPTICA / CONTACTOLOGIA =============
export const OPTICA_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_OPTIC_SERVICES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['optica_contactologia'],
    options: [
      { id: 'glasses', label: { es: 'Venta de anteojos', 'pt-BR': 'Venda de óculos' }, emoji: '👓', impactScore: 15 },
      { id: 'contacts', label: { es: 'Lentes de contacto', 'pt-BR': 'Lentes de contato' }, emoji: '👁️', impactScore: 18 },
      { id: 'exams', label: { es: 'Exámenes visuales', 'pt-BR': 'Exames visuais' }, emoji: '🔬', impactScore: 18 },
      { id: 'sunglasses', label: { es: 'Anteojos de sol', 'pt-BR': 'Óculos de sol' }, emoji: '🕶️', impactScore: 12 },
      { id: 'low_vision', label: { es: 'Baja visión', 'pt-BR': 'Baixa visão' }, emoji: '🔍', impactScore: 15 },
    ],
  },
  {
    id: 'Q_OPTIC_LAB',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Tenés laboratorio propio?', 'pt-BR': 'Você tem laboratório próprio?' },
    type: 'single',
    businessTypes: ['optica_contactologia'],
    options: [
      { id: 'full', label: { es: 'Sí, completo', 'pt-BR': 'Sim, completo' }, emoji: '🔬', impactScore: 20 },
      { id: 'basic', label: { es: 'Básico (montaje)', 'pt-BR': 'Básico (montagem)' }, emoji: '🔧', impactScore: 15 },
      { id: 'external', label: { es: 'No, tercerizo', 'pt-BR': 'Não, terceirizo' }, emoji: '📤', impactScore: 10 },
    ],
  },
  {
    id: 'Q_OPTIC_CUSTOMERS_WEEK',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuántos clientes atendés por semana?', 'pt-BR': 'Quantos clientes você atende por semana?' },
    type: 'single',
    businessTypes: ['optica_contactologia'],
    options: [
      { id: '1-20', label: { es: '1-20 clientes', 'pt-BR': '1-20 clientes' }, emoji: '👤', impactScore: 10 },
      { id: '21-50', label: { es: '21-50 clientes', 'pt-BR': '21-50 clientes' }, emoji: '👥', impactScore: 15 },
      { id: '51-100', label: { es: '51-100 clientes', 'pt-BR': '51-100 clientes' }, emoji: '📈', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🔥', impactScore: 20 },
    ],
  },
];

// Export all health questions
export const ALL_SALUD_QUESTIONS: GastroQuestion[] = [
  ...CLINICA_QUESTIONS,
  ...CONSULTORIO_QUESTIONS,
  ...ODONTOLOGIA_QUESTIONS,
  ...LABORATORIO_QUESTIONS,
  ...DIAGNOSTICO_IMAGENES_QUESTIONS,
  ...KINESIOLOGIA_QUESTIONS,
  ...PSICOLOGIA_QUESTIONS,
  ...NUTRICION_QUESTIONS,
  ...MEDICINA_ESTETICA_QUESTIONS,
  ...CENTRO_ESTETICA_QUESTIONS,
  ...SPA_QUESTIONS,
  ...GIMNASIO_QUESTIONS,
  ...YOGA_PILATES_QUESTIONS,
  ...PELUQUERIA_QUESTIONS,
  ...BARBERIA_QUESTIONS,
  ...MANICURIA_QUESTIONS,
  ...DEPILACION_QUESTIONS,
  ...OPTICA_QUESTIONS,
];
