// Tourism, Hospitality, Leisure & Events - Ultra-specific Questionnaire
// Sector A2_TURISMO - 18 business types with 5-8 questions each

import type { GastroQuestion } from '../gastroQuestionsEngine';

// ============= HOTEL URBANO / BUSINESS QUESTIONS =============
export const HOTEL_URBANO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_HOTEL_STARS',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuántas estrellas tiene tu hotel?', 'pt-BR': 'Quantas estrelas tem seu hotel?' },
    help: { es: 'Categorización oficial o equivalente', 'pt-BR': 'Categorização oficial ou equivalente' },
    type: 'single',
    required: true,
    businessTypes: ['hotel_urbano'],
    options: [
      { id: '5_stars', label: { es: '5 estrellas / Luxury', 'pt-BR': '5 estrelas / Luxo' }, emoji: '⭐', impactScore: 25 },
      { id: '4_stars', label: { es: '4 estrellas / Superior', 'pt-BR': '4 estrelas / Superior' }, emoji: '🌟', impactScore: 20 },
      { id: '3_stars', label: { es: '3 estrellas / Standard', 'pt-BR': '3 estrelas / Standard' }, emoji: '✨', impactScore: 15 },
      { id: '2_stars', label: { es: '2 estrellas / Económico', 'pt-BR': '2 estrelas / Econômico' }, emoji: '🏨', impactScore: 10 },
      { id: 'unrated', label: { es: 'Sin categorizar', 'pt-BR': 'Sem categoria' }, emoji: '🏢', impactScore: 5 },
    ],
  },
  {
    id: 'Q_HOTEL_ROOMS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántas habitaciones tenés?', 'pt-BR': 'Quantos quartos você tem?' },
    type: 'single',
    businessTypes: ['hotel_urbano'],
    options: [
      { id: '1-20', label: { es: '1-20 habitaciones', 'pt-BR': '1-20 quartos' }, emoji: '🛏️', impactScore: 8 },
      { id: '21-50', label: { es: '21-50 habitaciones', 'pt-BR': '21-50 quartos' }, emoji: '🏨', impactScore: 12 },
      { id: '51-100', label: { es: '51-100 habitaciones', 'pt-BR': '51-100 quartos' }, emoji: '🏢', impactScore: 15 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🏙️', impactScore: 20 },
    ],
  },
  {
    id: 'Q_HOTEL_OCCUPANCY',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 9,
    title: { es: '¿Cuál es tu ocupación promedio anual?', 'pt-BR': 'Qual é sua ocupação média anual?' },
    help: { es: 'Porcentaje de habitaciones vendidas', 'pt-BR': 'Porcentagem de quartos vendidos' },
    type: 'single',
    businessTypes: ['hotel_urbano'],
    options: [
      { id: 'high_80', label: { es: '+80% ocupación', 'pt-BR': '+80% ocupação' }, emoji: '🔥', impactScore: 25 },
      { id: 'good_60', label: { es: '60-80% ocupación', 'pt-BR': '60-80% ocupação' }, emoji: '👍', impactScore: 18 },
      { id: 'medium_40', label: { es: '40-60% ocupación', 'pt-BR': '40-60% ocupação' }, emoji: '📊', impactScore: 10 },
      { id: 'low_40', label: { es: 'Menos del 40%', 'pt-BR': 'Menos de 40%' }, emoji: '📉', impactScore: 0 },
    ],
  },
  {
    id: 'Q_HOTEL_OTA',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Qué OTAs/canales usás para vender?', 'pt-BR': 'Quais OTAs/canais você usa para vender?' },
    type: 'multi',
    businessTypes: ['hotel_urbano'],
    options: [
      { id: 'booking', label: { es: 'Booking.com', 'pt-BR': 'Booking.com' }, emoji: '🔵', impactScore: 15 },
      { id: 'expedia', label: { es: 'Expedia/Hotels.com', 'pt-BR': 'Expedia/Hotels.com' }, emoji: '🟡', impactScore: 12 },
      { id: 'airbnb', label: { es: 'Airbnb', 'pt-BR': 'Airbnb' }, emoji: '🏠', impactScore: 10 },
      { id: 'direct', label: { es: 'Web propia/Directo', 'pt-BR': 'Site próprio/Direto' }, emoji: '🌐', impactScore: 20 },
      { id: 'corporate', label: { es: 'Corporativos/Agencias', 'pt-BR': 'Corporativos/Agências' }, emoji: '🏢', impactScore: 15 },
    ],
  },
  {
    id: 'Q_HOTEL_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['hotel_urbano'],
    options: [
      { id: 'breakfast', label: { es: 'Desayuno incluido', 'pt-BR': 'Café da manhã incluído' }, emoji: '🥐', impactScore: 10 },
      { id: 'restaurant', label: { es: 'Restaurante propio', 'pt-BR': 'Restaurante próprio' }, emoji: '🍽️', impactScore: 12 },
      { id: 'gym', label: { es: 'Gimnasio', 'pt-BR': 'Academia' }, emoji: '🏋️', impactScore: 8 },
      { id: 'pool', label: { es: 'Piscina', 'pt-BR': 'Piscina' }, emoji: '🏊', impactScore: 10 },
      { id: 'spa', label: { es: 'Spa/Wellness', 'pt-BR': 'Spa/Wellness' }, emoji: '🧖', impactScore: 12 },
      { id: 'meeting', label: { es: 'Salas de reuniones', 'pt-BR': 'Salas de reuniões' }, emoji: '📊', impactScore: 10 },
      { id: 'parking', label: { es: 'Estacionamiento', 'pt-BR': 'Estacionamento' }, emoji: '🅿️', impactScore: 8 },
    ],
  },
  {
    id: 'Q_HOTEL_CORPORATE_PCT',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Qué % de huéspedes son corporativos?', 'pt-BR': 'Qual % de hóspedes são corporativos?' },
    type: 'single',
    businessTypes: ['hotel_urbano'],
    options: [
      { id: 'high_70', label: { es: '+70% corporativo', 'pt-BR': '+70% corporativo' }, emoji: '💼', impactScore: 15 },
      { id: 'mixed_50', label: { es: '40-70% corporativo', 'pt-BR': '40-70% corporativo' }, emoji: '📊', impactScore: 12 },
      { id: 'leisure_mostly', label: { es: 'Mayoría turismo', 'pt-BR': 'Maioria turismo' }, emoji: '🧳', impactScore: 10 },
      { id: 'events', label: { es: 'Eventos/Grupos', 'pt-BR': 'Eventos/Grupos' }, emoji: '🎉', impactScore: 10 },
    ],
  },
];

// ============= HOTEL BOUTIQUE QUESTIONS =============
export const HOTEL_BOUTIQUE_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_BOUTIQUE_CONCEPT',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuál es el concepto/temática de tu hotel?', 'pt-BR': 'Qual é o conceito/temática do seu hotel?' },
    type: 'single',
    required: true,
    businessTypes: ['hotel_boutique'],
    options: [
      { id: 'design', label: { es: 'Diseño/Arquitectura', 'pt-BR': 'Design/Arquitetura' }, emoji: '🎨', impactScore: 20 },
      { id: 'historic', label: { es: 'Histórico/Patrimonio', 'pt-BR': 'Histórico/Patrimônio' }, emoji: '🏛️', impactScore: 18 },
      { id: 'wellness', label: { es: 'Wellness/Bienestar', 'pt-BR': 'Wellness/Bem-estar' }, emoji: '🧘', impactScore: 15 },
      { id: 'gastro', label: { es: 'Gastronómico', 'pt-BR': 'Gastronômico' }, emoji: '👨‍🍳', impactScore: 18 },
      { id: 'artistic', label: { es: 'Artístico/Cultural', 'pt-BR': 'Artístico/Cultural' }, emoji: '🖼️', impactScore: 15 },
      { id: 'nature', label: { es: 'Naturaleza/Eco', 'pt-BR': 'Natureza/Eco' }, emoji: '🌿', impactScore: 15 },
    ],
  },
  {
    id: 'Q_BOUTIQUE_ROOMS_COUNT',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántas habitaciones tenés?', 'pt-BR': 'Quantos quartos você tem?' },
    type: 'single',
    businessTypes: ['hotel_boutique'],
    options: [
      { id: '1-10', label: { es: '1-10 habitaciones', 'pt-BR': '1-10 quartos' }, emoji: '🏠', impactScore: 15 },
      { id: '11-25', label: { es: '11-25 habitaciones', 'pt-BR': '11-25 quartos' }, emoji: '🏨', impactScore: 12 },
      { id: '26-50', label: { es: '26-50 habitaciones', 'pt-BR': '26-50 quartos' }, emoji: '🏢', impactScore: 8 },
    ],
  },
  {
    id: 'Q_BOUTIQUE_EXPERIENCE',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué experiencias exclusivas ofrecés?', 'pt-BR': 'Quais experiências exclusivas você oferece?' },
    type: 'multi',
    businessTypes: ['hotel_boutique'],
    options: [
      { id: 'tasting', label: { es: 'Catas/Degustaciones', 'pt-BR': 'Degustações' }, emoji: '🍷', impactScore: 12 },
      { id: 'tours', label: { es: 'Tours privados', 'pt-BR': 'Tours privados' }, emoji: '🗺️', impactScore: 12 },
      { id: 'cooking', label: { es: 'Clases de cocina', 'pt-BR': 'Aulas de culinária' }, emoji: '👨‍🍳', impactScore: 10 },
      { id: 'spa', label: { es: 'Tratamientos spa', 'pt-BR': 'Tratamentos spa' }, emoji: '🧖', impactScore: 12 },
      { id: 'concierge', label: { es: 'Concierge dedicado', 'pt-BR': 'Concierge dedicado' }, emoji: '🎩', impactScore: 15 },
      { id: 'rooftop', label: { es: 'Rooftop/Vista exclusiva', 'pt-BR': 'Rooftop/Vista exclusiva' }, emoji: '🌃', impactScore: 12 },
    ],
  },
  {
    id: 'Q_BOUTIQUE_ADR',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu tarifa promedio por noche (ADR)?', 'pt-BR': 'Qual é sua tarifa média por noite (ADR)?' },
    type: 'single',
    businessTypes: ['hotel_boutique'],
    options: [
      { id: 'luxury_300', label: { es: '+$300 USD/noche', 'pt-BR': '+$300 USD/noite' }, emoji: '💎', impactScore: 25 },
      { id: 'premium_150', label: { es: '$150-300 USD/noche', 'pt-BR': '$150-300 USD/noite' }, emoji: '✨', impactScore: 20 },
      { id: 'mid_80', label: { es: '$80-150 USD/noche', 'pt-BR': '$80-150 USD/noite' }, emoji: '🏨', impactScore: 12 },
      { id: 'accessible', label: { es: 'Menos de $80 USD', 'pt-BR': 'Menos de $80 USD' }, emoji: '💰', impactScore: 8 },
    ],
  },
  {
    id: 'Q_BOUTIQUE_REVIEWS',
    category: 'marketing',
    mode: 'complete',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Cuál es tu rating promedio en OTAs?', 'pt-BR': 'Qual é seu rating médio nas OTAs?' },
    type: 'single',
    businessTypes: ['hotel_boutique'],
    options: [
      { id: 'excellent_95', label: { es: '9.5+ Excepcional', 'pt-BR': '9.5+ Excepcional' }, emoji: '🏆', impactScore: 25 },
      { id: 'great_9', label: { es: '9.0-9.4 Excelente', 'pt-BR': '9.0-9.4 Excelente' }, emoji: '⭐', impactScore: 20 },
      { id: 'good_85', label: { es: '8.5-8.9 Muy bueno', 'pt-BR': '8.5-8.9 Muito bom' }, emoji: '👍', impactScore: 12 },
      { id: 'ok_8', label: { es: 'Menos de 8.5', 'pt-BR': 'Menos de 8.5' }, emoji: '📊', impactScore: 5 },
    ],
  },
];

// ============= RESORT / ALL INCLUSIVE QUESTIONS =============
export const RESORT_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_RESORT_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de resort sos?', 'pt-BR': 'Que tipo de resort você é?' },
    type: 'single',
    required: true,
    businessTypes: ['resort_all_inclusive'],
    options: [
      { id: 'beach', label: { es: 'Resort de playa', 'pt-BR': 'Resort de praia' }, emoji: '🏖️', impactScore: 20 },
      { id: 'mountain', label: { es: 'Resort de montaña', 'pt-BR': 'Resort de montanha' }, emoji: '⛰️', impactScore: 18 },
      { id: 'spa_wellness', label: { es: 'Spa & Wellness resort', 'pt-BR': 'Spa & Wellness resort' }, emoji: '🧖', impactScore: 18 },
      { id: 'golf', label: { es: 'Golf resort', 'pt-BR': 'Golf resort' }, emoji: '⛳', impactScore: 20 },
      { id: 'family', label: { es: 'Resort familiar', 'pt-BR': 'Resort familiar' }, emoji: '👨‍👩‍👧', impactScore: 15 },
      { id: 'adults_only', label: { es: 'Solo adultos', 'pt-BR': 'Somente adultos' }, emoji: '🥂', impactScore: 18 },
    ],
  },
  {
    id: 'Q_RESORT_PLAN',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué planes de estadía ofrecés?', 'pt-BR': 'Quais planos de estadia você oferece?' },
    type: 'multi',
    businessTypes: ['resort_all_inclusive'],
    options: [
      { id: 'all_inclusive', label: { es: 'All Inclusive', 'pt-BR': 'All Inclusive' }, emoji: '🎉', impactScore: 20 },
      { id: 'half_board', label: { es: 'Media pensión', 'pt-BR': 'Meia pensão' }, emoji: '🍽️', impactScore: 12 },
      { id: 'full_board', label: { es: 'Pensión completa', 'pt-BR': 'Pensão completa' }, emoji: '🍳', impactScore: 15 },
      { id: 'room_only', label: { es: 'Solo habitación', 'pt-BR': 'Somente quarto' }, emoji: '🛏️', impactScore: 8 },
    ],
  },
  {
    id: 'Q_RESORT_ACTIVITIES',
    category: 'menu',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Qué actividades incluye tu resort?', 'pt-BR': 'Quais atividades seu resort inclui?' },
    type: 'multi',
    businessTypes: ['resort_all_inclusive'],
    options: [
      { id: 'pool', label: { es: 'Piscinas', 'pt-BR': 'Piscinas' }, emoji: '🏊', impactScore: 10 },
      { id: 'water_sports', label: { es: 'Deportes acuáticos', 'pt-BR': 'Esportes aquáticos' }, emoji: '🏄', impactScore: 12 },
      { id: 'spa', label: { es: 'Spa', 'pt-BR': 'Spa' }, emoji: '🧖', impactScore: 10 },
      { id: 'kids_club', label: { es: 'Kids club', 'pt-BR': 'Kids club' }, emoji: '🧒', impactScore: 12 },
      { id: 'entertainment', label: { es: 'Shows/Entretenimiento', 'pt-BR': 'Shows/Entretenimento' }, emoji: '🎭', impactScore: 12 },
      { id: 'excursions', label: { es: 'Excursiones', 'pt-BR': 'Excursões' }, emoji: '🗺️', impactScore: 10 },
    ],
  },
  {
    id: 'Q_RESORT_STAY_LENGTH',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuál es la estadía promedio?', 'pt-BR': 'Qual é a estadia média?' },
    type: 'single',
    businessTypes: ['resort_all_inclusive'],
    options: [
      { id: '1-3', label: { es: '1-3 noches', 'pt-BR': '1-3 noites' }, emoji: '⚡', impactScore: 8 },
      { id: '4-7', label: { es: '4-7 noches', 'pt-BR': '4-7 noites' }, emoji: '📅', impactScore: 15 },
      { id: '7-14', label: { es: '7-14 noches', 'pt-BR': '7-14 noites' }, emoji: '🏝️', impactScore: 20 },
      { id: '14+', label: { es: 'Más de 14 noches', 'pt-BR': 'Mais de 14 noites' }, emoji: '🌴', impactScore: 18 },
    ],
  },
];

// ============= HOSTEL / HOSTAL QUESTIONS =============
export const HOSTEL_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_HOSTEL_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de hostel sos?', 'pt-BR': 'Que tipo de hostel você é?' },
    type: 'single',
    required: true,
    businessTypes: ['hostel'],
    options: [
      { id: 'party', label: { es: 'Hostel fiestero', 'pt-BR': 'Hostel festivo' }, emoji: '🎉', impactScore: 15 },
      { id: 'social', label: { es: 'Social/Comunitario', 'pt-BR': 'Social/Comunitário' }, emoji: '👥', impactScore: 12 },
      { id: 'quiet', label: { es: 'Tranquilo/Descanso', 'pt-BR': 'Tranquilo/Descanso' }, emoji: '😌', impactScore: 12 },
      { id: 'boutique', label: { es: 'Hostel boutique', 'pt-BR': 'Hostel boutique' }, emoji: '✨', impactScore: 18 },
      { id: 'backpacker', label: { es: 'Mochilero clásico', 'pt-BR': 'Mochileiro clássico' }, emoji: '🎒', impactScore: 10 },
    ],
  },
  {
    id: 'Q_HOSTEL_BEDS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántas camas tenés en total?', 'pt-BR': 'Quantas camas você tem no total?' },
    type: 'single',
    businessTypes: ['hostel'],
    options: [
      { id: '1-20', label: { es: '1-20 camas', 'pt-BR': '1-20 camas' }, emoji: '🛏️', impactScore: 8 },
      { id: '21-50', label: { es: '21-50 camas', 'pt-BR': '21-50 camas' }, emoji: '🏨', impactScore: 12 },
      { id: '51-100', label: { es: '51-100 camas', 'pt-BR': '51-100 camas' }, emoji: '🏢', impactScore: 15 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🏙️', impactScore: 18 },
    ],
  },
  {
    id: 'Q_HOSTEL_ROOM_TYPES',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Qué tipos de habitación ofrecés?', 'pt-BR': 'Quais tipos de quarto você oferece?' },
    type: 'multi',
    businessTypes: ['hostel'],
    options: [
      { id: 'dorm_4', label: { es: 'Dormitorio 4-6 camas', 'pt-BR': 'Dormitório 4-6 camas' }, emoji: '🛏️', impactScore: 10 },
      { id: 'dorm_8', label: { es: 'Dormitorio 8-12 camas', 'pt-BR': 'Dormitório 8-12 camas' }, emoji: '🏢', impactScore: 8 },
      { id: 'private', label: { es: 'Privadas', 'pt-BR': 'Privados' }, emoji: '🔒', impactScore: 15 },
      { id: 'female', label: { es: 'Solo mujeres', 'pt-BR': 'Só mulheres' }, emoji: '👩', impactScore: 10 },
      { id: 'pods', label: { es: 'Pods/Cápsulas', 'pt-BR': 'Pods/Cápsulas' }, emoji: '📦', impactScore: 12 },
    ],
  },
  {
    id: 'Q_HOSTEL_ACTIVITIES',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Qué actividades organizás?', 'pt-BR': 'Quais atividades você organiza?' },
    type: 'multi',
    businessTypes: ['hostel'],
    options: [
      { id: 'walking_tours', label: { es: 'Walking tours', 'pt-BR': 'Walking tours' }, emoji: '🚶', impactScore: 12 },
      { id: 'pub_crawl', label: { es: 'Pub crawl', 'pt-BR': 'Pub crawl' }, emoji: '🍻', impactScore: 10 },
      { id: 'dinners', label: { es: 'Cenas grupales', 'pt-BR': 'Jantares em grupo' }, emoji: '🍽️', impactScore: 10 },
      { id: 'games', label: { es: 'Noches de juegos', 'pt-BR': 'Noites de jogos' }, emoji: '🎲', impactScore: 8 },
      { id: 'yoga', label: { es: 'Yoga/Meditación', 'pt-BR': 'Yoga/Meditação' }, emoji: '🧘', impactScore: 8 },
      { id: 'none', label: { es: 'No organizamos', 'pt-BR': 'Não organizamos' }, emoji: '❌', impactScore: 0 },
    ],
  },
  {
    id: 'Q_HOSTEL_BOOKING_SOURCE',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿De dónde vienen tus reservas?', 'pt-BR': 'De onde vêm suas reservas?' },
    type: 'multi',
    businessTypes: ['hostel'],
    options: [
      { id: 'hostelworld', label: { es: 'Hostelworld', 'pt-BR': 'Hostelworld' }, emoji: '🌍', impactScore: 15 },
      { id: 'booking', label: { es: 'Booking.com', 'pt-BR': 'Booking.com' }, emoji: '🔵', impactScore: 12 },
      { id: 'direct', label: { es: 'Web propia', 'pt-BR': 'Site próprio' }, emoji: '🌐', impactScore: 18 },
      { id: 'walkin', label: { es: 'Walk-ins', 'pt-BR': 'Walk-ins' }, emoji: '🚶', impactScore: 8 },
      { id: 'google', label: { es: 'Google/Maps', 'pt-BR': 'Google/Maps' }, emoji: '📍', impactScore: 10 },
    ],
  },
];

// ============= AGENCIA DE VIAJES QUESTIONS =============
export const AGENCIA_VIAJES_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_AGENCIA_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de agencia sos?', 'pt-BR': 'Que tipo de agência você é?' },
    type: 'single',
    required: true,
    businessTypes: ['agencia_viajes'],
    options: [
      { id: 'traditional', label: { es: 'Agencia tradicional (local)', 'pt-BR': 'Agência tradicional (física)' }, emoji: '🏪', impactScore: 12 },
      { id: 'online', label: { es: 'Agencia online (OTA propia)', 'pt-BR': 'Agência online (OTA própria)' }, emoji: '💻', impactScore: 18 },
      { id: 'corporate', label: { es: 'Corporativa/Empresas', 'pt-BR': 'Corporativa/Empresas' }, emoji: '💼', impactScore: 20 },
      { id: 'specialized', label: { es: 'Especializada (nicho)', 'pt-BR': 'Especializada (nicho)' }, emoji: '🎯', impactScore: 18 },
      { id: 'hybrid', label: { es: 'Híbrida (local + online)', 'pt-BR': 'Híbrida (física + online)' }, emoji: '🔄', impactScore: 15 },
    ],
  },
  {
    id: 'Q_AGENCIA_PRODUCTS',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué productos vendés más?', 'pt-BR': 'Quais produtos você mais vende?' },
    type: 'multi',
    businessTypes: ['agencia_viajes'],
    options: [
      { id: 'packages', label: { es: 'Paquetes armados', 'pt-BR': 'Pacotes montados' }, emoji: '📦', impactScore: 15 },
      { id: 'flights', label: { es: 'Aéreos sueltos', 'pt-BR': 'Aéreos avulsos' }, emoji: '✈️', impactScore: 10 },
      { id: 'hotels', label: { es: 'Hoteles/Alojamiento', 'pt-BR': 'Hotéis/Hospedagem' }, emoji: '🏨', impactScore: 12 },
      { id: 'cruises', label: { es: 'Cruceros', 'pt-BR': 'Cruzeiros' }, emoji: '🚢', impactScore: 15 },
      { id: 'insurance', label: { es: 'Asistencia al viajero', 'pt-BR': 'Seguro viagem' }, emoji: '🛡️', impactScore: 8 },
      { id: 'transfers', label: { es: 'Transfers/Traslados', 'pt-BR': 'Transfers/Traslados' }, emoji: '🚐', impactScore: 8 },
    ],
  },
  {
    id: 'Q_AGENCIA_DESTINATION',
    category: 'menu',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuál es tu destino principal?', 'pt-BR': 'Qual é seu destino principal?' },
    type: 'single',
    businessTypes: ['agencia_viajes'],
    options: [
      { id: 'domestic', label: { es: 'Nacional/Doméstico', 'pt-BR': 'Nacional/Doméstico' }, emoji: '🏠', impactScore: 10 },
      { id: 'latam', label: { es: 'Latinoamérica', 'pt-BR': 'América Latina' }, emoji: '🌎', impactScore: 12 },
      { id: 'usa_caribe', label: { es: 'USA/Caribe', 'pt-BR': 'EUA/Caribe' }, emoji: '🏝️', impactScore: 15 },
      { id: 'europe', label: { es: 'Europa', 'pt-BR': 'Europa' }, emoji: '🇪🇺', impactScore: 15 },
      { id: 'worldwide', label: { es: 'Mundial/Variado', 'pt-BR': 'Mundial/Variado' }, emoji: '🌍', impactScore: 18 },
    ],
  },
  {
    id: 'Q_AGENCIA_TECH',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Qué tecnología usás para cotizar?', 'pt-BR': 'Qual tecnologia você usa para cotar?' },
    type: 'single',
    businessTypes: ['agencia_viajes'],
    options: [
      { id: 'gds', label: { es: 'GDS (Amadeus, Sabre)', 'pt-BR': 'GDS (Amadeus, Sabre)' }, emoji: '💻', impactScore: 20 },
      { id: 'b2b', label: { es: 'Plataformas B2B', 'pt-BR': 'Plataformas B2B' }, emoji: '🔗', impactScore: 15 },
      { id: 'direct', label: { es: 'Directo con proveedores', 'pt-BR': 'Direto com fornecedores' }, emoji: '📞', impactScore: 10 },
      { id: 'mixed', label: { es: 'Combinación', 'pt-BR': 'Combinação' }, emoji: '🔄', impactScore: 12 },
    ],
  },
  {
    id: 'Q_AGENCIA_TICKETS_MONTH',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántas ventas hacés por mes?', 'pt-BR': 'Quantas vendas você faz por mês?' },
    type: 'single',
    businessTypes: ['agencia_viajes'],
    options: [
      { id: '1-10', label: { es: '1-10 ventas', 'pt-BR': '1-10 vendas' }, emoji: '📊', impactScore: 8 },
      { id: '11-30', label: { es: '11-30 ventas', 'pt-BR': '11-30 vendas' }, emoji: '📈', impactScore: 12 },
      { id: '31-100', label: { es: '31-100 ventas', 'pt-BR': '31-100 vendas' }, emoji: '🚀', impactScore: 18 },
      { id: '100+', label: { es: 'Más de 100', 'pt-BR': 'Mais de 100' }, emoji: '🔥', impactScore: 25 },
    ],
  },
];

// ============= TOURS GUIADOS / EXCURSIONES QUESTIONS =============
export const TOURS_GUIADOS_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_TOURS_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de tours ofrecés?', 'pt-BR': 'Que tipo de tours você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['tours_guiados'],
    options: [
      { id: 'walking', label: { es: 'Walking tours', 'pt-BR': 'Walking tours' }, emoji: '🚶', impactScore: 12 },
      { id: 'gastro', label: { es: 'Tours gastronómicos', 'pt-BR': 'Tours gastronômicos' }, emoji: '🍽️', impactScore: 15 },
      { id: 'cultural', label: { es: 'Culturales/Históricos', 'pt-BR': 'Culturais/Históricos' }, emoji: '🏛️', impactScore: 12 },
      { id: 'adventure', label: { es: 'Aventura/Naturaleza', 'pt-BR': 'Aventura/Natureza' }, emoji: '🧗', impactScore: 15 },
      { id: 'city', label: { es: 'City tours', 'pt-BR': 'City tours' }, emoji: '🚌', impactScore: 10 },
      { id: 'private', label: { es: 'Tours privados', 'pt-BR': 'Tours privados' }, emoji: '👤', impactScore: 18 },
    ],
  },
  {
    id: 'Q_TOURS_DURATION',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuánto duran tus tours típicamente?', 'pt-BR': 'Quanto duram seus tours tipicamente?' },
    type: 'single',
    businessTypes: ['tours_guiados'],
    options: [
      { id: '1-2h', label: { es: '1-2 horas', 'pt-BR': '1-2 horas' }, emoji: '⚡', impactScore: 8 },
      { id: '3-4h', label: { es: '3-4 horas (medio día)', 'pt-BR': '3-4 horas (meio dia)' }, emoji: '🌅', impactScore: 12 },
      { id: 'full_day', label: { es: 'Día completo', 'pt-BR': 'Dia completo' }, emoji: '☀️', impactScore: 15 },
      { id: 'multi_day', label: { es: 'Varios días', 'pt-BR': 'Vários dias' }, emoji: '📅', impactScore: 20 },
    ],
  },
  {
    id: 'Q_TOURS_GROUP_SIZE',
    category: 'operation',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es el tamaño típico de grupo?', 'pt-BR': 'Qual é o tamanho típico do grupo?' },
    type: 'single',
    businessTypes: ['tours_guiados'],
    options: [
      { id: 'private', label: { es: 'Privados (1-4)', 'pt-BR': 'Privados (1-4)' }, emoji: '👤', impactScore: 18 },
      { id: 'small', label: { es: 'Pequeños (5-10)', 'pt-BR': 'Pequenos (5-10)' }, emoji: '👥', impactScore: 15 },
      { id: 'medium', label: { es: 'Medianos (11-20)', 'pt-BR': 'Médios (11-20)' }, emoji: '🚐', impactScore: 12 },
      { id: 'large', label: { es: 'Grandes (20+)', 'pt-BR': 'Grandes (20+)' }, emoji: '🚌', impactScore: 10 },
    ],
  },
  {
    id: 'Q_TOURS_BOOKING',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cómo te reservan los clientes?', 'pt-BR': 'Como os clientes reservam?' },
    type: 'multi',
    businessTypes: ['tours_guiados'],
    options: [
      { id: 'viator', label: { es: 'Viator/TripAdvisor', 'pt-BR': 'Viator/TripAdvisor' }, emoji: '🦉', impactScore: 15 },
      { id: 'getyourguide', label: { es: 'GetYourGuide', 'pt-BR': 'GetYourGuide' }, emoji: '🎫', impactScore: 15 },
      { id: 'airbnb', label: { es: 'Airbnb Experiences', 'pt-BR': 'Airbnb Experiences' }, emoji: '🏠', impactScore: 12 },
      { id: 'website', label: { es: 'Web propia', 'pt-BR': 'Site próprio' }, emoji: '🌐', impactScore: 18 },
      { id: 'whatsapp', label: { es: 'WhatsApp/Directo', 'pt-BR': 'WhatsApp/Direto' }, emoji: '📱', impactScore: 10 },
      { id: 'hotels', label: { es: 'Hoteles/Concierge', 'pt-BR': 'Hotéis/Concierge' }, emoji: '🏨', impactScore: 12 },
    ],
  },
  {
    id: 'Q_TOURS_LANGUAGES',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 6,
    title: { es: '¿En qué idiomas das tours?', 'pt-BR': 'Em quais idiomas você faz tours?' },
    type: 'multi',
    businessTypes: ['tours_guiados'],
    options: [
      { id: 'spanish', label: { es: 'Español', 'pt-BR': 'Espanhol' }, emoji: '🇪🇸', impactScore: 10 },
      { id: 'english', label: { es: 'Inglés', 'pt-BR': 'Inglês' }, emoji: '🇬🇧', impactScore: 15 },
      { id: 'portuguese', label: { es: 'Portugués', 'pt-BR': 'Português' }, emoji: '🇧🇷', impactScore: 12 },
      { id: 'french', label: { es: 'Francés', 'pt-BR': 'Francês' }, emoji: '🇫🇷', impactScore: 10 },
      { id: 'german', label: { es: 'Alemán', 'pt-BR': 'Alemão' }, emoji: '🇩🇪', impactScore: 10 },
      { id: 'other', label: { es: 'Otros idiomas', 'pt-BR': 'Outros idiomas' }, emoji: '🌍', impactScore: 8 },
    ],
  },
];

// ============= PARQUE TEMATICO / ATRACCION QUESTIONS =============
export const PARQUE_TEMATICO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_PARQUE_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de parque/atracción sos?', 'pt-BR': 'Que tipo de parque/atração você é?' },
    type: 'single',
    required: true,
    businessTypes: ['parque_tematico'],
    options: [
      { id: 'theme_park', label: { es: 'Parque temático', 'pt-BR': 'Parque temático' }, emoji: '🎢', impactScore: 20 },
      { id: 'water_park', label: { es: 'Parque acuático', 'pt-BR': 'Parque aquático' }, emoji: '🌊', impactScore: 18 },
      { id: 'amusement', label: { es: 'Parque de diversiones', 'pt-BR': 'Parque de diversões' }, emoji: '🎡', impactScore: 15 },
      { id: 'zoo', label: { es: 'Zoológico/Acuario', 'pt-BR': 'Zoológico/Aquário' }, emoji: '🦁', impactScore: 15 },
      { id: 'adventure', label: { es: 'Parque aventura', 'pt-BR': 'Parque aventura' }, emoji: '🧗', impactScore: 15 },
      { id: 'indoor', label: { es: 'Indoor/Centro entretenimiento', 'pt-BR': 'Indoor/Centro entretenimento' }, emoji: '🎮', impactScore: 12 },
    ],
  },
  {
    id: 'Q_PARQUE_CAPACITY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu capacidad diaria?', 'pt-BR': 'Qual é sua capacidade diária?' },
    type: 'single',
    businessTypes: ['parque_tematico'],
    options: [
      { id: 'small_500', label: { es: 'Hasta 500 personas', 'pt-BR': 'Até 500 pessoas' }, emoji: '👥', impactScore: 10 },
      { id: 'medium_2000', label: { es: '500-2000 personas', 'pt-BR': '500-2000 pessoas' }, emoji: '🏢', impactScore: 15 },
      { id: 'large_5000', label: { es: '2000-5000 personas', 'pt-BR': '2000-5000 pessoas' }, emoji: '🏙️', impactScore: 18 },
      { id: 'mega', label: { es: 'Más de 5000', 'pt-BR': 'Mais de 5000' }, emoji: '🌆', impactScore: 22 },
    ],
  },
  {
    id: 'Q_PARQUE_TICKET_TYPE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué tipos de tickets vendés?', 'pt-BR': 'Quais tipos de ingressos você vende?' },
    type: 'multi',
    businessTypes: ['parque_tematico'],
    options: [
      { id: 'general', label: { es: 'Entrada general', 'pt-BR': 'Entrada geral' }, emoji: '🎫', impactScore: 10 },
      { id: 'fast_pass', label: { es: 'Fast Pass/VIP', 'pt-BR': 'Fast Pass/VIP' }, emoji: '⚡', impactScore: 15 },
      { id: 'season', label: { es: 'Pase anual/temporada', 'pt-BR': 'Passe anual/temporada' }, emoji: '📅', impactScore: 18 },
      { id: 'group', label: { es: 'Grupos/Escolares', 'pt-BR': 'Grupos/Escolares' }, emoji: '👨‍👩‍👧‍👦', impactScore: 12 },
      { id: 'combos', label: { es: 'Combos (comida+entrada)', 'pt-BR': 'Combos (comida+entrada)' }, emoji: '🍔', impactScore: 12 },
    ],
  },
  {
    id: 'Q_PARQUE_SEASONALITY',
    category: 'finance',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuál es tu temporada más fuerte?', 'pt-BR': 'Qual é sua temporada mais forte?' },
    type: 'multi',
    businessTypes: ['parque_tematico'],
    options: [
      { id: 'summer', label: { es: 'Verano', 'pt-BR': 'Verão' }, emoji: '☀️', impactScore: 15 },
      { id: 'winter_holidays', label: { es: 'Vacaciones invierno', 'pt-BR': 'Férias de inverno' }, emoji: '❄️', impactScore: 12 },
      { id: 'weekends', label: { es: 'Fines de semana (todo el año)', 'pt-BR': 'Finais de semana (todo ano)' }, emoji: '📅', impactScore: 10 },
      { id: 'school_breaks', label: { es: 'Recesos escolares', 'pt-BR': 'Férias escolares' }, emoji: '🎒', impactScore: 12 },
      { id: 'stable', label: { es: 'Estable todo el año', 'pt-BR': 'Estável todo o ano' }, emoji: '📊', impactScore: 18 },
    ],
  },
];

// ============= SALON DE EVENTOS SOCIALES QUESTIONS =============
export const SALON_EVENTOS_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_SALON_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de eventos organizás principalmente?', 'pt-BR': 'Que tipo de eventos você organiza principalmente?' },
    type: 'multi',
    required: true,
    businessTypes: ['salon_eventos'],
    options: [
      { id: 'weddings', label: { es: 'Casamientos', 'pt-BR': 'Casamentos' }, emoji: '💒', impactScore: 20 },
      { id: 'quince', label: { es: '15 años/Debuts', 'pt-BR': '15 anos/Debutantes' }, emoji: '👸', impactScore: 15, countries: ['AR', 'MX', 'BR'] },
      { id: 'birthdays', label: { es: 'Cumpleaños', 'pt-BR': 'Aniversários' }, emoji: '🎂', impactScore: 12 },
      { id: 'corporate', label: { es: 'Eventos corporativos', 'pt-BR': 'Eventos corporativos' }, emoji: '💼', impactScore: 15 },
      { id: 'graduations', label: { es: 'Graduaciones', 'pt-BR': 'Formaturas' }, emoji: '🎓', impactScore: 12 },
      { id: 'communions', label: { es: 'Comuniones/Bautismos', 'pt-BR': 'Comunhões/Batizados' }, emoji: '⛪', impactScore: 10 },
    ],
  },
  {
    id: 'Q_SALON_CAPACITY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu capacidad máxima?', 'pt-BR': 'Qual é sua capacidade máxima?' },
    type: 'single',
    businessTypes: ['salon_eventos'],
    options: [
      { id: 'small_100', label: { es: 'Hasta 100 personas', 'pt-BR': 'Até 100 pessoas' }, emoji: '👥', impactScore: 10 },
      { id: 'medium_250', label: { es: '100-250 personas', 'pt-BR': '100-250 pessoas' }, emoji: '🏢', impactScore: 15 },
      { id: 'large_500', label: { es: '250-500 personas', 'pt-BR': '250-500 pessoas' }, emoji: '🏛️', impactScore: 18 },
      { id: 'mega', label: { es: 'Más de 500', 'pt-BR': 'Mais de 500' }, emoji: '🌆', impactScore: 20 },
    ],
  },
  {
    id: 'Q_SALON_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué servicios incluís?', 'pt-BR': 'Quais serviços você inclui?' },
    type: 'multi',
    businessTypes: ['salon_eventos'],
    options: [
      { id: 'catering', label: { es: 'Catering propio', 'pt-BR': 'Catering próprio' }, emoji: '🍽️', impactScore: 18 },
      { id: 'dj_sound', label: { es: 'DJ/Sonido', 'pt-BR': 'DJ/Som' }, emoji: '🎧', impactScore: 12 },
      { id: 'decoration', label: { es: 'Decoración', 'pt-BR': 'Decoração' }, emoji: '🎨', impactScore: 12 },
      { id: 'photo_video', label: { es: 'Foto/Video', 'pt-BR': 'Foto/Vídeo' }, emoji: '📸', impactScore: 10 },
      { id: 'coordinator', label: { es: 'Coordinador de eventos', 'pt-BR': 'Coordenador de eventos' }, emoji: '👔', impactScore: 15 },
      { id: 'parking', label: { es: 'Estacionamiento', 'pt-BR': 'Estacionamento' }, emoji: '🅿️', impactScore: 8 },
    ],
  },
  {
    id: 'Q_SALON_PRICE_MODEL',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cómo cobrás?', 'pt-BR': 'Como você cobra?' },
    type: 'single',
    businessTypes: ['salon_eventos'],
    options: [
      { id: 'per_person', label: { es: 'Por persona', 'pt-BR': 'Por pessoa' }, emoji: '👤', impactScore: 15 },
      { id: 'fixed', label: { es: 'Precio fijo por evento', 'pt-BR': 'Preço fixo por evento' }, emoji: '💰', impactScore: 12 },
      { id: 'hourly', label: { es: 'Por hora', 'pt-BR': 'Por hora' }, emoji: '⏰', impactScore: 8 },
      { id: 'packages', label: { es: 'Paquetes todo incluido', 'pt-BR': 'Pacotes tudo incluído' }, emoji: '📦', impactScore: 18 },
    ],
  },
  {
    id: 'Q_SALON_EVENTS_MONTH',
    category: 'finance',
    mode: 'complete',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántos eventos hacés por mes (promedio)?', 'pt-BR': 'Quantos eventos você faz por mês (média)?' },
    type: 'single',
    businessTypes: ['salon_eventos'],
    options: [
      { id: '1-4', label: { es: '1-4 eventos', 'pt-BR': '1-4 eventos' }, emoji: '📊', impactScore: 10 },
      { id: '5-10', label: { es: '5-10 eventos', 'pt-BR': '5-10 eventos' }, emoji: '📈', impactScore: 15 },
      { id: '11-20', label: { es: '11-20 eventos', 'pt-BR': '11-20 eventos' }, emoji: '🚀', impactScore: 20 },
      { id: '20+', label: { es: 'Más de 20', 'pt-BR': 'Mais de 20' }, emoji: '🔥', impactScore: 25 },
    ],
  },
];

// ============= OCIO NOCTURNO (BOLICHE/CLUB) QUESTIONS =============
export const OCIO_NOCTURNO_QUESTIONS: GastroQuestion[] = [
  {
    id: 'Q_CLUB_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de venue sos?', 'pt-BR': 'Que tipo de venue você é?' },
    type: 'single',
    required: true,
    businessTypes: ['ocio_nocturno'],
    options: [
      { id: 'nightclub', label: { es: 'Club/Discoteca', 'pt-BR': 'Clube/Discoteca' }, emoji: '🪩', impactScore: 18 },
      { id: 'pub_live', label: { es: 'Pub con música en vivo', 'pt-BR': 'Pub com música ao vivo' }, emoji: '🎸', impactScore: 15 },
      { id: 'rooftop', label: { es: 'Rooftop/Terraza', 'pt-BR': 'Rooftop/Terraço' }, emoji: '🌃', impactScore: 18 },
      { id: 'electronic', label: { es: 'Club electrónico', 'pt-BR': 'Clube eletrônico' }, emoji: '🎧', impactScore: 18 },
      { id: 'latin', label: { es: 'Latino/Tropical', 'pt-BR': 'Latino/Tropical' }, emoji: '💃', impactScore: 15 },
      { id: 'karaoke', label: { es: 'Karaoke', 'pt-BR': 'Karaokê' }, emoji: '🎤', impactScore: 12 },
    ],
  },
  {
    id: 'Q_CLUB_CAPACITY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu capacidad?', 'pt-BR': 'Qual é sua capacidade?' },
    type: 'single',
    businessTypes: ['ocio_nocturno'],
    options: [
      { id: 'small_200', label: { es: 'Hasta 200 personas', 'pt-BR': 'Até 200 pessoas' }, emoji: '👥', impactScore: 10 },
      { id: 'medium_500', label: { es: '200-500 personas', 'pt-BR': '200-500 pessoas' }, emoji: '🏢', impactScore: 15 },
      { id: 'large_1000', label: { es: '500-1000 personas', 'pt-BR': '500-1000 pessoas' }, emoji: '🏛️', impactScore: 18 },
      { id: 'mega', label: { es: 'Más de 1000', 'pt-BR': 'Mais de 1000' }, emoji: '🌆', impactScore: 22 },
    ],
  },
  {
    id: 'Q_CLUB_REVENUE_MIX',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿De dónde viene tu ingreso principal?', 'pt-BR': 'De onde vem sua receita principal?' },
    type: 'single',
    businessTypes: ['ocio_nocturno'],
    options: [
      { id: 'door', label: { es: 'Puerta/Entrada', 'pt-BR': 'Porta/Entrada' }, emoji: '🎫', impactScore: 12 },
      { id: 'bar', label: { es: 'Barra/Consumo', 'pt-BR': 'Bar/Consumo' }, emoji: '🍾', impactScore: 18 },
      { id: 'vip', label: { es: 'Mesas/VIP', 'pt-BR': 'Mesas/VIP' }, emoji: '🥂', impactScore: 20 },
      { id: 'mixed', label: { es: 'Mix equilibrado', 'pt-BR': 'Mix equilibrado' }, emoji: '📊', impactScore: 15 },
      { id: 'events', label: { es: 'Eventos privados', 'pt-BR': 'Eventos privados' }, emoji: '🎉', impactScore: 15 },
    ],
  },
  {
    id: 'Q_CLUB_NIGHTS',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cuáles son tus noches más fuertes?', 'pt-BR': 'Quais são suas noites mais fortes?' },
    type: 'multi',
    businessTypes: ['ocio_nocturno'],
    options: [
      { id: 'friday', label: { es: 'Viernes', 'pt-BR': 'Sexta' }, emoji: '🎉', impactScore: 15 },
      { id: 'saturday', label: { es: 'Sábado', 'pt-BR': 'Sábado' }, emoji: '🥳', impactScore: 18 },
      { id: 'thursday', label: { es: 'Jueves', 'pt-BR': 'Quinta' }, emoji: '🍻', impactScore: 10 },
      { id: 'sunday', label: { es: 'Domingo', 'pt-BR': 'Domingo' }, emoji: '☀️', impactScore: 8 },
      { id: 'special', label: { es: 'Solo eventos especiales', 'pt-BR': 'Só eventos especiais' }, emoji: '⭐', impactScore: 12 },
    ],
  },
  {
    id: 'Q_CLUB_PROMOTION',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cómo promocionás tu venue?', 'pt-BR': 'Como você promove seu venue?' },
    type: 'multi',
    businessTypes: ['ocio_nocturno'],
    options: [
      { id: 'instagram', label: { es: 'Instagram', 'pt-BR': 'Instagram' }, emoji: '📸', impactScore: 15 },
      { id: 'tiktok', label: { es: 'TikTok', 'pt-BR': 'TikTok' }, emoji: '🎵', impactScore: 12 },
      { id: 'rrpp', label: { es: 'RRPP/Promotores', 'pt-BR': 'Promotores' }, emoji: '👥', impactScore: 15 },
      { id: 'guest_list', label: { es: 'Guest lists', 'pt-BR': 'Guest lists' }, emoji: '📋', impactScore: 12 },
      { id: 'influencers', label: { es: 'Influencers', 'pt-BR': 'Influencers' }, emoji: '⭐', impactScore: 12 },
      { id: 'events_app', label: { es: 'Apps de eventos', 'pt-BR': 'Apps de eventos' }, emoji: '📱', impactScore: 10 },
    ],
  },
];

// Export all tourism questions
export const ALL_TURISMO_QUESTIONS: GastroQuestion[] = [
  ...HOTEL_URBANO_QUESTIONS,
  ...HOTEL_BOUTIQUE_QUESTIONS,
  ...RESORT_QUESTIONS,
  ...HOSTEL_QUESTIONS,
  ...AGENCIA_VIAJES_QUESTIONS,
  ...TOURS_GUIADOS_QUESTIONS,
  ...PARQUE_TEMATICO_QUESTIONS,
  ...SALON_EVENTOS_QUESTIONS,
  ...OCIO_NOCTURNO_QUESTIONS,
];

// Export function to get questions for a specific tourism business type
export function getTurismQuestions(businessTypeId: string): GastroQuestion[] {
  return ALL_TURISMO_QUESTIONS.filter(q => 
    q.businessTypes?.includes(businessTypeId)
  );
}
