// ============================================
// TURISMO - Extended Questions by Business Type
// Adds 30-40 specific questions per business type
// to reach 65-75 total questions per type
// ============================================

import { TurismQuestion, TURISM_BUSINESS_TYPES } from './turismConstants';

const { 
  HOTEL_URBANO, HOTEL_BOUTIQUE, RESORT, HOSTEL, APART_HOTEL, POSADA, ALQUILER_TEMP,
  AGENCIA_VIAJES, TOURS, TURISMO_AVENTURA, OPERADOR_TURISTICO,
  PARQUE_TEMATICO, ATRACCIONES, ENTRETENIMIENTO, TEATRO,
  SALON_EVENTOS, EVENTOS_CORP, PRODUCTORA
} = TURISM_BUSINESS_TYPES;

// ============================================
// HOTEL URBANO / BUSINESS - Extended
// ============================================
export const HOTEL_URBANO_EXTENDED: TurismQuestion[] = [
  {
    id: 'HU01_GUEST_PROFILE',
    category: 'clientes',
    categoryLabel: { es: 'Clientes', 'pt-BR': 'Clientes' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: '¿Cuál es tu cliente principal?', 'pt-BR': 'Qual é seu cliente principal?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'corporate', label: { es: 'Corporativo/Negocios', 'pt-BR': 'Corporativo/Negócios' }, emoji: '💼' },
      { id: 'leisure', label: { es: 'Turismo/Ocio', 'pt-BR': 'Turismo/Lazer' }, emoji: '🏖️' },
      { id: 'mixed', label: { es: 'Mix 50/50', 'pt-BR': 'Mix 50/50' }, emoji: '🔄' },
      { id: 'events', label: { es: 'Eventos/Convenciones', 'pt-BR': 'Eventos/Convenções' }, emoji: '🎪' },
    ],
  },
  {
    id: 'HU02_CORPORATE_ACCOUNTS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Tenés cuentas corporativas?', 'pt-BR': 'Você tem contas corporativas?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'many', label: { es: 'Sí, varias (+10)', 'pt-BR': 'Sim, várias (+10)' }, emoji: '🏢' },
      { id: 'few', label: { es: 'Sí, algunas (3-10)', 'pt-BR': 'Sim, algumas (3-10)' }, emoji: '📋' },
      { id: 'minimal', label: { es: 'Pocas (1-2)', 'pt-BR': 'Poucas (1-2)' }, emoji: '📝' },
      { id: 'none', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU03_MEETING_ROOMS',
    category: 'servicios',
    categoryLabel: { es: 'Servicios', 'pt-BR': 'Serviços' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Tenés salas de reuniones?', 'pt-BR': 'Você tem salas de reunião?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'yes_large', label: { es: 'Sí, varias salas', 'pt-BR': 'Sim, várias salas' }, emoji: '🏛️' },
      { id: 'yes_small', label: { es: 'Sí, 1-2 salas', 'pt-BR': 'Sim, 1-2 salas' }, emoji: '🚪' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU04_AIRPORT_PROXIMITY',
    category: 'ubicacion',
    categoryLabel: { es: 'Ubicación', 'pt-BR': 'Localização' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: 'Distancia al aeropuerto', 'pt-BR': 'Distância ao aeroporto' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'near', label: { es: 'Cerca (<15 min)', 'pt-BR': 'Perto (<15 min)' }, emoji: '✈️' },
      { id: 'medium', label: { es: 'Media (15-45 min)', 'pt-BR': 'Média (15-45 min)' }, emoji: '🚗' },
      { id: 'far', label: { es: 'Lejos (+45 min)', 'pt-BR': 'Longe (+45 min)' }, emoji: '🛣️' },
    ],
  },
  {
    id: 'HU05_BUSINESS_CENTER',
    category: 'servicios',
    categoryLabel: { es: 'Servicios', 'pt-BR': 'Serviços' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Tenés business center/cowork?', 'pt-BR': 'Você tem business center/cowork?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'yes', label: { es: 'Sí', 'pt-BR': 'Sim' }, emoji: '💻' },
      { id: 'partial', label: { es: 'Espacio limitado', 'pt-BR': 'Espaço limitado' }, emoji: '🪑' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU06_TRANSIT_ACCESS',
    category: 'ubicacion',
    categoryLabel: { es: 'Ubicación', 'pt-BR': 'Localização' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: 'Acceso a transporte público', 'pt-BR': 'Acesso a transporte público' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'excellent', label: { es: 'Excelente (metro/subte)', 'pt-BR': 'Excelente (metrô)' }, emoji: '🚇' },
      { id: 'good', label: { es: 'Bueno (buses)', 'pt-BR': 'Bom (ônibus)' }, emoji: '🚌' },
      { id: 'limited', label: { es: 'Limitado', 'pt-BR': 'Limitado' }, emoji: '🚗' },
    ],
  },
  {
    id: 'HU07_RESTAURANT_TYPE',
    category: 'fnb',
    categoryLabel: { es: 'F&B', 'pt-BR': 'A&B' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Qué tipo de restaurante tenés?', 'pt-BR': 'Que tipo de restaurante você tem?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'full', label: { es: 'Full service (almuerzo/cena)', 'pt-BR': 'Full service (almoço/jantar)' }, emoji: '🍽️' },
      { id: 'breakfast_only', label: { es: 'Solo desayuno', 'pt-BR': 'Só café da manhã' }, emoji: '🍳' },
      { id: 'cafe', label: { es: 'Café/Snacks', 'pt-BR': 'Café/Lanches' }, emoji: '☕' },
      { id: 'none', label: { es: 'Sin restaurante', 'pt-BR': 'Sem restaurante' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU08_ROOM_SERVICE',
    category: 'fnb',
    categoryLabel: { es: 'F&B', 'pt-BR': 'A&B' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Ofrecés room service?', 'pt-BR': 'Você oferece room service?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: '24h', label: { es: 'Sí, 24hs', 'pt-BR': 'Sim, 24h' }, emoji: '🌙' },
      { id: 'limited', label: { es: 'Sí, horario limitado', 'pt-BR': 'Sim, horário limitado' }, emoji: '⏰' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU09_GYM_FITNESS',
    category: 'amenities',
    categoryLabel: { es: 'Amenities', 'pt-BR': 'Amenidades' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés gimnasio?', 'pt-BR': 'Você tem academia?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'full', label: { es: 'Sí, completo', 'pt-BR': 'Sim, completa' }, emoji: '🏋️' },
      { id: 'basic', label: { es: 'Sí, básico', 'pt-BR': 'Sim, básica' }, emoji: '💪' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU10_PARKING',
    category: 'amenities',
    categoryLabel: { es: 'Amenities', 'pt-BR': 'Amenidades' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Tenés estacionamiento?', 'pt-BR': 'Você tem estacionamento?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'own', label: { es: 'Sí, propio', 'pt-BR': 'Sim, próprio' }, emoji: '🅿️' },
      { id: 'valet', label: { es: 'Sí, valet', 'pt-BR': 'Sim, valet' }, emoji: '🚗' },
      { id: 'nearby', label: { es: 'Convenio cercano', 'pt-BR': 'Convênio próximo' }, emoji: '📍' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU11_WIFI_QUALITY',
    category: 'tecnologia',
    categoryLabel: { es: 'Tecnología', 'pt-BR': 'Tecnologia' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: 'Calidad de WiFi', 'pt-BR': 'Qualidade do WiFi' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'high_speed', label: { es: 'Alta velocidad (+100 Mbps)', 'pt-BR': 'Alta velocidade (+100 Mbps)' }, emoji: '🚀' },
      { id: 'good', label: { es: 'Buena (50-100 Mbps)', 'pt-BR': 'Boa (50-100 Mbps)' }, emoji: '📶' },
      { id: 'basic', label: { es: 'Básica (<50 Mbps)', 'pt-BR': 'Básica (<50 Mbps)' }, emoji: '📡' },
    ],
  },
  {
    id: 'HU12_LAUNDRY_SERVICE',
    category: 'servicios',
    categoryLabel: { es: 'Servicios', 'pt-BR': 'Serviços' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Ofrecés servicio de lavandería?', 'pt-BR': 'Você oferece serviço de lavanderia?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'express', label: { es: 'Sí, express mismo día', 'pt-BR': 'Sim, express mesmo dia' }, emoji: '⚡' },
      { id: 'normal', label: { es: 'Sí, normal', 'pt-BR': 'Sim, normal' }, emoji: '👔' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU13_STAR_RATING',
    category: 'posicionamiento',
    categoryLabel: { es: 'Posicionamiento', 'pt-BR': 'Posicionamento' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: 'Categoría oficial (estrellas)', 'pt-BR': 'Categoria oficial (estrelas)' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: '5star', label: { es: '5 estrellas', 'pt-BR': '5 estrelas' }, emoji: '⭐⭐⭐⭐⭐' },
      { id: '4star', label: { es: '4 estrellas', 'pt-BR': '4 estrelas' }, emoji: '⭐⭐⭐⭐' },
      { id: '3star', label: { es: '3 estrellas', 'pt-BR': '3 estrelas' }, emoji: '⭐⭐⭐' },
      { id: 'no_rating', label: { es: 'Sin categorización', 'pt-BR': 'Sem categoria' }, emoji: '🏨' },
    ],
  },
  {
    id: 'HU14_CONCIERGE',
    category: 'servicios',
    categoryLabel: { es: 'Servicios', 'pt-BR': 'Serviços' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés servicio de concierge?', 'pt-BR': 'Você tem serviço de concierge?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'yes', label: { es: 'Sí, dedicado', 'pt-BR': 'Sim, dedicado' }, emoji: '🎩' },
      { id: 'reception', label: { es: 'Lo hace recepción', 'pt-BR': 'A recepção faz' }, emoji: '🔔' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU15_LATE_CHECKOUT',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Ofrecés late checkout?', 'pt-BR': 'Você oferece late checkout?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'free', label: { es: 'Sí, gratis (según disponibilidad)', 'pt-BR': 'Sim, grátis (conforme disponibilidade)' }, emoji: '✅' },
      { id: 'paid', label: { es: 'Sí, con cargo', 'pt-BR': 'Sim, com taxa' }, emoji: '💰' },
      { id: 'loyalty', label: { es: 'Solo miembros programa', 'pt-BR': 'Só membros programa' }, emoji: '👑' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU16_LOYALTY_PROGRAM',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Tenés programa de fidelización?', 'pt-BR': 'Você tem programa de fidelização?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'own', label: { es: 'Sí, propio', 'pt-BR': 'Sim, próprio' }, emoji: '⭐' },
      { id: 'chain', label: { es: 'De la cadena', 'pt-BR': 'Da rede' }, emoji: '🏨' },
      { id: 'planning', label: { es: 'En desarrollo', 'pt-BR': 'Em desenvolvimento' }, emoji: '🔧' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU17_PMS_SYSTEM',
    category: 'tecnologia',
    categoryLabel: { es: 'Tecnología', 'pt-BR': 'Tecnologia' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Qué PMS usás?', 'pt-BR': 'Qual PMS você usa?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'opera', label: { es: 'Opera/Micros', 'pt-BR': 'Opera/Micros' }, emoji: '🏢' },
      { id: 'cloudbeds', label: { es: 'Cloudbeds', 'pt-BR': 'Cloudbeds' }, emoji: '☁️' },
      { id: 'other_pms', label: { es: 'Otro PMS profesional', 'pt-BR': 'Outro PMS profissional' }, emoji: '💻' },
      { id: 'excel', label: { es: 'Excel/Manual', 'pt-BR': 'Excel/Manual' }, emoji: '📊' },
      { id: 'none', label: { es: 'Ninguno', 'pt-BR': 'Nenhum' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU18_REVENUE_MANAGEMENT',
    category: 'precios',
    categoryLabel: { es: 'Precios', 'pt-BR': 'Preços' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Tenés revenue manager?', 'pt-BR': 'Você tem revenue manager?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'yes_dedicated', label: { es: 'Sí, dedicado', 'pt-BR': 'Sim, dedicado' }, emoji: '📈' },
      { id: 'yes_shared', label: { es: 'Sí, compartido', 'pt-BR': 'Sim, compartilhado' }, emoji: '👥' },
      { id: 'owner', label: { es: 'Lo hace el dueño', 'pt-BR': 'O dono faz' }, emoji: '👤' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU19_GROUP_BUSINESS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '% de ingresos por grupos', 'pt-BR': '% de receita por grupos' },
    type: 'slider',
    min: 0,
    max: 80,
    unit: '%',
    businessTypes: [HOTEL_URBANO],
  },
  {
    id: 'HU20_AVERAGE_RATE',
    category: 'precios',
    categoryLabel: { es: 'Precios', 'pt-BR': 'Preços' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: 'Tarifa rack promedio', 'pt-BR': 'Tarifa balcão média' },
    type: 'money',
    businessTypes: [HOTEL_URBANO],
  },
  {
    id: 'HU21_CORPORATE_RATE_DISCOUNT',
    category: 'precios',
    categoryLabel: { es: 'Precios', 'pt-BR': 'Preços' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: 'Descuento corporativo promedio', 'pt-BR': 'Desconto corporativo médio' },
    type: 'slider',
    min: 0,
    max: 50,
    unit: '%',
    businessTypes: [HOTEL_URBANO],
  },
  {
    id: 'HU22_CANCELLATION_RATE',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '% de cancelaciones', 'pt-BR': '% de cancelamentos' },
    type: 'slider',
    min: 0,
    max: 40,
    unit: '%',
    businessTypes: [HOTEL_URBANO],
  },
  {
    id: 'HU23_NO_SHOW_RATE',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Finanzas',
    title: { es: '% de no-shows', 'pt-BR': '% de no-shows' },
    type: 'slider',
    min: 0,
    max: 20,
    unit: '%',
    businessTypes: [HOTEL_URBANO],
  },
  {
    id: 'HU24_BOOKING_WINDOW',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: 'Ventana de reserva promedio', 'pt-BR': 'Janela de reserva média' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'same_day', label: { es: 'Mismo día', 'pt-BR': 'Mesmo dia' }, emoji: '⚡' },
      { id: '1-3days', label: { es: '1-3 días', 'pt-BR': '1-3 dias' }, emoji: '📅' },
      { id: '1week', label: { es: '1 semana', 'pt-BR': '1 semana' }, emoji: '📆' },
      { id: '2weeks+', label: { es: '2+ semanas', 'pt-BR': '2+ semanas' }, emoji: '🗓️' },
    ],
  },
  {
    id: 'HU25_COMPETITOR_TRACKING',
    category: 'competencia',
    categoryLabel: { es: 'Competencia', 'pt-BR': 'Concorrência' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Monitoreás precios de competencia?', 'pt-BR': 'Você monitora preços da concorrência?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'yes_tool', label: { es: 'Sí, con herramienta', 'pt-BR': 'Sim, com ferramenta' }, emoji: '🔍' },
      { id: 'yes_manual', label: { es: 'Sí, manual', 'pt-BR': 'Sim, manual' }, emoji: '👀' },
      { id: 'sometimes', label: { es: 'A veces', 'pt-BR': 'Às vezes' }, emoji: '🔄' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU26_SHUTTLE_SERVICE',
    category: 'servicios',
    categoryLabel: { es: 'Servicios', 'pt-BR': 'Serviços' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés shuttle aeropuerto?', 'pt-BR': 'Você tem transfer aeroporto?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'free', label: { es: 'Sí, gratis', 'pt-BR': 'Sim, grátis' }, emoji: '✅' },
      { id: 'paid', label: { es: 'Sí, pago', 'pt-BR': 'Sim, pago' }, emoji: '💰' },
      { id: 'on_request', label: { es: 'Bajo pedido', 'pt-BR': 'Sob pedido' }, emoji: '📞' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU27_GUEST_SATISFACTION',
    category: 'calidad',
    categoryLabel: { es: 'Calidad', 'pt-BR': 'Qualidade' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Medís satisfacción del huésped?', 'pt-BR': 'Você mede satisfação do hóspede?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'yes_tool', label: { es: 'Sí, con software', 'pt-BR': 'Sim, com software' }, emoji: '📊' },
      { id: 'yes_manual', label: { es: 'Sí, encuestas', 'pt-BR': 'Sim, pesquisas' }, emoji: '📝' },
      { id: 'reviews_only', label: { es: 'Solo por reseñas', 'pt-BR': 'Só por avaliações' }, emoji: '⭐' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU28_CHAIN_AFFILIATION',
    category: 'modelo',
    categoryLabel: { es: 'Modelo', 'pt-BR': 'Modelo' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Pertenecés a alguna cadena?', 'pt-BR': 'Você pertence a alguma rede?' },
    type: 'single',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'international', label: { es: 'Sí, internacional', 'pt-BR': 'Sim, internacional' }, emoji: '🌐' },
      { id: 'national', label: { es: 'Sí, nacional', 'pt-BR': 'Sim, nacional' }, emoji: '🏠' },
      { id: 'soft_brand', label: { es: 'Soft brand', 'pt-BR': 'Soft brand' }, emoji: '🏷️' },
      { id: 'independent', label: { es: 'Independiente', 'pt-BR': 'Independente' }, emoji: '🏨' },
    ],
  },
  {
    id: 'HU29_SUSTAINABILITY',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés prácticas sustentables?', 'pt-BR': 'Você tem práticas sustentáveis?' },
    type: 'multi',
    businessTypes: [HOTEL_URBANO],
    options: [
      { id: 'energy', label: { es: 'Ahorro energía', 'pt-BR': 'Economia energia' }, emoji: '💡' },
      { id: 'water', label: { es: 'Ahorro agua', 'pt-BR': 'Economia água' }, emoji: '💧' },
      { id: 'waste', label: { es: 'Reciclaje', 'pt-BR': 'Reciclagem' }, emoji: '♻️' },
      { id: 'certified', label: { es: 'Certificación ambiental', 'pt-BR': 'Certificação ambiental' }, emoji: '🌿' },
      { id: 'none', label: { es: 'Ninguna formal', 'pt-BR': 'Nenhuma formal' }, emoji: '❌' },
    ],
  },
  {
    id: 'HU30_STAFF_PER_ROOM',
    category: 'equipo',
    categoryLabel: { es: 'Equipo', 'pt-BR': 'Equipe' },
    mode: 'complete',
    score_area: 'Equipo',
    title: { es: 'Ratio empleados/habitación', 'pt-BR': 'Ratio funcionários/quarto' },
    type: 'slider',
    min: 0.2,
    max: 2,
    unit: 'emp/hab',
    businessTypes: [HOTEL_URBANO],
  },
];

// ============================================
// HOTEL BOUTIQUE - Extended
// ============================================
export const HOTEL_BOUTIQUE_EXTENDED: TurismQuestion[] = [
  {
    id: 'HB01_DESIGN_STYLE',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: 'Estilo arquitectónico principal', 'pt-BR': 'Estilo arquitetônico principal' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'historic', label: { es: 'Histórico/Colonial', 'pt-BR': 'Histórico/Colonial' }, emoji: '🏛️' },
      { id: 'contemporary', label: { es: 'Contemporáneo/Minimalista', 'pt-BR': 'Contemporâneo/Minimalista' }, emoji: '🎨' },
      { id: 'art_deco', label: { es: 'Art Déco', 'pt-BR': 'Art Déco' }, emoji: '✨' },
      { id: 'rustic', label: { es: 'Rústico/Campo', 'pt-BR': 'Rústico/Campo' }, emoji: '🌾' },
      { id: 'eclectic', label: { es: 'Ecléctico', 'pt-BR': 'Eclético' }, emoji: '🎭' },
    ],
  },
  {
    id: 'HB02_UNIQUE_ROOMS',
    category: 'producto',
    categoryLabel: { es: 'Producto', 'pt-BR': 'Produto' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Cada habitación es única?', 'pt-BR': 'Cada quarto é único?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'all_unique', label: { es: 'Sí, todas diferentes', 'pt-BR': 'Sim, todas diferentes' }, emoji: '🎨' },
      { id: 'categories', label: { es: 'Por categorías temáticas', 'pt-BR': 'Por categorias temáticas' }, emoji: '📚' },
      { id: 'standardized', label: { es: 'Estandarizadas', 'pt-BR': 'Padronizadas' }, emoji: '📋' },
    ],
  },
  {
    id: 'HB03_OWNER_PRESENCE',
    category: 'modelo',
    categoryLabel: { es: 'Modelo', 'pt-BR': 'Modelo' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿El dueño está presente?', 'pt-BR': 'O dono está presente?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'always', label: { es: 'Siempre (vive ahí)', 'pt-BR': 'Sempre (mora lá)' }, emoji: '🏠' },
      { id: 'often', label: { es: 'Frecuentemente', 'pt-BR': 'Frequentemente' }, emoji: '👀' },
      { id: 'occasionally', label: { es: 'Ocasionalmente', 'pt-BR': 'Ocasionalmente' }, emoji: '📅' },
      { id: 'never', label: { es: 'Nunca (gestión tercerizada)', 'pt-BR': 'Nunca (gestão terceirizada)' }, emoji: '📞' },
    ],
  },
  {
    id: 'HB04_PERSONALIZED_WELCOME',
    category: 'experiencia',
    categoryLabel: { es: 'Experiencia', 'pt-BR': 'Experiência' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Ofrecés bienvenida personalizada?', 'pt-BR': 'Você oferece boas-vindas personalizadas?' },
    type: 'multi',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'drink', label: { es: 'Bebida de bienvenida', 'pt-BR': 'Bebida de boas-vindas' }, emoji: '🥂' },
      { id: 'amenity', label: { es: 'Amenity especial', 'pt-BR': 'Amenidade especial' }, emoji: '🎁' },
      { id: 'tour', label: { es: 'Tour del hotel', 'pt-BR': 'Tour do hotel' }, emoji: '🚶' },
      { id: 'local_tips', label: { es: 'Tips locales personalizados', 'pt-BR': 'Dicas locais personalizadas' }, emoji: '📍' },
      { id: 'none', label: { es: 'Check-in estándar', 'pt-BR': 'Check-in padrão' }, emoji: '📋' },
    ],
  },
  {
    id: 'HB05_LOCAL_SOURCING',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '% de productos locales/artesanales', 'pt-BR': '% de produtos locais/artesanais' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
    businessTypes: [HOTEL_BOUTIQUE],
  },
  {
    id: 'HB06_SIGNATURE_EXPERIENCE',
    category: 'experiencia',
    categoryLabel: { es: 'Experiencia', 'pt-BR': 'Experiência' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Tenés experiencia/actividad signature?', 'pt-BR': 'Você tem experiência/atividade signature?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'yes', label: { es: 'Sí, muy diferenciada', 'pt-BR': 'Sim, muito diferenciada' }, emoji: '⭐' },
      { id: 'developing', label: { es: 'En desarrollo', 'pt-BR': 'Em desenvolvimento' }, emoji: '🔧' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB07_SOCIAL_MEDIA_PRESENCE',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Tu red social más fuerte', 'pt-BR': 'Sua rede social mais forte' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'instagram', label: { es: 'Instagram', 'pt-BR': 'Instagram' }, emoji: '📸' },
      { id: 'facebook', label: { es: 'Facebook', 'pt-BR': 'Facebook' }, emoji: '📘' },
      { id: 'tiktok', label: { es: 'TikTok', 'pt-BR': 'TikTok' }, emoji: '🎵' },
      { id: 'pinterest', label: { es: 'Pinterest', 'pt-BR': 'Pinterest' }, emoji: '📌' },
      { id: 'none', label: { es: 'Ninguna activa', 'pt-BR': 'Nenhuma ativa' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB08_PRESS_COVERAGE',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés cobertura de prensa/blogs?', 'pt-BR': 'Você tem cobertura de imprensa/blogs?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'yes_regular', label: { es: 'Sí, regular', 'pt-BR': 'Sim, regular' }, emoji: '📰' },
      { id: 'yes_occasional', label: { es: 'Sí, ocasional', 'pt-BR': 'Sim, ocasional' }, emoji: '📄' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB09_INFLUENCER_HOSTING',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Trabajás con influencers?', 'pt-BR': 'Você trabalha com influencers?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'yes_paid', label: { es: 'Sí, pagos', 'pt-BR': 'Sim, pagos' }, emoji: '💰' },
      { id: 'yes_exchange', label: { es: 'Sí, intercambio', 'pt-BR': 'Sim, intercâmbio' }, emoji: '🔄' },
      { id: 'considering', label: { es: 'Lo estoy evaluando', 'pt-BR': 'Estou avaliando' }, emoji: '🤔' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB10_SPECIAL_OCCASIONS',
    category: 'experiencia',
    categoryLabel: { es: 'Experiencia', 'pt-BR': 'Experiência' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Ofrecés paquetes ocasiones especiales?', 'pt-BR': 'Você oferece pacotes ocasiões especiais?' },
    type: 'multi',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'honeymoon', label: { es: 'Luna de miel', 'pt-BR': 'Lua de mel' }, emoji: '💑' },
      { id: 'anniversary', label: { es: 'Aniversarios', 'pt-BR': 'Aniversários' }, emoji: '🎂' },
      { id: 'proposal', label: { es: 'Pedida de mano', 'pt-BR': 'Pedido de casamento' }, emoji: '💍' },
      { id: 'birthday', label: { es: 'Cumpleaños', 'pt-BR': 'Aniversários' }, emoji: '🎁' },
      { id: 'none', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB11_TURNDOWN_SERVICE',
    category: 'servicios',
    categoryLabel: { es: 'Servicios', 'pt-BR': 'Serviços' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Ofrecés turndown service?', 'pt-BR': 'Você oferece turndown service?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'yes', label: { es: 'Sí', 'pt-BR': 'Sim' }, emoji: '🛏️' },
      { id: 'on_request', label: { es: 'Bajo pedido', 'pt-BR': 'Sob pedido' }, emoji: '📞' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB12_IN_ROOM_AMENITIES',
    category: 'amenities',
    categoryLabel: { es: 'Amenities', 'pt-BR': 'Amenidades' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: 'Amenities premium en habitación', 'pt-BR': 'Amenidades premium no quarto' },
    type: 'multi',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'nespresso', label: { es: 'Nespresso/Café premium', 'pt-BR': 'Nespresso/Café premium' }, emoji: '☕' },
      { id: 'minibar_premium', label: { es: 'Minibar premium', 'pt-BR': 'Frigobar premium' }, emoji: '🍷' },
      { id: 'bath_products', label: { es: 'Productos baño de autor', 'pt-BR': 'Produtos banho de autor' }, emoji: '🧴' },
      { id: 'robe_slippers', label: { es: 'Bata y pantuflas', 'pt-BR': 'Roupão e chinelos' }, emoji: '👘' },
      { id: 'tech', label: { es: 'Tecnología (Alexa, Chromecast)', 'pt-BR': 'Tecnologia (Alexa, Chromecast)' }, emoji: '📱' },
    ],
  },
  {
    id: 'HB13_ART_COLLECTION',
    category: 'identidad',
    categoryLabel: { es: 'Identidad', 'pt-BR': 'Identidade' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés colección de arte?', 'pt-BR': 'Você tem coleção de arte?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'curated', label: { es: 'Sí, curada/profesional', 'pt-BR': 'Sim, curada/profissional' }, emoji: '🖼️' },
      { id: 'local_artists', label: { es: 'Artistas locales', 'pt-BR': 'Artistas locais' }, emoji: '🎨' },
      { id: 'decorative', label: { es: 'Solo decorativo', 'pt-BR': 'Só decorativo' }, emoji: '🖼️' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB14_LIBRARY_BOOKS',
    category: 'amenities',
    categoryLabel: { es: 'Amenities', 'pt-BR': 'Amenidades' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés biblioteca/sala de lectura?', 'pt-BR': 'Você tem biblioteca/sala de leitura?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'yes', label: { es: 'Sí', 'pt-BR': 'Sim' }, emoji: '📚' },
      { id: 'corner', label: { es: 'Rincón de lectura', 'pt-BR': 'Canto de leitura' }, emoji: '📖' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'HB15_WINE_SELECTION',
    category: 'fnb',
    categoryLabel: { es: 'F&B', 'pt-BR': 'A&B' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Tenés bodega/selección de vinos?', 'pt-BR': 'Você tem adega/seleção de vinhos?' },
    type: 'single',
    businessTypes: [HOTEL_BOUTIQUE],
    options: [
      { id: 'curated', label: { es: 'Sí, selección curada', 'pt-BR': 'Sim, seleção curada' }, emoji: '🍷' },
      { id: 'basic', label: { es: 'Sí, básica', 'pt-BR': 'Sim, básica' }, emoji: '🍾' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
];

// ============================================
// AGENCIA DE VIAJES - Extended
// ============================================
export const AGENCIA_VIAJES_EXTENDED: TurismQuestion[] = [
  {
    id: 'AV01_AGENCY_TYPE',
    category: 'modelo',
    categoryLabel: { es: 'Modelo', 'pt-BR': 'Modelo' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Tipo de agencia', 'pt-BR': 'Tipo de agência' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'retail', label: { es: 'Minorista (venta al público)', 'pt-BR': 'Varejo (venda ao público)' }, emoji: '🏪' },
      { id: 'wholesale', label: { es: 'Mayorista', 'pt-BR': 'Atacado' }, emoji: '🏢' },
      { id: 'both', label: { es: 'Ambos', 'pt-BR': 'Ambos' }, emoji: '🔄' },
      { id: 'online', label: { es: 'Solo online (OTA propia)', 'pt-BR': 'Só online (OTA própria)' }, emoji: '💻' },
    ],
  },
  {
    id: 'AV02_SPECIALIZATION',
    category: 'producto',
    categoryLabel: { es: 'Producto', 'pt-BR': 'Produto' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Tenés especialización?', 'pt-BR': 'Você tem especialização?' },
    type: 'multi',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'luxury', label: { es: 'Lujo', 'pt-BR': 'Luxo' }, emoji: '💎' },
      { id: 'adventure', label: { es: 'Aventura', 'pt-BR': 'Aventura' }, emoji: '🏔️' },
      { id: 'cruise', label: { es: 'Cruceros', 'pt-BR': 'Cruzeiros' }, emoji: '🚢' },
      { id: 'disney', label: { es: 'Disney/Parques', 'pt-BR': 'Disney/Parques' }, emoji: '🏰' },
      { id: 'weddings', label: { es: 'Lunas de miel/Bodas', 'pt-BR': 'Lua de mel/Casamentos' }, emoji: '💒' },
      { id: 'corporate', label: { es: 'Viajes corporativos', 'pt-BR': 'Viagens corporativas' }, emoji: '💼' },
      { id: 'groups', label: { es: 'Grupos', 'pt-BR': 'Grupos' }, emoji: '👥' },
      { id: 'none', label: { es: 'Generalista', 'pt-BR': 'Generalista' }, emoji: '🌍' },
    ],
  },
  {
    id: 'AV03_DESTINATIONS',
    category: 'producto',
    categoryLabel: { es: 'Producto', 'pt-BR': 'Produto' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Destinos principales', 'pt-BR': 'Destinos principais' },
    type: 'multi',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'domestic', label: { es: 'Nacional', 'pt-BR': 'Nacional' }, emoji: '🏠' },
      { id: 'latam', label: { es: 'Latinoamérica', 'pt-BR': 'América Latina' }, emoji: '🌎' },
      { id: 'usa_canada', label: { es: 'USA/Canadá', 'pt-BR': 'EUA/Canadá' }, emoji: '🗽' },
      { id: 'europe', label: { es: 'Europa', 'pt-BR': 'Europa' }, emoji: '🗼' },
      { id: 'asia', label: { es: 'Asia', 'pt-BR': 'Ásia' }, emoji: '🏯' },
      { id: 'other', label: { es: 'Otros', 'pt-BR': 'Outros' }, emoji: '🌍' },
    ],
  },
  {
    id: 'AV04_IATA_MEMBERSHIP',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Tenés licencia IATA?', 'pt-BR': 'Você tem licença IATA?' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'yes', label: { es: 'Sí', 'pt-BR': 'Sim' }, emoji: '✈️' },
      { id: 'no_gds', label: { es: 'No, uso consolidador', 'pt-BR': 'Não, uso consolidador' }, emoji: '🔄' },
      { id: 'applying', label: { es: 'En proceso', 'pt-BR': 'Em processo' }, emoji: '⏳' },
    ],
  },
  {
    id: 'AV05_GDS_SYSTEM',
    category: 'tecnologia',
    categoryLabel: { es: 'Tecnología', 'pt-BR': 'Tecnologia' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Qué GDS usás?', 'pt-BR': 'Qual GDS você usa?' },
    type: 'multi',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'amadeus', label: { es: 'Amadeus', 'pt-BR': 'Amadeus' }, emoji: '🖥️' },
      { id: 'sabre', label: { es: 'Sabre', 'pt-BR': 'Sabre' }, emoji: '🖥️' },
      { id: 'galileo', label: { es: 'Galileo/Travelport', 'pt-BR': 'Galileo/Travelport' }, emoji: '🖥️' },
      { id: 'none', label: { es: 'Ninguno (web directo)', 'pt-BR': 'Nenhum (web direto)' }, emoji: '🌐' },
    ],
  },
  {
    id: 'AV06_REVENUE_MODEL',
    category: 'finanzas',
    categoryLabel: { es: 'Finanzas', 'pt-BR': 'Finanças' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: 'Modelo de ingresos principal', 'pt-BR': 'Modelo de receita principal' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'commission', label: { es: 'Comisión de proveedores', 'pt-BR': 'Comissão de fornecedores' }, emoji: '💰' },
      { id: 'fee', label: { es: 'Fee/Honorarios', 'pt-BR': 'Fee/Honorários' }, emoji: '📋' },
      { id: 'markup', label: { es: 'Markup sobre neto', 'pt-BR': 'Markup sobre líquido' }, emoji: '📈' },
      { id: 'mixed', label: { es: 'Mixto', 'pt-BR': 'Misto' }, emoji: '🔄' },
    ],
  },
  {
    id: 'AV07_AVERAGE_BOOKING',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: 'Valor promedio por reserva', 'pt-BR': 'Valor médio por reserva' },
    type: 'money',
    businessTypes: [AGENCIA_VIAJES],
  },
  {
    id: 'AV08_BOOKINGS_PER_MONTH',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Tráfico',
    title: { es: 'Reservas cerradas por mes', 'pt-BR': 'Reservas fechadas por mês' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: '1-10', label: { es: '1-10', 'pt-BR': '1-10' }, emoji: '📊' },
      { id: '11-30', label: { es: '11-30', 'pt-BR': '11-30' }, emoji: '📈' },
      { id: '31-100', label: { es: '31-100', 'pt-BR': '31-100' }, emoji: '🚀' },
      { id: '100+', label: { es: '+100', 'pt-BR': '+100' }, emoji: '🔥' },
    ],
  },
  {
    id: 'AV09_LEAD_SOURCE',
    category: 'marketing',
    categoryLabel: { es: 'Marketing', 'pt-BR': 'Marketing' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: 'Principal fuente de leads', 'pt-BR': 'Principal fonte de leads' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'referrals', label: { es: 'Referidos', 'pt-BR': 'Indicações' }, emoji: '🗣️' },
      { id: 'social', label: { es: 'Redes sociales', 'pt-BR': 'Redes sociais' }, emoji: '📱' },
      { id: 'google', label: { es: 'Google/SEO', 'pt-BR': 'Google/SEO' }, emoji: '🔍' },
      { id: 'ads', label: { es: 'Publicidad paga', 'pt-BR': 'Publicidade paga' }, emoji: '📢' },
      { id: 'walk_in', label: { es: 'Local físico', 'pt-BR': 'Local físico' }, emoji: '🏪' },
    ],
  },
  {
    id: 'AV10_CRM_USAGE',
    category: 'tecnologia',
    categoryLabel: { es: 'Tecnología', 'pt-BR': 'Tecnologia' },
    mode: 'complete',
    score_area: 'Eficiencia',
    title: { es: '¿Usás CRM?', 'pt-BR': 'Você usa CRM?' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'yes_travel', label: { es: 'Sí, específico turismo', 'pt-BR': 'Sim, específico turismo' }, emoji: '✈️' },
      { id: 'yes_general', label: { es: 'Sí, genérico', 'pt-BR': 'Sim, genérico' }, emoji: '💼' },
      { id: 'excel', label: { es: 'Excel/Manual', 'pt-BR': 'Excel/Manual' }, emoji: '📊' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'AV11_SUPPLIER_RELATIONSHIPS',
    category: 'operacion',
    categoryLabel: { es: 'Operación', 'pt-BR': 'Operação' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '¿Tenés contratos directos con hoteles?', 'pt-BR': 'Você tem contratos diretos com hotéis?' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'many', label: { es: 'Sí, varios', 'pt-BR': 'Sim, vários' }, emoji: '📑' },
      { id: 'few', label: { es: 'Algunos', 'pt-BR': 'Alguns' }, emoji: '📄' },
      { id: 'none', label: { es: 'Solo mayoristas', 'pt-BR': 'Só atacadistas' }, emoji: '🏢' },
    ],
  },
  {
    id: 'AV12_AFTER_SALES',
    category: 'servicio',
    categoryLabel: { es: 'Servicio', 'pt-BR': 'Serviço' },
    mode: 'complete',
    score_area: 'Reputación',
    title: { es: '¿Cómo es tu servicio post-venta?', 'pt-BR': 'Como é seu serviço pós-venda?' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: '24_7', label: { es: 'Soporte 24/7', 'pt-BR': 'Suporte 24/7' }, emoji: '🌙' },
      { id: 'business_hours', label: { es: 'Horario comercial', 'pt-BR': 'Horário comercial' }, emoji: '🏢' },
      { id: 'minimal', label: { es: 'Mínimo', 'pt-BR': 'Mínimo' }, emoji: '📞' },
    ],
  },
  {
    id: 'AV13_PAYMENT_PLANS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '¿Ofrecés planes de pago/cuotas?', 'pt-BR': 'Você oferece parcelamento?' },
    type: 'single',
    businessTypes: [AGENCIA_VIAJES],
    options: [
      { id: 'yes_own', label: { es: 'Sí, propios', 'pt-BR': 'Sim, próprios' }, emoji: '💳' },
      { id: 'yes_card', label: { es: 'Cuotas tarjeta', 'pt-BR': 'Parcelas cartão' }, emoji: '💳' },
      { id: 'no', label: { es: 'No', 'pt-BR': 'Não' }, emoji: '❌' },
    ],
  },
  {
    id: 'AV14_REPEAT_CLIENTS',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Crecimiento',
    title: { es: '% de clientes recurrentes', 'pt-BR': '% de clientes recorrentes' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
    businessTypes: [AGENCIA_VIAJES],
  },
  {
    id: 'AV15_INSURANCE_SALES',
    category: 'ventas',
    categoryLabel: { es: 'Ventas', 'pt-BR': 'Vendas' },
    mode: 'complete',
    score_area: 'Rentabilidad',
    title: { es: '% de ventas con seguro de viaje', 'pt-BR': '% de vendas com seguro viagem' },
    type: 'slider',
    min: 0,
    max: 100,
    unit: '%',
    businessTypes: [AGENCIA_VIAJES],
  },
];

// Combine all extended questions
export const TURISMO_EXTENDED_QUESTIONS: TurismQuestion[] = [
  ...HOTEL_URBANO_EXTENDED,
  ...HOTEL_BOUTIQUE_EXTENDED,
  ...AGENCIA_VIAJES_EXTENDED,
];
