// Tourism, Hospitality, Leisure & Events - COMPLETE 18 Business Types
// Sector A2_TURISMO - Ultra-specific questionnaires

import type { VistaSetupQuestion } from '../vistaSetupQuestion';

// ============= POSADA / LODGE QUESTIONS =============
export const POSADA_LODGE_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_POSADA_STYLE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuál es el estilo de tu posada/lodge?', 'pt-BR': 'Qual é o estilo da sua pousada/lodge?' },
    type: 'single',
    required: true,
    businessTypes: ['posada_lodge'],
    options: [
      { id: 'rustic', label: { es: 'Rústico/Campo', 'pt-BR': 'Rústico/Campo' }, emoji: '🏡', impactScore: 15 },
      { id: 'eco', label: { es: 'Eco-lodge', 'pt-BR': 'Eco-lodge' }, emoji: '🌿', impactScore: 18 },
      { id: 'adventure', label: { es: 'Aventura/Outdoor', 'pt-BR': 'Aventura/Outdoor' }, emoji: '🏔️', impactScore: 15 },
      { id: 'wine', label: { es: 'Viñedos/Enoturismo', 'pt-BR': 'Vinícola/Enoturismo' }, emoji: '🍷', impactScore: 18 },
      { id: 'thermal', label: { es: 'Termas/Wellness', 'pt-BR': 'Termas/Wellness' }, emoji: '♨️', impactScore: 18 },
      { id: 'beach', label: { es: 'Playa/Costa', 'pt-BR': 'Praia/Costa' }, emoji: '🏖️', impactScore: 15 },
    ],
  },
  {
    id: 'Q_POSADA_ROOMS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cuántas habitaciones/cabañas tenés?', 'pt-BR': 'Quantos quartos/chalés você tem?' },
    type: 'single',
    businessTypes: ['posada_lodge'],
    options: [
      { id: '1-5', label: { es: '1-5 unidades', 'pt-BR': '1-5 unidades' }, emoji: '🏠', impactScore: 10 },
      { id: '6-12', label: { es: '6-12 unidades', 'pt-BR': '6-12 unidades' }, emoji: '🏘️', impactScore: 15 },
      { id: '13-25', label: { es: '13-25 unidades', 'pt-BR': '13-25 unidades' }, emoji: '🏨', impactScore: 18 },
      { id: '25+', label: { es: 'Más de 25', 'pt-BR': 'Mais de 25' }, emoji: '🏢', impactScore: 20 },
    ],
  },
  {
    id: 'Q_POSADA_EXPERIENCES',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué experiencias ofrecés?', 'pt-BR': 'Quais experiências você oferece?' },
    type: 'multi',
    businessTypes: ['posada_lodge'],
    options: [
      { id: 'hiking', label: { es: 'Senderismo/Trekking', 'pt-BR': 'Trilhas/Trekking' }, emoji: '🥾', impactScore: 12 },
      { id: 'horseback', label: { es: 'Cabalgatas', 'pt-BR': 'Cavalgadas' }, emoji: '🐴', impactScore: 12 },
      { id: 'gastronomy', label: { es: 'Experiencias gastro', 'pt-BR': 'Experiências gastro' }, emoji: '🍽️', impactScore: 15 },
      { id: 'birdwatching', label: { es: 'Avistaje/Naturaleza', 'pt-BR': 'Observação/Natureza' }, emoji: '🦅', impactScore: 10 },
      { id: 'fishing', label: { es: 'Pesca', 'pt-BR': 'Pesca' }, emoji: '🎣', impactScore: 10 },
      { id: 'spa', label: { es: 'Spa/Masajes', 'pt-BR': 'Spa/Massagens' }, emoji: '🧖', impactScore: 12 },
    ],
  },
  {
    id: 'Q_POSADA_MEAL_PLAN',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Qué plan de comidas ofrecés?', 'pt-BR': 'Qual plano de refeições você oferece?' },
    type: 'single',
    businessTypes: ['posada_lodge'],
    options: [
      { id: 'all_inclusive', label: { es: 'Pensión completa', 'pt-BR': 'Pensão completa' }, emoji: '🍽️', impactScore: 18 },
      { id: 'half_board', label: { es: 'Media pensión', 'pt-BR': 'Meia pensão' }, emoji: '🥐', impactScore: 15 },
      { id: 'breakfast', label: { es: 'Solo desayuno', 'pt-BR': 'Só café da manhã' }, emoji: '☕', impactScore: 10 },
      { id: 'self_catering', label: { es: 'Sin comidas', 'pt-BR': 'Sem refeições' }, emoji: '🏠', impactScore: 8 },
    ],
  },
  {
    id: 'Q_POSADA_STAY_LENGTH',
    category: 'operation',
    mode: 'complete',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cuál es la estadía promedio?', 'pt-BR': 'Qual é a estadia média?' },
    type: 'single',
    businessTypes: ['posada_lodge'],
    options: [
      { id: '1-2', label: { es: '1-2 noches', 'pt-BR': '1-2 noites' }, emoji: '⚡', impactScore: 8 },
      { id: '3-4', label: { es: '3-4 noches', 'pt-BR': '3-4 noites' }, emoji: '📅', impactScore: 15 },
      { id: '5-7', label: { es: '5-7 noches', 'pt-BR': '5-7 noites' }, emoji: '🏝️', impactScore: 18 },
      { id: '7+', label: { es: 'Más de una semana', 'pt-BR': 'Mais de uma semana' }, emoji: '🌴', impactScore: 20 },
    ],
  },
];

// ============= APART HOTEL / SUITES QUESTIONS =============
export const APART_HOTEL_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_APART_TARGET',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Cuál es tu público principal?', 'pt-BR': 'Qual é seu público principal?' },
    type: 'single',
    required: true,
    businessTypes: ['apart_hotel'],
    options: [
      { id: 'business', label: { es: 'Ejecutivos/Viajeros de negocios', 'pt-BR': 'Executivos/Viajantes de negócios' }, emoji: '💼', impactScore: 18 },
      { id: 'families', label: { es: 'Familias', 'pt-BR': 'Famílias' }, emoji: '👨‍👩‍👧', impactScore: 15 },
      { id: 'long_stay', label: { es: 'Estadías largas/Relocación', 'pt-BR': 'Estadias longas/Relocação' }, emoji: '📦', impactScore: 18 },
      { id: 'medical', label: { es: 'Turismo médico', 'pt-BR': 'Turismo médico' }, emoji: '🏥', impactScore: 15 },
      { id: 'mixed', label: { es: 'Mix variado', 'pt-BR': 'Mix variado' }, emoji: '🔀', impactScore: 12 },
    ],
  },
  {
    id: 'Q_APART_UNITS',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántas unidades tenés?', 'pt-BR': 'Quantas unidades você tem?' },
    type: 'single',
    businessTypes: ['apart_hotel'],
    options: [
      { id: '1-10', label: { es: '1-10 unidades', 'pt-BR': '1-10 unidades' }, emoji: '🏠', impactScore: 10 },
      { id: '11-30', label: { es: '11-30 unidades', 'pt-BR': '11-30 unidades' }, emoji: '🏢', impactScore: 15 },
      { id: '31-60', label: { es: '31-60 unidades', 'pt-BR': '31-60 unidades' }, emoji: '🏙️', impactScore: 18 },
      { id: '60+', label: { es: 'Más de 60', 'pt-BR': 'Mais de 60' }, emoji: '🌆', impactScore: 20 },
    ],
  },
  {
    id: 'Q_APART_AMENITIES',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 7,
    title: { es: '¿Qué amenities ofrecés?', 'pt-BR': 'Quais amenidades você oferece?' },
    type: 'multi',
    businessTypes: ['apart_hotel'],
    options: [
      { id: 'kitchen', label: { es: 'Cocina completa', 'pt-BR': 'Cozinha completa' }, emoji: '🍳', impactScore: 15 },
      { id: 'laundry', label: { es: 'Lavandería', 'pt-BR': 'Lavanderia' }, emoji: '🧺', impactScore: 10 },
      { id: 'gym', label: { es: 'Gimnasio', 'pt-BR': 'Academia' }, emoji: '🏋️', impactScore: 10 },
      { id: 'pool', label: { es: 'Piscina', 'pt-BR': 'Piscina' }, emoji: '🏊', impactScore: 12 },
      { id: 'coworking', label: { es: 'Coworking/Business center', 'pt-BR': 'Coworking/Business center' }, emoji: '💻', impactScore: 12 },
      { id: 'parking', label: { es: 'Estacionamiento', 'pt-BR': 'Estacionamento' }, emoji: '🅿️', impactScore: 10 },
    ],
  },
  {
    id: 'Q_APART_STAY_TYPE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué tipo de estadías manejás más?', 'pt-BR': 'Que tipo de estadias você mais administra?' },
    type: 'single',
    businessTypes: ['apart_hotel'],
    options: [
      { id: 'short', label: { es: 'Cortas (1-7 noches)', 'pt-BR': 'Curtas (1-7 noites)' }, emoji: '⚡', impactScore: 10 },
      { id: 'medium', label: { es: 'Medias (1-4 semanas)', 'pt-BR': 'Médias (1-4 semanas)' }, emoji: '📅', impactScore: 15 },
      { id: 'long', label: { es: 'Largas (1-3 meses)', 'pt-BR': 'Longas (1-3 meses)' }, emoji: '📆', impactScore: 18 },
      { id: 'extended', label: { es: 'Extendidas (+3 meses)', 'pt-BR': 'Estendidas (+3 meses)' }, emoji: '🏠', impactScore: 20 },
    ],
  },
  {
    id: 'Q_APART_SERVICES',
    category: 'menu',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 6,
    title: { es: '¿Qué servicios adicionales ofrecés?', 'pt-BR': 'Quais serviços adicionais você oferece?' },
    type: 'multi',
    businessTypes: ['apart_hotel'],
    options: [
      { id: 'cleaning', label: { es: 'Limpieza periódica', 'pt-BR': 'Limpeza periódica' }, emoji: '🧹', impactScore: 12 },
      { id: 'concierge', label: { es: 'Concierge 24h', 'pt-BR': 'Concierge 24h' }, emoji: '🎩', impactScore: 15 },
      { id: 'breakfast', label: { es: 'Desayuno opcional', 'pt-BR': 'Café da manhã opcional' }, emoji: '🥐', impactScore: 10 },
      { id: 'transfers', label: { es: 'Transfers', 'pt-BR': 'Transfers' }, emoji: '🚐', impactScore: 8 },
    ],
  },
];

// ============= ALQUILER TEMPORARIO / SHORT STAY QUESTIONS =============
export const ALQUILER_TEMPORARIO_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_ALQUILER_PROPERTY_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de propiedad alquilás?', 'pt-BR': 'Que tipo de propriedade você aluga?' },
    type: 'single',
    required: true,
    businessTypes: ['alquiler_temporario'],
    options: [
      { id: 'apartment', label: { es: 'Departamento/Piso', 'pt-BR': 'Apartamento' }, emoji: '🏢', impactScore: 15 },
      { id: 'house', label: { es: 'Casa completa', 'pt-BR': 'Casa completa' }, emoji: '🏠', impactScore: 18 },
      { id: 'cabin', label: { es: 'Cabaña/Cottage', 'pt-BR': 'Chalé/Cottage' }, emoji: '🏡', impactScore: 15 },
      { id: 'studio', label: { es: 'Monoambiente/Studio', 'pt-BR': 'Kitnet/Studio' }, emoji: '🛏️', impactScore: 10 },
      { id: 'room', label: { es: 'Habitación privada', 'pt-BR': 'Quarto privado' }, emoji: '🚪', impactScore: 8 },
      { id: 'unique', label: { es: 'Alojamiento único', 'pt-BR': 'Hospedagem única' }, emoji: '✨', impactScore: 20 },
    ],
  },
  {
    id: 'Q_ALQUILER_UNITS_COUNT',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuántas propiedades gestionás?', 'pt-BR': 'Quantas propriedades você gerencia?' },
    type: 'single',
    businessTypes: ['alquiler_temporario'],
    options: [
      { id: '1', label: { es: '1 propiedad', 'pt-BR': '1 propriedade' }, emoji: '🏠', impactScore: 8 },
      { id: '2-5', label: { es: '2-5 propiedades', 'pt-BR': '2-5 propriedades' }, emoji: '🏘️', impactScore: 12 },
      { id: '6-15', label: { es: '6-15 propiedades', 'pt-BR': '6-15 propriedades' }, emoji: '🏢', impactScore: 18 },
      { id: '15+', label: { es: 'Más de 15', 'pt-BR': 'Mais de 15' }, emoji: '🌆', impactScore: 22 },
    ],
  },
  {
    id: 'Q_ALQUILER_PLATFORMS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿En qué plataformas publicás?', 'pt-BR': 'Em quais plataformas você publica?' },
    type: 'multi',
    businessTypes: ['alquiler_temporario'],
    options: [
      { id: 'airbnb', label: { es: 'Airbnb', 'pt-BR': 'Airbnb' }, emoji: '🏠', impactScore: 15 },
      { id: 'booking', label: { es: 'Booking.com', 'pt-BR': 'Booking.com' }, emoji: '🔵', impactScore: 12 },
      { id: 'vrbo', label: { es: 'VRBO/HomeAway', 'pt-BR': 'VRBO/HomeAway' }, emoji: '🏡', impactScore: 10 },
      { id: 'direct', label: { es: 'Web propia', 'pt-BR': 'Site próprio' }, emoji: '🌐', impactScore: 18 },
      { id: 'local', label: { es: 'Plataformas locales', 'pt-BR': 'Plataformas locais' }, emoji: '📍', impactScore: 8 },
    ],
  },
  {
    id: 'Q_ALQUILER_OCCUPANCY',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es tu ocupación promedio anual?', 'pt-BR': 'Qual é sua ocupação média anual?' },
    type: 'single',
    businessTypes: ['alquiler_temporario'],
    options: [
      { id: 'high_70', label: { es: '+70% ocupación', 'pt-BR': '+70% ocupação' }, emoji: '🔥', impactScore: 25 },
      { id: 'good_50', label: { es: '50-70% ocupación', 'pt-BR': '50-70% ocupação' }, emoji: '👍', impactScore: 18 },
      { id: 'medium_30', label: { es: '30-50% ocupación', 'pt-BR': '30-50% ocupação' }, emoji: '📊', impactScore: 10 },
      { id: 'low', label: { es: 'Menos del 30%', 'pt-BR': 'Menos de 30%' }, emoji: '📉', impactScore: 5 },
    ],
  },
  {
    id: 'Q_ALQUILER_MANAGEMENT',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Cómo gestionás las propiedades?', 'pt-BR': 'Como você gerencia as propriedades?' },
    type: 'single',
    businessTypes: ['alquiler_temporario'],
    options: [
      { id: 'self', label: { es: 'Yo mismo/a', 'pt-BR': 'Eu mesmo/a' }, emoji: '👤', impactScore: 10 },
      { id: 'software', label: { es: 'Con software (Hostaway, Guesty)', 'pt-BR': 'Com software (Hostaway, Guesty)' }, emoji: '💻', impactScore: 18 },
      { id: 'team', label: { es: 'Equipo propio', 'pt-BR': 'Equipe própria' }, emoji: '👥', impactScore: 15 },
      { id: 'outsourced', label: { es: 'Tercerizado', 'pt-BR': 'Terceirizado' }, emoji: '🤝', impactScore: 12 },
    ],
  },
];

// ============= OPERADOR TURISTICO / RECEPTIVO QUESTIONS =============
export const OPERADOR_TURISTICO_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_OPERADOR_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de operador sos?', 'pt-BR': 'Que tipo de operador você é?' },
    type: 'single',
    required: true,
    businessTypes: ['operador_turistico'],
    options: [
      { id: 'receptive', label: { es: 'Receptivo (turistas entrantes)', 'pt-BR': 'Receptivo (turistas entrantes)' }, emoji: '🛬', impactScore: 18 },
      { id: 'outbound', label: { es: 'Emisivo (turistas salientes)', 'pt-BR': 'Emissivo (turistas saindo)' }, emoji: '🛫', impactScore: 15 },
      { id: 'dmc', label: { es: 'DMC (Destination Management)', 'pt-BR': 'DMC (Destination Management)' }, emoji: '🗺️', impactScore: 20 },
      { id: 'mice', label: { es: 'MICE/Corporativo', 'pt-BR': 'MICE/Corporativo' }, emoji: '💼', impactScore: 18 },
      { id: 'both', label: { es: 'Mixto (receptivo + emisivo)', 'pt-BR': 'Misto (receptivo + emissivo)' }, emoji: '🔄', impactScore: 15 },
    ],
  },
  {
    id: 'Q_OPERADOR_PRODUCTS',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué productos armás/vendés?', 'pt-BR': 'Quais produtos você monta/vende?' },
    type: 'multi',
    businessTypes: ['operador_turistico'],
    options: [
      { id: 'packages', label: { es: 'Paquetes completos', 'pt-BR': 'Pacotes completos' }, emoji: '📦', impactScore: 18 },
      { id: 'excursions', label: { es: 'Excursiones/Day tours', 'pt-BR': 'Excursões/Day tours' }, emoji: '🚌', impactScore: 12 },
      { id: 'transfers', label: { es: 'Transfers', 'pt-BR': 'Transfers' }, emoji: '🚐', impactScore: 10 },
      { id: 'incentives', label: { es: 'Viajes de incentivo', 'pt-BR': 'Viagens de incentivo' }, emoji: '🏆', impactScore: 15 },
      { id: 'events', label: { es: 'Eventos/Congresos', 'pt-BR': 'Eventos/Congressos' }, emoji: '🎪', impactScore: 15 },
      { id: 'custom', label: { es: 'Tailor-made/A medida', 'pt-BR': 'Sob medida' }, emoji: '✨', impactScore: 18 },
    ],
  },
  {
    id: 'Q_OPERADOR_CLIENTS',
    category: 'marketing',
    mode: 'both',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Quiénes son tus clientes principales?', 'pt-BR': 'Quem são seus principais clientes?' },
    type: 'multi',
    businessTypes: ['operador_turistico'],
    options: [
      { id: 'agencies', label: { es: 'Agencias de viajes', 'pt-BR': 'Agências de viagens' }, emoji: '🏪', impactScore: 15 },
      { id: 'direct', label: { es: 'Turistas directos', 'pt-BR': 'Turistas diretos' }, emoji: '👥', impactScore: 12 },
      { id: 'corporate', label: { es: 'Empresas', 'pt-BR': 'Empresas' }, emoji: '💼', impactScore: 18 },
      { id: 'otas', label: { es: 'OTAs/Online', 'pt-BR': 'OTAs/Online' }, emoji: '💻', impactScore: 12 },
      { id: 'wholesalers', label: { es: 'Mayoristas internacionales', 'pt-BR': 'Operadoras internacionais' }, emoji: '🌍', impactScore: 15 },
    ],
  },
  {
    id: 'Q_OPERADOR_PAX_YEAR',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántos pasajeros movés por año?', 'pt-BR': 'Quantos passageiros você move por ano?' },
    type: 'single',
    businessTypes: ['operador_turistico'],
    options: [
      { id: 'small_500', label: { es: 'Hasta 500 pax', 'pt-BR': 'Até 500 pax' }, emoji: '📊', impactScore: 10 },
      { id: 'medium_2000', label: { es: '500-2000 pax', 'pt-BR': '500-2000 pax' }, emoji: '📈', impactScore: 15 },
      { id: 'large_5000', label: { es: '2000-5000 pax', 'pt-BR': '2000-5000 pax' }, emoji: '🚀', impactScore: 20 },
      { id: 'mega', label: { es: 'Más de 5000 pax', 'pt-BR': 'Mais de 5000 pax' }, emoji: '🔥', impactScore: 25 },
    ],
  },
  {
    id: 'Q_OPERADOR_TECH',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Qué tecnología usás?', 'pt-BR': 'Qual tecnologia você usa?' },
    type: 'single',
    businessTypes: ['operador_turistico'],
    options: [
      { id: 'erp', label: { es: 'ERP turístico (Dingus, OOBT)', 'pt-BR': 'ERP turístico (Dingus, OOBT)' }, emoji: '💻', impactScore: 20 },
      { id: 'crm', label: { es: 'CRM + Excel', 'pt-BR': 'CRM + Excel' }, emoji: '📊', impactScore: 12 },
      { id: 'manual', label: { es: 'Mayormente manual', 'pt-BR': 'Maiormente manual' }, emoji: '📓', impactScore: 5 },
      { id: 'custom', label: { es: 'Sistema propio', 'pt-BR': 'Sistema próprio' }, emoji: '⚙️', impactScore: 15 },
    ],
  },
];

// ============= TURISMO AVENTURA / OUTDOOR QUESTIONS =============
export const TURISMO_AVENTURA_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_AVENTURA_ACTIVITIES',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué actividades ofrecés?', 'pt-BR': 'Quais atividades você oferece?' },
    type: 'multi',
    required: true,
    businessTypes: ['turismo_aventura'],
    options: [
      { id: 'rafting', label: { es: 'Rafting/Kayak', 'pt-BR': 'Rafting/Caiaque' }, emoji: '🚣', impactScore: 15 },
      { id: 'climbing', label: { es: 'Escalada/Rappel', 'pt-BR': 'Escalada/Rapel' }, emoji: '🧗', impactScore: 15 },
      { id: 'trekking', label: { es: 'Trekking/Montañismo', 'pt-BR': 'Trekking/Montanhismo' }, emoji: '🥾', impactScore: 12 },
      { id: 'zipline', label: { es: 'Tirolesa/Canopy', 'pt-BR': 'Tirolesa/Arvorismo' }, emoji: '🌲', impactScore: 12 },
      { id: 'diving', label: { es: 'Buceo/Snorkel', 'pt-BR': 'Mergulho/Snorkel' }, emoji: '🤿', impactScore: 15 },
      { id: 'paragliding', label: { es: 'Parapente/Vuelos', 'pt-BR': 'Parapente/Voos' }, emoji: '🪂', impactScore: 15 },
      { id: 'offroad', label: { es: '4x4/Off-road', 'pt-BR': '4x4/Off-road' }, emoji: '🚙', impactScore: 12 },
      { id: 'ski', label: { es: 'Ski/Snowboard', 'pt-BR': 'Ski/Snowboard' }, emoji: '⛷️', impactScore: 15 },
    ],
  },
  {
    id: 'Q_AVENTURA_RISK_LEVEL',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es el nivel de dificultad más común?', 'pt-BR': 'Qual é o nível de dificuldade mais comum?' },
    type: 'single',
    businessTypes: ['turismo_aventura'],
    options: [
      { id: 'family', label: { es: 'Familiar/Todos', 'pt-BR': 'Familiar/Todos' }, emoji: '👨‍👩‍👧', impactScore: 12 },
      { id: 'moderate', label: { es: 'Moderado', 'pt-BR': 'Moderado' }, emoji: '🏃', impactScore: 15 },
      { id: 'challenging', label: { es: 'Desafiante', 'pt-BR': 'Desafiador' }, emoji: '💪', impactScore: 15 },
      { id: 'extreme', label: { es: 'Extremo', 'pt-BR': 'Extremo' }, emoji: '⚡', impactScore: 18 },
    ],
  },
  {
    id: 'Q_AVENTURA_EQUIPMENT',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Tenés equipamiento propio?', 'pt-BR': 'Você tem equipamento próprio?' },
    type: 'single',
    businessTypes: ['turismo_aventura'],
    options: [
      { id: 'full', label: { es: 'Todo propio', 'pt-BR': 'Tudo próprio' }, emoji: '✅', impactScore: 20 },
      { id: 'partial', label: { es: 'Parte propio, parte alquilado', 'pt-BR': 'Parte próprio, parte alugado' }, emoji: '🔄', impactScore: 12 },
      { id: 'rental', label: { es: 'Mayormente alquilado', 'pt-BR': 'Maiormente alugado' }, emoji: '🤝', impactScore: 8 },
    ],
  },
  {
    id: 'Q_AVENTURA_SAFETY',
    category: 'operation',
    mode: 'complete',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué certificaciones/seguros tenés?', 'pt-BR': 'Quais certificações/seguros você tem?' },
    type: 'multi',
    businessTypes: ['turismo_aventura'],
    options: [
      { id: 'guides_cert', label: { es: 'Guías certificados', 'pt-BR': 'Guias certificados' }, emoji: '🎓', impactScore: 18 },
      { id: 'insurance', label: { es: 'Seguro de accidentes', 'pt-BR': 'Seguro de acidentes' }, emoji: '🛡️', impactScore: 18 },
      { id: 'first_aid', label: { es: 'Primeros auxilios', 'pt-BR': 'Primeiros socorros' }, emoji: '🩹', impactScore: 12 },
      { id: 'rescue', label: { es: 'Plan de rescate', 'pt-BR': 'Plano de resgate' }, emoji: '🚁', impactScore: 15 },
      { id: 'iso', label: { es: 'ISO/Certificaciones', 'pt-BR': 'ISO/Certificações' }, emoji: '✅', impactScore: 15 },
    ],
  },
  {
    id: 'Q_AVENTURA_GROUP_SIZE',
    category: 'operation',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cuál es el tamaño típico de grupo?', 'pt-BR': 'Qual é o tamanho típico do grupo?' },
    type: 'single',
    businessTypes: ['turismo_aventura'],
    options: [
      { id: 'individual', label: { es: 'Individual/Parejas', 'pt-BR': 'Individual/Casais' }, emoji: '👤', impactScore: 15 },
      { id: 'small', label: { es: 'Pequeños (4-8)', 'pt-BR': 'Pequenos (4-8)' }, emoji: '👥', impactScore: 15 },
      { id: 'medium', label: { es: 'Medianos (9-15)', 'pt-BR': 'Médios (9-15)' }, emoji: '🚐', impactScore: 12 },
      { id: 'large', label: { es: 'Grandes (+15)', 'pt-BR': 'Grandes (+15)' }, emoji: '🚌', impactScore: 10 },
    ],
  },
];

// ============= ATRACCIONES / TICKETS / EXPERIENCIAS QUESTIONS =============
export const ATRACCIONES_TICKETS_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_ATRACCION_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de atracción/experiencia sos?', 'pt-BR': 'Que tipo de atração/experiência você é?' },
    type: 'single',
    required: true,
    businessTypes: ['atracciones_tickets'],
    options: [
      { id: 'museum', label: { es: 'Museo/Galería', 'pt-BR': 'Museu/Galeria' }, emoji: '🏛️', impactScore: 15 },
      { id: 'observation', label: { es: 'Mirador/Observatorio', 'pt-BR': 'Mirante/Observatório' }, emoji: '🔭', impactScore: 15 },
      { id: 'show', label: { es: 'Show/Espectáculo', 'pt-BR': 'Show/Espetáculo' }, emoji: '🎭', impactScore: 18 },
      { id: 'experience', label: { es: 'Experiencia inmersiva', 'pt-BR': 'Experiência imersiva' }, emoji: '🎮', impactScore: 18 },
      { id: 'sports', label: { es: 'Evento deportivo', 'pt-BR': 'Evento esportivo' }, emoji: '⚽', impactScore: 15 },
      { id: 'escape', label: { es: 'Escape room/Juegos', 'pt-BR': 'Escape room/Jogos' }, emoji: '🔐', impactScore: 12 },
      { id: 'wine', label: { es: 'Catas/Degustaciones', 'pt-BR': 'Degustações' }, emoji: '🍷', impactScore: 15 },
    ],
  },
  {
    id: 'Q_ATRACCION_CAPACITY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu capacidad por sesión/turno?', 'pt-BR': 'Qual é sua capacidade por sessão/turno?' },
    type: 'single',
    businessTypes: ['atracciones_tickets'],
    options: [
      { id: 'small_20', label: { es: 'Hasta 20 personas', 'pt-BR': 'Até 20 pessoas' }, emoji: '👥', impactScore: 10 },
      { id: 'medium_50', label: { es: '20-50 personas', 'pt-BR': '20-50 pessoas' }, emoji: '🏢', impactScore: 12 },
      { id: 'large_200', label: { es: '50-200 personas', 'pt-BR': '50-200 pessoas' }, emoji: '🏛️', impactScore: 15 },
      { id: 'massive', label: { es: 'Más de 200', 'pt-BR': 'Mais de 200' }, emoji: '🌆', impactScore: 18 },
    ],
  },
  {
    id: 'Q_ATRACCION_TICKETING',
    category: 'operation',
    mode: 'both',
    dimension: 'traffic',
    weight: 8,
    title: { es: '¿Cómo vendés tus entradas?', 'pt-BR': 'Como você vende seus ingressos?' },
    type: 'multi',
    businessTypes: ['atracciones_tickets'],
    options: [
      { id: 'onsite', label: { es: 'Boletería física', 'pt-BR': 'Bilheteria física' }, emoji: '🎫', impactScore: 10 },
      { id: 'website', label: { es: 'Web propia', 'pt-BR': 'Site próprio' }, emoji: '🌐', impactScore: 18 },
      { id: 'otas', label: { es: 'OTAs (Viator, GYG)', 'pt-BR': 'OTAs (Viator, GYG)' }, emoji: '🦉', impactScore: 12 },
      { id: 'resellers', label: { es: 'Revendedores/Agencias', 'pt-BR': 'Revendedores/Agências' }, emoji: '🏪', impactScore: 12 },
      { id: 'ticketmaster', label: { es: 'Ticketmaster/Passline', 'pt-BR': 'Ticketmaster/Sympla' }, emoji: '🎟️', impactScore: 15 },
    ],
  },
  {
    id: 'Q_ATRACCION_PRICING',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cómo estructurás tus precios?', 'pt-BR': 'Como você estrutura seus preços?' },
    type: 'multi',
    businessTypes: ['atracciones_tickets'],
    options: [
      { id: 'fixed', label: { es: 'Precio único', 'pt-BR': 'Preço único' }, emoji: '💰', impactScore: 10 },
      { id: 'dynamic', label: { es: 'Precio dinámico', 'pt-BR': 'Preço dinâmico' }, emoji: '📈', impactScore: 18 },
      { id: 'tiers', label: { es: 'Por categorías (VIP, General)', 'pt-BR': 'Por categorias (VIP, Geral)' }, emoji: '⭐', impactScore: 15 },
      { id: 'combos', label: { es: 'Combos/Paquetes', 'pt-BR': 'Combos/Pacotes' }, emoji: '📦', impactScore: 12 },
      { id: 'discounts', label: { es: 'Descuentos (estudiantes, etc)', 'pt-BR': 'Descontos (estudantes, etc)' }, emoji: '🎓', impactScore: 10 },
    ],
  },
];

// ============= TEATRO / SALA DE ESPECTACULOS QUESTIONS =============
export const TEATRO_ESPECTACULOS_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_TEATRO_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de espacio sos?', 'pt-BR': 'Que tipo de espaço você é?' },
    type: 'single',
    required: true,
    businessTypes: ['teatro_espectaculos'],
    options: [
      { id: 'theater', label: { es: 'Teatro tradicional', 'pt-BR': 'Teatro tradicional' }, emoji: '🎭', impactScore: 18 },
      { id: 'concert', label: { es: 'Sala de conciertos', 'pt-BR': 'Casa de shows' }, emoji: '🎵', impactScore: 18 },
      { id: 'cultural', label: { es: 'Centro cultural', 'pt-BR': 'Centro cultural' }, emoji: '🏛️', impactScore: 15 },
      { id: 'comedy', label: { es: 'Stand up/Comedy club', 'pt-BR': 'Stand up/Comedy club' }, emoji: '🎤', impactScore: 15 },
      { id: 'independent', label: { es: 'Espacio independiente', 'pt-BR': 'Espaço independente' }, emoji: '🎨', impactScore: 12 },
      { id: 'multipurpose', label: { es: 'Multiuso/Polivalente', 'pt-BR': 'Multiuso/Polivalente' }, emoji: '🔄', impactScore: 12 },
    ],
  },
  {
    id: 'Q_TEATRO_CAPACITY',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es tu capacidad?', 'pt-BR': 'Qual é sua capacidade?' },
    type: 'single',
    businessTypes: ['teatro_espectaculos'],
    options: [
      { id: 'intimate_100', label: { es: 'Hasta 100 butacas', 'pt-BR': 'Até 100 lugares' }, emoji: '🎭', impactScore: 10 },
      { id: 'small_300', label: { es: '100-300 butacas', 'pt-BR': '100-300 lugares' }, emoji: '🏛️', impactScore: 15 },
      { id: 'medium_800', label: { es: '300-800 butacas', 'pt-BR': '300-800 lugares' }, emoji: '🏢', impactScore: 18 },
      { id: 'large', label: { es: 'Más de 800', 'pt-BR': 'Mais de 800' }, emoji: '🌆', impactScore: 22 },
    ],
  },
  {
    id: 'Q_TEATRO_CONTENT',
    category: 'menu',
    mode: 'both',
    dimension: 'reputation',
    weight: 8,
    title: { es: '¿Qué tipo de contenido programás?', 'pt-BR': 'Que tipo de conteúdo você programa?' },
    type: 'multi',
    businessTypes: ['teatro_espectaculos'],
    options: [
      { id: 'own_productions', label: { es: 'Producciones propias', 'pt-BR': 'Produções próprias' }, emoji: '🎬', impactScore: 18 },
      { id: 'rental', label: { es: 'Alquiler de sala', 'pt-BR': 'Aluguel de sala' }, emoji: '🔑', impactScore: 12 },
      { id: 'coproductions', label: { es: 'Coproducciones', 'pt-BR': 'Coproduções' }, emoji: '🤝', impactScore: 15 },
      { id: 'touring', label: { es: 'Shows de gira', 'pt-BR': 'Shows em turnê' }, emoji: '🚌', impactScore: 15 },
      { id: 'festivals', label: { es: 'Festivales/Ciclos', 'pt-BR': 'Festivais/Ciclos' }, emoji: '🎪', impactScore: 12 },
    ],
  },
  {
    id: 'Q_TEATRO_FUNCTIONS',
    category: 'operation',
    mode: 'both',
    dimension: 'profitability',
    weight: 7,
    title: { es: '¿Cuántas funciones hacés por semana?', 'pt-BR': 'Quantas sessões você faz por semana?' },
    type: 'single',
    businessTypes: ['teatro_espectaculos'],
    options: [
      { id: '1-3', label: { es: '1-3 funciones', 'pt-BR': '1-3 sessões' }, emoji: '📊', impactScore: 10 },
      { id: '4-7', label: { es: '4-7 funciones', 'pt-BR': '4-7 sessões' }, emoji: '📈', impactScore: 15 },
      { id: '8-14', label: { es: '8-14 funciones', 'pt-BR': '8-14 sessões' }, emoji: '🚀', impactScore: 18 },
      { id: '14+', label: { es: 'Más de 14', 'pt-BR': 'Mais de 14' }, emoji: '🔥', impactScore: 22 },
    ],
  },
  {
    id: 'Q_TEATRO_TICKETING',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cómo vendés tus entradas?', 'pt-BR': 'Como você vende seus ingressos?' },
    type: 'multi',
    businessTypes: ['teatro_espectaculos'],
    options: [
      { id: 'box_office', label: { es: 'Boletería propia', 'pt-BR': 'Bilheteria própria' }, emoji: '🎫', impactScore: 12 },
      { id: 'alternativa', label: { es: 'Alternativa Teatral', 'pt-BR': 'Alternativa Teatral' }, emoji: '🎭', impactScore: 12, countries: ['AR'] },
      { id: 'plateanet', label: { es: 'Plateanet/Ticketek', 'pt-BR': 'Ticketmaster/Sympla' }, emoji: '🎟️', impactScore: 15 },
      { id: 'website', label: { es: 'Web propia', 'pt-BR': 'Site próprio' }, emoji: '🌐', impactScore: 18 },
    ],
  },
];

// ============= EVENTOS CORPORATIVOS (MICE) QUESTIONS =============
export const EVENTOS_MICE_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_MICE_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de eventos corporativos organizás?', 'pt-BR': 'Que tipo de eventos corporativos você organiza?' },
    type: 'multi',
    required: true,
    businessTypes: ['eventos_mice'],
    options: [
      { id: 'meetings', label: { es: 'Reuniones/Meetings', 'pt-BR': 'Reuniões/Meetings' }, emoji: '👥', impactScore: 12 },
      { id: 'incentives', label: { es: 'Viajes de incentivo', 'pt-BR': 'Viagens de incentivo' }, emoji: '🏆', impactScore: 18 },
      { id: 'conferences', label: { es: 'Conferencias/Congresos', 'pt-BR': 'Conferências/Congressos' }, emoji: '🎤', impactScore: 18 },
      { id: 'exhibitions', label: { es: 'Exposiciones/Ferias', 'pt-BR': 'Exposições/Feiras' }, emoji: '🏢', impactScore: 15 },
      { id: 'team_building', label: { es: 'Team building', 'pt-BR': 'Team building' }, emoji: '🤝', impactScore: 15 },
      { id: 'launches', label: { es: 'Lanzamientos de producto', 'pt-BR': 'Lançamentos de produto' }, emoji: '🚀', impactScore: 18 },
    ],
  },
  {
    id: 'Q_MICE_VENUE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Tenés venue propio?', 'pt-BR': 'Você tem venue próprio?' },
    type: 'single',
    businessTypes: ['eventos_mice'],
    options: [
      { id: 'own', label: { es: 'Sí, venue propio', 'pt-BR': 'Sim, venue próprio' }, emoji: '🏢', impactScore: 20 },
      { id: 'partner', label: { es: 'Venues asociados', 'pt-BR': 'Venues associados' }, emoji: '🤝', impactScore: 15 },
      { id: 'any', label: { es: 'Trabajo con cualquier venue', 'pt-BR': 'Trabalho com qualquer venue' }, emoji: '🔄', impactScore: 12 },
      { id: 'virtual', label: { es: 'Principalmente virtual', 'pt-BR': 'Principalmente virtual' }, emoji: '💻', impactScore: 10 },
    ],
  },
  {
    id: 'Q_MICE_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['eventos_mice'],
    options: [
      { id: 'full_planning', label: { es: 'Planificación integral', 'pt-BR': 'Planejamento integral' }, emoji: '📋', impactScore: 18 },
      { id: 'catering', label: { es: 'Catering', 'pt-BR': 'Catering' }, emoji: '🍽️', impactScore: 12 },
      { id: 'av', label: { es: 'Audiovisual/Técnica', 'pt-BR': 'Audiovisual/Técnica' }, emoji: '🎥', impactScore: 15 },
      { id: 'logistics', label: { es: 'Logística/Transfers', 'pt-BR': 'Logística/Transfers' }, emoji: '🚐', impactScore: 12 },
      { id: 'entertainment', label: { es: 'Entretenimiento', 'pt-BR': 'Entretenimento' }, emoji: '🎭', impactScore: 12 },
      { id: 'branding', label: { es: 'Branding/Decoración', 'pt-BR': 'Branding/Decoração' }, emoji: '🎨', impactScore: 10 },
    ],
  },
  {
    id: 'Q_MICE_SIZE',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuál es el tamaño promedio de tus eventos?', 'pt-BR': 'Qual é o tamanho médio dos seus eventos?' },
    type: 'single',
    businessTypes: ['eventos_mice'],
    options: [
      { id: 'small_50', label: { es: 'Hasta 50 personas', 'pt-BR': 'Até 50 pessoas' }, emoji: '👥', impactScore: 10 },
      { id: 'medium_200', label: { es: '50-200 personas', 'pt-BR': '50-200 pessoas' }, emoji: '🏢', impactScore: 15 },
      { id: 'large_500', label: { es: '200-500 personas', 'pt-BR': '200-500 pessoas' }, emoji: '🏛️', impactScore: 18 },
      { id: 'massive', label: { es: 'Más de 500', 'pt-BR': 'Mais de 500' }, emoji: '🌆', impactScore: 22 },
    ],
  },
  {
    id: 'Q_MICE_CLIENTS',
    category: 'marketing',
    mode: 'complete',
    dimension: 'traffic',
    weight: 7,
    title: { es: '¿Cómo conseguís clientes?', 'pt-BR': 'Como você consegue clientes?' },
    type: 'multi',
    businessTypes: ['eventos_mice'],
    options: [
      { id: 'referrals', label: { es: 'Referidos', 'pt-BR': 'Indicações' }, emoji: '👥', impactScore: 18 },
      { id: 'agencies', label: { es: 'Agencias de comunicación', 'pt-BR': 'Agências de comunicação' }, emoji: '📣', impactScore: 12 },
      { id: 'direct', label: { es: 'Venta directa a empresas', 'pt-BR': 'Venda direta a empresas' }, emoji: '💼', impactScore: 15 },
      { id: 'licitaciones', label: { es: 'Licitaciones', 'pt-BR': 'Licitações' }, emoji: '📄', impactScore: 12 },
      { id: 'digital', label: { es: 'Marketing digital', 'pt-BR': 'Marketing digital' }, emoji: '📱', impactScore: 10 },
    ],
  },
];

// ============= PRODUCTORA DE EVENTOS QUESTIONS =============
export const PRODUCTORA_EVENTOS_QUESTIONS: VistaSetupQuestion[] = [
  {
    id: 'Q_PRODUCTORA_TYPE',
    category: 'identity',
    mode: 'both',
    dimension: 'reputation',
    weight: 9,
    title: { es: '¿Qué tipo de eventos producís?', 'pt-BR': 'Que tipo de eventos você produz?' },
    type: 'multi',
    required: true,
    businessTypes: ['productora_eventos'],
    options: [
      { id: 'concerts', label: { es: 'Recitales/Conciertos', 'pt-BR': 'Shows/Concertos' }, emoji: '🎵', impactScore: 18 },
      { id: 'festivals', label: { es: 'Festivales', 'pt-BR': 'Festivais' }, emoji: '🎪', impactScore: 20 },
      { id: 'sports', label: { es: 'Eventos deportivos', 'pt-BR': 'Eventos esportivos' }, emoji: '⚽', impactScore: 15 },
      { id: 'corporate', label: { es: 'Eventos corporativos', 'pt-BR': 'Eventos corporativos' }, emoji: '💼', impactScore: 15 },
      { id: 'cultural', label: { es: 'Eventos culturales', 'pt-BR': 'Eventos culturais' }, emoji: '🎭', impactScore: 12 },
      { id: 'weddings', label: { es: 'Bodas/Sociales', 'pt-BR': 'Casamentos/Sociais' }, emoji: '💒', impactScore: 15 },
    ],
  },
  {
    id: 'Q_PRODUCTORA_SCALE',
    category: 'operation',
    mode: 'both',
    dimension: 'efficiency',
    weight: 8,
    title: { es: '¿Cuál es la escala típica de tus eventos?', 'pt-BR': 'Qual é a escala típica dos seus eventos?' },
    type: 'single',
    businessTypes: ['productora_eventos'],
    options: [
      { id: 'intimate_500', label: { es: 'Hasta 500 personas', 'pt-BR': 'Até 500 pessoas' }, emoji: '👥', impactScore: 10 },
      { id: 'medium_2000', label: { es: '500-2000 personas', 'pt-BR': '500-2000 pessoas' }, emoji: '🏢', impactScore: 15 },
      { id: 'large_10000', label: { es: '2000-10000 personas', 'pt-BR': '2000-10000 pessoas' }, emoji: '🏟️', impactScore: 20 },
      { id: 'massive', label: { es: 'Más de 10000', 'pt-BR': 'Mais de 10000' }, emoji: '🌆', impactScore: 25 },
    ],
  },
  {
    id: 'Q_PRODUCTORA_SERVICES',
    category: 'menu',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Qué servicios ofrecés?', 'pt-BR': 'Quais serviços você oferece?' },
    type: 'multi',
    businessTypes: ['productora_eventos'],
    options: [
      { id: 'production', label: { es: 'Producción general', 'pt-BR': 'Produção geral' }, emoji: '🎬', impactScore: 18 },
      { id: 'technical', label: { es: 'Técnica (sonido, luces)', 'pt-BR': 'Técnica (som, luz)' }, emoji: '🔊', impactScore: 15 },
      { id: 'stage', label: { es: 'Escenografía', 'pt-BR': 'Cenografia' }, emoji: '🎪', impactScore: 12 },
      { id: 'talent', label: { es: 'Contratación de artistas', 'pt-BR': 'Contratação de artistas' }, emoji: '⭐', impactScore: 15 },
      { id: 'ticketing', label: { es: 'Venta de entradas', 'pt-BR': 'Venda de ingressos' }, emoji: '🎫', impactScore: 12 },
      { id: 'sponsors', label: { es: 'Gestión de sponsors', 'pt-BR': 'Gestão de patrocinadores' }, emoji: '💰', impactScore: 15 },
    ],
  },
  {
    id: 'Q_PRODUCTORA_EVENTS_YEAR',
    category: 'finance',
    mode: 'both',
    dimension: 'profitability',
    weight: 8,
    title: { es: '¿Cuántos eventos producís por año?', 'pt-BR': 'Quantos eventos você produz por ano?' },
    type: 'single',
    businessTypes: ['productora_eventos'],
    options: [
      { id: '1-5', label: { es: '1-5 eventos', 'pt-BR': '1-5 eventos' }, emoji: '📊', impactScore: 10 },
      { id: '6-15', label: { es: '6-15 eventos', 'pt-BR': '6-15 eventos' }, emoji: '📈', impactScore: 15 },
      { id: '16-30', label: { es: '16-30 eventos', 'pt-BR': '16-30 eventos' }, emoji: '🚀', impactScore: 20 },
      { id: '30+', label: { es: 'Más de 30', 'pt-BR': 'Mais de 30' }, emoji: '🔥', impactScore: 25 },
    ],
  },
  {
    id: 'Q_PRODUCTORA_EQUIPMENT',
    category: 'operation',
    mode: 'complete',
    dimension: 'efficiency',
    weight: 7,
    title: { es: '¿Tenés equipamiento propio?', 'pt-BR': 'Você tem equipamento próprio?' },
    type: 'single',
    businessTypes: ['productora_eventos'],
    options: [
      { id: 'full', label: { es: 'Sí, equipamiento completo', 'pt-BR': 'Sim, equipamento completo' }, emoji: '✅', impactScore: 20 },
      { id: 'partial', label: { es: 'Parcial, alquilo resto', 'pt-BR': 'Parcial, alugo resto' }, emoji: '🔄', impactScore: 15 },
      { id: 'rental', label: { es: 'Alquilo todo', 'pt-BR': 'Alugo tudo' }, emoji: '🤝', impactScore: 10 },
      { id: 'partners', label: { es: 'Socios técnicos fijos', 'pt-BR': 'Parceiros técnicos fixos' }, emoji: '💼', impactScore: 12 },
    ],
  },
];

// Export all additional tourism questions
export const TURISMO_ADDITIONAL_QUESTIONS: VistaSetupQuestion[] = [
  ...POSADA_LODGE_QUESTIONS,
  ...APART_HOTEL_QUESTIONS,
  ...ALQUILER_TEMPORARIO_QUESTIONS,
  ...OPERADOR_TURISTICO_QUESTIONS,
  ...TURISMO_AVENTURA_QUESTIONS,
  ...ATRACCIONES_TICKETS_QUESTIONS,
  ...TEATRO_ESPECTACULOS_QUESTIONS,
  ...EVENTOS_MICE_QUESTIONS,
  ...PRODUCTORA_EVENTOS_QUESTIONS,
];

// Export function to get additional tourism questions for a specific business type
export function getTurismAdditionalQuestions(businessTypeId: string): VistaSetupQuestion[] {
  return TURISMO_ADDITIONAL_QUESTIONS.filter(q => 
    q.businessTypes?.includes(businessTypeId)
  );
}
